### PR TITLE
tweak(metaevent): Change COMMANDUSABLE_OBSERVER to no longer apply in Shell Map

### LINKED ISSUE #1945: Shell map pauses/steps one frame with replay controls and speeds up with increased FPS
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

The shell map pauses when pressing P  and advances one frame at a time when pressing O, same behavior as replay controls. When going into a multiplayer chat, pressing P or O while the chat box is still not in focus will pause the shell map and type in the chat box at the same time

Additionally, increasing FPS causes the shell map to speed up and thus increasing the main menu animations and sounds.

### Reproduction Steps

1- Launch the game and wait for the shell map to load.
2- Press P -> the shell map pauses.
3- Press O -> the shell map advances one frame
4. Increase FPS -> shell map and menu animations and sounds speed up
5. go into a multiplayer chat without focusing the chat box and press P -> the shell map pauses and letter P will be typed in the chat box.

### Additional Context

https://github.com/user-attachments/assets/68053346-4556-41b8-8652-91eff3595879

https://github.com/user-attachments/assets/58782ac4-266d-4066-81d9-25a55940d481

### PR DESCRIPTION
**Pull request by xezon**
* Follow up for #1530
* Relates to #1945

This changes `COMMANDUSABLE_OBSERVER` to no longer apply in Shell Map. It applies when observing (including Replay).

Previously buttons P and O took affect in Shell Map. But this causes confusion because players press these buttons in the lobby when typing messages.

The Shell Map can still be paused and stepped with Shift+P, Shift+O.

This change does not really fix #1945

### CODE REVIEW

File: Generals/Code/GameEngine/Include/Common/Player.h [hunk 1]
```diff
@@ -590,9 +590,9 @@ class Player : public Snapshot
 
 	Bool isPlayableSide( void ) const;
 
-	Bool isPlayerObserver( void ) const; // Favor !isActive() - this is used for Observer GUI mostly, not in-game stuff
-	Bool isPlayerDead(void) const; // Favor !isActive() - this is used so OCLs don't give us stuff after death.
-	Bool isPlayerActive(void) const;
+	Bool isPlayerObserver( void ) const; // Favor !isPlayerActive() - this is used for Observer GUI mostly, not in-game stuff
+	Bool isPlayerDead(void) const; // Favor !isPlayerActive() - this is used so OCLs don't give us stuff after death.
+	Bool isPlayerActive(void) const; // Player is alive and no observer. !isPlayerActive() is synonymous for observing.
```
Comment (bobtista) [inline Generals/Code/GameEngine/Include/Common/Player.h]: nit: 
no observer -> non-observer or not observer
synonymous for -> synonymous with

**Comment by bobtista** [comment]
LGTM, though I think the local player should be an observer in the shell map. 🤷

File: Generals/Code/GameEngine/Include/Common/Player.h (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Include/Common/Player.h]: Fixed
