### PR TITLE
fix(filesystem): Decouple File System from NameKeyGenerator and its CRC influence

### LINKED ISSUE #1531: Generals is CRC mismatching
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [ ] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Generals is CRC mismatching.

### Reproduction Steps

Run the attached Replay

[12-57-43_2v2_s_DESKTOP3_banorama_ttttt.zip](https://github.com/user-attachments/files/22126907/12-57-43_2v2_s_DESKTOP3_banorama_ttttt.zip)

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1531

This change decouples the File System from the NameKeyGenerator and its CRC influence. There are Name Key(s) somewhere used for CRC'ing and the File Existence Cache in File System influences the Name Keys on Engine Init.

I replaced the File Existence Map and preserved the 3 critical Name Keys for retail compatibility.

## TODO

- [x] Replicate in Generals (verify ID's)

### CODE REVIEW

**Comment by xezon** [comment]
This was pain...

**Comment by xezon** [comment]
Generals is not compiling before replicating.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp [hunk 1]
```diff
@@ -140,16 +140,17 @@ void GlobalLanguage::init( void )
 	AsciiString fname;
 	fname.format("Data\\%s\\Language.ini", GetRegistryLanguage().str());
 
+	//check if we're running Win9x variant since they may need different fonts
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp]: We could just strip out anything relating to operating system support before windows 7.

We have already done so for other changes that removed workarounds for a few windows 2000 problems.

Is the language9x.ini really needed for the correct key name generation of other key name pairs?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp]: It would be possible to remove this now. I did this previously with #1496 but closed it because it caused CRC mismatching. This code is only needed for Windows before XP.

We can revive #1496 after this is merged.

Comment (OmniBlade) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp]: Even if it is required for correct keygen @Mauller this change looks like it covers for that by auto registering the name key for the file so the language9x.ini logic looks to me like it could just be stripped out? At a glance does this bit of code even need touching in this PR?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp]: I reverted the Win 9x code changes.

Comment (Mauller) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GlobalLanguage.cpp]: It is interesting how just 3 files cause this weird issue.

**Comment by xezon** [comment]
Replicated in Generals.

**Comment by xezon** [comment]
I can confirm that this now also fixes the CRC mismatch in Generals.
