### PR TITLE
bugfix(wbview3d): Fix crash on window resize in Generals World Builder

### LINKED ISSUE #2008: Generals World-builder  Crash when Switching from one Window size to another
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [ ] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

generals-weekly-2025-12-12.zip   when Changing window size the World Builder Crashes with no crash or error pop up. 

### Reproduction Steps

1. Install fresh copy of generals Steam Version.
2. Install the generals-weekly-2025-12-12 patch
3. open WorldBuilderV.exe
4. change the windows size from default 800x600 to 1024x768
5. change the window size back to 800x600 from 1024x768

### Additional Context

https://github.com/user-attachments/assets/69cbbae5-1bed-4641-91fb-f4dd94a79f7d

### PR DESCRIPTION
**Pull request by jurassicLizard**
- fixes #2008
  - Note 1: This issue only affects Generals but not Zero Hour
  - Note 2: Crash happens When Switching from one Window size to another (#2008), Brought the logic to be the exact same as in the generals zero-hour WorldBuilder which is known to work without crashing: Removing shutdown and reinit when resetting the display size appears to resolve the issue. When shutting down and reinitializing the device might not be ready yet by the time the call is made again to Wd3ShaderManager::init() and this causes the Generals WorldBuilder to crash when resizing from a resolution to another and then back to that resolution again. nullpointer checks inside the init function didnot help alleviate the issue
  - See Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DShaderManager.cpp  and GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp for more information

Working Zero Hour implementation from main branch : https://github.com/TheSuperHackers/GeneralsGameCode/blob/6818fae6278182c6cffee4b0e2e0752e647dd165/GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp#L594

### CODE REVIEW

File: Generals/Code/Tools/WorldBuilder/src/wbview3d.cpp [hunk 1]
```diff
@@ -573,10 +573,18 @@ void WbView3d::reset3dEngineDisplaySize(Int width, Int height)
 	bogusTacticalView.setOrigin(0,0);
 	m_actualWinSize.x = width;
 	m_actualWinSize.y = height;
+	// TheSuperHackers @bugfix jurassiclizard 19/01/2026  Fix Generals World-builder Crash
```
Comment (xezon) [inline Generals/Code/Tools/WorldBuilder/src/wbview3d.cpp]: This entire comment block can be removed because this is simply merging Zero Hour code to Generals and we do not comment these merges.

Otherwise this is fine.

**Comment by jurassicLizard** [comment]
is this related to this : https://github.com/TheSuperHackers/GeneralsGameCode/issues/1220 ? somehow i can't replicate that particular 1220 crash in that issue the debugger it doesnot jump to any exception . I can not confirm however if this is related to this fix or not

File: Generals/Code/Tools/WorldBuilder/src/wbview3d.cpp (hunk 1 above)
Comment (jurassicLizard) [reply Generals/Code/Tools/WorldBuilder/src/wbview3d.cpp]: Comment removed: 46ea36659a3156869bfabc5433b084bb350e622b
