### PR TITLE
bugfix(input): Fix touchpad upward scrolling in UI list boxes

### LINKED ISSUE #2584: Bug: Choppy/unsmooth scrolling UP using laptop touchpad (`GadgetListBox`)
There is a scrolling rendering/input issue when using a laptop touchpad to scroll upwards in UI lists. The scrolling list scrolls up momentarily and then jumps back down, whereas other scrolling methods work perfectly.

https://github.com/user-attachments/assets/bc830ae0-3ca5-43f8-89cd-ccec2d3a1974

**Steps to Reproduce:**
1. Open the game on a laptop with a touchpad.
2. Navigate to any menu containing a vertical list box (`GadgetListBox`).
3. Use the touchpad to scroll **UP**.
4. Observe the glitchy/choppy scrolling behavior.

**Expected Behavior:**
Scrolling up via the touchpad should be as smooth and consistent as scrolling down.

**Additional Context / Diagnostics:**
* 🟢 Scrolling **DOWN** via touchpad is perfectly smooth.
* 🟢 Scrolling both UP and DOWN using a standard physical **mouse wheel** works flawlessly.
* The issue is isolated strictly to upward touchpad scroll inputs.

**Investigation so far:**
I attempted to debug this and briefly looked into the UI elements' logic (e.g., `GadgetListBox.cpp`, `GadgetVerticalSlider.cpp`), specifically around the `adjustDisplay` function and slider positioning. My suspicion is that touchpad delta events (which are often continuous and fractional compared to discrete mouse wheel ticks) might be mishandled, incorrectly rounded, or truncated when calculating the upward (negative/positive) scroll offset. However, I wasn't able to successfully implement a complete fix for this behavior.

### PR DESCRIPTION
**Pull request by afc-afc0**
## Summary                                                                                                                             
  
  - Fixes touchpad upward scrolling in UI list boxes (GadgetListBox) where the list momentarily scrolls up then jumps back down            - Preserves wheel delta sign when normalizing, so touchpad's small continuous deltas are no longer truncated to 0 and misidentified as downward scroll                                                                                                                        
  - Mouse wheel behavior is completely unchanged

  ## Root Cause

  In `Mouse::createStreamMessages()`, the wheel delta was divided by `MOUSE_WHEEL_DELTA` (120) before being sent as a message argument.  
  Touchpad devices send small deltas (e.g. +30) that truncate to 0 on integer division. In `WindowXlat.cpp`, the direction check `if     
  (argument > 0)` maps 0 to `GWM_WHEEL_DOWN`, causing upward touchpad scroll to be treated as downward.

  ## Fix

  Clamp the normalized wheel delta to at least `1` or `-1` based on the original sign of `wheelPos`, ensuring the scroll direction is    
  always preserved. Only `Mouse.cpp` is changed — no consumers need modification.

  ## Test plan

  - [x] Verified mouse wheel scrolls up and down correctly in UI list boxes
  - [x] Verified mouse wheel zoom in/out works correctly on the map
  - [x] Verified no regression in combo box scrolling
  - [x] Verified touchpad upward scrolling no longer jumps back down

### CODE REVIEW

**Review by DevGeniusCode — APPROVED** [review]

**Comment by DevGeniusCode** [comment]
Good catch, closes #2584
I checked mine and it did solve the issue
Need to replicate to vanilla generals

File: Core/GameEngine/Source/GameClient/Input/Mouse.cpp [hunk 1]
```diff
@@ -824,7 +824,9 @@ void Mouse::createStreamMessages()
 		{
 			msg = TheMessageStream->appendMessage( GameMessage::MSG_RAW_MOUSE_WHEEL );
 			msg->appendPixelArgument( m_currMouse.pos );
-			msg->appendIntegerArgument( m_currMouse.wheelPos / 120 );  // wheel delta
+			// TheSuperHackers @bugfix Preserve wheel delta sign for touchpad scroll direction detection
```
Comment (xezon) [inline Core/GameEngine/Source/GameClient/Input/Mouse.cpp]: The comment is a bit incomplete. It would be better if it clarified that it now guarantees a non-zero value.

File: Core/GameEngine/Source/GameClient/Input/Mouse.cpp [hunk 2]
```diff
@@ -824,7 +824,9 @@ void Mouse::createStreamMessages()
...
+			const Int wheelTicks = m_currMouse.wheelPos / MOUSE_WHEEL_DELTA;
+			msg->appendIntegerArgument( m_currMouse.wheelPos > 0 ? max( 1, wheelTicks ) : min( -1, wheelTicks ) );
```
Comment (xezon) [inline Core/GameEngine/Source/GameClient/Input/Mouse.cpp]: Minor: could be written as.
```cpp
Int wheelTicks = m_currMouse.wheelPos / MOUSE_WHEEL_DELTA;
wheelTicks = m_currMouse.wheelPos > 0 ? max( 1, wheelTicks ) : min( -1, wheelTicks );
msg->appendIntegerArgument( wheelTicks );
```

Comment (xezon) [inline Core/GameEngine/Source/GameClient/Input/Mouse.cpp]: It is not clear to me that this fix proposal is the best approach. Perhaps it would be better to make this message argument a float type instead of integer? It looks like it would be possible. Follow all code at MSG_RAW_MOUSE_WHEEL.

Comment (afc-afc0) [reply Core/GameEngine/Source/GameClient/Input/Mouse.cpp]: I tried to my make scope smaller for my first PR, with that being said. I created another commit following float method, which I also tested and worked fine I followed the MSG_RAW_MOUSE_WHEEL saw no issues, winProcessMouseEvent only dereferences data* pointer for drag events (GWM_LEFT_DRAG). For wheel events, it calls winSendInputMsg   
  with packed mouse coordinates and 0, the wheel pointer is never forwarded. 

Making float divisions just for mousepad might be an overkill. I understand fixing like this doesn't look great either.

Commit: https://github.com/afc-afc0/CnC_Generals_Zero_Hour/commit/f80cee8b6ae207c005f1209695f13d9bde161df3

Comment (xezon) [reply Core/GameEngine/Source/GameClient/Input/Mouse.cpp]: The float argument change looks better than this one.

**Review by xezon — APPROVED** [review]
Looking good.
