### PR TITLE
bugfix(worldbuilder): Fix optimized trees not being shown in object placer preview window

### LINKED ISSUE #381: Worldbuilder: Bug: Optimization made for trees in ZH broke the w3d model preview under ZH worldbuilder
Vgen WB dont have this issue and you can still see the 3d preview when you select the object via object selection opts

### PR DESCRIPTION
**Pull request by ViTeXFTW**
- Fixes #381

**Description**
When making Zero Hour the devs created an optimized module (W3DTreeDraw) for drawing trees. They forgot to add the preview handling in WorldBuilder to handle this new draw type, which results in the preview not showing anything when having an object of the W3DTreeDraw module selected.

**Root Cause**
WorldBuilder attempts to get the module data for getting the model name of the object. However the format of the `W3DModelDraw` module data and `W3DTreeDraw` module data are different and there is not an exposed and generic way to get the information without explicitly casting the data to the expected type (`W3DModelDrawModuleData` or `W3DTreeDrawModuleData`).

**Fix**
Added a fallback function call to get the `W3DTreeDrawModuleData` if the normal `W3DModelDraw` fails which preserves the original behavior and also enables preview of tree types. 

Old:
image

New:
image

## TODO

-  ~~Replicate in Generals~~

### CODE REVIEW

File: GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp [hunk 1]
```diff
@@ -20,6 +20,7 @@
 //
 
 #include "StdAfx.h"
+#include "W3DDevice/GameClient/Module/W3DTreeDraw.h"
```
Comment (xezon) [inline GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp]: Group it with the other similar files

File: GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp [hunk 2]
```diff
@@ -1118,6 +1119,15 @@ AsciiString WbView3d::getBestModelName(const ThingTemplate* tt, const ModelCondi
 			{
 				return md->getBestModelNameForWB(c);
 			}
+
+			// TheSuperHackers @bugfix ViTeXFTW 15/02/2025 Fix tree objects not showing
+			// a preview in WB object placer. The W3DTreeDraw module stores its model name
+			// differently from W3DModelDraw.
```
Comment (xezon) [inline GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp]: Minor. Comment could take 2 lines instead of 3.

**Comment by ViTeXFTW** [comment]
> Needs to be replicated in Generals

This is not an issue in Generals as it didn't have the optimized treee - only zero hour issue

File: GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp [hunk 3]
```diff
@@ -1118,6 +1119,14 @@ AsciiString WbView3d::getBestModelName(const ThingTemplate* tt, const ModelCondi
 			{
 				return md->getBestModelNameForWB(c);
 			}
+
+			// TheSuperHackers @bugfix ViTeXFTW 15/02/2025 Fix tree objects not showing a preview in
```
Comment (Caball009) [inline GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp]: Where are the ~snows~ bugs of yesteryear?

Comment (ViTeXFTW) [reply GeneralsMD/Code/Tools/WorldBuilder/src/wbview3d.cpp]: f
