### PR TITLE
bugfix(lobby): Properly sort CRC mismatched game rooms to the bottom of the lobby

### LINKED ISSUE #967: Bugged sorting in GameSortStruct::operator()
Sorting logic is wrong in `GameSortStruct::operator()` with `g2Good`.

```cpp
struct GameSortStruct
{
	bool operator()(GameSpyStagingRoom *g1, GameSpyStagingRoom *g2) const
	{
		// sort CRC mismatches to the bottom
		Bool g1Good = (g1->getExeCRC() != TheGlobalData->m_exeCRC || g1->getIniCRC() != TheGlobalData->m_iniCRC);
		Bool g2Good = (g1->getExeCRC() != TheGlobalData->m_exeCRC || g1->getIniCRC() != TheGlobalData->m_iniCRC); // <--- wrong
		if ( g1Good ^ g2Good )
		{
			return g1Good;
		}
...
```

### PR DESCRIPTION
**Pull request by bobtista**
- Fixes #967 Bugged sorting in GameSortStruct::operator()

Addressed had three issues:

1. Copy-paste error: g2Good was checking g1 instead of g2
2. Confusing variable names: g1Good/g2Good were true when CRCs were bad, not good
3. Wrong return value: returned g1Good instead of g2Good, sorting mismatches to top instead of bottom

### CODE REVIEW

File: Core/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp [hunk 1]
```diff
@@ -474,11 +474,11 @@ struct GameSortStruct
 	bool operator()(GameSpyStagingRoom *g1, GameSpyStagingRoom *g2) const
 	{
 		// sort CRC mismatches to the bottom
-		Bool g1Good = (g1->getExeCRC() != TheGlobalData->m_exeCRC || g1->getIniCRC() != TheGlobalData->m_iniCRC);
-		Bool g2Good = (g1->getExeCRC() != TheGlobalData->m_exeCRC || g1->getIniCRC() != TheGlobalData->m_iniCRC);
-		if ( g1Good ^ g2Good )
+		Bool g1Mismatch = (g1->getExeCRC() != TheGlobalData->m_exeCRC || g1->getIniCRC() != TheGlobalData->m_iniCRC);
+		Bool g2Mismatch = (g2->getExeCRC() != TheGlobalData->m_exeCRC || g2->getIniCRC() != TheGlobalData->m_iniCRC);
```
Comment (Skyaero42) [inline Core/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp]: I would go for `g1Mismatches` or `isMismatch1`

**Review by Skyaero42 — COMMENTED** [review]
I don't think we will ever use Gamespy again - especially with GO around the corner, but it is a good catch of an error. Surprised it was never caught by EA.

File: Core/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp [hunk 2]
```diff
@@ -474,11 +474,11 @@ struct GameSortStruct
 	bool operator()(GameSpyStagingRoom *g1, GameSpyStagingRoom *g2) const
 	{
 		// sort CRC mismatches to the bottom
-		Bool g1Good = (g1->getExeCRC() != TheGlobalData->m_exeCRC || g1->getIniCRC() != TheGlobalData->m_iniCRC);
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp:477]: Are you sure this is all correct now? I would have expected:

```cpp
		Bool g1Good = (g1->getExeCRC() == TheGlobalData->m_exeCRC && g1->getIniCRC() == TheGlobalData->m_iniCRC);
		Bool g2Good = (g1->getExeCRC() == TheGlobalData->m_exeCRC && g1->getIniCRC() == TheGlobalData->m_iniCRC);
		if ( g1Good ^ g2Good )
		{
			return g1Good;
		}
```

Comment (bobtista) [reply Core/GameEngine/Source/GameNetwork/GameSpy/LobbyUtils.cpp:477]: It's correct either way, but yours is positive logic and matches another comparison for g2UnknownLadder. I updated to use your approach

**Review by xezon — APPROVED** [review]
