### PR TITLE
[GEN][ZH] Fix crash when exiting Replay playback while a player places a beacon

### LINKED ISSUE #76: Game crashes when exiting Replay Mode while player places beacon
Game crashes when exiting Replay Mode while player places beacon. Maybe also happens in regular match. However, this crash is easy to reproduce in Replay Mode when using Frame Step functionality from GenTool to reach specific frame in Replay.

GenTool fixes this crash by injecting naked function at address `0x4544C1` taking 6 bytes.

```
//////////////////////////////////////////////////////////////////////////////////////

// CPU Disasm (Zero Hour 1.04)
// Address   Hex dump          Command                                  Comments
// 004544C0  /$  51            PUSH ECX                                 ; game.004544C0(guessed Arg1)
// 004544C1  |.  8B81 DC000000 MOV EAX,DWORD PTR DS:[ECX+0DC]
// 004544C7  |.  85C0          TEST EAX,EAX
// 004544C9  |.  56            PUSH ESI
// 004544CA  |.  8B7424 0C     MOV ESI,DWORD PTR SS:[ARG.1]
// 004544CE  |.  C74424 04 000 MOV DWORD PTR SS:[LOCAL.0],0
// 004544D6  |.  8906          MOV DWORD PTR DS:[ESI],EAX
// 004544D8  |.  74 07         JZ SHORT 004544E1
// 004544DA  |.  50            PUSH EAX                                 ; /pTarget => [ARG.ECX+0DC]
// 004544DB  |.  FF15 2C929300 CALL DWORD PTR DS:[<&KERNEL32.Interlocke ; \KERNEL32.InterlockedIncrement
// 004544E1  |>  8BC6          MOV EAX,ESI
// 004544E3  |.  5E            POP ESI
// 004544E4  |.  59            POP ECX
// 004544E5  \.  C2 0400       RETN 4

//////////////////////////////////////////////////////////////////////////////////////

DWORD ccFixBeaconCrashRet;
__declspec(naked) void CC_FixBeaconCrash_ZH()
{
	__asm
	{
		pop [ccFixBeaconCrashRet]
		test ecx, ecx
		je Fix
		MOV EAX, DWORD PTR DS:[ECX+0xDC]
		jmp End
	Fix:
		mov eax, 0
	End:
		push [ccFixBeaconCrashRet]
		ret
	}
}
```

### PR DESCRIPTION
**Pull request by xezon**
* Merge after #969
* Fixes #76
* Relates to #850

This change fixes a game crash when exiting Replay playback while a player places a beacon.

The null crash does occur in GameLogic::logicMessageDispatcher, but the root cause of the problem already starts earlier.

The `RecorderClass` can still push replay commands to the CommandList before the final `MSG_CLEAR_GAME_DATA` is processed in the same frame. `MSG_CLEAR_GAME_DATA` will destroy the match session.

## Callstack for when MSG_CLEAR_GAME_DATA is processed

```
 	generalszh.exe!GameLogic::reset() Line 453	C++
 	generalszh.exe!SubsystemInterfaceList::resetAll() Line 188	C++
 	[Inline Frame] generalszh.exe!GameLogic::isInMultiplayerGame() Line 418	C++
 	generalszh.exe!GameEngine::reset() Line 699	C++
 	generalszh.exe!GameLogic::clearGameData(bool showScoreScreen) Line 281	C++
 	generalszh.exe!GameLogic::logicMessageDispatcher(GameMessage * msg, void * userData) Line 464	C++
>	generalszh.exe!GameLogic::processCommandList(CommandList * list) Line 2594	C++
 	generalszh.exe!GameLogic::update() Line 3764	C++
 	generalszh.exe!Win32GameEngine::update() Line 93	C++
 	generalszh.exe!GameEngine::execute() Line 819	C++
 	generalszh.exe!GameMain(int argc, char * * argv) Line 47	C++
 	generalszh.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 988	C++
 	[Inline Frame] generalszh.exe!invoke_main() Line 102	C++
 	generalszh.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!764cfcc9()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!77ca82ae()	Unknown
 	ntdll.dll!77ca827e()	Unknown
```

## Code for when MSG_PLACE_BEACON is appended, MSG_CLEAR_GAME_DATA is processed

```cpp
void GameLogic::update( void )
{
...
  // Update the Recorder
  {
    TheRecorder->UPDATE(); // <--- Pushes MSG_PLACE_BEACON in the last frame
  }

  // process client commands
  {
    processCommandList( TheCommandList ); // <--- Processes MSG_CLEAR_GAME_DATA, calls GameLogic::reset() which deletes all things, then processes MSG_PLACE_BEACON, then crashes the game
  }
...
}
```

## Solution

Stop appending Replay commands after MSG_CLEAR_GAME_DATA command was appended.

### CODE REVIEW

File: Generals/Code/GameEngine/Include/Common/Recorder.h [hunk 1]
```diff
@@ -137,7 +137,13 @@ class RecorderClass : public SubsystemInterface {
...
 	void readArgument(GameMessageArgumentDataType type, GameMessage *msg);
 
-	void cullBadCommands();														///< prevent the user from giving mouse commands that he shouldn't be able to do during playback.
+	struct CullBadCommandsResult
+	{
+		CullBadCommandsResult() : hasClearGameDataMessage(false) {}
+		Bool hasClearGameDataMessage;
+	};
+
+	CullBadCommandsResult cullBadCommands(); ///< prevent the user from giving mouse commands that he shouldn't be able to do during playback.
```
Comment (Skyaero42) [inline Generals/Code/GameEngine/Include/Common/Recorder.h:146]: Why do you return a struct - that only contains a boolean -  instead of returning the boolean directly?

Comment (xezon) [reply Generals/Code/GameEngine/Include/Common/Recorder.h:146]: Because the returned boolean has no name.

**Review by roossienb — APPROVED** [review]

File: Generals/Code/GameEngine/Include/Common/Recorder.h (hunk 1 above)
Comment (Mauller) [reply Generals/Code/GameEngine/Include/Common/Recorder.h:146]: Maybe the ```cullBadCommand()``` functions should be renamed to something like ```filterCommands()``` then have it set a boolean of something like ```m_clearDataMessageSeen``` then act on that instead of adding a structure for this.

Comment (xezon) [reply Generals/Code/GameEngine/Include/Common/Recorder.h:146]: No need to add a new member to this class. Returning a 1 byte struct is perfectly fine.

File: GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp [hunk 2]
```diff
@@ -1520,8 +1531,15 @@ void RecorderClass::cullBadCommands() {
 			deleteInstance(msg);
 		}
 
+		if (msg->getType() == GameMessage::MSG_CLEAR_GAME_DATA)
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp]: Can do else if here.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/Recorder.cpp]: Fixed.
