### PR TITLE
bugfix(script): Fix crash if nearest command button target is not found

### LINKED ISSUE #1419: Game crash when USA Battleship fires on two different targets in sequence
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When a USA Battleship fires on a target, it works perfectly. If it then fires on a _new, different_ target, the game crashes.

I have not checked if this exists in vGen, but I assume it doesn't since there aren't any working battleships in vGen

### Reproduction Steps

This [map](https://github.com/user-attachments/files/21580472/BattleshipSequenceTest.zip) demonstrates the crash. Open it with Worldbuilder to see what is going on, and try it with ScriptDebugger to see where the crash happens.

### Additional Context

From the map demonstration, I would hazard a guess that some kind of Flag is not reset or similar, given that the first target works but afterwards the game crashes consistently.

### PR DESCRIPTION
**Pull request by Stubbjax**
* Fixes #1419

This change fixes a missing null check on the best object in the else block of `ScriptActions::doTeamUseCommandButtonOnNearestObjectType`, which leads to a crash.

### CODE REVIEW

**Comment by Caball009** [comment]
Is there no possibility that this changes retail behavior? Not all logic relies on the value of `bestObj`.

**Comment by xezon** [comment]
> Is there no possibility that this changes retail behavior? Not all logic relies on the value of `bestObj`.

I looked around and `doTeamUseCommandButtonOnNearestObjectType` is the only function that can call into `doCommandButtonAtObject` with NULL obj.

With the fix as is, we can even add an assert for `obj != NULL` in `doCommandButtonAtObject` and remove the one null check in there.

**Comment by Caball009** [comment]
Is it possible that this is 'called' from `doTeamUseCommandButtonOnNearestObjectType`? It doesn't rely on the object pointer.
https://github.com/TheSuperHackers/GeneralsGameCode/blob/3db937327b0975a8c5064c77613f8f34b12a1e9a/GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp#L5552-L5557

**Comment by xezon** [comment]
Yes it looks as if theoretically someone could call this script `ScriptAction::TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_OBJECTTYPE` with no valid object type and GUI_COMMAND_STOP and then it would stop the group. Very unlikely to happen, even on Mod maps I expect. But still.

So to play this safe, it is probably better to do a RETAIL_COMPATIBLE_CRC fix as well.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp [hunk 1]
```diff
@@ -5534,13 +5534,27 @@ void Object::doCommandButtonAtObject( const CommandButton *commandButton, Object
...
 					ai->aiCombatDrop( obj, *(obj->getPosition()), cmdSource );
 				}
 				return;
 			case GUI_COMMAND_SPECIAL_POWER:
 			{
+#if RETAIL_COMPATIBLE_CRC
+				if (!obj)
+				{
+					return;
+				}
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp]: You can simplify these to

```
if (!obj)
  return;
```

for less vertical space, but is also fine otherwise.

**Comment by xezon** [comment]
There is a merge conflict now.

**Review by xezon — APPROVED** [review]
