### PR TITLE
bugfix(audiomanager): Fix dummy audio manager implementation for failing audio length script conditions in headless mode

### LINKED ISSUE #2295: Incomplete implementation of dummy audio manager can cause mismatches in headless mode
```
*** IF ***
  Sound 'AirRaidSiren' has completed playing.
*** THEN ***
  [???]All of Player 'player0''s buildings and units are dealt a lethal amount of damage.
```

The above script only works correctly if the implementation for `AudioManager::getFileLengthMS` returns the right value. Our dummy implementation `AudioManagerDummy` doesn't do that. Some custom maps with scripts like the above can mismatch in headless mode because of this.

## Reproduction:
1. Use this map, it contains the above script: [audio_manager_test2.zip](https://github.com/user-attachments/files/25349680/audio_manager_test2.zip)
2. Start a skirmish / multiplayer game (using the first slot), no interaction required.
3. Save the replay.
4. Check the replay inside the game. It should not mismatch.
5. Check the replay with headless mode, it should mismatch.

**Edited message to use a script action that actually causes a mismatch.**

### PR DESCRIPTION
**Pull request by Caball009**
* Closes https://github.com/TheSuperHackers/GeneralsGameCode/issues/2295
* Follow up for https://github.com/TheSuperHackers/GeneralsGameCode/pull/651

Our current implementation of dummy audio manager is incomplete, because it cannot return the actual length of audio files. Replays will mismatch if they contain scripts that rely on this.

## TODO:
- ~~Make sure the Github CI can access the audio files.~~
- [x] Replicate in Generals.

### CODE REVIEW

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h [hunk 1]
```diff
@@ -330,3 +330,53 @@ class MilesAudioManager : public AudioManager
...
+	virtual void pauseAmbient(Bool shouldPause) {}
+	virtual void killAudioEventImmediately(AudioHandle audioEvent) {}
+	virtual void nextMusicTrack() {}
+	virtual void prevMusicTrack() {}
+	virtual Bool isMusicPlaying() const { return false; }
+	virtual Bool hasMusicTrackCompleted(const AsciiString& trackName, Int numberOfTimes) const { return false; }
+	virtual AsciiString getMusicTrackName() const { return ""; }
+	//virtual void openDevice() {}
+	//virtual void closeDevice() {}
+	//virtual void* getDevice() { return nullptr; }
```
[the remark this answers is not in the document]
Comment (Caball009) [reply Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h]: I think there's value in providing a complete implementation of AudioManager. The functions that are commented out show clearly, more so than the comment, which functions are not overridden for this dummy implementation.

File: GeneralsMD/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h [hunk 2]
```diff
@@ -77,7 +77,7 @@ class Win32GameEngine : public GameEngine
 	virtual NetworkInterface *createNetwork();				///< Factory for the network
 	virtual Radar *createRadar();											///< Factory for radar
 	virtual WebBrowser *createWebBrowser();						///< Factory for embedded browser
-	virtual AudioManager *createAudioManager();				///< Factory for audio device
+	virtual AudioManager *createAudioManager(Bool headless);				///< Factory for audio device
```
Comment (xezon) [inline GeneralsMD/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: Maybe do `Bool dummy` ? Because it may not just be headless that want's to use a dummy in the future, aka the Dummy class should not care in what context it is used.

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h [hunk 3]
```diff
@@ -330,3 +330,53 @@ class MilesAudioManager : public AudioManager
 
 };
 
+// TheSuperHackers @feature helmutbuhler 17/05/2025 AudioManager that does almost nothing. Used for Headless Mode.
```
Comment (xezon) [inline Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h]: "Useful for headless mode"

File: GeneralsMD/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h [hunk 4]
```diff
@@ -77,7 +77,7 @@ class Win32GameEngine : public GameEngine
 	virtual NetworkInterface *createNetwork();				///< Factory for the network
 	virtual Radar *createRadar();											///< Factory for radar
```
Comment (xezon) [inline GeneralsMD/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: Perhaps mirror the implemention for createRadar?

It currently also does `TheGlobalData->m_headless ? NEW RadarDummy : createRadar()`

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h [hunk 5]
```diff
@@ -330,3 +330,53 @@ class MilesAudioManager : public AudioManager
...
+// @bugfix Caball009 16/02/2026 Scripts may require the actual audio file length to function properly.
```
Comment (xezon) [inline Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h]: Perhaps clarify that this is CRC relevant

**Comment by Caball009** [comment]
Addressed feedback.

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h [hunk 6]
```diff
@@ -330,3 +330,53 @@ class MilesAudioManager : public AudioManager
...
+	virtual Bool has3DSensitiveStreamsPlaying() const { return false; }
+	virtual void* getHandleForBink() { return nullptr; }
+	virtual void releaseHandleForBink() {}
+	virtual void friend_forcePlayAudioEventRTS(const AudioEventRTS* eventToPlay) {}
+	virtual void setPreferredProvider(AsciiString providerNdx) {}
+	virtual void setPreferredSpeaker(AsciiString speakerType) {}
+	//virtual Real getFileLengthMS(AsciiString strToLoad) const { return 0.0f; }
+	virtual void closeAnySamplesUsingFile(const void* fileToClose) {}
+	virtual void setDeviceListenerPosition() {}
+};
```
[the remark this answers is not in the document]
Comment (Caball009) [reply Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h:382]: I'm not sure what the right course of action is here. Should `m_audioOn` always be enabled, or maybe always enabled for headless mode? 

With `m_audioOn` disabled the device won't be opened, but even if it were, scripts that rely on speech / sound effect length would still fail.

[the remark this answers is not in the document]
Comment (xezon) [reply Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h:382]: m_audioOn=0 would also mismatch with the regular Audio Manager right?

If so, then this should be no concern. The Dummy works the same way. We expect an untampered GameData.ini file.

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h [hunk 7]
```diff
@@ -330,3 +330,53 @@ class MilesAudioManager : public AudioManager
 
 };
 
+// TheSuperHackers @feature helmutbuhler 17/05/2025 AudioManager that does almost nothing. Useful for headless mode.
+// @bugfix Caball009 16/02/2026 Scripts may require the actual audio file length to function properly, which is important for the CRC computation.
```
[the remark this answers is not in the document]
Comment (Caball009) [reply Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h]: That's the date from the previous comment.

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (Caball009) [reply Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h:382]: > m_audioOn=0 would also mismatch with the regular Audio Manager right?

It's been a minute, but yes I think that's the case.

> If so, then this should be no concern. The Dummy works the same way. We expect an untampered GameData.ini file.

Yeah, that's fair.

**Comment by Caball009** [comment]
Replicated in Generals.

**Comment by Caball009** [comment]
> Make sure the Github CI can access the audio files.

@tintinhamans Would you mind taking care of this?

File: Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h [hunk 8]
```diff
@@ -97,6 +97,6 @@ inline ArchiveFileSystem *Win32GameEngine::createArchiveFileSystem() { return NE
 inline ParticleSystemManager* Win32GameEngine::createParticleSystemManager(Bool dummy) { return dummy ? static_cast<ParticleSystemManager*>(NEW ParticleSystemManagerDummy) : NEW W3DParticleSystemManager; }
 
 inline NetworkInterface *Win32GameEngine::createNetwork() { return NetworkInterface::createNetwork(); }
-inline Radar *Win32GameEngine::createRadar() { return NEW W3DRadar; }
+inline Radar *Win32GameEngine::createRadar(Bool dummy) { return dummy ? static_cast<Radar*>(NEW RadarDummy) : NEW W3DRadar; }
```
Comment (xezon) [inline Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: Can we write this without static_cast?

**Review by xezon — APPROVED** [review]

File: Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h (hunk 8 above)
Comment (Caball009) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: Don't think so, a cast is required. It's the same as `ParticleSystemManager`.

Comment (xezon) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: I think bobtista got around this problem by not using ternary operator.

Comment (Caball009) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: https://github.com/TheSuperHackers/GeneralsGameCode/blob/d31c6c54d3e6448bdcb184d46935164dc027ef15/GeneralsMD/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h#L97

I don't see it.

Comment (xezon) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: Maybe it is not yet merged. Not sure. But I have seen it before.

Comment (Caball009) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: What's the next step here?

**Comment by Caball009** [comment]
PR is ready to be merged AFAIC.

The Github CI files should be updated to include the audio files, but that doesn't have to stop this PR from being merged.

File: Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h (hunk 8 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: I tested this.

```cpp
inline Radar *Win32GameEngine::createRadar(Bool dummy) { return dummy ? NEW RadarDummy : NEW W3DRadar; }
```
will cause compile error:

`GeneralsMD\Code\GameEngineDevice\Include\Win32Device\Common\Win32GameEngine.h(100,90): error C2446: ':': no conversion from 'W3DRadar *' to 'RadarDummy *'`

But if you write it like the following, then there will be no compile error.

```cpp
inline Radar *Win32GameEngine::createRadar(Bool dummy)
{
	if (dummy)
		return NEW RadarDummy;
	return NEW W3DRadar;
}
```

I suggest to write all of them like that without the ternary operator and static_cast.

Comment (Caball009) [reply Generals/Code/GameEngineDevice/Include/Win32Device/Common/Win32GameEngine.h]: Tweaked.

File: Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h [hunk 9]
```diff
@@ -330,3 +330,53 @@ class MilesAudioManager : public AudioManager
 
 };
 
+// TheSuperHackers @feature helmutbuhler 17/05/2025 AudioManager that does almost nothing. Useful for headless mode.
+// @bugfix Caball009 26/03/2026 Scripts may require the actual audio file length to function properly, which is important for the CRC computation.
+// The Miles AudioManager handles the device opening / closure, so that getFileLengthMS can function as intended.
+class MilesAudioManagerDummy : public MilesAudioManager
+{
+#if defined(RTS_DEBUG)
+	virtual void audioDebugDisplay(DebugDisplayInterface* dd, void* userData, FILE* fp) {}
```
Comment (xezon) [inline Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h]: Missing override keyword

Comment (Caball009) [reply Core/GameEngineDevice/Include/MilesAudioDevice/MilesAudioManager.h]: Added.

**Comment by xezon** [comment]
Merge this now? There still is 1 open TODO

**Comment by Caball009** [comment]
I've tagged @tintinhamans multiple times, but I'm not sure what the current state of the audio files is. 

Can be merged now AFAIC.
