### PR TITLE
bugfix(ai): Undetected mines can now be approached when using a disarm weapon

### LINKED ISSUE #1874: Dozer stuck inside Command Center when Clear Mines is issued on mined location during exit
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Dozer can get stuck inside the Command Center if the player makes a Clear Mines command on a mined location while the Dozer is still exiting the Command Center.

### Reproduction Steps

1. Start a match as China/USA on a map with mines (e.g., Tiny Tactics).
2. Build a Dozer from the Command Center.
3. While the Dozer is still in the process of leaving the Command Center, do a Clear Mines command on a mined location.
4. The dozer gets stuck inside the command center.

### Additional Context

- The bug happened in the most recent World Series Final between ViViD and ExCaL.
- This is a retail bug.

https://github.com/user-attachments/assets/f396aa69-9391-4be5-b844-9e6b24e3859c

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1874

This change allows undetected mines to be approached when using a disarm weapon.

In the retail game, a worker or dozer refuses to perform a mine disarming command if there are undetected mines at the targeted location. This is because there is no logic in the `AIAttackApproachTargetState` (entered when a weapon is out of range) to accommodate the special-case mine disarming behaviour, and the state returns a fail if the target is stealthed and undetected irrespective of the initial command's success.

### Before
The worker does not proceed to disarm mines

https://github.com/user-attachments/assets/567881f3-b0ae-47ee-8f18-498afbd423e3

### After
The worker proceeds to disarm mines

https://github.com/user-attachments/assets/654b88ba-a794-40fc-87c9-a4bf1ed7484a

### CODE REVIEW

**Comment by bobtista** [comment]
LGTM

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp [hunk 1]
```diff
@@ -2682,7 +2682,15 @@ StateReturnType AIAttackApproachTargetState::updateInternal()
 		}
 		if( victim->testStatus( OBJECT_STATUS_STEALTHED ) && !victim->testStatus( OBJECT_STATUS_DETECTED ) && !victim->testStatus( OBJECT_STATUS_DISGUISED ) )
 		{
+#if RETAIL_COMPATIBLE_CRC
 			return STATE_FAILURE;	// If obj is stealthed, can no longer approach.
+#else
+			Bool isTargetingMine = weapon && weapon->getDamageType() == DAMAGE_DISARM &&
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp]: Can be made `const`.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp [hunk 2]
```diff
@@ -2682,7 +2682,15 @@ StateReturnType AIAttackApproachTargetState::updateInternal()
 		}
 		if( victim->testStatus( OBJECT_STATUS_STEALTHED ) && !victim->testStatus( OBJECT_STATUS_DETECTED ) && !victim->testStatus( OBJECT_STATUS_DISGUISED ) )
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp:2683]: The same condition also exists in `AIAttackPursueTargetState::updateInternal`. Does that need similar treatment?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp [hunk 3]
```diff
@@ -2682,7 +2682,15 @@ StateReturnType AIAttackApproachTargetState::updateInternal()
...
 		{
+#if RETAIL_COMPATIBLE_CRC
 			return STATE_FAILURE;	// If obj is stealthed, can no longer approach.
+#else
+			const Bool isTargetingMine = weapon && weapon->getDamageType() == DAMAGE_DISARM &&
+				(victim->isKindOf(KINDOF_MINE) || victim->isKindOf(KINDOF_BOOBY_TRAP) || victim->isKindOf(KINDOF_DEMOTRAP));
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp:2691]: If the damage type is `DAMAGE_DISARM`, do we even need to test for the target kindof? We assume that all object kinds can be approached if they can be disarmed, no?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp [hunk 4]
```diff
@@ -2682,7 +2682,15 @@ StateReturnType AIAttackApproachTargetState::updateInternal()
...
+
+			if (!isTargetingMine)
+				return STATE_FAILURE;	// If obj is stealthed, can no longer approach - unless we're targeting a mine!
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp]: I suggest move the EA comment up like so:

```
// If obj is stealthed, can no longer approach
// TheSuperHackers @bugfix Except when disarming stealthed mine-like objects
```

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp (hunk 3 above)
Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp:2691]: I intended to prioritise consistency by following the same conditional patterns used in `Weapon.cpp`.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp (hunk 2 above)
Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp:2683]: Assuming this state is dependent on a moving target, I cannot imagine any cases where it makes sense to pursue an undetected moving target, let alone a moving minefield.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp (hunk 3 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp:2691]: Okay. Perhaps we can open an issue report for looking into simplifying these conditions later.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp (hunk 4 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/AI/AIStates.cpp]: Edit was not pushed.
