### PR TITLE
bugfix(object): Fix veterancy effect spawning at the map origin when a veteran unit is produced

### LINKED ISSUE #51: Veterancy animation spawns at 0 0 while unit spawns in building
Veterancy animation spawns at 0 0 while unit spawns in building. Can anything be done about that? Or is this a pure code issue?

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #51

This change fixes the veterancy effect appearing at the map origin for spawned units (produced from buildings, dropped from planes, spawned by scripts, etc.).

It turns out `Object::onVeterancyLevelChanged` has an optional `provideFeedback` parameter for playing the veterancy effect, so the solution was to simply pass `false` to it when called via `ExperienceTracker::setMinVeterancyLevel` (which is only called from the offending `VeterancyGainCreate` module).

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp [hunk 1]
```diff
@@ -93,7 +93,7 @@ void ExperienceTracker::setMinVeterancyLevel( VeterancyLevel newLevel )
 		m_currentLevel = newLevel;
 		m_currentExperience = m_parent->getTemplate()->getExperienceRequired(m_currentLevel); //Minimum for this level
 		if (m_parent)
-			m_parent->onVeterancyLevelChanged( oldLevel, newLevel );
+			m_parent->onVeterancyLevelChanged( oldLevel, newLevel, false );
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp]: How about pass this down from `ExperienceTracker::setMinVeterancyLevel( VeterancyLevel newLevel, Bool provideFeedback )` ? Yes `VeterancyGainCreate::onCreate` is the only caller right now, but technically `setMinVeterancyLevel` could also be used by something that calls it after unit creation.

Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp]: The alternative fix here is that the positioning of the feedback effect on unit creation is fixed. But perhaps that would look too spammy and annoying when many units leave their factories with veterancy effects?

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp]: Sure. I originally considered this but I couldn't think of any circumstances where something would call this after creation instead of `setVeterancyLevel`.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp]: I can't imagine it would be helpful feedback for the player to see this effect every time a veteran unit is produced or spawned.

**Review by xezon — APPROVED** [review]
Looks good.

File: Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp (hunk 1 above)
Comment (Mauller) [reply Generals/Code/GameEngine/Source/GameLogic/Object/ExperienceTracker.cpp]: I was going to say before this got merged that the veterancy create logic is also run long before the objects position is updated and changing the order of this would likely break compatibility.
