### PR TITLE
fix(connection): Implement file content validation for map transfers

### LINKED ISSUE #1817: Map transfers lack file content validation
### Prerequisites

* [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

* [x] Command & Conquer Generals
* [x] Command & Conquer Generals: Zero Hour
* [ ] Other (please specify below)

### Bug Description

The current game lacks file content validation during map transfers. While file extension validation can prevent obviously malicious file types, an attacker could still craft malicious files with valid extensions (.map, .ini, .str, .wak) that contain unexpected or harmful data structures. Without content validation, the game may attempt to parse and execute malformed or malicious data.

### Reproduction Steps

1. Initiate a map transfer in multiplayer
2. Transfer a file with a valid extension (.map, .ini, etc.) but malformed or malicious content
3. Observe that no validation is performed on the actual file contents before processing
4. The game attempts to parse the file without verifying its structure or contents

### Additional Context

This is a security enhancement related to the map transfer system. Issue #272 identified security vulnerabilities in map file transfers, and PR #1058 addressed path traversal. However, additional layers of security are needed:

- File extension validation (proposed in #1816) - ensures only approved file types
- **File content validation (this issue)** - ensures transferred files contain valid, expected data structures

Content validation should verify:
- File headers match expected formats for each file type
- File sizes are within reasonable limits
- Data structures conform to expected schemas
- No embedded executable code or scripts in data files

### PR DESCRIPTION
**Pull request by bobtista**
- Closes #1817

Implements file content validation during map transfer operations to prevent malformed or malicious files from being processed.

## Implementation

Adds `FileSystem::hasValidTransferFileContent()` which validates transferred file content in memory before writing to disk. If validation fails, the file is never written and the transfer is silently aborted.

**Validation methods:**

- **`.map` files** - Validates magic bytes `CkMp` (Chunky Map header)
- **`.ini` files** - Checks for null bytes to ensure text format (rejects binary)
- **`.tga` files** - Validates minimum size (18 bytes for valid TGA header)
- **`.str`, `.txt`, `.wak`** - Size validation only

**Maximum file sizes:**
- `.map`: 5 MB
- `.ini`: 2 MB
- `.str`: 512 KB
- `.txt`: 1 MB
- `.tga`: 2 MB
- `.wak`: 128 KB

### CODE REVIEW

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 1]
```diff
@@ -457,3 +457,174 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	const Int MAX_STR_SIZE = 5 * 1024 * 1024;
+	const Int MAX_TGA_SIZE = 20 * 1024 * 1024;
+	const Int MAX_TXT_SIZE = 5 * 1024 * 1024;
+	const Int MAX_WAK_SIZE = 10 * 1024 * 1024;
+
+#ifdef _WIN32
+	if (_stricmp(lastDot, ".map") == 0)
+#else
+	if (strcasecmp(lastDot, ".map") == 0)
+#endif
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: If we are supporting linux at this time, this should be a macro instead

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 2]
```diff
@@ -457,3 +457,174 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	{
+		if (fileSize > MAX_MAP_SIZE)
+		{
+			DEBUG_LOG(("Map file '%s' exceeds maximum size (%d bytes).", filePath.str(), fileSize));
+			isValid = false;
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: imho, if it is not valid, you should immediately return (and yes, that means closing the file every time). This prevents a possible mistake that isValid is overwritten later on, which would be a security risk.

It would also reduce the number of else statements.

Can you pass the opened File as a parameter in C++? You could then make 2 functions, the validator itself (which does not have to bother about opening/closing files and a container/wrapper that handles the file stuff. This ensures security and proper file handling.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 3]
```diff
@@ -457,3 +457,174 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+#endif
+	{
+		Int maxSize = MAX_STR_SIZE;
+#ifdef _WIN32
+		if (_stricmp(lastDot, ".txt") == 0)
+#else
+		if (strcasecmp(lastDot, ".txt") == 0)
+#endif
+		{
+			maxSize = MAX_TXT_SIZE;
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: This logic is difficult to read. Suggestion:

```cpp
int isStr = (_stricmp(lastDot, ".str") == 0);
int isTxt = (_stricmp(lastDot, ".txt") == 0);

if (isStr || isTxt)
{
    Int maxSize = isTxt ? MAX_TXT_SIZE : MAX_STR_SIZE;

    // other logic
}
```

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 4]
```diff
@@ -457,3 +457,174 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+		file->close();
+		return false;
+	}
+
+	const Int MAX_MAP_SIZE = 50 * 1024 * 1024;
+	const Int MAX_INI_SIZE = 10 * 1024 * 1024;
+	const Int MAX_STR_SIZE = 5 * 1024 * 1024;
+	const Int MAX_TGA_SIZE = 20 * 1024 * 1024;
+	const Int MAX_TXT_SIZE = 5 * 1024 * 1024;
+	const Int MAX_WAK_SIZE = 10 * 1024 * 1024;
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: These sizes are too large
I looked in my map folder, and nothing is exceeding 300 kB. That included highly customized maps like AOD

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 5]
```diff
@@ -742,6 +742,20 @@ void ConnectionManager::processFile(NetFileCommandMsg *msg)
...
+			DEBUG_LOG(("File '%s' failed content validation, deleting.", realFileName.str()));
+			remove(realFileName.str());
+#ifdef COMPRESS_TARGAS
+			if (deleteBuf)
+			{
+				delete[] buf;
+				buf = NULL;
+			}
+#endif
+			return;
```
Comment (Skyaero42) [inline Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: So what happens now? The file is deleted, but the transfer continues. What will the user see? An error message. Does the game crash?

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 4 above)
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: ok dropped sizes

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 1 above)
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: We aren't yet... but while I'm here might as well add it - added STRICMP for cross-platform string comparison.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 2 above)
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: Ok, I split validation into a helper `validateFileContent()` that takes the opened File as a parameter, and refactored to use early returns. The wrapper function handles file opening/closing

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp (hunk 5 above)
Comment (bobtista) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Not exactly, but I don't think it's ideal either, because the timeout is I think set to 2 minutes, which is forever in today time. 
If I understand correctly, the transfer is silently aborted (file deleted, no progress message sent). The sender will timeout waiting for progress confirmation, so they'll see 0% and will be stuck waiting for 2 minutes - practically speaking they're likely to ctrl alt delete (I would). If not, I haven't tested this yet, but I think they'd get returned to whatever menu they were in before they tried to transfer the map

Comment (Skyaero42) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: If the timer times out, you go back to the main room where you can join or create games.

That begs the following question: Do we need to adjust the timeout to 1 minute?

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 4 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: I was made aware by Ibra/MrS that there are maps that are over half a MB in size. So this will need additional research on what good thresholds are.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 6]
```diff
@@ -49,6 +49,12 @@
 #include "Common/file.h"
 #include "Common/FileSystem.h"
 
+#ifdef _WIN32
+#define STRICMP(s1, s2) _stricmp(s1, s2)
+#else
+#define STRICMP(s1, s2) strcasecmp(s1, s2)
+#endif
+
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Maybe globalize this? Not sure where to put it yet.
I was thinking `CppMacros.h`, but that is more for VC6 compatibility
`compat.h` has a `_WIN32` check, so maybe thats where linux stuff can also go?

Would like to have input from others here

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 7]
```diff
@@ -457,3 +463,125 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+//============================================================================
+// FileSystem::hasValidTransferFileContent
+//============================================================================
+// TheSuperHackers @security bobtista 06/11/2025
+// Validates file content format during map transfer operations.
+// Checks file headers, magic bytes, size limits, and basic structure to prevent
+// malformed or malicious files from being processed.
+//============================================================================
+static Bool validateFileContent(File* file, const AsciiString& filePath, const char* extension)
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: There is a lot of duplicate code here. I think I would create a map/dictionary (I don't know what it is called in C++) with the extension as key and max size as value.

First would be to find the extension (if not there -> return) and then check filesize. This can all be done in a separate method. This keeps the logic a lot more concise.

But I would like another opinion on that.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 4 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: Based on conversations with a number of map makers, 2 MB at the moment is possible (the largest map file currently known), but almost impossible to play. However, with TSH optimizations it may be possible in the future. 

5 MB per file seems to be on the very safe side of things, while from a security perspective is still small. So I think that would be a good value.

**Comment by xezon** [comment]
Were all comments from SkyAero worked on?

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp (hunk 5 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: For now this is addressed

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 8]
```diff
@@ -457,3 +463,125 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	const Int MAX_STR_SIZE = 512 * 1024;
+	const Int MAX_TGA_SIZE = 2 * 1024 * 1024;
+	const Int MAX_TXT_SIZE = 512 * 1024;
+	const Int MAX_WAK_SIZE = 512 * 1024;
+
+	if (STRICMP(extension, ".map") == 0)
+	{
+		if (fileSize > MAX_MAP_SIZE)
+		{
+			DEBUG_LOG(("Map file '%s' exceeds maximum size (%d bytes).", filePath.str(), fileSize));
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Instead of `filePath`, would `file->getName()` work here?

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 7 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: This looks better now

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 6 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: @xezon I need a second opinion on this. Keep the macro in this file or move it somewhere else?

Comment (xezon) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: Check string_compat.h

```
#define stricmp strcasecmp
```

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 9]
```diff
@@ -742,6 +742,22 @@ void ConnectionManager::processFile(NetFileCommandMsg *msg)
 		fp = NULL;
 		DEBUG_LOG(("Wrote %d bytes to file %s!", len, realFileName.str()));
 
+		// TheSuperHackers @security bobtista 06/11/2025 Validate file content after writing
+		if (!FileSystem::hasValidTransferFileContent(realFileName))
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Why is this validated after write? Better validate when in memory, before file write.

**Review by Skyaero42 — DISMISSED** [review]
This looks good to me.
Nice security addition to the game.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 10]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+
+	static const TransferFileRule transferFileRules[] =
+	{
+		{ ".map", 5 * 1024 * 1024 },
+		{ ".ini", 512 * 1024 },
+		{ ".str", 512 * 1024 },
+		{ ".txt", 512 * 1024 },
+		{ ".tga", 2 * 1024 * 1024 },
+		{ ".wak", 512 * 1024 },
+	};
```
[the remark this answers is not in the document]
Comment (xezon) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: What is going on here?

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 11]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+		if (dataSize < 4 || data[0] != 'C' || data[1] != 'k' || data[2] != 'M' || data[3] != 'p')
+		{
+			DEBUG_LOG(("Map file '%s' has invalid magic bytes.", filePath.str()));
+			return false;
+		}
+	}
+	else if (stricmp(lastDot, ".ini") == 0)
+	{
+		// Check for null bytes to ensure text format
+		Int bytesToCheck = dataSize < 512 ? dataSize : 512;
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: std::max

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 12]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	{
+		DEBUG_LOG(("File '%s' exceeds maximum size (%d bytes, limit %d bytes).", filePath.str(), dataSize, matchedRule->maxSize));
+		return false;
+	}
+
+	// Extension-specific content validation
+	if (stricmp(lastDot, ".map") == 0)
+	{
+		// Validate magic bytes "CkMp"
+		if (dataSize < 4 || data[0] != 'C' || data[1] != 'k' || data[2] != 'M' || data[3] != 'p')
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Perhaps simplify with memcmp

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 13]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+			if (data[i] == 0)
+			{
+				DEBUG_LOG(("INI file '%s' contains null bytes (likely binary).", filePath.str()));
+				return false;
+			}
+		}
+	}
+	else if (stricmp(lastDot, ".tga") == 0)
+	{
+		// Validate minimum TGA header size
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Check

https://chatgpt.com/s/t_698f705bf1dc8191a5f833d59d10f32d

https://chatgpt.com/s/t_698f70835cec8191ae73b99a5ba73bcb

I do see "TRUEVISION-XFILE." at the bottom of Game TGA file, so can go with that.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 14]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+// content in memory before writing to disk.
+Bool FileSystem::hasValidTransferFileContent(const AsciiString& filePath, const UnsignedByte* data, Int dataSize)
+{
+	struct TransferFileRule
+	{
+		const char* ext;
+		Int maxSize;
+	};
+
+	static const TransferFileRule transferFileRules[] =
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: I suggest move this and the struct outside the function into an anonymous namespace or the FileSystem class to tidy this up.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 15]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	const char* lastDot = strrchr(filePath.str(), '.');
+	if (lastDot == nullptr)
+	{
+		DEBUG_LOG(("File '%s' has no extension for content validation.", filePath.str()));
+		return false;
+	}
+
+	// Find matching rule by extension
+	const TransferFileRule* matchedRule = nullptr;
+	for (Int i = 0; i < ARRAY_SIZE(transferFileRules); ++i)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Better make this a separate function `getTransferFileRule` to keep this function tidy.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 16]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+
+	// Check size limit
+	if (dataSize > matchedRule->maxSize)
+	{
+		DEBUG_LOG(("File '%s' exceeds maximum size (%d bytes, limit %d bytes).", filePath.str(), dataSize, matchedRule->maxSize));
+		return false;
+	}
+
+	// Extension-specific content validation
+	if (stricmp(lastDot, ".map") == 0)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: This is not great because it basically repeats what was already done in the loop above to find the `matchedRule`.

I suggest introduce an `enum TransferFileType` and a function `getTransferFileType(const char* fileName)` and then go from there write more readable code (e.g. use enum value for switch case or array indexing).

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: Updated the PR description to match the code

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 11 above)
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: I think std::min here actually

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 17]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+		break;
+	}
+
+	case TRANSFER_FILE_TGA:
+		if (dataSize < 18)
+		{
+			DEBUG_LOG(("TGA file '%s' is too small to be valid (minimum 18 bytes).", filePath.str()));
+			return false;
+		}
+		if (memcmp(data + dataSize - 18, "TRUEVISION-XFILE.", 18) != 0)
```
[the remark this answers is not in the document]
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: The offset is correct — you can verify in Core/Libraries/Source/WWVegas/WWLib/TARGA.h:134-142:
```
  typedef struct _TGA2Footer {
      long Extension;    // 4 bytes (offset 0 from footer start)
      long Developer;    // 4 bytes (offset 4)
      char Signature[16]; // 16 bytes (offset 8)
      char RsvdChar;     // 1 byte '.' (offset 24)
      char BZST;         // 1 byte '\0' (offset 25)
  } TGA2Footer;          // 26 bytes total
```
  The Signature field starts at footer offset 8, which is EOF - 18 (26 - 8). Our memcmp(data +
  dataSize - 18, "TRUEVISION-XFILE.", 18) checks exactly Signature + RsvdChar + BZST — the last 18
  bytes. Starting at dataSize - 26 would read the Extension and Developer fields instead.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 11 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: min indeed

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 18]
```diff
@@ -457,3 +457,93 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
 
 	return true;
 }
+
+//============================================================================
+// FileSystem::hasValidTransferFileContent
+//============================================================================
+// TheSuperHackers @security bobtista 12/02/2026 Validates transferred file
+// content in memory before writing to disk.
+Bool FileSystem::hasValidTransferFileContent(const AsciiString& filePath, const UnsignedByte* data, Int dataSize)
```
Comment (Caball009) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: `Int dataSize`
Can we use `UnsignedInt` here and all the way back to the source? (`msg->getFileLength()`)

`Int maxSize`
Would then also have to be changed.

Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: I changed it for the things I added, should changing the rest of this be its own PR?

Comment (xezon) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: Please do not touch CommandMsg at this time. A big refactor is in the works.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 19]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+
+enum TransferFileType
+{
+	TRANSFER_FILE_MAP,
+	TRANSFER_FILE_INI,
+	TRANSFER_FILE_STR,
+	TRANSFER_FILE_TXT,
+	TRANSFER_FILE_TGA,
+	TRANSFER_FILE_WAK,
+	TRANSFER_FILE_COUNT
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Please use non macro case.

TransferFileType_Map,
TransferFileType_Ini,
...

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 20]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+struct TransferFileRule
+{
+	const char* ext;
+	UnsignedInt maxSize;
+	TransferFileType type;
+};
+
+const TransferFileRule transferFileRules[] =
+{
+	{ ".map", 5 * 1024 * 1024, TRANSFER_FILE_MAP },
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Type is not necessary in here. The type is implicit by the Index position in this array.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 21]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	{ ".ini", 512 * 1024, TRANSFER_FILE_INI },
+	{ ".str", 512 * 1024, TRANSFER_FILE_STR },
+	{ ".txt", 512 * 1024, TRANSFER_FILE_TXT },
+	{ ".tga", 2 * 1024 * 1024, TRANSFER_FILE_TGA },
+	{ ".wak", 512 * 1024, TRANSFER_FILE_WAK },
+};
+
+const TransferFileRule* getTransferFileRule(const char* extension)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Better make function:

```cpp
TransferFileType getTransferFileType(const char* fileName)
```

Then use enum value as index into arrays.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 22]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	{
+		DEBUG_LOG(("File '%s' exceeds maximum size (%u bytes, limit %u bytes).", filePath.str(), dataSize, rule->maxSize));
+		return false;
+	}
+
+	// Extension-specific content validation
+	switch (rule->type)
+	{
+	case TRANSFER_FILE_MAP:
+		if (dataSize < 4 || memcmp(data, "CkMp", 4) != 0)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Style: Better use {} consistently

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 23]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+		{
+			DEBUG_LOG(("Map file '%s' has invalid magic bytes.", filePath.str()));
+			return false;
+		}
+		break;
+
+	case TRANSFER_FILE_INI:
+	{
+		UnsignedInt bytesToCheck = std::min(dataSize, 512u);
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: const

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 18 above)
Comment (Caball009) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: > I changed it for the things I added, should changing the rest of this be its own PR?

Yeah, that's fine imo,

It's hard to imagine that the value would or could be negative, but `hasValidTransferFileContent` should now catch it at least. 

Even if the larger context would make it impossible for the value to be negative, I think there's value in making functions clearer and more secure at a 'local' level (within reason).

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 24]
```diff
@@ -457,3 +457,121 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+		break;
+	}
+
+	case TRANSFER_FILE_TGA:
+		if (dataSize < 44)
+		{
+			DEBUG_LOG(("TGA file '%s' is too small to be valid (minimum header 18 + footer 26 = 44 bytes).", filePath.str()));
+			return false;
+		}
+		if (memcmp(data + dataSize - 18, "TRUEVISION-XFILE.", 18) != 0)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Perhaps memcpy into _TGA2Footer, then do memcmp ?

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 25]
```diff
@@ -457,3 +458,130 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+} // namespace
+
+//============================================================================
+// FileSystem::hasValidTransferFileContent
+//============================================================================
+// TheSuperHackers @security bobtista 12/02/2026 Validates transferred file
+// content in memory before writing to disk.
+Bool FileSystem::hasValidTransferFileContent(const AsciiString& filePath, const UnsignedByte* data, UnsignedInt dataSize)
+{
+	const char* lastDot = strrchr(filePath.str(), '.');
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Better name this fileExt

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 26]
```diff
@@ -457,3 +458,130 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	if (lastDot == nullptr)
+	{
+		DEBUG_LOG(("File '%s' has no extension for content validation.", filePath.str()));
+		return false;
+	}
+
+	const TransferFileType fileType = getTransferFileType(lastDot);
+	if (fileType == TransferFileType_Count)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Better add a TransferFileType_Invalid = -1 value. Is more explicit.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 27]
```diff
@@ -457,3 +458,130 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+{
+	{ ".map", 5 * 1024 * 1024 },
+	{ ".ini", 512 * 1024 },
+	{ ".str", 512 * 1024 },
+	{ ".txt", 512 * 1024 },
+	{ ".tga", 2 * 1024 * 1024 },
+	{ ".wak", 512 * 1024 },
+};
+
+TransferFileType getTransferFileType(const char* extension)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: On second thought, the way you had it before with returning the `const TransferFileRule*` as pointer was actually better than my suggestion, because it avoids "unsafe" indexing into the array later on. The advantage of the enum value approach is however that it is more versatile, for example it can work on a second array too.

Both are fine.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 28]
```diff
@@ -457,3 +458,130 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+		if (dataSize < sizeof(TGAHeader) + sizeof(TGA2Footer))
+		{
+			DEBUG_LOG(("TGA file '%s' is too small to be valid.", filePath.str()));
+			return false;
+		}
+		TGA2Footer footer;
+		memcpy(&footer, data + dataSize - sizeof(footer), sizeof(footer));
+		if (memcmp(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature)) != 0
+			|| footer.RsvdChar != '.'
+			|| footer.BZST != '\0')
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Maybe make it

```cpp
const Bool isTGA2 = memcmp(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature)) == 0 && footer.RsvdChar == '.' && footer.BZST == '\0';
if (!isTGA2)
  ...
```

Either way is fine.

**Review by xezon — APPROVED** [review]
Looking good.

**Review by xezon — APPROVED** [review]

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 29]
```diff
@@ -734,6 +735,20 @@ void ConnectionManager::processFile(NetFileCommandMsg *msg)
 	}
 #endif // COMPRESS_TARGAS
 
+	// TheSuperHackers @security bobtista 12/02/2026 Validate file content in memory before writing to disk
+	if (!FileSystem::hasValidTransferFileContent(realFileName, buf, len))
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: I just realize now, this function ideally is not part of FileSystem, because the FileSystem does not care about network file transfers. All of this should go into the Connection Manager where it is actually used.

**Review by xezon — CHANGES_REQUESTED** [review]

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp (hunk 29 above)
Comment (bobtista) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Done

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 30]
```diff
@@ -378,3 +457,4 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
 
 	return true;
 }
+
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Superfluous new line added

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 31]
```diff
@@ -84,44 +86,165 @@ static Bool hasValidTransferFileExtension(const AsciiString& filePath)
...
+	{
+		if (stricmp(extension, transferFileRules[i].ext) == 0)
+		{
+			return static_cast<TransferFileType>(i);
+		}
+	}
+	return TransferFileType_Invalid;
+}
+
+// TheSuperHackers @security bobtista 12/02/2026 Validates transferred file
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Duplicate comment can be removed.

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 32]
```diff
@@ -52,6 +53,7 @@
 #include "GameLogic/VictoryConditions.h"
 #include "GameClient/DisconnectMenu.h"
 #include "GameClient/InGameUI.h"
+#include "TARGA.h"
 
 static Bool hasValidTransferFileExtension(const AsciiString& filePath)
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp:58]: When this is merged, can you make a follow refactor and merge this logic with the new stuff added below? It looks like this function can be greatly simplified.

See `getTransferFileType`

**Review by xezon — DISMISSED** [review]

File: Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 33]
```diff
@@ -84,44 +86,163 @@ static Bool hasValidTransferFileExtension(const AsciiString& filePath)
...
+};
+
+static const TransferFileRule transferFileRules[TransferFileType_Count] =
+{
+	{ ".map", 5 * 1024 * 1024 },
+	{ ".ini", 512 * 1024 },
+	{ ".str", 512 * 1024 },
+	{ ".txt", 512 * 1024 },
+	{ ".tga", 2 * 1024 * 1024 },
+	{ ".wak", 512 * 1024 },
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: I was about to merge this change, but looking over these sizes I do wonder how they came to be. TGA size looks pretty big, INI maybe too small for a massive Mod Map?

And why is TXT there? Does the game actually transfer it?

Also, I think we need to make these values configurable in an INI file, so that Mods can customize file transfer limits.

Comment (Skyaero42) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: According to Kabuse, a 2 MB map is already insane, so 5 MB is on the safe side.
.str, .wak and .txt are always small, so 512 kb is more then enough.
Can't find the data on .tga and ini anymore. I think tga is fine, ini may need to go to 1 MB.

I would be against a configurable ini. This would defeat the purpose of the security measure as a malicious host could still transfer large files.

Comment (Caball009) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: HLH - Black Dawn has a map.ini file slightly larger than 1024 KB fwiw.

Comment (xezon) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: > I would be against a configurable ini. This would defeat the purpose of the security measure as a malicious host could still transfer large files.

Can you elaborate on this security threat? How would that work?

Comment (Skyaero42) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: > > I would be against a configurable ini. This would defeat the purpose of the security measure as a malicious host could still transfer large files.
> 
> Can you elaborate on this security threat? How would that work?

Uncapped file size in general poses a security thread (denial of service), which could lead to overfilled memory and/or disk - causing game or computer crash.

The 2 minute timeout in the transfer window partially that infinite dos isn't possible - which alleviates some of the thread.

File size of transfers should be capped in the application for proper security. Allowing users to configure that as an option defeats the purpose of such a cap.

Make it 5 or 10 MB if you want to play it safe, but I think it is better to understand what a realistic filesize is for each type. I've got 500 maps installed on my PC, the largest files are .tga and .map, each still well under 1 MB, so we are looking at the extreme maps.

Based on @Caball009 feedback, ini may have to go to 2 MB, but the rest should be good.

Comment (xezon) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: > Allowing users to configure that as an option defeats the purpose of such a cap.

It still is unclear how that would become an issue. INI file settings are local. If the local user does not change them, then there is no threat level for his local machine.

The INI configurability allows Mod Creators to customize the limits for when they ship larger content than the base game does.

Comment (Skyaero42) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: I see your point. Agreed, making this configurable in the ini options gives mod creators the freedom they need.

Comment (mirelle7) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: No legitimate mod maker is going to instruct a player in the match chat to go edit their .ini files; if we're priming users to make local security changes based on lobby chat, we have much bigger problems than file size limits, the threat is social not technical.
We have GenHub for larger mods and we shouldn't increase the configuration surface here. Adding a file limit user option implies we also have to add a configurable timeout limit. I think bobtista original approach is the correct one.

Comment (xezon) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: > No legitimate mod maker is going to instruct a player in the match chat to go edit their .ini files

That is not the intent. The intent is that the Mod Creator can customize these limits that previously did not exist, if he knows that his Mod has different requirements than the retail game content.

Comment (bobtista) [reply Core/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Ok I downloaded 2k+ maps and found the average and max sizes for things, and combined it with the feedback from here. With the most recent commit, this should be good - if somehow future maps ever exceed these limits, we can adjust

**Review by xezon — APPROVED** [review]

**Comment by Caball009** [comment]
@bobtista I see the magic bytes `CkMp` in my .map files but only at offset 14.

**Comment by bobtista** [comment]
> @bobtista I see the magic bytes `CkMp` in my .map files but only at offset 14.

it's written in DataChunk.cpp (DataChunkTableOfContents::write()):                                                                
  Byte tag[4]={'C','k', 'M', 'p'};
  s.write(tag, sizeof(tag));

But now looking again, it later gets compressed and ends up at another offset eg 14. I'll look into a fix...
