### PR TITLE
[GEN][ZH] Fix uninitialized memory access in Get_OS_Info

### LINKED ISSUE #97: Game crashes on launch when IdealStaticGameLOD setting is missing from Options.ini
Game crashes on launch when `IdealStaticGameLOD` setting is missing from **Options.ini** file. Reproducible on Windows 10. **Options.ini** is meant to be generated on first launch, but game cannot do this because likely function that evaluates default setting for `IdealStaticGameLOD` crashes the process.

Crash can be avoided by creating Options.ini file in
"%USERPROFILE%\Documents\Command and Conquer Generals Zero Hour Data"
with `IdealStaticGameLOD = Low` written in it.

Callstack
```
>	game.dat!007d1a0f() 	
 	[Frames below may be incorrect and/or missing, no symbols loaded for game.dat]	
 	game.dat!007d199d() 	
 	game.dat!007d1932() 	
 	game.dat!007d1816() 	
 	game.dat!00785206() 	
 	game.dat!007851d2() 	
 	ntdll.dll!_ZwSetInformationThread@16()  + 0xc bytes	
 	KernelBase.dll!SetThreadPriority()  + 0x49 bytes	
```

Code
```
007D19EE  nop              
007D19EF  nop              
007D19F0  push        ebx  
007D19F1  push        ebp  
007D19F2  push        esi  
007D19F3  mov         esi,dword ptr [esp+14h] 
007D19F7  push        edi  
007D19F8  mov         edi,dword ptr [esp+14h] 
007D19FC  mov         eax,esi 
007D19FE  mov         ebx,65h 
007D1A03  mov         ecx,edi 
007D1A05  mov         edx,65h 
007D1A0A  sub         ecx,esi 
007D1A0C  mov         ebp,dword ptr [ecx+eax] 
007D1A0F  mov         dword ptr [eax],ebp 
007D1A11  add         eax,4 
007D1A14  dec         edx  
007D1A15  jne         007D1A0C 
007D1A17  dec         ebx  
007D1A18  jne         007D1A03 
007D1A1A  pop         edi  
007D1A1B  pop         esi  
007D1A1C  pop         ebp  
007D1A1D  pop         ebx  
007D1A1E  ret   
```

Registers
```
EAX = 05AC1000 EBX = 0000001C ECX = FFFE21D4 EDX = 0000004B ESI = 05AB9C64 EDI = 05A9BE38 EIP = 007D1A0F ESP = 0019AF78 EBP = 0002856A EFL = 00010206 

05AC1000 = ???????? 
```

### LINKED ISSUE #437: Startup crash: Bad memory access in `CPUDetectClass::Init_Compact_Log`
### Area(s) with this issue?

_No response_

### Describe the issue

Init_Compact_Log doesn't zero-initialize the `os_info` object, and `Get_OS_Info` isn't guaranteed to initialize all of the members either. This is causing a startup crash, especially on the VS2022 branch, whenever `os_info.Code` happens to pick up non-zero garbage data.

This ticket is to fix that by always initializing the values in `Get_OS_Info`, instead.

Will open a PR for this shortly.

### Steps to reproduce

1. Startup game
2. Be unlucky
3. Observe crash
4. If you have a debugger attached, observe the crash occurring when calling `COMPACTLOG` below.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by JAJames**
* Fixes #437

Changes below are minimal

Analysis:
* `generals.exe` was crashing in `CPUDetectClass::Init_Compact_Log` when attempting to log the `Code` and `SubCode` strings on `os_info`, due to them being initialized with garbage data.
* This was caused because there were not entries for any Windows newer than XP
* This was also caused because the `os_info` object was not default-initialized with any sane values

Changes:
1) Moved the zero-initialization from the `default` block, to just always execute first instead, so that it's guaranteed to be zero-initialized and set
2) Added entries for Windows Vista/7/8/8.1/10/11
3) Added a fallback entry for versions otherwise not detected
4) My IDE ate the micro symbol, I suppose because the source file isn't actually stored as UTF-8, but some other encoding instead. Instead of dwelling on it, I just replaced it with the letter `u`.

Impact:
* Startup no longer crashes here (instead, I now crash due to an INI parsing issue)
* I don't think this actually affects anything else however, except for logs.

### CODE REVIEW

File: GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp [hunk 1]
```diff
@@ -1068,7 +1068,7 @@ void CPUDetectClass::Init_Processor_Log()
 	}
 
 	if (CPUDetectClass::Get_L1_Instruction_Trace_Cache_Size()) {
-		SYSLOG(("L1 Instruction Trace Cache: %d way set associative, %dk �OPs\r\n",
+		SYSLOG(("L1 Instruction Trace Cache: %d way set associative, %dk uOPs\r\n",
```
Comment (VodkaPotato) [inline GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp]: ~~Why was this character changed?~~ Nevermind, reread the description, see point 4.

Comment (JAJames) [reply GeneralsMD/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp]: Apparently, someone else changed it to the word "micro" in main anyways!

**Comment by VodkaPotato** [comment]
Be advised CPUDetectClass::Init_OS on Win10 will initialize that we have version Major 6 and minor 2, and therefore we get windows 8.0 as the reported OS!
image
image

**Review by xezon — APPROVED** [review]

File: Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp [hunk 2]
```diff
@@ -1265,12 +1265,14 @@ void Get_OS_Info(
 	unsigned build_minor=(OSVersionBuildNumber&0xff0000)>>16;
 	unsigned build_sub=(OSVersionBuildNumber&0xffff);
 
+	// Fill os_info with default values, before anything else
+	memset(&os_info,0,sizeof(os_info));
+	os_info.Code="UNKNOWN";
+	os_info.SubCode="UNKNOWN";
+	os_info.VersionString="UNKNOWN";
+
```
Comment (Niko1879) [inline Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp:1273]: Could we default initialise in the `OSInfoStruct` definition instead, and remove the memset?

Comment (xezon) [reply Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp:1273]: Replaced memset with 0 initialization.

Edit: That did not compile with vs6. Returning to the mighty memset.

**Comment by xezon** [comment]
> Be advised CPUDetectClass::Init_OS on Win10 will initialize that we have version Major 6 and minor 2

I can confirm this also happens on my machine.

Other than that, fix works correctly and **prevents crashing when the Options.ini is absent**.
