### PR TITLE
[GEN][ZH] Fix security issue in map transfer by validating file paths when creating real paths from portable paths

### LINKED ISSUE #272: Security issues in the code
Since this seems to be turning into an active fork which is amazing, you might be interested in this: https://chaos.social/@gsuberland/114077566516453231 It seems like there are some problem with potentially writing to people's disk via remote attacks.

### PR DESCRIPTION
**Pull request by slurmlord**
* Relates to #272

_The discussion in #272 is quite detailed, so the summary here is briefer. Please refer to the original discussion if there are sections here that are unclear, as they are probably already explained more eloquently there._

# The Problem
The game has a concept of "Portable Map Paths", where the path to a map/file is stored relative to a well-known base path. The 3 base paths that can be used are "Save\", "Maps\" and "UserData\Maps\", and are used as the start of the Portable Map Path.
The `GameState::portableMapPathToRealMapPath` function is used to convert a Portable Map Path to a real path on disk, by prefixing the Portable Map Path with a local directory. As an example, the corresponding real map path for the Portable Map Path `Save\SomeFile.bin` would be something like `C:\Users\username\Documents\Command and Conquer Generals Zero Hour Data\Save\SomeFile.bin`.
The issue is that a Portable Map Path could contain troublesome path components, like `..\..\..\` or similar, which when merged with the intended base path actually ends up _outside_ the intended base path . Expanding the previous example, the Portable Map Path `Save\..\..\..\..\..\windows\system32\Some.exe` would actually end up as `c:\windows\system32\some.exe`.
Some places (loading save games, network map transfers) these Portable Map Paths are used for defining where a file should be saved to, so in practice a malicious Portable Map Path could be used to overwrite arbitrary files on the user's system.

# The Solution
When combining the Portable Map Path with the base path in `GameState::portableMapPathToRealMapPath`, validate that the resulting absolute path is within the base path. This validation is done by normalizing the absolute path and comparing it to the normalized base path. If the normalized absolute path does not start with the normalized base path, the Portable Map Path is considered invalid and an error is returned.
In order to facilitate this, the LocalFileSystem implementations get a new `normalizePath` method, which is implemented via the `GetFullPathName` Win32 function, and `std::filesystem::path::lexically_normal`. This function is then exposed through FileSystem, as the underlying LocalFileSystem implementation is not public.

The major change is that now `GameState::portableMapPathToRealMapPath` _can_ return an empty string in case of a troublesome Portable Map Path. As far as I can see, a malicious Portable Map Path could come from a save file or a map transfer. Both of these now recognize the condition and semi-gracefully degrades (no explicit message as to what went wrong to the user, but no overwrite of unwanted files either).

### CODE REVIEW

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp [hunk 1]
```diff
@@ -339,3 +339,14 @@ Bool StdLocalFileSystem::createDirectory(AsciiString directory)
 	}
 	return result;
 }
+
+AsciiString StdLocalFileSystem::normalizePath(const AsciiString& filePath) const
+{
+	std::string nonNormalized(filePath.str());
+#ifndef _WIN32
+	// Replace backslashes with forward slashes on unix
+	std::replace(unNormalized.begin(), unNormalized.end(), '\\', '/');
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:348]: I think std::filesystem::path does this already upon initialization / assignment, and if not, it has a member function for it: `std::filesystem::path::make_preferred`.

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp [hunk 2]
```diff
@@ -339,3 +339,14 @@ Bool StdLocalFileSystem::createDirectory(AsciiString directory)
...
+#endif
+	std::filesystem::path pathNonNormalized(nonNormalized);
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:350]: `std::filesystem::path` is C++17 so it's not compatible with VC6's C++98.

edit: I must be overlooking something as the VC6 build was successful.

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp (hunk 1 above)
Comment (slurmlord) [reply GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:348]: Yeah, I thought so, too, but then as I read https://en.cppreference.com/w/cpp/filesystem/path/make_preferred.html my understanding is now that since backslash is considered a valid character in a POSIX file name, it will not be replaced by make_preferred? Thus the "heavy-handed" approach.

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp (hunk 2 above)
Comment (slurmlord) [reply GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:350]: Yep, VC6 will use the Win32LocalFileSystem implementation instead.

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp (hunk 1 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp:348]: It looks you're right about that: https://godbolt.org/z/ebhexrE6s Notice how only MSVC converts both paths to a consistent format.

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp [hunk 3]
```diff
@@ -902,37 +902,86 @@ AsciiString GameState::realMapPathToPortableMapPath(const AsciiString& in) const
...
+		DEBUG_CRASH(("Unable to normalize base directory path '%s'.\n", basePath.str()));
+		return false;
+	}
+	else if (filePathNormalized.isEmpty())
+	{
+		DEBUG_CRASH(("Unable to normalize file path '%s'.\n", testPath.str()));
+		return false;
+	}
+#ifdef _WIN32
+	if (!basePathNormalized.endsWith("\\"))
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: This code can become easier to read with a

```cpp
#ifdef _WIN32
  const char* pathSep = "\\";
#else
  const char* pathSep = "/";
#endif
```

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp [hunk 4]
```diff
@@ -902,37 +902,86 @@ AsciiString GameState::realMapPathToPortableMapPath(const AsciiString& in) const
...
+	}
+
+	if (!filePathNormalized.startsWithNoCase(basePathNormalized))
+#else
+	if (!basePathNormalized.endsWith("/"))
+	{
+		basePathNormalized.concat("/");
+	}
+
+	if (!filePathNormalized.startsWith(basePathNormalized))
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: Better write this as

```cpp
#ifdef _WIN32
  if (!filePathNormalized.startsWithNoCase(basePathNormalized))
#else
  if (!filePathNormalized.startsWith(basePathNormalized))
#endif
```

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp [hunk 5]
```diff
@@ -902,37 +902,86 @@ AsciiString GameState::realMapPathToPortableMapPath(const AsciiString& in) const
...
+		return AsciiString::TheEmptyString;
+	}
+
 	prefix.toLower();
 	return prefix;
 }
 
+Bool GameState::isPathInDirectory(const AsciiString& testPath, const AsciiString& basePath) const
+{
+	AsciiString filePathNormalized = TheFileSystem->normalizePath(testPath);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: I suggest keep using same terminology "test" for derived strings for clarity.

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp [hunk 6]
```diff
@@ -902,37 +902,86 @@ AsciiString GameState::realMapPathToPortableMapPath(const AsciiString& in) const
...
+	if (!isPathInDirectory(prefix, containingBasePath))
+	{
+		return AsciiString::TheEmptyString;
+	}
+
 	prefix.toLower();
 	return prefix;
 }
 
+Bool GameState::isPathInDirectory(const AsciiString& testPath, const AsciiString& basePath) const
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: It looks as if this can be a static function.

Perhaps it would also be a better fit somewhere in the file system files, if it could be useful for other code in the future?

File: Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 7]
```diff
@@ -688,7 +688,16 @@ void ConnectionManager::processFile(NetFileCommandMsg *msg)
 	DEBUG_LOG(("%ls\n", log.str()));
 #endif
 
-	if (TheFileSystem->doesFileExist(msg->getRealFilename().str()))
+	AsciiString realFileName = msg->getRealFilename();
+	DEBUG_ASSERTLOG((!realFileName.isEmpty(), "Got a file name transferred that failed to normalize: '%s'!\n", msg->getPortableFilename().str()));
+
+	if (realFileName.isEmpty())
+	{
+		// As the file name failed to normalize (in other words is bogus), do nothing and let the transfer time out.
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Please add a `TheSuperHackers @security` prefix here.

File: Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp [hunk 8]
```diff
@@ -1044,7 +1044,14 @@ Bool ParseAsciiStringToGameInfo(GameInfo *game, AsciiString options)
 			mapName.concat(token);
 			mapName.concat('.');
 			mapName.concat(TheMapCache->getMapExtension());
-			mapName = TheGameState->portableMapPathToRealMapPath(mapName);
+			AsciiString realMapName = TheGameState->portableMapPathToRealMapPath(mapName);
+			if (realMapName.isEmpty())
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp:1048]: I think this warrants a `TheSuperHackers @security` comment with explanation.

File: Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp [hunk 9]
```diff
@@ -214,3 +214,16 @@ Bool Win32LocalFileSystem::createDirectory(AsciiString directory)
 	}
 	return FALSE;
 }
+
+AsciiString Win32LocalFileSystem::normalizePath(const AsciiString& filePath) const
+{
+	TCHAR normalizeBuffer[MAX_PATH];
+	DWORD charsWritten = GetFullPathName(filePath.str(), MAX_PATH, normalizeBuffer, NULL);
+	if (charsWritten == 0 || charsWritten > MAX_PATH)
```
Comment (xezon) [inline Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp]: Instead of using `normalizeBuffer[MAX_PATH]` we could call `GetFullPathName` once with a zero buffer to get the required length, and then allocate a AsciiString buffer with the necessary length, and then call `GetFullPathName` a second time with the AsciiString buffer.

File: GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp [hunk 10]
```diff
@@ -339,3 +339,14 @@ Bool StdLocalFileSystem::createDirectory(AsciiString directory)
 	}
 	return result;
 }
+
+AsciiString StdLocalFileSystem::normalizePath(const AsciiString& filePath) const
+{
+	std::string nonNormalized(filePath.str());
+#ifndef _WIN32
+	// Replace backslashes with forward slashes on unix
```
Comment (xezon) [inline GeneralsMD/Code/GameEngineDevice/Source/StdDevice/Common/StdLocalFileSystem.cpp]: This comment says "unix" but the code refers to anything non-windows.

File: Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 11]
```diff
@@ -688,7 +688,16 @@ void ConnectionManager::processFile(NetFileCommandMsg *msg)
 	DEBUG_LOG(("%ls\n", log.str()));
 #endif
 
-	if (TheFileSystem->doesFileExist(msg->getRealFilename().str()))
+	AsciiString realFileName = msg->getRealFilename();
+	DEBUG_ASSERTLOG((!realFileName.isEmpty(), "Got a file name transferred that failed to normalize: '%s'!\n", msg->getPortableFilename().str()));
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Parentheses look wrong here.

Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: This path is coming from the network, right? Why is this an assert?

Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Assert condition is redundant, by moving it into the scope below.

File: Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp [hunk 12]
```diff
@@ -1044,7 +1044,14 @@ Bool ParseAsciiStringToGameInfo(GameInfo *game, AsciiString options)
...
+			{
+				optionsOk = FALSE;
+				DEBUG_LOG(("ParseAsciiStringToGameInfo - saw bogus map name ('%s'); quitting\n", mapName.str()));
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp:1054]: This says quitting. This implies that the application is quitting now?

**Review by xezon — COMMENTED** [review]
Nice fix. Some comments.

File: Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp (hunk 8 above)
Comment (slurmlord) [reply Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp:1048]: As always when writing comments it's hard to judge if they're useful or not.. Does this explain enough, in your opinion or should there be more?

File: Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp (hunk 12 above)
Comment (slurmlord) [reply Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp:1054]: The phrasing was borrowed from other error cases in the same function - I think it's meant to indicate we're quitting/abandoning the current game that's being parsed, not the entire application.

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp (hunk 6 above)
Comment (slurmlord) [reply Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: I moved it as a static to FileSystem in the latest iteration, does that seem like an OK place to have it?

File: Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp (hunk 9 above)
Comment (slurmlord) [reply Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp]: Implemented in the latest iteration. Looks a bit strange with the `retval - 1`, but it's because `getBufferForRead` reserves `len + 1` characters.

File: Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp (hunk 11 above)
Comment (slurmlord) [reply Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: The path is coming from the network, where the host has just sent the client a file (map) and a location where it should be written to. If there's a malicious host, it could have sent a "map name" that was actually pointing to a file anywhere on the disk.
`getRealFilename` calls `GameState::portableMapPathToRealMapPath`, so it could now return an empty string in this case. I used an assert just to make it obvious to the user that the path was invalid and that's why the transfer timed out, but as that's only visible in debug builds anyway it's probably better suited for a `DEBUG_LOG` instead.

File: Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp [hunk 13]
```diff
@@ -214,3 +214,24 @@ Bool Win32LocalFileSystem::createDirectory(AsciiString directory)
 	}
 	return FALSE;
 }
+
+AsciiString Win32LocalFileSystem::normalizePath(const AsciiString& filePath) const
+{
+	DWORD retval = GetFullPathNameA(filePath.str(), 0, NULL, NULL);
+	if (retval == 0)
+	{
+		DEBUG_LOG(("Unable to determine buffer size for normalized file path. Error=(%d).\n", GetLastError()));
```
Comment (xezon) [inline Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp]: %u

twice

File: Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp [hunk 14]
```diff
@@ -214,3 +214,24 @@ Bool Win32LocalFileSystem::createDirectory(AsciiString directory)
...
+		// empty string is used as a non-success
```
Comment (xezon) [inline Generals/Code/GameEngineDevice/Source/Win32Device/Common/Win32LocalFileSystem.cpp]: Can omit this comment. It is already explained in the FileSystem.h comment.

File: Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp (hunk 8 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameNetwork/GameInfo.cpp:1048]: Looks ok. I would have tried to avoid parentheses in the sentences because they can lead to confusions.

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp [hunk 15]
```diff
@@ -902,33 +902,44 @@ AsciiString GameState::realMapPathToPortableMapPath(const AsciiString& in) const
...
 		prefix = TheMapCache->getUserMapDir();
 		prefix.concat("\\");
+		containingBasePath = prefix;
 		prefix.concat(getMapLeafAndDirName(in));
 	}
 	else
 	{
 		DEBUG_CRASH(("Map file was not found in any of the expected directories; this is impossible"));
 		//throw INI_INVALID_DATA;
 		// uncaught exceptions crash us. better to just use a bad path.
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: This EA comment is now outdated and can be adjusted.

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp (hunk 6 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: Looks ok.

**Review by xezon — COMMENTED** [review]
Looks very good. Just a few more minor comments.

**Review by xezon — APPROVED** [review]
Looks very good to me. Very secure.

**Comment by xezon** [comment]
Title optimized.
