### PR TITLE
[GEN][ZH] Prevent a custom Display Resolution from changing when making other changes in the Options Menu

### LINKED ISSUE #453: In-Game options change resets resolution to 800x600 and crashes the game
Changing in-game options resets the resolution to 800x600 and crashes the game. GenTool fixes this with a hack.

Retail 1.04/vs6 build:

https://github.com/user-attachments/assets/1920bce7-3900-439e-8dfb-1c7678d6bc4e

Retail 1.04 + GenTool: 

https://github.com/user-attachments/assets/87621aa3-c815-450a-8357-28f5deb76f10

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #453
* Relates to #1028

This change prevents a custom display resolution from changing when making changes in the Options Menu.

Originally, the Display Resolution combo box in the Options Menu did not recognize custom resolutions that were set in the Options.ini. This would force the resolution to change when applying any changes in the Options Menu. When this happened in-game, then the game crashed.

### A custom resolution now shows in the Combo Box

shot_20250608_085936_1

## TODO

- [x] Replicate in Generals

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp [hunk 1]
```diff
@@ -1630,22 +1629,21 @@ void OptionsMenuInit( WindowLayout *layout, void *userData )
...
+		// This avoids force changing the resolution when the user has set a custom resolution (in Options.ini).
+		Int xres = TheDisplay->getWidth();
+		Int yres = TheDisplay->getHeight();
+		str.format(L"%d x %d",xres,yres);
+		GadgetComboBoxAddEntry( comboBoxResolution, str, color );
+		selectedResIndex = GadgetComboBoxGetLength( comboBoxResolution ) - 1;
 	}
 
-	TheWritableGlobalData->m_xResolution = selectedXRes;
-	TheWritableGlobalData->m_yResolution = selectedYRes;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp:1647]: This is an additional sneaky bug. It changes the resolution to what the combo box default is without confirming any resolution change. This causes a notable bug when declining a resolution change. Afterwards the GlobalData resolution is incorrectly set and causes misbehavior in the Options Menu resolution combo box.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp [hunk 2]
```diff
@@ -1630,22 +1629,21 @@ void OptionsMenuInit( WindowLayout *layout, void *userData )
...
 			selectedResIndex=i;
 	}
 
 	if (selectedResIndex == -1)	//check if saved mode no longer available
-	{	//pick default resolution
-		selectedXRes = 800;
-		selectedXRes = 600;
-		selectedResIndex = defaultResIndex;
+	{
+		// TheSuperHackers @tweak xezon 08/06/2025 Now adds the current resolution instead of defaulting to 800 x 600.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp]: I think this needs testing in fullscreen. It might only work in Windowed Mode. Fullscreen will offer less freedoms in choosing custom resolutions.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp (hunk 1 above)
Comment (Mauller) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp:1647]: Someone goofed here.

**Review by Mauller — APPROVED** [review]
Works as intended when run in windowed mode, i have not tested in fullscreen yet since i have other things going on.

**Comment by Mauller** [comment]
Copy across looks clean

**Comment by xezon** [comment]
Replicated in Generals.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp (hunk 2 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp]: Works in fullscreen.
