### PR TITLE
[GEN][ZH] Fix list element erasure with iterator on unrelated container in ResourceGatheringManager::findBestSupplyCenter, MilesAudioManager::killLowestPrioritySoundImmediately

### LINKED ISSUE #342: ResourceGatheringManager::findBestSupplyCenter tries to erase an element with an iterator on an unrelated container
I was testing with jmarshall2323's fork, however the bug exists in the original source code

**Affected Files:**
``Generals/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp``
``GeneralsMD/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp``

https://github.com/TheSuperHackers/GeneralsGameCode/blob/0a05454d8574207440a5fb15241b98ad0b435590/Generals/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp#L237

the function ``findBestSupplyCenter`` seems to have been copied from ``findBestSupplyWarehouse`` the specified line above seems to have been left unmodified after being copied, so it is using an iterator of ``m_supplyCenters`` to erase an element in ``m_supplyWarehouses``

this throws an error in modern builds (jmarshall2323's) but I have no clue what it would have done back in the day with VS6.0 era STL

this does not affect game play in anyway, as the loop will just skip it and keep going, at wrost it would be slightly slower, but with modern versions it throws an exception as this is an illegal write

solution:
basically replace ``m_supplyWarehouses`` with ``m_supplyCenters`` at both of those lines as this is the correct behavior

https://github.com/TheSuperHackers/GeneralsGameCode/blob/0a05454d8574207440a5fb15241b98ad0b435590/Generals/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp#L237
https://github.com/TheSuperHackers/GeneralsGameCode/blob/0a05454d8574207440a5fb15241b98ad0b435590/GeneralsMD/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp#L237

### LINKED ISSUE #537: MilesAudioManager::killLowestPrioritySoundImmediately tries to erase an element with an iterator on an unrelated container
### Area(s) with this issue?

_No response_

### Describe the issue

Miles audio manager attempts to use an iterator to erase a playing 3D sound using an iterator that is out of bounds of the container. Line 2071 - killLowestPrioritySoundImmediately

This could be casued by other memory issues as the pointer is returning 0xDEADBEEF which could be an indication that something has altered memory in an unexpected way and we are going beyond allocated memory.

### Steps to reproduce

Run Generals under debug in VS22

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Mauller**
* Resolves #342
* Resolves #537 
* Closes #349
* Relates to #563 

Within some iterator use, likely due to copy and paste errors, there are iterators being used on the wrong container.

In the short term this can cause memory leaks as the required data is never freed from the container.

This can also cause unexpected behaviour as the container is growing with data that should have been removed.

There is also a bug fix for a cast that was setting the wrong type on a pointer, this does not seem to affect runtime but could be an issue in the future.

### CODE REVIEW

File: GeneralsMD/Code/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp [hunk 1]
```diff
@@ -2087,9 +2087,9 @@ Bool MilesAudioManager::killLowestPrioritySoundImmediately( AudioEventRTS *event
 
 				if( playing->m_audioEventRTS && playing->m_audioEventRTS == lowestPriorityEvent ) 
 				{
-					//Release this 3D sound channel immediately because we are going to play another sound in it's place.
+					//Release this sound channel immediately because we are going to play another sound in it's place.
 					releasePlayingAudio( playing );
-					m_playing3DSounds.erase( it );
+					m_playingSounds.erase( it );
```
Comment (xezon) [inline GeneralsMD/Code/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp:2092]: I am 99% sure that this just worked with no bugs with stlport's implementation.

```cpp
  iterator erase(iterator __position) {
    _List_node_base* __next_node = __position._M_node->_M_next; // accesses next node
    _List_node_base* __prev_node = __position._M_node->_M_prev; // accesses prev node
    _Node* __n = (_Node*) __position._M_node; // accesses current node
    __prev_node->_M_next = __next_node; // writes prev node
    __next_node->_M_prev = __prev_node; // writes next node
    _Destroy(&__n->_M_data); // calls destructor with the same type (PlayingAudio*)
    this->_M_node.deallocate(__n, 1); // calls deallocate on default allocator for std::list
    return iterator((_Node*)__next_node); // return local
    }
```

Same with `m_supplyCenters.erase( iterator )`

So these were no runtime issues in the retail game.

File: GeneralsMD/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp [hunk 2]
```diff
@@ -213,7 +213,7 @@ Object *ResourceGatheringManager::findBestSupplyCenter( Object *queryObject )
 		if( dock )
 		{
 			static const NameKeyType key_centerUpdate = NAMEKEY("SupplyCenterDockUpdate");
-			SupplyWarehouseDockUpdate *centerModule = (SupplyWarehouseDockUpdate*)dock->findUpdateModule( key_centerUpdate );
+			SupplyCenterDockUpdate *centerModule = (SupplyCenterDockUpdate*)dock->findUpdateModule( key_centerUpdate );
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/Common/RTS/ResourceGatheringManager.cpp:216]: This certainly was no runtime bug, because this pointer is just tested for null.

File: GeneralsMD/Code/GameEngine/Source/Common/System/SubsystemInterface.cpp [hunk 3]
```diff
@@ -146,7 +146,7 @@ void SubsystemInterfaceList::addSubsystem(SubsystemInterface* sys)
 void SubsystemInterfaceList::removeSubsystem(SubsystemInterface* sys)
 {
 #ifdef DUMP_PERF_STATS
-	for (SubsystemList::iterator it = m_allSubsystems.begin(); it != m_subsystems.end(); ++it)
+	for (SubsystemList::iterator it = m_allSubsystems.begin(); it != m_allSubsystems.end(); ++it)
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/Common/System/SubsystemInterface.cpp:149]: This is a debug bug fix. No concern for retail game.

**Review by xezon — APPROVED** [review]
Fixes look correct.

File: GeneralsMD/Code/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp (hunk 1 above)
Comment (Mauller) [reply GeneralsMD/Code/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp:2092]: That is funny that it essentially looks like it does not care what container it is called on, just that erase is called with an iterator.
