### PR TITLE
tweak(network): Add file extension validation to network map transfer

### LINKED ISSUE #1816: Map transfer system lacks file extension validation
### Prerequisites

* [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

* [x] Command & Conquer Generals
* [x] Command & Conquer Generals: Zero Hour
* [ ] Other (please specify below)

### Bug Description

The current game lacks file extension validation during map transfers. An attacker could potentially transfer files with arbitrary extensions, bypassing OS-level security controls or enabling further exploitation.

Issue #272 identified security vulnerabilities in map file transfers. PR #1058 addressed path traversal, but additional security improvements can be made by validating file extensions (.map, .ini, .str, .wak) during the transfer process.

### Reproduction Steps

1. Initiate a map transfer in multiplayer
2. Observe that files with arbitrary extensions could potentially be transferred
3. No validation is performed on the file extension before transfer

### Additional Context

This is a security enhancement related to the map transfer system. While path traversal was addressed in PR #1058, adding file extension validation would provide an additional layer of security by ensuring only legitimate map-related files (.map, .ini, .str, .wak) can be transferred between clients.

### PR DESCRIPTION
**Pull request by bobtista**
Adds whitelist-based validation of file extensions during map transfers and save game loading to prevent arbitrary file types from being written to disk.

- Closes #1816 
- Related to issue #272

### CODE REVIEW

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 1]
```diff
@@ -457,3 +457,47 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+{
+	static const char* validExtensions[] = {
+		".map",
+		".ini",
+		".str",
+		".wak",
+		".tga",
+		".txt"
+	};
+	static const Int numValidExtensions = sizeof(validExtensions) / sizeof(validExtensions[0]);
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: Use `ARRAY_SIZE() `

**Review by Skyaero42 — COMMENTED** [review]
So what happens if a file id blocked? Does the transfer freeze? Game mismatch?

**Comment by bobtista** [comment]
> So what happens if a file id blocked? Does the transfer freeze? Game mismatch?

It gets ignored and logged - this is the same behavior as the existing path traversal protection.

- hasValidTransferFileExtension() returns false
- portableMapPathToRealMapPath() returns empty string
- ConnectionManager::processFile() logs: "Got a file name transferred that failed to normalize"
- The transfer is silently dropped and will eventually timeout

Note: I have not confirmed this with testing yet, I don't have my testing PC with me

File: Core/GameEngine/Include/Common/FileSystem.h [hunk 2]
```diff
@@ -161,6 +161,7 @@ class FileSystem : public SubsystemInterface
 
 	static AsciiString normalizePath(const AsciiString& path);	///< normalizes a file path. The path can refer to a directory. File path must be absolute, but does not need to exist. Returns an empty string on failure.
 	static Bool isPathInDirectory(const AsciiString& testPath, const AsciiString& basePath);	///< determines if a file path is within a base path. Both paths must be absolute, but do not need to exist.
+	static Bool hasValidTransferFileExtension(const AsciiString& filePath);	///< validates that a file path has an approved extension for map transfer operations. Returns true if extension is whitelisted (.map, .ini, .str, .wak, .tga, .txt), false otherwise. TheSuperHackers @security bobtista 06/11/2025
```
Comment (xezon) [inline Core/GameEngine/Include/Common/FileSystem.h]: This function should not be part of file system. It is a file transfer specific function.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 3]
```diff
@@ -457,3 +457,47 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+	if (lastDot == NULL || lastDot[1] == '\0')
+	{
+		DEBUG_LOG(("File path '%s' has no extension.", filePath.str()));
+		return false;
+	}
+
+	for (Int i = 0; i < numValidExtensions; ++i)
+	{
+#ifdef _WIN32
+		if (_stricmp(lastDot, validExtensions[i]) == 0)
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: This kind of platform coding should be avoided. Check string_compat.h for alternative.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 4]
```diff
@@ -457,3 +457,47 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+{
+	static const char* validExtensions[] = {
+		".map",
+		".ini",
+		".str",
+		".wak",
+		".tga",
+		".txt"
+	};
+	static const Int numValidExtensions = ARRAY_SIZE(validExtensions);
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: ARRAY_SIZE gives compile time value. No need to store in static variable.

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 5]
```diff
@@ -457,3 +457,47 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+
+	const char* lastDot = strrchr(filePath.str(), '.');
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: perhaps call it `fileExt`

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 6]
```diff
@@ -457,3 +457,47 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+//============================================================================
+Bool FileSystem::hasValidTransferFileExtension(const AsciiString& filePath)
+{
+	static const char* validExtensions[] = {
+		".map",
+		".ini",
+		".str",
+		".wak",
+		".tga",
+		".txt"
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: maybe use strings without dot

File: Core/GameEngine/Source/Common/System/FileSystem.cpp [hunk 7]
```diff
@@ -457,3 +457,47 @@ Bool FileSystem::isPathInDirectory(const AsciiString& testPath, const AsciiStrin
...
+// FileSystem::hasValidTransferFileExtension
+//============================================================================
+// TheSuperHackers @security bobtista 06/11/2025
+// Validates file extensions for map transfer operations to prevent arbitrary
+// file types from being transferred over the network or loaded from save games.
+// This is a security measure to mitigate arbitrary file write vulnerabilities.
+//============================================================================
+Bool FileSystem::hasValidTransferFileExtension(const AsciiString& filePath)
+{
+	static const char* validExtensions[] = {
```
Comment (xezon) [inline Core/GameEngine/Source/Common/System/FileSystem.cpp]: static const char* const

File: Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp [hunk 8]
```diff
@@ -933,6 +933,13 @@ AsciiString GameState::portableMapPathToRealMapPath(const AsciiString& in) const
 		return AsciiString::TheEmptyString;
 	}
 
+	// TheSuperHackers @security bobtista 06/11/2025 Validate file extension to prevent arbitrary file types
+	if (!FileSystem::hasValidTransferFileExtension(prefix))
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/SaveGame/GameState.cpp]: Conceptually this test does not belong into this function. It probably needs to be moved into `ConnectionManager::processFile`.

File: Core/GameEngine/Include/Common/FileSystem.h (hunk 2 above)
Comment (bobtista) [reply Core/GameEngine/Include/Common/FileSystem.h]: ok moved to ConnectionManager

File: Core/GameEngine/Source/Common/System/FileSystem.cpp (hunk 3 above)
Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: ok using strcasecmp now

Comment (bobtista) [reply Core/GameEngine/Source/Common/System/FileSystem.cpp]: actually stricmp

File: Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 9]
```diff
@@ -53,6 +53,45 @@
 #include "GameClient/DisconnectMenu.h"
 #include "GameClient/InGameUI.h"
 
+//============================================================================
+// hasValidTransferFileExtension
+//============================================================================
+// TheSuperHackers @security bobtista 06/11/2025
+// Validates file extensions for map transfer operations to prevent arbitrary
+// file types from being transferred over the network or loaded from save games.
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Can remove these comments here because down at callsite it already has sufficient comment.

File: Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp [hunk 10]
```diff
@@ -53,6 +53,45 @@
...
+
+	for (Int i = 0; i < ARRAY_SIZE(validExtensions); ++i)
+	{
+		if (stricmp(fileExt, validExtensions[i]) == 0)
+		{
+			return true;
+		}
+	}
+
+	DEBUG_LOG(("File path '%s' has invalid extension '%s' for transfer operations.", filePath.str(), fileExt));
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameNetwork/ConnectionManager.cpp]: Better remove this log and the one above. There already is a log at

```cpp
	if (!hasValidTransferFileExtension(realFileName))
	{
		DEBUG_LOG(("File '%s' has invalid extension for transfer operations.", realFileName.str()));
		return;
	}
```

so this would currently log twice.

**Review by xezon — APPROVED** [review]
Looks good.

**Comment by xezon** [comment]
Needs rebase.
