### PR TITLE
bugfix(view): Fix and improve camera area constraints and camera pivoting

### LINKED ISSUE #1270: Camera does not scroll down far enough if centered on higher elevated terrain
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When scrolling down to the bottom of the map, the elevation the camera has centered on determines how far it will go down to the edge of the map. The higher the terrain, the higher it stops before reaching the edge.

This makes it harder to see objects on the edge of the map, since the controlbar will block the view

### Reproduction Steps

Load into Defcon, lower middle spot, center the map (Numpad 5) on lower ground, then scroll to the bottom of the map on higher elevation, then recenter again to see the difference

### Additional Context

High centered

Image

Low centered

Image

Screenshots with higher map pitch, issue is present with default pitch

### LINKED ISSUE #1486: Camera rotation doesn't orbitate at right position after terrain height change
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

If you rotate the camera and then you move it to a higher (or lower) terrain and you rotate it again, it will no longer orbitate. Resetting the camera is a temporary workaround.

### Reproduction Steps

1. Start a new game on a map with different height values around the terrain
2. Rotate camera (this step is just for comparison)
3. Move it to a different location with different height
4. Rotate camera

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Fixes #1270
* Fixes #1486

The camera area constraints are now recalculated when the camera zoom changes, for example because of terrain elevation changes in the camera's view. The camera will be smoothly pushed away from the constraints, but not while the user is scrolling, to make the scrolling along the map border a pleasant experience. This behavior ensures that the view can reach and see all areas of the map, and especially the bottom map border. The camera can now also be moved a bit closer to the map edges. All this is very useful to avoid issues where some units or structures are not possible to get into the view, for example a Chinook at a Supply at the top edge of a map (TheSuperHackers/GeneralsRankedMaps#7). Or a Dozer at the bottom edge of a valley on Defcon 6.

Additionally the camera pivoting was fixed. The camera now repositions correctly towards its ground pivot instead of zooming to a pivot that is not aligned to the terrain ground. User facing this looks identical, but technically it is different. Scrolling to different locations of the map will now keep the camera pivot always correctly centered to the ground. It is no longer necessary to press Numpad 5 to recenter the pivot.

This change also implicitly fixes the broken scripted camera in the USA 01 intro, which was introduced by change #2291.

## Known issues

The scripted camera will not always position perfectly at the original locations when the ground pivot was changed. This will be fixed in a future change.

## TODO

- [x] Replicate in Generals
- [x] Add pull id to commits

### CODE REVIEW

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 1]
```diff
@@ -425,6 +418,93 @@ void W3DView::buildCameraTransform( Matrix3D *transform, const Vector3 &sourcePo
...
+		{
+			Vector2 groundLevelCenter;
+			Vector2 terrainHeightCenter;
+			groundLevelCenter.X = Vector3::Find_X_At_Z(groundLevel, sourcePos, targetPos);
+			groundLevelCenter.Y = Vector3::Find_Y_At_Z(groundLevel, sourcePos, targetPos);
+			terrainHeightCenter.X = Vector3::Find_X_At_Z(m_terrainHeightAtPivot, sourcePos, targetPos);
+			terrainHeightCenter.Y = Vector3::Find_Y_At_Z(m_terrainHeightAtPivot, sourcePos, targetPos);
+			Vector2 posDiff = terrainHeightCenter - groundLevelCenter;
+
+			// Adjust the strength of the repositioning for low camera pitch, because its makes less sense
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: "because it makes less sense"

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 2]
```diff
@@ -425,6 +418,93 @@ void W3DView::buildCameraTransform( Matrix3D *transform, const Vector3 &sourcePo
...
+			// to move the camera around when it looks over the terrain.
+			const Real pitch = WWMath::Asin(fabs(delta.Z) / delta.Length());
+			constexpr const Real lowerPitch = DEG_TO_RADF(15.f);
+			constexpr const Real upperPitch = DEG_TO_RADF(30.f);
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:473]: Would be better to give these constraints a suitable name.

15 and 30 degrees just look arbitrary on the surface.

**Review by Mauller — COMMENTED** [review]
I don't see any major issues at first glance, but i would perform some replay checking due to the new initialisation of class variables.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 2 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:473]: They are arbitrary. Below 30 degrees the strengths decreases from 1 to 0 at 15 degrees. Maybe I can rewrite this logic using a lerp function to make this clearer.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 1 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: Fixed

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 2 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:473]: Rewritten with a new `WWMath::Inverse_Lerp` function.

**Comment by xezon** [comment]
Replicated in Generals with conflict

```
D:\Projects\TheSuperHackers\GeneralsGameCode>FOR /F "delims=" %b IN ('git merge-base --fork-point main') DO git diff %b  1>changes.patch

D:\Projects\TheSuperHackers\GeneralsGameCode>git diff 8cf9456cee31bbee015dffe6ac87376e361bcd04  1>changes.patch

D:\Projects\TheSuperHackers\GeneralsGameCode>git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch
Checking patch Generals/GameEngine/Include/GameClient/View.h...
error: Generals/GameEngine/Include/GameClient/View.h: No such file or directory
Checking patch Generals/GameEngineDevice/Include/W3DDevice/GameClient/W3DView.h...
error: Generals/GameEngineDevice/Include/W3DDevice/GameClient/W3DView.h: No such file or directory
Checking patch Generals/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp...
error: Generals/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp: No such file or directory
Checking patch Generals/Libraries/Include/Lib/BaseType.h...
error: Generals/Libraries/Include/Lib/BaseType.h: No such file or directory
Checking patch Generals/Libraries/Source/WWVegas/WWMath/wwmath.h...
error: Generals/Libraries/Source/WWVegas/WWMath/wwmath.h: No such file or directory
Checking patch Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp...
error: while searching for:
//------------------------------------------------------------------------------
void InGameUI::resetCamera()
{
        ViewLocation currentView;
        TheTacticalView->getLocation( &currentView );
        TheTacticalView->resetCamera( &currentView.getPosition(), 1, 0.0f, 0.0f );
}

//------------------------------------------------------------------------------

error: patch failed: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp:4503
Checking patch Generals/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp...
Hunk #1 succeeded at 315 (offset 1 line).
Applying patch Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp with 1 reject...
Rejected hunk #1.
Applied patch Generals/Code/GameEngine/Source/GameClient/MessageStream/LookAtXlat.cpp cleanly.
```
