### PR TITLE
fix(logic): Fix unexpected return in GameLogic::logicMessageDispatcher's switch case MSG_CANCEL_UNIT_CREATE

### LINKED ISSUE #1211: Unexpected return in case GameMessage::MSG_CANCEL_UNIT_CREATE in GameLogic::logicMessageDispatcher
The return statement is unexpected.

```cpp
		case GameMessage::MSG_CANCEL_UNIT_CREATE:
		{
#if RETAIL_COMPATIBLE_AIGROUP
			Object *producer = getSingleObjectFromSelection(currentlySelectedGroup);
#else
			Object *producer = getSingleObjectFromSelection(currentlySelectedGroup.Peek());
#endif
			ProductionID productionID = (ProductionID)msg->getArgument( 0 )->integer;
			
			// sanity
			if( producer == NULL )
				break;
				
			// sanity, the player must control the producer			
			if( producer->getControllingPlayer() != thisPlayer )
				break;

			// get the unit production interface
			ProductionUpdateInterface *pu = producer->getProductionUpdateInterface();
			if( pu == NULL )
				return; // <------ THIS RETURN IS UNEXPECTED

			// cancel the production
			pu->cancelUnitCreate( productionID );

			break;

		}  // end GameMessage::MSG_CANCEL_UNIT_CREATE
```

### PR DESCRIPTION
**Pull request by bobtista**
* Fixes #1211

The change is wrapped behind the RETAIL_COMPATIBLE_CRC flag to be safe, though I haven't tested for mismatches without it.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp [hunk 1]
```diff
@@ -1390,7 +1390,11 @@ void GameLogic::logicMessageDispatcher( GameMessage *msg, void *userData )
 			// get the unit production interface
 			ProductionUpdateInterface *pu = producer->getProductionUpdateInterface();
 			if( pu == NULL )
+#if RETAIL_COMPATIBLE_CRC
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp]: It could be necessary. Please test if it is.

Comment (bobtista) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp]: I built and ran it locally but wasn't able to get this code to hit. I'll try pushing a commit without the flag and see if the CI replays mismatch

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp]: It does make sense that this return/break never hits, because we expect the object to have a production update interface.

**Review by xezon — APPROVED** [review]
No Risk. No Fun.
