### PR TITLE
bugfix(battleplan): Multiple battle plans are now always applied correctly

### LINKED ISSUE #46: Owning two USA Strategy Centers with Search And Destroy ability selected does not grant a single range bonus
Owning two USA Strategy Centers with Search And Destroy ability selected does not grant a single range bonus. Reported by Goldfish.

### LINKED ISSUE #2209: USA Strategy Center Battle Plans do not stack when activated in "incorrect" order
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

* Relates to #46

USA Strategy Center Battle Plans do not stack when activated in "incorrect" order.

Dominator:
> When you have 2 strategy centers, you can stack them by setting Bombardment and then SND (in that order). However if its not done in this order, then you can't stack. I think SND always has to be set last, which is totally not neccessary and is some weird oddity.

### Reproduction Steps

1. Get 2 USA Strategy Centers
2. Select Search and Destroy on Strategy Center 1
3. Select Bombardment on Strategy Center 2

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Stubbjax**
* Fixes #46
* Fixes #2209
* Merge after #2335

This change fixes an issue where multiple Strategy Center battle plans are not correctly applied. The issue is that only the most recent plan is applied, as only the new plan data is passed to the battle plan application logic.

For example, in retail, if the player has Search and Destroy on one Strategy Center, and then selects Bombardment on another, the data that gets applied to all units becomes:

```
Search and Destroy: 0 (this undoes the range bonus)
Bombardment: 1 (new bonus is applied)
Hold the Line: 0
```

After this change, the logic correctly accounts for existing plans, and so the data becomes this:

```
Search and Destroy: 1 (range bonus remains intact)
Bombardment: 1 (new bonus is applied)
Hold the Line: 0
```

In the `Player::applyBattlePlanBonusesForPlayerObjects` method, the `bonus` is essentially the delta, while `m_battlePlanBonuses` is the combined bonus. The problem was that the `bonus` was being applied to units instead of `m_battlePlanBonuses`. However, the armour scalar is still expected as a delta when being applied to units, so a temporary `newBonus` is now used to merge the armour scalar delta with the combined bonus.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 1]
```diff
@@ -3148,7 +3148,17 @@ void Player::applyBattlePlanBonusesForPlayerObjects( const BattlePlanBonuses *bo
 	}
 
 	DUMPBATTLEPLANBONUSES(m_battlePlanBonuses, this, nullptr);
+#if RETAIL_COMPATIBLE_CRC
 	iterateObjects( localApplyBattlePlanBonusesToObject, (void*)bonus );
+#else
+	// TheSuperHackers @bugfix Stubbjax 05/02/2026 Apply all bonuses the player has rather than just the most recent.
+	BattlePlanBonuses* newBonus = newInstance(BattlePlanBonuses);
+	*newBonus = *m_battlePlanBonuses;
+	newBonus->m_armorScalar = bonus->m_armorScalar;
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: > However, the armour scalar is still expected as a delta when being applied to units, so a temporary `newBonus` is now used to merge the armour scalar delta with the combined bonus.

Looks correct, but is confusing to understand.

How about we do

```cpp
#if RETAIL_COMPATIBLE_CRC
virtual void applyDamageScalar( Real scalar ) { m_damageScalar *= scalar; }
#else
virtual void applyDamageScalar( Real scalar ) { m_damageScalar = scalar; }
#endif
```

and any other change necessary to make it work. This should be easier to use and maintain, because it will not be necessary to scale back to 1 but actually set it directly. And allocating a temporary `BattlePlanBonuses` will also no longer be necessary.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: I had a go at this but it significantly expands the change's scope and complexity with at least 5 `RETAIL_COMPATIBLE_CRC` conditions. It's not possible to have it work for the vision range scalar without substantial refactors either.

Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: Ok. Then we better leave as is.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 2]
```diff
@@ -3148,7 +3148,17 @@ void Player::applyBattlePlanBonusesForPlayerObjects( const BattlePlanBonuses *bo
 	}
 
 	DUMPBATTLEPLANBONUSES(m_battlePlanBonuses, this, nullptr);
+#if RETAIL_COMPATIBLE_CRC
 	iterateObjects( localApplyBattlePlanBonusesToObject, (void*)bonus );
+#else
+	// TheSuperHackers @bugfix Stubbjax 05/02/2026 Apply all bonuses the player has rather than just the most recent.
+	BattlePlanBonuses* newBonus = newInstance(BattlePlanBonuses);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: After #2335 this allocation can be removed.

Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: #2335 has been merged and this allocation can now be turned into stack variable.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 3]
```diff
@@ -3152,7 +3152,16 @@ void Player::applyBattlePlanBonusesForPlayerObjects( const BattlePlanBonusesData
...
 	DUMPBATTLEPLANBONUSES(m_battlePlanBonuses, this, nullptr);
+#if RETAIL_COMPATIBLE_CRC
 	iterateObjects( localApplyBattlePlanBonusesToObject, const_cast<BattlePlanBonusesData *>(bonus) );
+#else
+	// TheSuperHackers @bugfix Stubbjax 05/02/2026 Apply all bonuses the player has rather than just the most recent.
+	BattlePlanBonusesData newBonus = *m_battlePlanBonuses;
+	newBonus.m_armorScalar = bonus->m_armorScalar;
+	newBonus.m_sightRangeScalar = bonus->m_sightRangeScalar;
+
+	iterateObjects(localApplyBattlePlanBonusesToObject, (void*)&newBonus);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: `(void*)` cast is not necessary. Cast is implicit.
