### PR TITLE
bugfix(particlesys): Restore Particle System IDs on save load before registering to ParticleSystemManager

### LINKED ISSUE #2315: Savegame error due to ParticleSystem master/slave not able to reconnect
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Savegame fails to load with the message "ParticleSystem::loadPostProcess - m_masterSystem is null or destroyed"

### Reproduction Steps

Run the attached savegame (win32)

### Additional Context

[00000044.zip](https://github.com/user-attachments/files/25340041/00000044.zip)

### PR DESCRIPTION
**Pull request by stephanmeesters**
- Closes #2315

Some savegames would error due to being unable to reconnect master/slave systems to a particle system.

This appeared to be caused because during xfer of the ParticleSystemManager, the particle systems would initially be assigned with a new (temporary) system ID, and only moments later be properly restored with xferSnapshot and receive the real system ID. However, particle systems were registered with ParticleSystemManager using this old invalid ID, which would cause lookup failures later.

The fix here is to defer the registration of particle systems with ParticleSystemManager until the system ID has been properly restored.

### CODE REVIEW

**Review by xezon — APPROVED** [review]
This looks very good. Nice find.

File: Core/GameEngine/Source/GameClient/System/ParticleSys.cpp [hunk 1]
```diff
@@ -3364,20 +3367,23 @@ void ParticleSystemManager::xfer( Xfer *xfer )
...
 
-			if( system == nullptr )
-			{
+			// read system data
+			xfer->xferSnapshot( system );
 
-				DEBUG_CRASH(( "ParticleSystemManager::xfer - Unable to allocate particle system '%s'",
+			if( system->getSystemID() == INVALID_PARTICLE_SYSTEM_ID )
+			{
+				DEBUG_CRASH(( "ParticleSystemManager::xfer - Unable to restore system ID to particle system '%s'",
```
Comment (xezon) [inline Core/GameEngine/Source/GameClient/System/ParticleSys.cpp:3384]: delete system on error

**Review by xezon — CHANGES_REQUESTED** [review]

File: Core/GameEngine/Source/GameClient/System/ParticleSys.cpp (hunk 1 above)
Comment (stephanmeesters) [reply Core/GameEngine/Source/GameClient/System/ParticleSys.cpp:3384]: Moved `friend_addParticleSystem(system)` to before the throw so that this gets properly handled. This was tested.

Edit: Actually I'll have another look at this, this works but reads a bit weird

Comment (xezon) [reply Core/GameEngine/Source/GameClient/System/ParticleSys.cpp:3384]: Looks strange. This means a particle with INVALID_PARTICLE_SYSTEM_ID is added to the Manager, which can never be looked up, because particles with INVALID_PARTICLE_SYSTEM_ID are by convention skipped.

It should delete the system here and add it only add it on full success.

File: Core/GameEngine/Source/GameClient/System/ParticleSys.cpp [hunk 2]
```diff
@@ -1260,7 +1263,8 @@ ParticleSystem::~ParticleSystem()
 
 	m_controlParticle = nullptr;
 
-	TheParticleSystemManager->friend_removeParticleSystem(this);
+	if (m_systemID != INVALID_PARTICLE_SYSTEM_ID)
+		TheParticleSystemManager->friend_removeParticleSystem(this);
```
Comment (xezon) [inline Core/GameEngine/Source/GameClient/System/ParticleSys.cpp:1268]: Can also use { } here for consistent style.

**Review by xezon — APPROVED** [review]
Looking good
