### PR TITLE
feat(client): Implement Player Observer and fix shrouding and ghost object issues

### LINKED ISSUE #439: Supply Dock is black/shadowed in Replay playback
Supply Dock is black/shadowed in Replay playback. GenTool fixes this issue with a hack.

Image

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Relates to #850
* Fixes #439
* Closes #1456

This change implements a Player Observer feature and fixes the most obvious shrouding and ghost object issues. The Player Observer is accessible through the Observer Control Bar and works in Replay and Multiplayer.

The feature is default enabled and can be disabled with `PlayerObserverEnabled=no` in Options.ini. Enabling this feature will incur some performance penalty, because all players need to track ghost objects.

The first commit of this change applies a bit of manual formatting to Ghost Object files to increase readability because EA wrote the code hard to read.

To implement the feature, the DEBUG_FOG_MEMORY related code had to be changed a bit to be usable.

While testing, many issues were identified and had to be fixed to make this properly work without crashing and bugging. There likely are more issues lurking, but the most egregious ones are dealt with. All fixes are separate commits.

Note that this implementation works much much better than what GenTool does.

## Image of Player Observer in Replay

shot_20250912_133229_4

## TODO

- [x] Replicate in Generals
- [x] Add PR number to commits

### CODE REVIEW

**Comment by xezon** [comment]
Generals fails compile until it is replicated.

File: Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp [hunk 1]
```diff
@@ -807,24 +807,27 @@ void RenderObjClass::Add(SceneClass * scene)
...
 			Scene->Remove_Render_Object(this);
-			return;
+			return true;
 		}
 	} else {
 		Container->Remove_Sub_Object(this);
-		return;
+		return true;
 	}
+	return false;
```
Comment (Skyaero42) [inline Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp]: I would suggest moving `return false` for readability

```cpp
#if 1
	if (Container == NULL) {
		if (Scene != NULL) {
			Scene->Remove_Render_Object(this);
			return true;
		}

        return false;
	} else {
		Container->Remove_Sub_Object(this);
		return true;
	}
```

File: Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp [hunk 2]
```diff
@@ -807,24 +807,27 @@ void RenderObjClass::Add(SceneClass * scene)
  *   11/04/1997 GH  : Created.                                                                 *
  *   2/25/99    GTH : moved to the base RenderObjClass                                         *
  *=============================================================================================*/
-void RenderObjClass::Remove(void)
+bool RenderObjClass::Remove(void)
 {
 	// All render objects have their scene pointers set.  To check if this is a "top level"
 	// object, (i.e. directly in the scene) you see if its Container pointer is NULL.
 #if 1
```
Comment (Skyaero42) [inline Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp:814]: Maybe remove the `#if 1` in here?

**Comment by xezon** [comment]
> Is the `ReplayObserverEnabled` already built in the game? I can't find back in the commits where it has been added.

I do not know what `ReplayObserverEnabled` is. Do you mean `PlayerObserverEnabled` ?

It is added with https://github.com/TheSuperHackers/GeneralsGameCode/pull/1569/commits/31b21c076bb7df6fe1791133aeb5236cd6127a8c

File: Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp (hunk 1 above)
Comment (xezon) [reply Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp]: Ok done.

File: Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp (hunk 2 above)
Comment (xezon) [reply Core/Libraries/Source/WWVegas/WW3D2/rendobj.cpp:814]: Yes could be cleaned up in another change. There are probably more places like this. I did not care for it in this change.

**Comment by xezon** [comment]
Rebased on main.

**Comment by Skyaero42** [comment]
> > Is the `ReplayObserverEnabled` already built in the game? I can't find back in the commits where it has been added.
> 
> I do not know what `ReplayObserverEnabled` is. Do you mean `PlayerObserverEnabled` ?
> 
> It is added with [31b21c0](https://github.com/TheSuperHackers/GeneralsGameCode/commit/31b21c076bb7df6fe1791133aeb5236cd6127a8c)

It says so in your main post:
> The feature is default enabled and can be disabled with ReplayObserverEnabled=no in Options.ini. Enabling this feature will incur some performance penalty, because all players need to track ghost objects.

is this a new option in options.ini, or was it already introduced?

**Comment by xezon** [comment]
> is this a new option in options.ini, or was it already introduced?

Incorrectly written. Fixed.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp [hunk 3]
```diff
@@ -530,6 +530,18 @@ Bool OptionPreferences::useCameraInReplays(void)
 	return FALSE;
 }
 
+Bool OptionPreferences::getPlayerObserverEnabled() const
+{
+	OptionPreferences::const_iterator it = find("PlayerObserverEnabled");
+	if (it == end())
+		return TRUE;
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp:531]: I wouldn't have this enabled by default as it's different behaviour to retail to have the shrouding showing when observing.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp:531]: There are reasons to default enable this:

1. It shows users that this feature now exists
2. It is far more useful to see the shroud of a player instead of just a few player stats in the Control Bar
3. It gives us more test coverage when this feature is default enabled

What we could do in a follow up is add a key mapping to toggle the Player Observer without going into the Options menu.

Comment (helmutbuhler) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp:531]: It's not different to retail when Gentool is used. I don't think we need an option to disable the shrouding.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/OptionsMenu.cpp:531]: GenTool also has an option to disable it in its menu. And it is default enabled.

**Comment by helmutbuhler** [comment]
Very nice PR! I haven't looked at the code, but when testing I noticed some issues with displaying oils that have been destroyed:
grafik
grafik
grafik
Unfortunately it's very random when the oil appears like this. I never noticed this in retail, I think it's likely this PR causes this.

In some situations it also shows the oil as ok:
grafik
Even though in this case the player should see it as destroyed (the player destroyed it in this case).
I can upload the replay where I took these screenshots, but it seems replay-independent.

**Comment by xezon** [comment]
Does this only happen when changing observed player or when playing? If this only happens with observed player, then it is no big concern and just another thing that needs fixing.

**Comment by helmutbuhler** [comment]
I think it only happens with observed players

**Comment by xezon** [comment]
Ok that is fine then. I am not surprised if there are more errors that need fixing. If you can send Replay with Repro then I can investigate (in this change or a follow up of this).

**Comment by xezon** [comment]
Replicated in Generals with some conflicts.

Every individual commit compiles.

Tested and worked in Generals.

**Comment by helmutbuhler** [comment]
I made an issue with the replay: https://github.com/TheSuperHackers/GeneralsGameCode/issues/1692

**Comment by xezon** [comment]
> I made an issue with the replay: #1692

I was unable to narrow the repro steps for the issue. It requires more testing and understanding. Anyway, I think it does not block merging this Pull. It is just another ghost issue that needs to be tackled somewhere once we understand the problem.

**Comment by xezon** [comment]
I tested Switch Teams (CTRL+Shift+Space) on Alpine Assault and it works to change the Player in live game. It is even possible to see the view of the Civilian train. The only issue is that switching to Observer does not force turn on the Radar. I can tackle this in a follow up.
