### PR TITLE
bugfix(gui): Remove slider bounds checks to prevent unexpected reset of custom settings

### LINKED ISSUE #2623: MaxParticles gets reset to 0 on options save if larger then 5000
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When MaxParticles is set outside of bounds [0, 5000] in the options.ini and the user presses 'accept' in the options menu (e.g. the user changed the checkbox of 'retaliation'), the MaxParticle value is reset to 0 - and no particles are rendered.

This is caused by the SET_SLIDER command, which breaks early if the current value is out of bounds leaving the slider position initialized to 0.

When the user presses the accept button, all parameters are read, including the particle slider - still set at zero - and (overwritten) to options.ini

### Reproduction Steps

1. Make sure 'Detail' in the options menu is set to 'Custom'
2. Open options.ini in Zero Hour Data in the documents folder.
3. Change MaxParticles to 15000
4. Save and close the file
5. Start the game
6. Go to the options menu
7. Press 'accept'
8. Reopen the options.ini game, observe the value for MaxParticles is now 0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Skyaero42**
- Resolves: #2623 

When any slider value is out of bounds, an early return is initialized, causing the slider position value not be set at all.
The slider position value is then 0, even if the minimum is higher than 0.

Instead the slider UI is bound instead. If the slider is touched by the user, it will set its value between the minimum and maximum - easily allowing to reset the value if needed.

I left a comment to ensure in the future coders understand why there is no check in place. Can remove if desired.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp [hunk 1]
```diff
@@ -394,8 +394,8 @@ WindowMsgHandledType GadgetHorizontalSliderSystem( GameWindow *window, UnsignedI
 			Int newPos = (Int)mData1;
 			GameWindow *child = window->winGetChild();
 
-			if( newPos < s->minVal || newPos > s->maxVal )
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp:397]: The same condition exists in GadgetVerticalSlider.cpp

File: Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp [hunk 2]
```diff
@@ -394,8 +394,8 @@ WindowMsgHandledType GadgetHorizontalSliderSystem( GameWindow *window, UnsignedI
...
-				break;
+			// TheSuperHackers @info position bounds check has been removed as it
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp]: `@fix`

File: Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp [hunk 3]
```diff
@@ -394,8 +394,8 @@ WindowMsgHandledType GadgetHorizontalSliderSystem( GameWindow *window, UnsignedI
...
+			// resets custom option.ini settings to 0. Has no effect on slider UI.
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp]: Perhaps rewrite this a bit like "No longer reject out of bounds positions to prevent ..."

**Review by xezon — CHANGES_REQUESTED** [review]
This fix is incomplete. When the underlying value is larger than the max, then the slider head surpasses the slider region.

Tested with MaxParticleCount = 6000

Image

File: Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp (hunk 1 above)
Comment (Skyaero42) [reply Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp:397]: Is vertical slider even used in the game?

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetHorizontalSlider.cpp:397]: According to WND all Comboboxes and Listboxes have VSliders

File: Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetVerticalSlider.cpp [hunk 4]
```diff
@@ -378,13 +378,14 @@ WindowMsgHandledType GadgetVerticalSliderSystem( GameWindow *window, UnsignedInt
...
-			if (newPos < s->minVal || newPos > s->maxVal)
-				break;
+			// TheSuperHackers @fix No longer reject out of bounds positions to prevent
+			// reset of custom option.ini settings to 0.
 
 			s->position = newPos;
 
 			// Translate to window coords
 			newPos = (Int)((s->maxVal - newPos) * s->numTicks);
+			newPos = clamp(0, newPos, (Int)((s->maxVal - s->minVal) * s->numTicks));
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetVerticalSlider.cpp:388]: Is clamping at min 0 correct? What if minVal is not 0 ?

Comment (Skyaero42) [reply Generals/Code/GameEngine/Source/GameClient/GUI/Gadget/GadgetVerticalSlider.cpp:388]: Yes that is correct. If newPos == s->maxVal, then newPos = 0

**Review by xezon — APPROVED** [review]
Tested and worked.
