### PR TITLE
[GEN][ZH] Fix infinite loop in ParticleSystemManager::update

### LINKED ISSUE #841: ParticleSystemManager::update is bogus
```cpp
void ParticleSystemManager::update( void )
{
...
	ParticleSystem *sys;

	for(ParticleSystemListIt it = m_allParticleSystemList.begin(); it != m_allParticleSystemList.end();) 
	{
		sys = (*it);
		if (!sys) {
			continue; // <---- this would cause infinite loop if it were to hit
		}

		if (sys->update(m_localPlayerIndex) == false)
		{
			++it;
			sys->deleteInstance();
		} else {
			++it;
		}
	}
}
```

### PR DESCRIPTION
**Pull request by Caball009**
* Fixes #841

The following loop contains undefined behavior:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/696cb63bd92b58962bc6618a39771ee36f069ace/Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp#L3039-L3055

The compiler can see that the forward progress guarantee is violated if the iterator (`*it`) points to a `nullptr`. In other words, this could become an infinite loop, which is undefined behavior in C++20 and the compiler is likely to get rid of the entire `!= nullptr` check:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/696cb63bd92b58962bc6618a39771ee36f069ace/Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp#L3043-L3046

### CODE REVIEW

**Comment by Caball009** [comment]
I'd like to draw some attention to another potential issue in this function and probably a ton of other places. The follow line does an erasure from the container, but the loop iterator isn't updated: https://github.com/TheSuperHackers/GeneralsGameCode/blob/696cb63bd92b58962bc6618a39771ee36f069ace/Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp#L3051
AFAICT this is allowed with the underlying container (`std::list`), but it's bad practice nonetheless. It'll become a problem if the container is changed to e.g. `std::vector`.

File: Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp [hunk 1]
```diff
@@ -3040,17 +3040,14 @@ void ParticleSystemManager::update( void )
 
 	for(ParticleSystemListIt it = m_allParticleSystemList.begin(); it != m_allParticleSystemList.end();)
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp]: Can just do `; ++it)`, no?

Comment (Mauller) [reply Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp]: im not sure if this loop works quite right as the iterator behaviour may be a bit undefined.
Inside deleteInstance the function ```ParticleSystemManager::friend_removeParticleSystem``` gets called by the particle system which then erases itself from the ```m_allParticleSystemList```.

im not sure if the iterator in this loop can then be considered in a valid state at that point, even the incremented one.

it might be that the list needs to be iterated over from the start again at this point if a deleteInstance occurs.

File: Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp [hunk 2]
```diff
@@ -3040,17 +3040,14 @@ void ParticleSystemManager::update( void )
 
 	for(ParticleSystemListIt it = m_allParticleSystemList.begin(); it != m_allParticleSystemList.end();) 
 	{
-		sys = (*it);
+		sys = (*it++); // increase iterator before potential erasure from the container!
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp]: Suggest to write

```cpp
// TheSuperHackers @info Must increment the list iterator before potential element erasure from the list.
sys = *it++;
```

File: Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp]: Right.

**Review by xezon — APPROVED** [review]

**Comment by Mauller** [comment]
I think it would also be better to change the loop to be a while loop as is more with convention for iterator loops that increment within the loop body.

```CPP
ParticleSystemListIt it = m_allParticleSystemList.begin(); 
while( it != m_allParticleSystemList.end() )  
{ 
    ...
}
```

**Comment by Caball009** [comment]
I feel silly for overlooking #841 somehow (I noticed the issue after some experiment).

> I think it would also be better to change the loop to be a while loop as is more with convention for iterator loops that increment within the loop body.
> 
> ```c++
> ParticleSystemListIt it = m_allParticleSystemList.begin(); 
> while( it != m_allParticleSystemList.end() )  
> { 
>     ...
> }
> ```

I agree. This way there's no temptation to make the iteration increment part of the loop itself:
`for(ParticleSystemListIt it = m_allParticleSystemList.begin(); it != m_allParticleSystemList.end(); ++it)`

The iterator increment must happen before the potential erasure, otherwise it's invalidated.

File: Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp (hunk 2 above)
Comment (Caball009) [reply Generals/Code/GameEngine/Source/GameClient/System/ParticleSys.cpp]: Done.

**Review by xezon — APPROVED** [review]

**Review by Mauller — APPROVED** [review]
