### PR TITLE
bugfix(view): Fix ground level of bookmarks, replay camera and game world microphone

### LINKED ISSUE #2520: Camera bookmarks zoom out past maximum
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Make bookmark with control+F1, then press F1.

### Reproduction Steps

See video. Tested using weekly-2026-03-27

### Additional Context

https://github.com/user-attachments/assets/70ee5f49-fc02-4b0d-9f16-7a5e64af1f3d

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #2520

This change fixes the ground level of bookmarks, replay camera and the game world microphone by merging `View::m_groundLevel` into `View::m_pos::z`.

`View::m_pos::z` was originally unused and `View::m_groundLevel` was effectively that. They are now consolidated which automatically adds the ground level into bookmarks and the replay camera through `ViewLocation` (cool).

The game world microphone, used for positional audio, did not calculate the microphone height correctly which was fixed as well.

In `View::lookAt` the pivot is now reset to the ground which corrects behavior as well.

## TODO

- [x] Replicate in Generals
- [x] Test a few cutscenes

### CODE REVIEW

**Comment by xezon** [comment]
Generals will fail to compile until replicated.

File: Core/GameEngine/Source/Common/Audio/GameAudio.cpp [hunk 1]
```diff
@@ -282,16 +282,16 @@ void AudioManager::reset()
 //-------------------------------------------------------------------------------------------------
 void AudioManager::update()
 {
-	Coord3D groundPos, microphonePos;
-	TheTacticalView->getPosition( &groundPos );
+	Coord3D microphonePos;
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/Audio/GameAudio.cpp]: Move to line 327 where it is used for the first time

**Review by Skyaero42 — CHANGES_REQUESTED** [review]

File: Core/GameEngine/Include/GameClient/View.h [hunk 2]
```diff
@@ -181,8 +181,10 @@ class View : public Snapshot
 	virtual Real getPitch() { return m_pitch; }										///< Return current camera pitch
 	virtual void setAngleToDefault();															///< Set the view angle back to default
 	virtual void setPitchToDefault();															///< Set the view pitch back to default
-	void setPosition( const Coord3D *pos ) { m_pos = *pos; }
-	void getPosition(Coord3D *pos) { *pos = m_pos;}							///< Returns position camera is looking at (z will be zero)
+	void setPosition( const Coord3D &pos ) { m_pos = pos; }
+	void setPosition2D( const Coord2D &pos ) { m_pos.x = pos.x; m_pos.y = pos.y; }
```
Comment (Mauller) [inline Core/GameEngine/Include/GameClient/View.h:191]: This might want to also zero m_pos.z.

File: Core/GameEngine/Include/GameClient/View.h [hunk 3]
```diff
@@ -302,7 +302,7 @@ class View : public Snapshot
 	UnsignedInt m_userControlLockedUntilFrame;									///< Locks the user control over camera until the given frame is reached
 	Bool m_isUserControlled;																		///< True if the user moved the camera last, false if the scripted camera moved the camera last
 
-	Coord3D m_pos;																							///< Pivot of the camera, in world coordinates // TheSuperHackers @todo Make this Coord2D or use the Z component
+	Coord3D m_pos;																							///< Pivot of the camera, in world coordinates
```
Comment (Mauller) [inline Core/GameEngine/Include/GameClient/View.h:312]: Not sure if this want's to be in this change, but i think this really needs a better name relative to its purpose.

`m_cameraPivotPos` etc

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 4]
```diff
@@ -305,9 +300,9 @@ void W3DView::buildCameraPosition( Vector3& sourcePos, Vector3& targetPos )
 	sourcePos *= heightScale;
 
 	// set look at position
-	targetPos.X += pos.x;
-	targetPos.Y += pos.y;
-	targetPos.Z += groundLevel;
+	targetPos.X = pos.x;
+	targetPos.Y = pos.y;
+	targetPos.Z = pos.z;
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:306]: targetPos = pos ? or does Coord3D not have a copy constructor?

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 5]
```diff
@@ -770,14 +764,11 @@ void W3DView::init()
 	setName("W3DView");
 	// set default camera "look at" point
 	Coord3D pos;
-	pos.x = 87.0f;
-	pos.y = 77.0f;
-	pos.z = 0;
+	pos.x = 87.0f * MAP_XY_FACTOR;
+	pos.y = 77.0f * MAP_XY_FACTOR;
+	pos.z = 10.0f;
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:770]: Might be good to have a constant for the default ground height and look at coords

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 6]
```diff
@@ -1873,7 +1864,9 @@ void W3DView::draw()
 	if( TheGlobalData->m_debugCamera )
 	{
 		UnsignedInt c = 0xaaffffff;
-		Coord3D worldPos = *getPosition();
+		Coord3D worldPos;
+		worldPos.x = getPosition().x;
+		worldPos.y = getPosition().y;
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: Wouldn't 

```C++
Coord3D worldPos = getPosition();
worldPos.z = TheTerrainLogic->getGroundHeight(worldPos.x, worldPos.y);
```

work here for a single call?

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 7]
```diff
@@ -3300,11 +3294,11 @@ void W3DView::moveAlongWaypointPath(Real milliseconds)
...
-		m_groundLevel = m_mcwpInfo.groundHeight[m_mcwpInfo.numWaypoints];
-
-		Coord3D pos = m_mcwpInfo.waypoints[m_mcwpInfo.numWaypoints];
-		pos.z = 0;
-		setPosition(&pos);
+		Coord3D pos;
+		pos.x = m_mcwpInfo.waypoints[m_mcwpInfo.numWaypoints].x;
+		pos.y = m_mcwpInfo.waypoints[m_mcwpInfo.numWaypoints].y;
+		pos.z = m_mcwpInfo.groundHeight[m_mcwpInfo.numWaypoints];
+		setPosition(pos);
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:3323]: Maybe?
```C++
Coord3D pos = m_mcwpInfo.waypoints[m_mcwpInfo.numWaypoints];
pos.z = m_mcwpInfo.groundHeight[m_mcwpInfo.numWaypoints];
```

File: Core/GameEngine/Include/GameClient/View.h (hunk 2 above)
Comment (xezon) [reply Core/GameEngine/Include/GameClient/View.h:191]: This intentionally only sets X Y, ignores Z.

File: Core/GameEngine/Include/GameClient/View.h (hunk 3 above)
Comment (xezon) [reply Core/GameEngine/Include/GameClient/View.h:312]: I agree but is beyond the scope of this change.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 4 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:306]: Vector3 does not know about Coord3D.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 6 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: Fixed

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 5 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:770]: I think these are just bogus values that will be overwritten soon afterwards. We could put 999999 here and it would change nothing.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 7 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:3323]: Fixed

File: Core/GameEngine/Source/Common/Audio/GameAudio.cpp (hunk 1 above)
Comment (xezon) [reply Core/GameEngine/Source/Common/Audio/GameAudio.cpp]: Fixed

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 4 above)
Comment (Mauller) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:306]: Ah no worries, i missed that they were different types, mostly been looking at this on github.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 5 above)
Comment (Mauller) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:770]: Seems odd to multiply them by MAP_XY_FACTOR if they are never used then.

File: Core/GameEngine/Include/GameClient/View.h (hunk 2 above)
Comment (Mauller) [reply Core/GameEngine/Include/GameClient/View.h:191]: So you have to be careful about calling getPosition if you have used setPosition2D since it could still be holding on to the z value.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 5 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:770]: Probably early values for testing or so.

File: Core/GameEngine/Include/GameClient/View.h (hunk 2 above)
Comment (xezon) [reply Core/GameEngine/Include/GameClient/View.h:191]: No. It is fine to modify X Y position without changing the height of the pivot.

**Review by Skyaero42 — APPROVED** [review]
Looks good to me. May also want to await @Mauller approval before merging

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 8]
```diff
@@ -1685,13 +1676,13 @@ void W3DView::calcDeltaScroll(Coord2D &screenDelta)
 {
 	screenDelta.x = 0;
 	screenDelta.y = 0;
-	Vector3 prevPos(m_previousLookAtPosition.x,m_previousLookAtPosition.y, m_groundLevel);
+	Vector3 prevPos(m_previousLookAtPosition.x, m_previousLookAtPosition.y, m_pos.z);
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1680]: this wants to be `m_previousLookAtPosition.z` which should be the ground level at the previous looked at position as m_pos.z could be different since then.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 9]
```diff
@@ -3065,7 +3057,7 @@ void W3DView::setupWaypointPath(Bool orient)
 		Real factor2 = curDistance / m_mcwpInfo.totalDistance;
 		Real factor1 = 1.0-factor2;
 		m_mcwpInfo.timeMultiplier[i] = m_timeMultiplier;
-		m_mcwpInfo.groundHeight[i] = m_groundLevel*factor1 + newGround*factor2;
+		m_mcwpInfo.groundHeight[i] = m_pos.z*factor1 + newGround*factor2;
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: Not sure if you want to do it here, but all instances of `m_mcwpInfo.groundHeight[i]` could be replaced with `m_mcwpInfo.waypoints[i].z`

then `m_mcwpInfo.groundHeight[]` could be removed from the `TMoveAlongWaypointPathInfo` struct as we then use Z on the wapoint for the ground height data.

Comment (Mauller) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: line 3296 would then be furthur simplified to just 

```c++
Coord3D pos = m_mcwpInfo.waypoints[m_mcwpInfo.numWaypoints];
setPosition(pos);
```

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 8 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1680]: I am not so sure about. I intentionally replaced `m_groundLevel` with `m_pos.z`, because this resembles what the original did and this function only cares about X Y, and not Z height differences, and maybe it would be a mistake to introduce Z shifts.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 10]
```diff
@@ -539,7 +533,7 @@ void W3DView::calcCameraAreaConstraints()
 		Matrix3D prevCameraTransform = m_3DCamera->Get_Transform();
 		m_3DCamera->Set_Transform(cameraTransform);
 
-		Real offset = calcCameraAreaOffset(m_groundLevel);
+		Real offset = calcCameraAreaOffset(m_pos.z);
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:537]: If we are only ever passing the ground level into `calcCameraAreaOffset`, we could internally make it use `m_pos.z` directly.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 8 above)
Comment (Mauller) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1680]: `m_previousLookAtPosition` is set by `getPosition()` so it should be more correct to use the z at the time `m_previousLookAtPosition` was set.

Comment (Mauller) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1680]: it could be the original implementation was not quite right since they didn't track historic ground level, camera::Project does take z into account internally when determining frustrum.

Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1680]: Yes but look at the context of this function: `void W3DView::calcDeltaScroll(Coord2D &screenDelta)`

This function is for scroll delta. It is only concerned about X Y. I would not touch this, unless it is proven that we need to fix it.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 10 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:537]: Yes but we can leave as is for now.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 9 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: `TMoveAlongWaypointPathInfo::groundHeight` removed. Tested and worked.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp (hunk 8 above)
Comment (Mauller) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1680]: The underlying camera functions that check the frustrum still use z etc.

But leave it for now to match current behaviour.

**Review by Mauller — APPROVED** [review]
Looks good, although what greptile brought up might want checking. But i don't see how it changes behaviour.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 11]
```diff
@@ -406,9 +400,8 @@ void W3DView::buildCameraTransform( Matrix3D *transform, const Vector3 &sourcePo
 						// WST 10.22.2002. Update the Listener positions used by audio system
 						//--------------------------------------------------------------------
 						Vector3 position = transform->Get_Translation();
-						Coord3D coord;
-						coord.set(position.X, position.Y, position.Z);
-						View::setPosition(&coord);
+						Coord3D coord = { position.X, position.Y, position.Z };
+						View::setPosition(coord);
```
[the remark this answers is not in the document]
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp]: Fixed

**Comment by xezon** [comment]
There are cutscene discrepancies in Generals that need looking into.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp [hunk 12]
```diff
@@ -1437,7 +1427,7 @@ void W3DView::update()
 				if (m_snapImmediate)
 					m_snapImmediate = FALSE;
 
-				m_groundLevel = objpos.z;
+				m_pos.z = objpos.z;
```
[the remark this answers is not in the document]
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1430]: This exactly replicates what the original did. I see no mistake.

**Comment by xezon** [comment]
I have appended new fixes for the scripted camera in regards to W3DView::lookAt. It now looks correct in Generals compaign cutscene.

**Comment by xezon** [comment]
Tested a few more cinematic scenes in Generals and it looked fine.
