### PR TITLE
bugfix(filesystem): Prevent loading wrong INIZH.big from Data/INI directory to prevent INI CRC mismatch

### LINKED ISSUE #1179: Duplicate and outdated INIZH.big file is not cleaned up on EA app/origin installs and is loaded
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

The game shipped with leftover outdated files (duplicate INIZH.big in Data/INI).

Line 342 in GameEngine.cpp tries to clean this up on startup, but this does not work on the EA app/origin version of the game because the folder is owned by the app and is not writable.

This results in the duplicate INI being loaded, which causes INI CRC not to match in multiplayer games, and can cause a mismatch if you do manage to get into game.

### Reproduction Steps

1. Install the game from EA App/Origin
2. Observe two INIZH.big files, one in the root folder and one in Data/INI
3. Run the game, notice that the DeleteFile/cleanup code does not successfully delete it (if you try to manually delete it via explorer, you'll need to give admin approval to do so
4. Try to join a multiplayer game which performs CRC checks, notice the CRC doesn't match, despite a clean game install via EA app
5. If you do manage to get past the CRC check, the game will eventually mismatch

### Additional Context

In GeneralsOnline, we now skip this file during loading, but there is probably a better solution for the longer term

### PR DESCRIPTION
**Pull request by bobtista**
- Fixes #1179

This change skips loading any BIG file matching `Data\INI\INIZH.big` during archive initialization.

### Testing

1. Install the game from EA App/Origin
2. Observe two INIZH.big files, one in the root folder and one in Data/INI
3. Run the game; notice that DeleteFile/cleanup code does not successfully delete it (this is expected and acceptable now)
4. Try to join a multiplayer game which performs CRC checks — CRC should now match
5. Play the multiplayer game — no mismatches should occur (From this issue)

### CODE REVIEW

**Comment by xezon** [comment]
Where is the Delete code? Can that be removed if it does not work anyway?

File: Core/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp [hunk 1]
```diff
@@ -215,6 +215,14 @@ Bool StdBIGFileSystem::loadBigFilesFromDirectory(AsciiString dir, AsciiString fi
 	Bool actuallyAdded = FALSE;
 	FilenameListIter it = filenameList.begin();
 	while (it != filenameList.end()) {
+		AsciiString filePath = (*it);
+		filePath.toLower();
+		// TheSuperHackers @fix bobtista 18/11/2025 Skip duplicate INIZH.big in Data\INI to prevent CRC mismatches on EA App/Origin installs
+		if (strstr(filePath.str(), "data\\ini\\inizh.big") != NULL || strstr(filePath.str(), "data/ini/inizh.big") != NULL) {
```
Comment (xezon) [inline Core/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp]: If this is Zero Hour specific, then it needs to be in `#if RTS_ZEROHOUR`

File: Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp [hunk 2]
```diff
@@ -216,6 +216,14 @@ Bool Win32BIGFileSystem::loadBigFilesFromDirectory(AsciiString dir, AsciiString
 	Bool actuallyAdded = FALSE;
 	FilenameListIter it = filenameList.begin();
 	while (it != filenameList.end()) {
+		AsciiString filePath = (*it);
+		filePath.toLower();
+		// TheSuperHackers @fix bobtista 18/11/2025 Skip duplicate INIZH.big in Data\INI to prevent CRC mismatches on EA App/Origin installs
+		if (strstr(filePath.str(), "data\\ini\\inizh.big") != NULL || strstr(filePath.str(), "data/ini/inizh.big") != NULL) {
```
Comment (xezon) [inline Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp]: `it->endsWithNoCase("data\\ini\\inizh.big") || it->endsWithNoCase("data/ini/inizh.big")`

Comment (xezon) [inline Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp]: `"data\\ini\\inizh.big"` path will not work if `dir` is not game root. Anything we can do about that?

**Comment by bobtista** [comment]
> Where is the Delete code? Can that be removed if it does not work anyway?

GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp line 402, and we can remove it yes. I'm unsure if it works on other installs eg the original CD, but we don't need it in any case. Remove it?

File: Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp (hunk 2 above)
Comment (bobtista) [reply Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp]: Yes, `endsWithNoCase` handles this, thanks for pointing it out to me. It matches the path suffix, so it works whether we're loading from the root directory or from installPath - both paths ending with `data\ini\inizh.big` will be detected.

**Comment by xezon** [comment]
I would say if this new change avoids all trouble, then remove the hack from Kris and transfer his original comment to the new hack to clarify the intention.

**Comment by xezon** [comment]
> notice that DeleteFile/cleanup code does not successfully delete it (this is expected and acceptable now)

Why does it not delete it? Does it fail because it does not have Admin privileges?

File: Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp (hunk 2 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp]: Ok makes sense.

**Comment by bobtista** [comment]
> > notice that DeleteFile/cleanup code does not successfully delete it (this is expected and acceptable now)
> 
> Why does it not delete it? Does it fail because it does not have Admin privileges?

Yes, from the issue "this does not work on the EA app/origin version of the game because the folder is owned by the app and is not writable."

File: Core/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp [hunk 3]
```diff
@@ -215,6 +215,14 @@ Bool StdBIGFileSystem::loadBigFilesFromDirectory(AsciiString dir, AsciiString fi
 	Bool actuallyAdded = FALSE;
 	FilenameListIter it = filenameList.begin();
 	while (it != filenameList.end()) {
+#if RTS_ZEROHOUR
+		// TheSuperHackers @fix bobtista 18/11/2025 Skip duplicate INIZH.big in Data\INI to prevent CRC mismatches on EA App/Origin installs
+		if ((*it).endsWithNoCase("data\\ini\\inizh.big") || (*it).endsWithNoCase("data/ini/inizh.big")) {
```
Comment (xezon) [inline Core/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp]: it->

File: Core/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp [hunk 4]
```diff
@@ -215,6 +215,14 @@ Bool StdBIGFileSystem::loadBigFilesFromDirectory(AsciiString dir, AsciiString fi
 	Bool actuallyAdded = FALSE;
 	FilenameListIter it = filenameList.begin();
 	while (it != filenameList.end()) {
+#if RTS_ZEROHOUR
+		// TheSuperHackers @fix bobtista 18/11/2025 Skip duplicate INIZH.big in Data\INI to prevent CRC mismatches on EA App/Origin installs
```
Comment (xezon) [inline Core/GameEngineDevice/Source/StdDevice/Common/StdBIGFileSystem.cpp]: `@bugfix` because it is user facing error

**Review by xezon — COMMENTED** [review]
> Remove it?

Yes. Move the EA comment to the new place.

**Comment by bobtista** [comment]
> Yes. Move the EA comment to the new place.

Done

**Review by xezon — APPROVED** [review]
Looks good.

File: Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp [hunk 5]
```diff
@@ -216,6 +216,16 @@ Bool Win32BIGFileSystem::loadBigFilesFromDirectory(AsciiString dir, AsciiString
 	Bool actuallyAdded = FALSE;
 	FilenameListIter it = filenameList.begin();
 	while (it != filenameList.end()) {
+#if RTS_ZEROHOUR
+		// TheSuperHackers @bugfix bobtista 18/11/2025 Skip duplicate INIZH.big in Data\INI to prevent CRC mismatches.
+		// English, Chinese, and Korean SKUs shipped with two INIZH.big files (one in Run directory, one in Run\Data\INI).
+		// The DeleteFile cleanup doesn't work on EA App/Origin installs because the folder is not writable, so we skip loading it instead.
+		if (it->endsWithNoCase("data\\ini\\inizh.big") || it->endsWithNoCase("data/ini/inizh.big")) {
```
Comment (xezon) [inline Core/GameEngineDevice/Source/Win32Device/Common/Win32BIGFileSystem.cpp]: How about we preserve the original case for good measure?

`Data\\INI\\INIZH.big`

**Review by xezon — APPROVED** [review]
