### PR TITLE
fix(font): Handle malformed fonts without crashing the game

### LINKED ISSUE #1790: FontCharsClass::Store_GDI_Char() crashes if pointersize is 0.
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

- Related to #1788 

If `PointerSize = 0` it causes a division by zero further on.

Recommended solution: catch the division by zero and add an assert.

### Reproduction Steps

n/a

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1790

`FontLibrary::getFont` allows creating fonts with 0 size, but they will be malformed and crash on use.

This happens because `FontCharsClass::Create_GDI_Font` will create a null `GDIBitmap` when the font size is zero.

```
 >	generalszh.exe!FontCharsClass::Store_GDI_Char(wchar_t ch) Line 1391	C++
 	generalszh.exe!FontCharsClass::Get_Char_Data(wchar_t ch) Line 1256	C++
 	generalszh.exe!FontCharsClass::Get_Char_Spacing(wchar_t ch) Line 1289	C++
 	generalszh.exe!Render2DSentenceClass::Allocate_New_Surface(const wchar_t * text, bool justCalcExtents) Line 645	C++
 	generalszh.exe!Render2DSentenceClass::Build_Sentence_Not_Centered(const wchar_t * text, int * hkX, int * hkY, bool justCalcExtents) Line 1005	C++
 	generalszh.exe!Render2DSentenceClass::Get_Formatted_Text_Extents(const wchar_t * text) Line 289	C++
 	generalszh.exe!W3DDisplayString::computeExtents() Line 362	C++
 	generalszh.exe!W3DDisplayString::setFont(GameFont * font) Line 308	C++
 	generalszh.exe!InGameUI::refreshRenderFpsResources() Line 5947	C++
 	generalszh.exe!InGameUI::refreshCustomUiResources() Line 5909	C++
 	generalszh.exe!InGameUI::reset() Line 2071	C++
 	generalszh.exe!W3DInGameUI::reset() Line 381	C++
 	generalszh.exe!GameClient::reset() Line 457	C++
 	generalszh.exe!W3DGameClient::reset() Line 106	C++
 	generalszh.exe!SubsystemInterfaceList::resetAll() Line 183	C++
 	generalszh.exe!GameEngine::resetSubsystems() Line 812	C++
 	generalszh.exe!GameEngine::init() Line 769	C++
 	generalszh.exe!Win32GameEngine::init() Line 66	C++
 	generalszh.exe!GameMain() Line 46	C++
 	generalszh.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 903	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
```

## TODO

- [x] Replicate in Generals

### CODE REVIEW

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp [hunk 1]
```diff
@@ -73,20 +73,13 @@
 //=============================================================================
 Bool W3DFontLibrary::loadFontData( GameFont *font )
 {
-	FontCharsClass *fontChar;
-
 	// sanity
 	if( font == NULL )
 		return FALSE;
 
-	if ((UnsignedInt)font->pointSize > 100)	//sanity check the size - anything over 100 is probably wrong. -MW
```
Comment (xezon) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp:82]: I put this test higher up the call chain for simplicity. `getFont` is the only caller of `loadFontData`.

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp [hunk 2]
```diff
@@ -73,20 +73,13 @@
...
-	{	// get the font data from the asset manager
-		fontChar = WW3DAssetManager::
-									Get_Instance()->Get_FontChars( font->nameString.str(), font->pointSize,
-																								 font->bold ? true : false );
-	}
+	// get the font data from the asset manager
+	FontCharsClass *fontChar = WW3DAssetManager::Get_Instance()->Get_FontChars(
+		font->nameString.str(), font->pointSize, font->bold ? true : false );
 
 	if( fontChar == NULL )
```
Comment (Skyaero42) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp:87]: Remove if-statement.
`Get_FontChars` does not return `NULL` object, so `fontChar` is never `NULL` here.

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp [hunk 3]
```diff
@@ -73,20 +73,13 @@
...
-	{	// get the font data from the asset manager
-		fontChar = WW3DAssetManager::
-									Get_Instance()->Get_FontChars( font->nameString.str(), font->pointSize,
-																								 font->bold ? true : false );
-	}
+	// get the font data from the asset manager
+	FontCharsClass *fontChar = WW3DAssetManager::Get_Instance()->Get_FontChars(
+		font->nameString.str(), font->pointSize, font->bold ? true : false );
 
 	if( fontChar == NULL )
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp:87]: same

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/GUI/W3DGameFont.cpp:87]: Right. This does not look sane. Fixed.

**Review by Skyaero42 — APPROVED** [review]
I think that's it

**Comment by xezon** [comment]
Replicated in Generals without conflicts

Game can now run without fonts.

shot_20251109_100239_1
