### PR TITLE
[GEN][ZH] Prevent game crash when a player is selected in Replay playback

### LINKED ISSUE #75: Game can crash when clicking on player icon in Replay Mode
Game can crash when clicking on player icon in Replay Mode. It is not 100%, but happens very regularly.

Here is a Replay for Zero Hour 1.04 where crash is reproducible:

[player_select_crash.zip](https://github.com/xezon/GeneralsGamePatch/files/7288370/player_select_crash.zip)

GenTool fixes this crash as following:

Inject naked function call at address `0x5FC8F5` taking 6 bytes to call naked function.

```c++
// CPU Disasm (Zero Hour 1.04)
// Address   Hex dump          Command                                  Comments
// 005FC8F0  |.  A1 A4A2A200   MOV EAX,DWORD PTR DS:[0A2A2A4]
// 005FC8F5  |.  E8 B6B7A00F   MOV CL,BYTE PTR DS:[EAX+86C]             ; inject here
// 005FC8FB  |.  84C9          TEST CL,CL
// 005FC8FD  |.  74 72         JE SHORT 005FC971
// 005FC8FF  |.  8B0D E0B6A200 MOV ECX,DWORD PTR DS:[0A2B6E0]
// 005FC905  |.  8B5424 28     MOV EDX,DWORD PTR SS:[LOCAL.70]
// 005FC909  |.  3991 B8020000 CMP DWORD PTR DS:[ECX+2B8],EDX
// 005FC90F  |.  75 60         JNE SHORT 005FC971
// 005FC911  |.  8BCD          MOV ECX,EBP
// 005FC913  |.  E8 A831F5FF   CALL 0054FAC0                            ; [game.0054FAC0
// 005FC918  |.  8B0D 88C0A200 MOV ECX,DWORD PTR DS:[0A2C088]

// The game crashes in function 0x54FAC0 -> called by multiple functions
// If you mess with 0x54FAC0, you can cause mismatches!
// It seems the object pointed to by EBP is missing data in a certain frames
// and the function wants to read data from it
// this will cause crashes as the memory is not valid
// To fix this, I figured that at EBP+C the value is always 0 when it crashes
// and greater one if not crashing
// So just skip the routine by moving 0 into CL and the work is done

//////////////////////////////////////////////////////////////////////////////////////

DWORD ccFixUnitSelectCrashRet;
__declspec(naked) void CC_FixUnitSelectCrash_ZH()
{
	__asm
	{
		pop [ccFixUnitSelectCrashRet]
		cmp dword ptr [ebp+0xC], 0
		je Fix
		mov cl, 1
		jmp End
	Fix:
		mov cl, 0
	End:
		push [ccFixUnitSelectCrashRet]
		ret
	}
}
```

### PR DESCRIPTION
**Pull request by xezon**
* Merge after #1002
* Replaces #1004
* Fixes #75
* Relates to #850

This change fixes a critical problem with AIGroup, that happens all the time in any match, but only crashes the Replay playback when a player is selected. The memory management of AIGroup is totally broken, and it will leak many AIGroups in AI matches (or matches that use AI scripts) and that will slow down iterating over `std::list<AIGroup *> m_groupList`.

## The Problem

AIGroup has a fundamental memory management flaw with its `AIGroup::remove` function. It deletes itself when all members are removed, which means that any non-AIGroup members holding a reference to that AIGroup will dangle when it is deleted.

This happens all the time in `GameLogic::logicMessageDispatcher` with its `currentlySelectedGroup` variable. It holds objects in a AIGroup, but that AIGroup can be deleted by external events, for example

```cpp
void GameLogic::logicMessageDispatcher( GameMessage *msg, void *userData )
{
...
  AIGroup* currentlySelectedGroup = NULL;

  if (isInGame())
  {
    if (msg->getType() >= GameMessage::MSG_BEGIN_NETWORK_MESSAGES && msg->getType() <= GameMessage::MSG_END_NETWORK_MESSAGES)
    {
      if (msg->getType() != GameMessage::MSG_LOGIC_CRC && msg->getType() != GameMessage::MSG_SET_REPLAY_CAMERA)
      {
        currentlySelectedGroup = TheAI->createGroup(); // can't do this outside a game - it'll cause sync errors galore.
        CRCGEN_LOG(( "Creating AIGroup %d in GameLogic::logicMessageDispatcher()\n", (currentlySelectedGroup)?currentlySelectedGroup->getID():0 ));
        thisPlayer->getCurrentSelectionAsAIGroup(currentlySelectedGroup);

...
  // process the message
  GameMessage::Type msgType = msg->getType();
  switch( msgType )
  {
...
    case GameMessage::MSG_REMOVE_BEACON:
    {
      AIGroup* allSelectedObjects = TheAI->createGroup();
      thisPlayer->getCurrentSelectionAsAIGroup(allSelectedObjects); // <----- xezon: this will delete the AIGroup pointed to by currentlySelectedGroup
```

There are multiple code paths like this that can delete `currentlySelectedGroup`.

## The Solution

With RETAIL_COMPATIBLE_CRC, `GameLogic::logicMessageDispatcher` now uses a massive hack to avoid crashing. It uses this hack because fixing AIGroup properly will mismatch with Retail. GenTool applies this exact hack since more than a decade.

## TODO

- [x] Test against VC6 Golden Replay
- [x] Replicate in Generals
- ~~Test against more replays~~

### CODE REVIEW

**Comment by xezon** [comment]
I think I will split this in 2.

**Comment by xezon** [comment]
Done.

**Review by Mauller — APPROVED** [review]
It is pretty nasty that, i guess other places are okay for this?

**Comment by xezon** [comment]
What do you mean by other places are okay for this?

**Comment by Mauller** [comment]
Oh I meant are the other places In the code that use this okay and dont need similar null testing?

**Comment by xezon** [comment]
We will know if we find more crashes.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp [hunk 1]
```diff
@@ -1997,6 +1997,14 @@ void GameLogic::logicMessageDispatcher( GameMessage *msg, void *userData )
 
 	}  // end switch
 
+#if RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @bugfix xezon 28/06/2025 This hack avoids crashing when players are selected during Replay playback.
+	// It can read data from an already deleted AIGroup and return this function when its member size is 0, signifying that
+	// it is indeed deleted.
+	if (currentlySelectedGroup && currentlySelectedGroup->getCount() == 0)
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp:2004]: As the comments points out `currentlySelectedGroup` may point to deallocated memory. It's not safe to access the `getCount` member function. The only reason it works is because the default behavior of the memory allocator doesn't include overwriting freed memory. 

If `MEMORYPOOL_DEBUG` is enabled, freed memory is overwritten with a garbage value, so `getCount()` doesn't return 0. The execution flow will continue and may crash below.
