### PR TITLE
fix(network): Fix missing value initialization of LANGameInfo::m_isDirectConnect

### LINKED ISSUE #1802: Always set isDirectConnect variable when announcing LAN game
When a game hoster announces their game to the lobby, the message is supposed to set `GameInfo.isDirectConnect` like so:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/e2385c5215927c55e8a7c0f2cc0cc92a69d6b11e/GeneralsMD/Code/GameEngine/Source/GameNetwork/LANAPI.cpp#L717-L718

https://github.com/TheSuperHackers/GeneralsGameCode/blob/e2385c5215927c55e8a7c0f2cc0cc92a69d6b11e/GeneralsMD/Code/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp#L197-L198

The same should be done below, otherwise the game may read uninitialized memory when parsing this message:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/e2385c5215927c55e8a7c0f2cc0cc92a69d6b11e/GeneralsMD/Code/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp#L67-L68

Additionally, `m_isDirectConnect` should probably be initialized in the constructor here:
https://github.com/TheSuperHackers/GeneralsGameCode/blob/e2385c5215927c55e8a7c0f2cc0cc92a69d6b11e/GeneralsMD/Code/GameEngine/Source/GameNetwork/LANGameInfo.cpp#L89-L100

### PR DESCRIPTION
**Pull request by bobtista**
- Fixes #1802 

## Summary
Fixes uninitialized memory bug in LAN game announcement messages when announcing games to the lobby.

## TODO
Testing

### CODE REVIEW

File: Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp [hunk 1]
```diff
@@ -65,6 +65,7 @@ void LANAPI::handleRequestLocations( LANMessage *msg, UnsignedInt senderIP )
 				strlcpy(reply.GameInfo.options, gameOpts.str(), ARRAY_SIZE(reply.GameInfo.options));
 				wcslcpy(reply.GameInfo.gameName, m_currentGame->getName().str(), ARRAY_SIZE(reply.GameInfo.gameName));
 				reply.GameInfo.inProgress = m_currentGame->isGameInProgress();
+				reply.GameInfo.isDirectConnect = m_currentGame->getIsDirectConnect();
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp:68]: What issue did this cause then? Was Direct Connect game visible in Network Lobby when it should not have been?

File: Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp [hunk 2]
```diff
@@ -92,6 +92,7 @@ LANGameInfo::LANGameInfo()
 	//Initializtions missing and needed
 	m_lastHeard = 0;
 	m_next = NULL;
+	m_isDirectConnect = false;
```
Comment (xezon) [inline Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp:93]: Are you certain this caused uninitialized memory use on runtime? LANGameInfo is allocated through Game Memory overloads, which means its memory is memset 0 before the constructor is called. So if you look at this object in debugger, then this field should 0 regardless.

Comment (bobtista) [reply Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp:93]: No, I think you're right here. Is it still good practice to do it explicitly here? If not, I can just drop that commit.

File: Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp (hunk 1 above)
Comment (bobtista) [reply Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp:68]: I don't have my PC to check this, I was just following the notes in the Issue. `handleRequestLocations` handler wasn't setting `reply.GameInfo.isDirectConnect` when building the game announcement message, so could we end up sending uninitialized data in that specific message struct?  Does LANMessage reply also get auto zeroed?

**Comment by Caball009** [comment]
In some cases `msg->GameInfo.isDirectConnect` shows up as uninitialized (0xCC) for me here: https://github.com/TheSuperHackers/GeneralsGameCode/blob/35b3f018773aa6a8683bd1b553e3c12cfe9db26f/Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp#L145

Reproduction:
1. Debug client 1.
2. Create a LAN game with client 2.
3. Join the lobby with client 1.

Maybe it only happens the first time that code executes after joining the lobby.

File: Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp (hunk 1 above)
Comment (xezon) [reply Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp:68]: You need to test the consequence of this bug so we can properly describe what this change fixes.

File: Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp (hunk 2 above)
Comment (xezon) [reply Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp:93]: This happens all over the code base. Class members are not explicitly zero initialized, which is a mistake in principle, but the memory allocator is forgiving (and very pessimistic) by zeroing every allocation.

**Comment by Caball009** [comment]
@bobtista Can you reproduce the issue with the above steps?

**Comment by bobtista** [comment]
> @bobtista Can you reproduce the issue with the above steps?

No, the joining client received game announcement: isDirectConnect=0 (0x00)

**Comment by Caball009** [comment]
Did you test with or without the changes in this PR?

You should definitely be able to reproduce the above steps without the changes, but it only happens the first time that code executes after joining the lobby.

**Comment by bobtista** [comment]
> Did you test with or without the changes in this PR?
> 
> You should definitely be able to reproduce the above steps without the changes, but it only happens the first time that code executes after joining the lobby.

Well the joining client was the fixed one, the hosting client was on main.  I'll try again

**Comment by bobtista** [comment]
> > @bobtista Can you reproduce the issue with the above steps?
> 
> No, the joining client received game

I started two new clients on main branch and followed the steps in order, got:
msg->GameInfo.isDirectConnect=true (204) / true (0xcc)

Repeated and got the same result 
msg->GameInfo.isDirectConnect=true (204) / true (0xcc)

I tried a third time and played around with going into network lobby and back to settings on both clients:
msg->GameInfo.isDirectConnect=false

There's something about the order

**Comment by Caball009** [comment]
Ok that's good. The issue should be fixed by the changes in this PR.

File: Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp (hunk 2 above)
Comment (Caball009) [reply Core/GameEngine/Source/GameNetwork/LANGameInfo.cpp:93]: > Are you certain this caused uninitialized memory use on runtime?

No, I don't think this changed anything, but it's always a good idea to initialize variables. The meaningful change is setting `reply.GameInfo.isDirectConnect`.

File: Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp (hunk 1 above)
Comment (Caball009) [reply Core/GameEngine/Source/GameNetwork/LANAPIhandlers.cpp:68]: > What issue did this cause then?

See other comments on this PR.

**Review by Caball009 — APPROVED** [review]
