### PR TITLE
tweak(drawable): Decouple stealth detected opacity fade time step from render update

### LINKED ISSUE #1719: Enemy stealthed units/buildings reveal animation flicker or animate too quickly at higher render FPS
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When enemy stealthed buildings or units are detected, the flashing reveal animation updates per render frame rather than per logic tick.
At higher render FPS, the animation runs too quickly and causes the building or unit to flicker.

### Reproduction Steps

1- Start a Skirmish match with GLA Stealth as opponent. 
2- Get them to stealth a building or build stealth base defenses.
3- Scan the building (USA drone, China Outposts etc.). 
4- Increase render FPS as you're observing the stealth reveal animation of the stealthed building.

### Additional Context

- This was first noticed on Generals Online then tested on the last weekly release to find the same behavior.

https://github.com/user-attachments/assets/3551304a-6f45-4496-b66d-7ea3f29ef17a

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1719
* Related to #1963

This change decouples the stealth opacity fade time step from the render update. This way it always fades with the same speed regardless of frame rate.

## TODO

- [x] Replicate in Generals

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp [hunk 1]
```diff
@@ -2607,16 +2607,27 @@ void Drawable::setStealthLook(StealthLookType look)
...
+			m_secondMaterialPassOpacity = 0.0f;
+		}
+		else if ( m_secondMaterialPassOpacity > VERY_TRANSPARENT_MATERIAL_PASS_OPACITY )
+		{
+			// keep fading any added material unless something has set it to zero
+			// TheSuperHackers @tweak The stealth opacity fade time step is now decoupled from the render update.
+			const Real timeScale = TheFramePacer->getActualLogicTimeScaleOverFpsRatio();
+			const Real opacityFrame = m_secondMaterialPassOpacity * MATERIAL_PASS_OPACITY_FADE_SCALAR;
+			const Real opacityStep = (m_secondMaterialPassOpacity - opacityFrame) * timeScale;
+			m_secondMaterialPassOpacity -= opacityStep;
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: I think this is slightly more performant and more in line with the structure of the original code.

```cpp
const Real materialPassOpacityFadeScalar = 1 - (1 - MATERIAL_PASS_OPACITY_FADE_SCALAR) * timeScale;
m_secondMaterialPassOpacity *= materialPassOpacityFadeScalar;
```

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: Both are 2 subtractions and 2 multiplications. Looks to be same cost maybe. Which one is easier to understand?

Comment (Skyaero42) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: Don't know if it matters much, but the section option compiles to less Assembly lines

{1A2285FC-434E-48AA-8929-EC786C554846}

If this is no performance improvement, then I would leave it as it is. I don't mind either in readability

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: Can you send godbolt link?

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: Not quite the same, but paints the same picture: https://godbolt.org/z/Yqjezxabj

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: It has one less sub because 1-constant is eval at compile.

Comment (Skyaero42) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: So one subtraction and one variable assignment less. No idea if that is measurable in performance.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp]: Tweaked.

**Comment by Caball009** [comment]
Comment and PR title should clarify that this is about **detected** stealth models.

**Review by Skyaero42 — APPROVED** [review]
Nice!

**Comment by xezon** [comment]
Replicated in Generals with conflicts.
