### PR TITLE
[GEN][ZH] Fix ThingTemplate copying to prevent multiplayer mismatch with original Shell Map and custom Maps

### LINKED ISSUE #856: Mismatches when using -quickstart
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

If some players use -quickstart to launch their game, and others do not, then a mismatch can occur where all the players with -quickstart have one checksum, and non-quickstart players have another checksum.

This is reproducible with a particular map: [Mod] Rebel Uprise 2 v10
The map is a heavily scripted map and also makes use of custom units. However, the fact that -quickstart is directly responsible for causing the mismatch here makes me think this is a game-related issue, and not a map-related issue. The map's scripts just make it convenient to replicate the bug.

Note that there is no mismatch if all players use either -quickstart or no -quickstart. This mismatch only occurs when there is a mix.

### Reproduction Steps

1. Have two players launch the game in -quickstart.
2. Have two players launch the game without quickstart.
3. Play multiplayer via Radmin in the LAN Lobby.
4. Play [Mod] Rebel Uprise 2 v10 (all players must select GLA for the map to work).
5. Have one player place one of the Hijackers in a hut with multiple flags. [This step may not be necessary, but it's what we kept doing.]
6. Have the player sell his Command Center.
7. Mismatch.
8. Have a look at the checksums in the replay. The players who launched the game with -quickstart will have one checksum value, the other players will have another checksum value.

### Additional Context

Map: [Mod] Rebel Uprise 2 v10
This map is part of the GenPatcher 'modded' map pack.
Direct download link: [Discord File Direct Link](https://cdn.discordapp.com/attachments/980161436850487296/1372143490099839027/Mod_Rebel_Uprise_2_v10.zip?ex=6825b3b5&is=68246235&hm=846b13a02371f81b771b343d37b159e3837a80556473b5e1e37d97948ac48239&)

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #856
* Closes #1194

This change fixes #856 and is an alternative implementation to #1194.

## TODO

- [x] Replicate in Generals
- [x] Test against replays in VC6

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h [hunk 1]
```diff
@@ -42,8 +42,14 @@
 	#undef SPARSEMATCH_DEBUG
 #endif
 
+typedef UnsignedInt SparseMatchFinderFlags;
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:45]: Is this needed? Unless I'm missing something, I think it'd be better to get rid of this `typedef`.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h [hunk 2]
```diff
@@ -185,9 +191,26 @@ class SparseMatchFinder
 		return result;
 	}
 
-	//-------------------------------------------------------------------------------------------------
 public:
 
+
+	//-------------------------------------------------------------------------------------------------
+	SparseMatchFinder() {}
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:198]: Is it necessary to define the constructor?

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h [hunk 3]
```diff
@@ -185,9 +191,26 @@ class SparseMatchFinder
...
+	SparseMatchFinder(const SparseMatchFinder& other)
+	{
+		*this = other;
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:201]: Shouldn't the copy flag be checked here as well?

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 2 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:198]: Technically we should define a destructor if we're following the rule of 3, but in this case it'd be empty and C++98 doesn't support the `default` keyword.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h [hunk 4]
```diff
@@ -185,9 +191,26 @@ class SparseMatchFinder
...
+	}
+
+	//-------------------------------------------------------------------------------------------------
+	SparseMatchFinder& operator=(const SparseMatchFinder& other)
+	{
+		if ((FLAGS & SparseMatchFinderFlags_NoCopy) == 0 && this != &other)
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h]: Could change the first check into `if CONSTEXPR` or `if CPP_11(constexpr)`; another if statement would be required for the second check.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 2 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:198]: There was a compile error when I did not add it. So I added that.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 3 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:201]: It is checked in the assignment operator (which this calls).

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 1 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:45]: This is the imgui style of declaring enums for flags.

The reason for this is that
```cpp
SparseMatchFinderFlags flags = flagName1 | flagName2;
```
does not work if SparseMatchFinderFlags is an enum. And it is bad to use `int` for flag types, because it is more difficult to follow what this flag type is then.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 3 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:201]: Ah right.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 4 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h]: Fixed.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 1 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:45]: It would work if you do it inside the enum itself (`flags1 = flagName1 | flagName2`), which may not be feasible for larger enums, but fair enough.

File: GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h (hunk 3 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:201]: I think this is a little awkward to have the copy constructor call the copy assignment operator and also potentially slightly inefficient if the data is copied. I'd propose this instead:

```
SparseMatchFinder(const SparseMatchFinder& other) : 
	m_bestMatches((FLAGS & SparseMatchFinderFlags_NoCopy) == 0 ? MatchMap() : other.m_bestMatches)
{}
```

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Include/Common/SparseMatchFinder.h:201]: If this construction was more simple then I would agree, but I think in this case it is easier to just write the code once for simpler C++ code. std::map does not allocate anything on default construction and there should be no worry about inefficiency - if the function was even called.

**Comment by Caball009** [comment]
The code looks alright. I can verify tomorrow whether the original issue is still fixed, although I don't see no reason why that wouldn't be the case.

I hope someone can run this against a large number of replays.

**Comment by helmutbuhler** [comment]
Checked with some replays, no mismatches.

**Comment by xezon** [comment]
Replicated in Generals without conflicts.
