### PR TITLE
bugfix(projectile): Fix out-of-bounds access in DumbProjectile which causes mismatch with very high speed weapons at small hit distances

### LINKED ISSUE #43: Tank projectiles cause mismatch
Tank projectiles cause mismatch. Please investigate how to fix this.

### PR DESCRIPTION
**Pull request by Caball009**
* Closes https://github.com/TheSuperHackers/GeneralsGameCode/issues/43

Sufficiently high weapon speeds expose an out-of-bounds access bug for `DumbProjectile`, which is the reason for non-deterministic behavior across clients (i.e. mismatches).

This PR should fix the bug properly, and make the behavior deterministic for retail and non-retail clients.

## TODO:
- ~[ ] Replicate in Generals~ 
Generals doesn't have this particular out-of-bounds bug.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 1]
```diff
@@ -649,7 +669,26 @@ UpdateSleepTime DumbProjectileBehavior::update()
...
+			// Using a fixed value means that the behavior is deterministic for patched clients.
+			if (m_flightPath.size() >= 2)
+			{
+				curPos = m_flightPath[1];
+			}
+			else
+			{
+				DEBUG_CRASH(("Vector must contain two or more elements; check the weapon speed value"));
+
+				const Coord3D indeterminateValue = Coord3D(-NAN, -NAN, -NAN);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Why -nan ? Is this sane?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 2]
```diff
@@ -446,7 +446,21 @@ Bool DumbProjectileBehavior::calcFlightPath(Bool recalcNumSegments)
 		Real flightDistance = flightCurve.getApproximateLength();
 		m_flightPathSegments = ceil( flightDistance / m_flightPathSpeed );
 	}
-	flightCurve.getSegmentPoints( m_flightPathSegments, &m_flightPath );
+
+#if RETAIL_COMPATIBLE_CRC
+	flightCurve.getSegmentPoints(m_flightPathSegments, &m_flightPath);
+#else
+	if (m_flightPathSegments >= 2)
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: I think this needs a `@bugfix` comment here describing the fix.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 3]
```diff
@@ -649,7 +669,26 @@ UpdateSleepTime DumbProjectileBehavior::update()
...
+			}
+			else
+			{
+				DEBUG_CRASH(("Vector must contain two or more elements; check the weapon speed value"));
+
+				const Coord3D indeterminateValue = Coord3D(-NAN, -NAN, -NAN);
+				curPos = indeterminateValue;
+			}
+#else
+			curPos = m_flightPath[1];
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Better: `Coord3D curPos = ...`

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 4]
```diff
@@ -446,7 +446,21 @@ Bool DumbProjectileBehavior::calcFlightPath(Bool recalcNumSegments)
...
+#if RETAIL_COMPATIBLE_CRC
+	flightCurve.getSegmentPoints(m_flightPathSegments, &m_flightPath);
+#else
+	if (m_flightPathSegments >= 2)
+	{
+		flightCurve.getSegmentPoints(m_flightPathSegments, &m_flightPath);
+	}
+	else
+	{
+		m_flightPathSegments = 0;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: I assume this means a single segment only is not possible?

**Review by xezon — COMMENTED** [review]
Looks logical in principle.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 4 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: That's my understanding, yes.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 1 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: No, I don't think this makes much sense. I thought I could delay a mismatch by setting these values, but it's probably a silly endeavor trying to get 'right' indeterminate values to imitate retail behavior.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 2 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Added comment.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 3 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Changed.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 5]
```diff
@@ -648,8 +670,26 @@ UpdateSleepTime DumbProjectileBehavior::update()
...
+			// The non-deterministic behavior for retail clients cannot be fixed, so this will remain a source of potential mismatches in retail compatibility mode.
+			// If there's only one element, set current position to a valid value so that the behavior is deterministic for patched clients.
+			if (m_flightPath.size() >= 2)
+			{
+				curPos = m_flightPath[1];
+			}
+			else
+			{
+				DEBUG_CRASH(("Vector must contain two or more elements; check the weapon speed value"));
+				curPos = prevPos;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: This does not look healthy. It would mean curDir becomes 0,0,0, which not a valid direction.

Maybe simply set curDir to 0,1,0 here so it looks in +Y direction.

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: I chose to do this with the position values, if that's ok. I also set the previous position, so that its value doesn't have to be inferred but is clear from the code here.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Looks ok.

**Review by xezon — APPROVED** [review]
Code looks correct to me.

**Comment by Caball009** [comment]
I hadn't at looked the Generals code until now. 

https://github.com/TheSuperHackers/GeneralsGameCode/blob/8c560e60e1ad3db4eea2a1ead2a6c18fa7eebc8f/GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp#L651-L652

https://github.com/TheSuperHackers/GeneralsGameCode/blob/8c560e60e1ad3db4eea2a1ead2a6c18fa7eebc8f/Generals/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp#L635-L638

It doesn't have this particular OOB bug, but I'm not entirely sure why the code was updated for Zero Hour or how the behavior changed.

**Comment by Caball009** [comment]
Maybe we can just leave the Generals code 'as is', and look at it in more detail later as part of a unification effort for this code.

**Comment by xezon** [comment]
Is the code very different yes?

**Comment by Caball009** [comment]
Check the links two comments back. It's not that different, but it doesn't have this particular OOB bug.

**Review by xezon — DISMISSED** [review]

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 6]
```diff
@@ -446,7 +446,23 @@ Bool DumbProjectileBehavior::calcFlightPath(Bool recalcNumSegments)
...
+#if RETAIL_COMPATIBLE_CRC
+	flightCurve.getSegmentPoints(m_flightPathSegments, &m_flightPath);
+#else
+	if (m_flightPathSegments >= 2)
+	{
+		flightCurve.getSegmentPoints(m_flightPathSegments, &m_flightPath);
+	}
+	else
+	{
+		m_flightPathSegments = 0;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Thinking about this again, is this really correct? If flight path segment is 1, then we would still expect the bullet to fly for one frame right? But with this change the single frame is turned into zero frames, effectively "cheating" by one frame.

**Comment by xezon** [comment]
@greptileai

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 6 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: I'm going to need a bit more time to look into this.

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Good catch. Updated the code to account for the single frame delay.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 7]
```diff
@@ -648,8 +653,36 @@ UpdateSleepTime DumbProjectileBehavior::update()
...
+
+			if (m_flightPath.size() >= 2)
+			{
+				prevPos = m_flightPath[0];
+				curPos = m_flightPath[1];
+			}
+			else
+			{
+				prevPos.set(0.0f, 0.0f, 0.0f);
+				curPos.set(0.0f, 1.0f, 0.0f);
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Perhaps we could do the same here as in the non-retail code.

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: That way the code could get a lot simpler:

```cpp
// TheSuperHackers ...
if (m_flightPath.size() < 2)
{
		DEBUG_CRASH(("Vector is expected to contain two or more elements; check the weapon speed value"));

		// there is no valid flight path to calculate but detonation needs to be delayed by a single frame
		++m_currentFlightPathStep;
		return UPDATE_SLEEP_NONE;
}

Coord3D prevPos = m_flightPath[0];
Coord3D curPos = m_flightPath[1];

Vector3 curDir ... /// original code continues
```

There would be no separate retail / non-retail code. Does this make sense?

**Review by xezon — CHANGES_REQUESTED** [review]
This is one of currently 3 open PRs with fixes for uninitialized variables, which come with a small risk of introducing new mismatches. These should be merged together without other PRs in between:
* #1748
* #2087
* #2096

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 7 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Is the flight path for 1 frame really malformed? Just because of the rotation calculation? Maybe this should just work with no expectations for lower weapon speeds. Maybe determine rotation by taking the projectile target or source position into account when the path has just 1 point.

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Is that an improvement? We would be doing more work than necessary, because I don't think the projectile is visible with only a single point.

I changed the code to what I think you had in mind.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 8]
```diff
@@ -648,8 +652,24 @@ UpdateSleepTime DumbProjectileBehavior::update()
...
+			Coord3D curPos;
+
+			if (m_flightPath.size() >= 2)
+			{
+				prevPos = m_flightPath[0];
+				curPos = m_flightPath[1];
+			}
+			else
+			{
+				DEBUG_CRASH(("Vector is expected to contain two or more elements; check the weapon speed value"));
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Is this debug necessary? What is the detriment now if this code path hits? Does it work correctly or not?

Maybe put the `DEBUG_CRASH` behind `RETAIL_COMPATIBLE_CRC`? Then it makes sense.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 7 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Yes this looks promising. Did you test it? Does it look ok?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 8 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: > Maybe put the `DEBUG_CRASH` behind `RETAIL_COMPATIBLE_CRC`? Then it makes sense.

Yeah, that makes more sense. Changed.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp (hunk 7 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: There's no visible projectile, but that's to be expected. There's also no bullet impact when force firing on the ground.

Where the damage is applied needs more testing, because it seems like it's applied to a much wider field.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 9]
```diff
@@ -648,8 +652,28 @@ UpdateSleepTime DumbProjectileBehavior::update()
...
+				curPos = m_flightPath[1];
+			}
+			else
+			{
+#if RETAIL_COMPATIBLE_CRC
+				DEBUG_CRASH(("A mismatch is likely to happen if this code path is used in a match with unpatched clients."
+					" Vector is expected to contain two or more elements; check the weapon speed value."));
+#endif
+
+				flightStep = m_flightPathStart;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Why is this necessary?

Previously it was set to `Coord3D flightStep = m_flightPath[m_currentFlightPathStep];`

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Because with a single flight step (`m_flightPathSegments == 1`) `getSegmentPoints` pushes a single element to `m_flightPath` with (0, 0, 0) coordinate values. I hadn't noticed this issue before.

**Review by xezon — COMMENTED** [review]
Ok. Should be good then.

**Comment by Caball009** [comment]
I'll put my last comment here, so it doesn't get buried.

With fewer than 2 points, there's no visible projectile, but that's to be expected. There's also no bullet impact when force firing on the ground. Where the damage is applied needs more testing, because it seems like it's applied to a much wider field.

**Comment by tintinhamans** [comment]
@greptileai

**Comment by tintinhamans** [comment]
@greptileai

**Comment by Caball009** [comment]
> With fewer than 2 points, there's no visible projectile, but that's to be expected. There's also no bullet impact when force firing on the ground. Where the damage is applied needs more testing, because it seems like it's applied to a much wider field.

Fixed. The projectile is still invisible, but that's alright. The projectile impact and damage are now properly applied to the projectile's destination.

This PR is ready to be merged whenever the other PRs are.

**Review by xezon — APPROVED** [review]

**Comment by xezon** [comment]
This change is labeled as NoRetail. Is that correct ?

**Comment by Caball009** [comment]
FWIW, I was under the impression this was never an issue for the retail game / vanilla files. However, I went through a large number of GenTool replays and came across one replay that mismatched because of this change. I'm only posting this for posterity. 

The tanks were on a slope, which is a [known contributing factor](https://github.com/TheSuperHackers/GeneralsGameCode/issues/43#issuecomment-2691349523) to the issue:

gen_zh_mm_pr2087

---

[09-29-13_3v1_komp6_komp7_komp8_komp10.zip](https://github.com/user-attachments/files/29923325/09-29-13_3v1_komp6_komp7_komp8_komp10.zip)

Edit: here are five more replays:
[09-33-21_3v1_danisowi_Andi_IVANICZ_EasyAI.zip](https://github.com/user-attachments/files/30027728/09-33-21_3v1_danisowi_Andi_IVANICZ_EasyAI.zip)
[09-40-43_1v1v2_ali321_ali_HardAI_HardAI.zip](https://github.com/user-attachments/files/30028607/09-40-43_1v1v2_ali321_ali_HardAI_HardAI.zip)
[12-53-58_3v1_DESKTOPG_9704_ahmadkha_MediAI.zip](https://github.com/user-attachments/files/30028911/12-53-58_3v1_DESKTOPG_9704_ahmadkha_MediAI.zip)
[17-50-44_4v1_DESKTOPG_9704_ahmadkha_mehran15_EasyAI.zip](https://github.com/user-attachments/files/30031268/17-50-44_4v1_DESKTOPG_9704_ahmadkha_mehran15_EasyAI.zip)
[14-55-35_2v1_adnan_Rayyan_EasyAI.zip](https://github.com/user-attachments/files/31160376/14-55-35_2v1_adnan_Rayyan_EasyAI.zip)
