### PR TITLE
[GEN][ZH] Fix incorrect garrison points debug assert hit in Shell Map

### LINKED ISSUE #1282: Garrison points assert on launch of Shell Map
There is a garrison points assert on launch of Shell Map. 
Possible introduced with #783 when the assert was moved out of the loop.

### PR DESCRIPTION
**Pull request by roossienb**
- Resolves #1282 
- Follow up on #783 

**Context**: PR #783 relocated a `DEBUG_ASSERTCRASH` outside the `for`-loop, which now triggers unexpectedly in the shell map scenario. This occurs because `containList` is empty in the shell map, meaning the assertion—previously nested and bypassed when the loop was skipped—is now always evaluated.

**Fix**: Update the assertion to also validate that `containList` is empty, ensuring consistent behavior regardless of loop execution.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp [hunk 1]
```diff
@@ -638,7 +638,7 @@ void GarrisonContain::trackTargets( void )
 	AIUpdateInterface *ai;
 	Object *obj;
 
-	DEBUG_ASSERTCRASH(m_garrisonPointsInitialized, ("garrisonPoints are not inited"));
+	DEBUG_ASSERTCRASH(m_garrisonPointsInitialized || containList.size() == 0, ("garrisonPoints are not inited"));
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Contain/GarrisonContain.cpp]: containList.empty()
