### PR TITLE
bugfix(fps): Fix and improve logic time step and render update decoupling 2

### LINKED ISSUE #1636: Motorized units weired movement
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When testing the latest release, I noticed that my own tanks and moving units were shaking in Twilight Flame. I only tested this for the USA and Twilight Flame map.

Is this a known issue?

Linked Video:

[vlc-record-2025-09-26-10h39m17s-Community Patch ~1 By Stubbjax for Command & Conquer (TM) Generals Zero Hour Version 1.04-.zip](https://github.com/user-attachments/files/22556468/vlc-record-2025-09-26-10h39m17s-Community.Patch.1.By.Stubbjax.for.Command.Conquer.TM.Generals.Zero.Hour.Version.1.04-.zip)

### Reproduction Steps

Start new game in multiplayer with AI and USA as own player with map Twilight flame
Build motorized vehicles 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Follow up for #1528
* Fixes #1636

This change is a follow up for #1528 and applies more fixes to properly decouple the render update from the logic step. This change has a lot of tiny commits to make it easy to review and find any issues that may arise from it.

The following issues were identified and fixed:

## W3DTankDraw update

Unlike `W3DTruckDraw` and `W3DTankTruckDraw`, the `W3DTankDraw::doDrawModule` did not call `W3DModelDraw::doDrawModule` on every render frame. This caused missing object transform on every non-logic frame. Simple fix.

## Snow update

Snow movement was updated once every logic frame. It is now smoothly updated every render frame.

## Segline update

Segmented line update (used by Lotus Hack, Patriot Assist beam) was updated once every logic frame. It is now smoothly updated every render frame.

## W3D Object Animation update

Decoupling the object animations for logic step was a bit more tricky because there was a bug that would not cause issues in the original implementation, but was a problem for the decoupling.

`Animatable3DObjClass::Single_Anim_Progress` was called twice every update, so trying to advance an animation with the render frame time would advance it twice as fast. This is now fixed.

`Animatable3DObjClass::Compute_Current_Frame` is now smoothly updated every render frame.

## WW Sync not in sync with Logic Step

The WW Sync was not perfectly in frame sync with the logic step. It was interleaved. This was introduced by previous changes. The result of this was that objects would move in one render frame, but object animations and physic movements would apply 1 render frame or so later. They would still have the same tick, but not on the exact frame. This is bad, because it gives the illusion of jittery movement.

The WW Sync and Logic Step are not back in sync.

## W3D Object Animation interpolation

All AnimClass animation have interpolation support for transforms and rotations. But `HRawAnimClass` had it intentionally disabled. This affects many (or all?) animations. Interpolations are now enabled, which makes all animations perfectly smooth. This is desirable on almost all animations, except for those that want to teleport meshes, such as blinking lights.

## Cloud update

The terrain cloud was updated once every logic frame. It is now smoothly updated every render frame. To do that, the cloud movement had to be moved out of its prior function into a new one that is only called once, instead of many times over.

## Drawable Tint Envelope update

The build placement preview object started flickering when it was colliding with objects. The reason for this was a bit more complicated to figure out: 

The calls to `colorTint` for the drawable in `InGameUI::handleBuildPlacements` on drawable collision are not called every logic frame, but every second logic frame. Furthermore, the tint envelope was not actually tinting with a stable color as was intended, but did attempt to fade the tint on the next frame. This caused the flickering on the alternating logic frames. This issue was fixed by correcting the tint logic mistakes.

## RingRenderObjClass::animate, SphereRenderObjClass::animate, DazzleRenderObjClass::Render, TexProjectClass::Pre_Render_Update

Courtesy. I adjusted these 4 to logically update correctly every render frame, but they appear to be unused and I have not found a way to test them.

## TODO

- [x] Replicate in Generals
- [x] Add pull id to commits

### CODE REVIEW

File: GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h [hunk 1]
```diff
@@ -162,18 +162,20 @@ class WW3D
 
 	static void Flip_To_Primary(void);
 
-	// TheSuperHackers @info Call this function to accumulate fractional render time.
-	// It will then call Sync with a new time on its own once an appropriate amount of time has passed.
+	// TheSuperHackers @info Add amount of milliseconds that the simulation has advanced in this render frame.
+	// This can be a fraction of a logic step. It will call Sync on its own once an appropriate amount of time has passed.
```
Comment (xezon) [inline GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h]: This comment is no longer correct.

Comment (xezon) [reply GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h]: Fixed

**Comment by xezon** [comment]
Fixed the w3dview compile error. Fixed a few variable and function names.

Generals will fail to compile until code is replicated for it.

**Comment by WWB2-account** [comment]
Am I correct to understand that snow and clouds now move at speeds dependent on render fps, e.g. twice as fast when having render 60, logic 30?

**Comment by xezon** [comment]
> Am I correct to understand that snow and clouds now move at speeds dependent on render fps, e.g. twice as fast when having render 60, logic 30?

No. Their speed will be determined by the logic time scale, but every render frame advances their movement.

**Comment by WWB2-account** [comment]
>>Am I correct to understand that snow and clouds now move at speeds dependent on render fps, e.g. twice as fast when having render 60, logic 30?

>No. Their speed will be determined by the logic time scale, but every render frame advances their movement.

Excellent. Understood.

**Comment by ElTioRata** [comment]
Just tested it a bit. Noticed that camera zoom speed is reduced at higher frame rates. Are you going to address this on another PR?

**Comment by xezon** [comment]
> Just tested it a bit. Noticed that camera zoom speed is reduced at higher frame rates. Are you going to address this on another PR?

I noticed that too. I will check.

Edit: fixed in #1587.

File: GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp [hunk 2]
```diff
@@ -166,6 +166,7 @@ const char* DAZZLE_INI_FILENAME="DAZZLE.INI";
 **
 ***********************************************************************************/
 
+float														WW3D::LogicFrameTimeMs = 33.33f;
```
Comment (Mauller) [inline GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp]: would be more accurate to define this as 1000.0f / 30.0f

**Review by Mauller — APPROVED** [review]
Looks good overall to me

File: GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp (hunk 2 above)
Comment (xezon) [reply GeneralsMD/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp]: Fixed.

It does not really matter. It is only initialized to a reasonable non zero value to avoid any potential division by zero on first use (when it is used before it is set by the update loop).

I added a comment.

**Comment by xezon** [comment]
Replicated to Generals with not so many conflicts.

Generals works.

**Comment by xezon** [comment]
The individual commits are compiling one after another.
