### PR TITLE
[GEN][ZH] Fix unsafe calls to _vsnprintf, _vsnwprintf, _snprintf, _snwprintf

### LINKED ISSUE #826: AsciiString::format_va is unsafe
```cpp
void AsciiString::format_va(const AsciiString& format, va_list args)
{
	validate();
	char buf[MAX_FORMAT_BUF_LEN];
  if (_vsnprintf(buf, sizeof(buf)/sizeof(char)-1, format.str(), args) < 0)
			throw ERROR_OUT_OF_MEMORY;
	set(buf);
	validate();
}
```

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l?view=msvc-170
> vsnprintf function always writes a null terminator, even if it truncates the output. When you use _vsnprintf and _vsnwprintf, the buffer is null-terminated only if there's room at the end (that is, if the number of characters to write is less than count)

We either need to use `vsnprintf` with len(buf) or zero terminate buf with `_vsnprintf` with len(buf)-1

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #826

This change fixes all unsafe calls to `_vsnprintf`, `_vsnwprintf`, `_snprintf`, `_snwprintf`. In practice most or all of these probably were no problem, but there was a small chance because these Microsoft specific versions do not null terminate when the whole buffer length is written to.

All code now calls the standard stdio functions. For VC6, an adapter header was added.

The following functions contained potentially unsafe calls:

| File                     | Function |
|--------------------------|----------|
| debug_debug              | Debug::Format::Format |
| debug_debug              | Debug::operator<< |
| profile_highlevel        | ProfileId::AsString |
| statistics               | Record_Texture_End |
| urlBuilder               | FormatURLFromRegistry |
| ini                      | INIClass::DuplicateCRCError |
| widestring               | WideStringClass::Format_Args |
| widestring               | WideStringClass::Format |
| wwfile                   | FileClass::Printf |
| wwfile                   | FileClass::Printf_Indented |
| wwstring                 | StringClass::Format_Args |
| wwstring                 | StringClass::Format |
| autorun                  | Dialog_Box_Proc |
| GameText                 | GameTextManager::fetch |
| AsciiString              | AsciiString::format_va |
| UnicodeString            | UnicodeString::format_va |
| InGameUI                 | InGameUI::message |
| PeerThread               | PeerThreadClass::Thread_Function |
| GameSpyPersistentStorage | getPersistentDataCallback |

### CODE REVIEW

**Comment by Mauller** [comment]
Doesn't seem to like some of the castings in VC6

```autorun.cpp(2658) : error C2664: 'snwprintf' : cannot convert parameter 2 from 'unsigned short [260]' to 'unsigned int'```

File: Dependencies/Utility/Utility/stdio_adapter.h [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+// Yes, this is called vswprintf instead of vsnwprintf
+inline int vswprintf(wchar_t* _Buffer, size_t _BufferCount, const wchar_t* _Format, va_list _ArgList)
+{
+    // Microsoft's _vsnwprintf does not null terminate when writing the entire length.
+    int result = _vsnwprintf(_Buffer, _BufferCount, _Format, _ArgList);
+    _Buffer[_BufferCount - 1] = L'\0';
+    return result;
+}
+
```
Comment (Mauller) [inline Dependencies/Utility/Utility/stdio_adapter.h:43]: It would be better to call these by and use the newer safe variants of these functions for cross compat and VS22 etc.

In this case it would be ```vsnwprintf_s``` for example, then provide a definition for it in terms of what you have done above for VC6.

```CPP
inline int vsnwprintf_s(wchar_t* _Buffer, size_t _BufferCount, const wchar_t* _Format, va_list _ArgList)
{
    // Microsoft's _vsnwprintf does not null terminate when writing the entire length.
    int result = _vsnwprintf(_Buffer, _BufferCount, _Format, _ArgList);
    _Buffer[_BufferCount - 1] = L'\0';
    return result;
}
```

The newer safe variants all null terminate the string and have other safer behaviour when the buffer limit is hit.

File: Dependencies/Utility/Utility/stdio_adapter.h [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+**	This program is distributed in the hope that it will be useful,
+**	but WITHOUT ANY WARRANTY; without even the implied warranty of
+**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+**	GNU General Public License for more details.
+**
+**	You should have received a copy of the GNU General Public License
+**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
+*/
+
+#pragma once
```
Comment (Mauller) [inline Dependencies/Utility/Utility/stdio_adapter.h:19]: You might want to add traditional header guards for VC6, it does not understand pragma once.
This could get included multiple times within a single compilation unit.

File: Dependencies/Utility/Utility/stdio_adapter.h (hunk 1 above)
Comment (xezon) [reply Dependencies/Utility/Utility/stdio_adapter.h:43]: I say that is well beyond the scope of this change. `vsnwprintf_s` has different function arguments.

File: Dependencies/Utility/Utility/stdio_adapter.h (hunk 2 above)
Comment (xezon) [reply Dependencies/Utility/Utility/stdio_adapter.h:19]: https://en.wikipedia.org/wiki/Pragma_once

Microsoft Visual C++ (since 4.2)

Comment (Mauller) [reply Dependencies/Utility/Utility/stdio_adapter.h:19]: Huh, i was getting conflicting information from different sources and the links that provides to the original sources don't provide any detail anymore for VC6.0

File: Dependencies/Utility/Utility/stdio_adapter.h (hunk 1 above)
Comment (Mauller) [reply Dependencies/Utility/Utility/stdio_adapter.h:43]: That's fair, it looks like the standard library implementations null terminate since C99.

**Review by Mauller — APPROVED** [review]
Looks Good. I see in some places they just relied on initialising the buffer to zero.

**Review by OmniBlade — APPROVED** [review]

**Comment by xezon** [comment]
Merge conflicts fixed.
