### PR TITLE
[GEN][ZH] Prevent executing death modules and spawning new objects to avoid asserts and crashes when unloading a map and destroying all objects

### LINKED ISSUE #896: Game runs death modules and eventually spawns new objects when unloading a level and destroying all objects
Game runs death modules and eventually spawns new objects when unloading a level and destroying all objects. This can have unintended consequences, such as crashing the game.

## Replay

Replay: [crash_debris_owner_pointer.zip](https://github.com/user-attachments/files/20297244/crash_debris_owner_pointer.zip)

## Crash Callstack

```
>	generalszh.exe!Player::getProductionVeterancyLevel(AsciiString buildTemplateName) Line 1997	C++
 	generalszh.exe!Object::Object(const ThingTemplate * tt, const BitFlags<45> & objectStatusMask, Team * team) Line 478	C++
 	generalszh.exe!GameLogic::friend_createObject(const ThingTemplate * thing, const BitFlags<45> & statusBits, Team * team) Line 3964	C++
 	generalszh.exe!ThingFactory::newObject(const ThingTemplate * tmplate, Team * team, BitFlags<45> statusBits) Line 329	C++
 	generalszh.exe!GenericObjectCreationNugget::reallyCreate(const Coord3D * pos, const Matrix3D * mtx, float orientation, const Object * sourceObj, unsigned int lifetimeFrames) Line 1369	C++
 	generalszh.exe!GenericObjectCreationNugget::create(const Object * primary, const Object * secondary, unsigned int lifetimeFrames) Line 797	C++
 	generalszh.exe!ObjectCreationList::createInternal(const Object * primary, const Object * secondary, unsigned int lifetimeFrames) Line 1569	C++
 	[Inline Frame] generalszh.exe!ObjectCreationList::create(const ObjectCreationList *) Line 163	C++
 	generalszh.exe!WeaponTemplate::fireWeaponTemplate(const Object * sourceObj, WeaponSlotType wslot, int specificBarrelToUse, Object * victimObj, const Coord3D * victimPos, const WeaponBonus & bonus, bool isProjectileDetonation, bool ignoreRanges, Weapon * firingWeapon, ObjectID * projectileID, bool inflictDamage) Line 976	C++
 	generalszh.exe!Weapon::privateFireWeapon(const Object * sourceObj, Object * victimObj, const Coord3D * victimPos, bool isProjectileDetonation, bool ignoreRanges, unsigned int extraBonusFlags, ObjectID * projectileID, bool inflictDamage) Line 2644	C++
 	[Inline Frame] generalszh.exe!Weapon::fireWeapon(const Object *) Line 2727	C++
 	generalszh.exe!WeaponStore::createAndFireTempWeapon(const WeaponTemplate * wt, const Object * source, const Coord3D * pos) Line 1544	C++
 	generalszh.exe!FireWeaponWhenDeadBehavior::onDie(const DamageInfo * damageInfo) Line 119	C++
 	generalszh.exe!Object::onDie(DamageInfo * damageInfo) Line 4563	C++
 	generalszh.exe!ActiveBody::attemptDamage(DamageInfo * damageInfo) Line 677	C++
 	generalszh.exe!Object::attemptDamage(DamageInfo * damageInfo) Line 1823	C++
 	generalszh.exe!Object::kill(DamageType damageType, DeathType deathType) Line 1964	C++
 	generalszh.exe!ParachuteContain::onRemoving(Object * rider) Line 582	C++
 	generalszh.exe!OpenContain::removeFromContainViaIterator(std::_List_iterator<std::_List_val<std::_List_simple_types<Object *>>> it, bool exposeStealthUnits) Line 678	C++
 	generalszh.exe!OpenContain::removeFromContain(Object * rider, bool exposeStealthUnits) Line 410	C++
 	generalszh.exe!Object::onDestroy() Line 757	C++
 	generalszh.exe!GameLogic::destroyObject(Object * obj) Line 4005	C++
 	generalszh.exe!OpenContain::onDelete() Line 846	C++
 	generalszh.exe!Object::onDestroy() Line 759	C++
 	generalszh.exe!GameLogic::destroyObject(Object * obj) Line 4005	C++
 	[Inline Frame] generalszh.exe!GameLogic::destroyAllObjectsImmediate() Line 317	C++
 	generalszh.exe!GameLogic::reset() Line 451	C++
 	generalszh.exe!SubsystemInterfaceList::resetAll() Line 188	C++
 	[Inline Frame] generalszh.exe!GameLogic::isInMultiplayerGame() Line 404	C++
 	generalszh.exe!GameEngine::reset() Line 697	C++
 	generalszh.exe!GameLogic::clearGameData(bool showScoreScreen) Line 281	C++
 	generalszh.exe!GameLogic::logicMessageDispatcher(GameMessage * msg, void * userData) Line 464	C++
 	generalszh.exe!GameLogic::processCommandList(CommandList * list) Line 2562	C++
 	generalszh.exe!GameLogic::update() Line 3732	C++
 	generalszh.exe!SubsystemInterface::UPDATE() Line 79	C++
 	generalszh.exe!GameEngine::update() Line 759	C++
 	generalszh.exe!Win32GameEngine::update() Line 93	C++
 	generalszh.exe!GameEngine::execute() Line 816	C++
 	generalszh.exe!GameMain(int argc, char * * argv) Line 47	C++
 	generalszh.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 1038	C++
 	[Inline Frame] generalszh.exe!invoke_main() Line 102	C++
 	generalszh.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!75aefcc9()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!779c82ae()	Unknown
 	ntdll.dll!779c827e()	Unknown
 	ntmarta.dll!70207369()	Unknown
```

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #896
* Closes #881
* Follow up for #809

This change fixes asserts and crashes from unloading maps and destroying all objects.

It does so by setting all objects effectively dead before deleting them. This way they do not apply terminal damage to other objects and no longer trigger death modules, that would eventually attempt to spawn new objects.
```
...
 	generalszh.exe!WeaponStore::createAndFireTempWeapon(const WeaponTemplate * wt, const Object * source, const Coord3D * pos) Line 1544	C++
 	generalszh.exe!FireWeaponWhenDeadBehavior::onDie(const DamageInfo * damageInfo) Line 119	C++
 	generalszh.exe!Object::onDie(DamageInfo * damageInfo) Line 4563	C++
 	generalszh.exe!ActiveBody::attemptDamage(DamageInfo * damageInfo) Line 677	C++
 	generalszh.exe!Object::attemptDamage(DamageInfo * damageInfo) Line 1823	C++
...
```
```cpp
void ActiveBody::attemptDamage( DamageInfo *damageInfo )
{
...
	if( obj->isEffectivelyDead() ) // <--- This change will prevent damages
		return;
```

Spawning new Objects fails at this time, because all `Player::getDefaultTeam` return null, which in turn will crash creating a new Object.
```cpp
>	generalszh.exe!Player::getProductionVeterancyLevel(AsciiString buildTemplateName) Line 1997	C++
 	generalszh.exe!Object::Object(const ThingTemplate * tt, const BitFlags<45> & objectStatusMask, Team * team) Line 478	C++
 	generalszh.exe!GameLogic::friend_createObject(const ThingTemplate * thing, const BitFlags<45> & statusBits, Team * team) Line 3964	C++
 	generalszh.exe!ThingFactory::newObject(const ThingTemplate * tmplate, Team * team, BitFlags<45> statusBits) Line 329	C++
 	generalszh.exe!GenericObjectCreationNugget::reallyCreate(const Coord3D * pos, const Matrix3D * mtx, float orientation, const Object * sourceObj, unsigned int lifetimeFrames) Line 1369	C++
 	generalszh.exe!GenericObjectCreationNugget::create(const Object * primary, const Object * secondary, unsigned int lifetimeFrames) Line 797	C++
 	generalszh.exe!ObjectCreationList::createInternal(const Object * primary, const Object * secondary, unsigned int lifetimeFrames) Line 1569	C++
 	[Inline Frame] generalszh.exe!ObjectCreationList::create(const ObjectCreationList *) Line 163	C++
 	generalszh.exe!WeaponTemplate::fireWeaponTemplate(const Object * sourceObj, WeaponSlotType wslot, int specificBarrelToUse, Object * victimObj, const Coord3D * victimPos, const WeaponBonus & bonus, bool isProjectileDetonation, bool ignoreRanges, Weapon * firingWeapon, ObjectID * projectileID, bool inflictDamage) Line 976	C++
...
```

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 1]
```diff
@@ -293,9 +293,18 @@ Bool GameLogic::isInSinglePlayerGame( void )
...
+
+	// TheSuperHackers @bugfix Set all remaining objects effectively dead to avoid triggering their
+	// death modules that eventually would spawn new objects, such as debris, which could then crash the game.
+	// See https://github.com/TheSuperHackers/GeneralsGameCode/issues/896
+	for( obj = m_objList; obj; obj = obj->getNextObject() )
+	{
+		obj->setEffectivelyDead(true);
+	}
+
+	// destroy all remaining objects
```
Comment (Mauller) [inline Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:307]: This could be added to the original loop before destroy object is called, no need to loop through all objects twice.

**Comment by Mauller** [comment]
The main issue is that game reset uses the same codepath as runtime object destruction.

This then leads to various object module behaviours being triggered when the modules "onDestory" function gets called during object destruction. This is unnecessary and can even be invalid as we are finding in various instances as they are found.

it would be a more extensive change but what we really need is a clean reset path that gets called for each object, drawable, module etc.

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:307]: I am skeptical about that, because an object can link to another object and tell that to destroy.

Comment (Mauller) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:307]: Set effectively dead is only setting status bits on the object and removing it from the radar

```cpp
void Object::setEffectivelyDead(Bool dead)
{
	if (dead)
		BitSet(m_privateStatus, EFFECTIVELY_DEAD);
	else
		BitClear(m_privateStatus, EFFECTIVELY_DEAD);

	if (dead)
	{
		if( m_radarData )
			TheRadar->removeObject( this );
	}
}
```

**Comment by xezon** [comment]
> This then leads to various object module behaviours being triggered when the modules "onDestory" function gets called during object destruction. This is unnecessary and can even be invalid as we are finding in various instances as they are found.

I suspect you refer to `onDelete`. We cannot just skip all destruction paths, because that will leak memory at some places. A more lightweight cleanup is probably possible, but requires more considerations then.

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:307]: Yes but if we set the host object dead and then delete it, then its child objects will not be set dead, and then they could do alive things.

**Comment by Mauller** [comment]
> I suspect you refer to `onDelete`. We cannot just skip all destruction paths, because that will leak memory at some places. A more lightweight cleanup is probably possible, but requires more considerations then.

hmm, i did mean ```onDestroy``` there is another interface for behaviour modules through this in ```destroyObject``` but i can't find how they link up to behaviour modules.

The behaviours i am thinking off probably get triggered through ```onDelete``` having looked at propoganda towers.

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp (hunk 1 above)
Comment (Mauller) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:307]: Yeah that's fair, an object containing others could trigger their death modules.

**Review by Mauller — APPROVED** [review]
