### PR TITLE
bugfix(gui): Fix game window animation movements to scale with display resolution

### LINKED ISSUE #2130: Communicator window slow to open/close at high resolution
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Opening and closing the communicator window is very slow when using 4K. It's good at 800x600.
At 4K the communicator button also is less responsive (see video).

Doesn't appear to depend much on PC speed, I recorded this on my old Windows PC but it's also slow on my very quick PC.

### Reproduction Steps

Set resolution and click communicator button see videos

### Additional Context

800x600:

https://github.com/user-attachments/assets/e7286114-8aaa-41cd-944e-ed881796cf45

4K:

https://github.com/user-attachments/assets/1a24fcb3-5595-4d8c-ab66-958f3fac8bd9

### PR DESCRIPTION
**Pull request by tophroxx**
This fixes window animation speeds and smoothing on different display resolutions. Closes #2130

I've made a quick video showcasing new behavior and retail behavior side-by-side. Unfortunately it was too big for GitHub, so i uploaded it to YouTube.

https://youtu.be/wDQdis7Z1L4

Pay attention to how fast the control bar slides from the bottom when i'm loading into a match, and also how fast the diplomacy screen slides from the top.

This PR adds 2 new ~~methods to the Display class~~ local helper functions and changes 4 children of the `ProcessAnimateWindow` class - `SlideFromLeft`, `SlideFromRight`, `SlideFromTop` and `SlideFromBottom`, making them benefit from these new methods. 
It also moves velocity and slowdown threshold initialization from the constructor into `initAnimateWindow`, which means that these values will scale properly even if user changes their resolution in runtime. 
I've made little changes to minimize the possibility of new issues appearing while still fixing the issue.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 1]
```diff
@@ -141,6 +137,11 @@ void ProcessAnimateWindowSlideFromRight::initAnimateWindow( wnd::AnimateWindow *
 	//set the window's position to the new start positions.
 	win->winSetPosition(startPos.x, startPos.y);
 
+	// TheSuperHackers @bugfix toph 29/01/2026 Use scaled pixel constants
+	// for slowdown threshold and velocity.
+	m_maxVel.x = -static_cast<Real>(TheDisplay->scaleVerticalConstant(40));
```
[the remark this answers is not in the document]
Comment (tophroxx) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: e6d01cc

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 2]
```diff
@@ -322,6 +319,11 @@ void ProcessAnimateWindowSlideFromLeft::initAnimateWindow( wnd::AnimateWindow *a
 	//set the window's position to the new start positions.
 	win->winSetPosition(startPos.x, startPos.y);
 
+	// TheSuperHackers @bugfix toph 29/01/2026 Use scaled pixel constants
+	// for slowdown threshold and velocity.
+	m_maxVel.x = static_cast<Real>(TheDisplay->scaleVerticalConstant(40));
```
[the remark this answers is not in the document]
Comment (tophroxx) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: e6d01cc

File: GeneralsMD/Code/GameEngine/Include/GameClient/Display.h [hunk 3]
```diff
@@ -90,6 +90,9 @@ class Display : public SubsystemInterface
 	virtual void dumpAssetUsage(const char* mapname) = 0;
 #endif
 
+	virtual UnsignedInt scaleHorizontalConstant(UnsignedInt x) { return (static_cast<Real>(x) / DEFAULT_DISPLAY_WIDTH) * getWidth(); }
+	virtual UnsignedInt scaleVerticalConstant(UnsignedInt y) { return (static_cast<Real>(y) / DEFAULT_DISPLAY_HEIGHT) * getHeight(); }
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Include/GameClient/Display.h]: This looks way to specific to warrant new virtual functions in the `Display` class. Make it local code in `ProcessAnimateWindow.cpp`.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 4]
```diff
@@ -75,13 +75,9 @@
 
 ProcessAnimateWindowSlideFromRight::ProcessAnimateWindowSlideFromRight( void )
 {
-	m_maxVel.x =  -40.0f;  // top speed windows travel in x and y
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp:78]: It would be good to still have everything initialized to something in the constructors.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 5]
```diff
@@ -141,6 +137,11 @@ void ProcessAnimateWindowSlideFromRight::initAnimateWindow( wnd::AnimateWindow *
 	//set the window's position to the new start positions.
 	win->winSetPosition(startPos.x, startPos.y);
 
+	// TheSuperHackers @bugfix toph 29/01/2026 Use scaled pixel constants
+	// for slowdown threshold and velocity.
+	m_maxVel.x = -static_cast<Real>(TheDisplay->scaleHorizontalConstant(40));
+	m_slowDownThreshold = TheDisplay->scaleHorizontalConstant(80);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Alternatively you could also just scale these values here with the width and height, and leave the -40, 80 in the constructor.

File: GeneralsMD/Code/GameEngine/Include/GameClient/Display.h (hunk 3 above)
Comment (tophroxx) [reply GeneralsMD/Code/GameEngine/Include/GameClient/Display.h]: is there a possibility that these functions could be useful in other pieces of UI code? that's the main reason i did it that way. but if you're sure, of course i will do local functions.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Include/GameClient/Display.h]: Possibly, but its also very simple code that can just be at different places.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 6]
```diff
@@ -141,6 +137,11 @@ void ProcessAnimateWindowSlideFromRight::initAnimateWindow( wnd::AnimateWindow *
 	//set the window's position to the new start positions.
 	win->winSetPosition(startPos.x, startPos.y);
 
+	// TheSuperHackers @bugfix toph 29/01/2026 Use scaled pixel constants
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Perhaps name yourself tophroxx so that your github name is recognizable.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp (hunk 5 above)
Comment (tophroxx) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: slight problem with that. i already tried. this would work for diplomacy screen, because it is recreated each time you press the "show diplomacy screen" button. but that's not the case with the control bar. same with any other global UI element that is created once per game launch and is used across matches. it seems i'll have to introduce 2 new fields to each animation class to store the initial unscaled values to handle this case properly. is this okay?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: No keep your approach then. Just set them 0 in the constructor then.

**Comment by tophroxx** [comment]
Done all requested changes and replicated the fix for vanilla Generals. Works there as well.

File: Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 7]
```diff
@@ -68,20 +68,26 @@
 // PRIVATE FUNCTIONS //////////////////////////////////////////////////////////
 //-----------------------------------------------------------------------------
 
+static UnsignedInt scaleHorizontalConstant(UnsignedInt x) {
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Minor style: Use

```
void function()
{
}
```

File: Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 8]
```diff
@@ -68,20 +68,26 @@
...
+	return (static_cast<Real>(x) / DEFAULT_DISPLAY_WIDTH) * TheDisplay->getWidth();
+}
+
+static UnsignedInt scaleVerticalConstant(UnsignedInt y) {
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Perhaps call these

scaleByDisplayWidth
scaleByDisplayHeight

?

Would be a bit more specific to what they do.

Also how about not modify a value in the functions, but simply return the scaler value.

So do

```
m_maxVel.x = 40 * getDisplayWidthScaler();
```

This would be a tiny bit simpler to read.

File: Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp [hunk 9]
```diff
@@ -141,6 +149,12 @@ void ProcessAnimateWindowSlideFromRight::initAnimateWindow( wnd::AnimateWindow *
 	//set the window's position to the new start positions.
 	win->winSetPosition(startPos.x, startPos.y);
 
+	// TheSuperHackers @bugfix tophroxx 31/01/2026 Use scaled pixel constants
+	// for slowdown threshold and velocity.
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Perhaps you can explain this better how it improves things user facing.

Comment (tophroxx) [reply Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: "Scale slowdown threshold and max velocity to fix window animation speed and smoothing across different resolutions"
Does that sound better?

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Maybe:

> Scale movement by display size so that it looks consistent regardless of the display resolution

Comment (tophroxx) [reply Generals/Code/GameEngine/Source/GameClient/GUI/ProcessAnimateWindow.cpp]: Superior english knowledge
