### PR TITLE
[GEN][ZH] Fix crash in StateMachine when a chained StateMachine update deletes the executor StateMachine

### LINKED ISSUE #212: Game will crash if Battle Bus with Rebels destroys Nuke Battle Masters
изображение
If sitting in Battle Bus or Civilian Building a Ranger, Rebel, Redguard, Colonel Burton or Minigunner destroys a Nuke Power Plant or Nuke Battle Master and because of this the Battle Bus or Neutral Building is dealt a lethal amount of damage, the game will be crashed.
But if Building is KindOf GARRISONABLE_UNTIL_DESTROYED it will be OK.
Map for test is attached:
[_Crash.zip](https://github.com/TheSuperHackers/GeneralsGamePatch/files/11420038/_Crash.zip)

P.S
Sorry for my english

### PR DESCRIPTION
**Pull request by xezon**
* Merge after #889 
* Fixes #212

This change fixes a crash in `StateMachine` that happens when a chained `StateMachine` update destroys the prior executor `StateMachine`. This issue happened with #212, where the Ranger's `StateMachine` in the Bus would kill the Power Plant, and then the Power Plant weapon would kill the Bus, which would then delete the `StateMachine` of the Ranger.

### CODE REVIEW

File: Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h [hunk 1]
```diff
@@ -428,7 +430,7 @@ bool operator ==(DummyPtrType * dummy, const RefCountPtr<RHS> & rhs)
 template <class RHS>
 bool operator !=(DummyPtrType * dummy, const RefCountPtr<RHS> & rhs)
 {
-	FAIL_IF(0 != dummy) {
+	if (0 != dummy) {
```
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h:434]: This header was never used... so FAIL_IF failed to compile. No clue what that was supposed to be.

Comment (Mauller) [reply Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h:434]: I am guessing it was some older form of custom assert like the debug asserts.

**Comment by Mauller** [comment]
I wonder if this behaviour is also why i see leaked states at times.

This will need some further testing for compat. It will definitely break compat in the situation it fixes, but then the vanilla game crashes at that point anyway.

**Comment by xezon** [comment]
I think this fix does not break compat at all. It does not change what the StateMachine does.

**Comment by Mauller** [comment]
> I think this fix does not break compat at all. It does not change what the StateMachine does.

It probably doesn't, i was just considering if there are any other silent issues surrounding this same problem that affect the transfer still.

But the parent state machine should still be destroyed in the same frame so probably doesn't affect the transfer.


This fix just made me think of the fix for the garrison contain initialisation. That fix caused a mismatch in the end since it changed initial contain behaviour from being multi to single framed.

**Comment by Mauller** [comment]
I think in the future we should ref count all states and state machines or have some form of dirty flag a state can set that can tell a state machine to clean itself up at the end of it's update.

**Comment by xezon** [comment]
I looked at State class, and I think these need no attention, because they are childs of StateMachine and bound to its life time. So as long as StateMachine lives, then so will all its contained States.

File: Generals/Code/GameEngine/Include/Common/StateMachine.h [hunk 2]
```diff
@@ -473,4 +481,13 @@ class SleepState :  public State
 EMPTY_DTOR(SleepState)
 
 
+//-----------------------------------------------------------------------------------------------------------
+// TheSuperHackers @info Misappropriates deleteInstance to call Release_Ref to keep the StateMachine fix small.
+// @todo Replace calls to deleteInstance with RefCountPtr<StateMachine> when so appropriate.
+inline void deleteInstance(StateMachine* state)
+{
+	state->Release_Ref();
```
Comment (Mauller) [inline Generals/Code/GameEngine/Include/Common/StateMachine.h]: This should be called "machine" rather than state to match the convention used within states.

File: Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h (hunk 1 above)
Comment (Mauller) [reply Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h:434]: Might be good to put a WWASSERT here

**Comment by Mauller** [comment]
@helmutbuhler Shared a replay that crashed the game, it appears that it was also due to an attacking battlebus being hit by a nuclear weapon.

File: Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h (hunk 1 above)
Comment (xezon) [reply Core/Libraries/Source/WWVegas/WWLib/ref_ptr.h:434]: Fixed.

File: Generals/Code/GameEngine/Include/Common/StateMachine.h (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngine/Include/Common/StateMachine.h]: Fixed.
