### PR TITLE
bugfix(input): Fix cargo units selection hack

### LINKED ISSUE #1544: Cargo unit with 1 passenger deselects new unit instead of loading it
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When a cargo unit already has 1 passenger at least, trying to load another unit doesn’t work. Instead of boarding, the selected unit gets deselected and the cargo unit itself becomes selected.

### Reproduction Steps

1. Start a game.
2. Create a cargo unit
3. Load 1 passenger inside
4. Try to load another passenger

Current behaviour:

https://github.com/user-attachments/assets/22597f5b-9551-4a9b-ac85-8c5c509b719d

Expected behaviour:

https://github.com/user-attachments/assets/578e62c8-c6ac-4065-b0a2-d8fe5e5908bd

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
* Follow up for #1460
* Fixes #1544
* Closes #1547

This change is a follow up for #1460 and an alternative to #1547 and fixes #1544.

Tested in test map [!SkirmishTestTransportGuys.zip](https://github.com/user-attachments/files/22555390/SkirmishTestTransportGuys.zip)

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp [hunk 1]
```diff
@@ -382,8 +378,14 @@ Bool addDrawableToList( Drawable *draw, void *userData )
 	// enemy selection logic to exit early (only 1 enemy unit can be selected at a time). Some players
 	// exploit this bug to determine if a transport contains passengers and consider this an important
 	// feature and an advanced skill to pull off, so we must leave the exploit.
-	if (draw->getObject() && draw->getObject()->getContain() && draw->getObject()->getContain()->getContainCount() > 0)
-		pds->drawableListToFill->push_back(draw); // Just add the unit twice to prevent enemy selections
+	if (!pds->isPointSelection)
+	{
+		const Object *obj = draw->getObject();
+		if (obj)
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp:384]: i would invert the logic and return false on !obj, flattens out the nesting a bit.

File: GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp [hunk 2]
```diff
@@ -365,7 +361,7 @@ Bool addDrawableToList( Drawable *draw, void *userData )
     const Object *obj = draw->getObject();
     if ( obj && obj->getContainedBy() )//hmm, interesting... he is not selectable but he is contained
     {// What we are after here is to propagate the selection the selection ti the container
-      // if the cobtainer is non-enclosing... see also selectionxlat, in the left_click case
+      // if the container is non-enclosing... see also SelectionXlat, in the left_click case
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp:364]: but my cobtainers! where will i store my corn?

**Review by Mauller — APPROVED** [review]
looks good and works as expected

File: GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp (hunk 1 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp:384]: Cannot do because it still needs to reach the code below.

File: GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp (hunk 2 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp:364]: Classic cobtainers

File: GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp (hunk 1 above)
Comment (Mauller) [reply GeneralsMD/Code/GameEngine/Source/GameClient/SelectionInfo.cpp:384]: Ah yes i overlooked that, is all good then.
