### PR TITLE
  bugfix(water): Fix river borders appearing darkened under shroud                                                                                                                                                

### LINKED ISSUE #2364: Rendering issue where river borders appear darkened under shroud
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

As reported by AlseeAns.

Retail game issue.

River borders are darkened when under shroud which lead many map makers to put rocks etc. to hide visual artifacts, see images below.

Image

Image

### Reproduction Steps

A minimal repo map is included with just a river which immediately showcase the darkening effect.

### Additional Context

[Ariver.zip](https://github.com/user-attachments/files/25621826/Ariver.zip)

### PR DESCRIPTION
**Pull request by afc-afc0**
Fixes #2364                                                                                                                                                                                                                                                           

## Description                                                                                                                                                                                                                                                          River borders appear darkened when under shroud, creating visual artifacts that force map makers to place rocks and other objects   to hide them.                                                                                                                     

  ### Root Cause

  River water rendering in `drawRiverWater()` applies the shroud as a separate multiplicative pass on the framebuffer after the     
  water is already alpha-blended onto the terrain. This causes double-darkening at transparent river edges:

  1. Terrain renders with its own shroud: `pixel = terrain × shroud`
  2. River alpha-blends on top: `pixel = α × water + (1-α) × terrain × shroud`
  3. River's multiplicative shroud pass darkens the entire framebuffer: `pixel = shroud × (α × water + (1-α) × terrain × shroud)`   

  The terrain contribution at river borders becomes `terrain × shroud²` instead of `terrain × shroud` — visibly darker than
  surrounding terrain. This is only noticeable under shroud (when `shroud < 1.0`), since `1.0² = 1.0`.

  Note: Trapezoid water (lakes/ponds) avoids this by applying shroud in texture stage 3 of the main pass when pixel shaders are     
  available. River water cannot do this because stage 3 is already used for the river alpha edge texture.

  ### Fix

  Applies shroud per-vertex by looking up the shroud level at each river vertex's world position and multiplying it into the vertex 
  diffuse color before alpha blending. This ensures only the water's color contribution is shroud-modulated:

  `pixel = α × (water × shroud) + (1-α) × (terrain × shroud) = shroud × (α × water + (1-α) × terrain)`

  The separate multiplicative shroud pass is removed, which also eliminates one draw call per river.

  ### Testing

  Tested with the minimal reproduction map (`Ariver.zip` from #2364) — river borders no longer show dark outlines under shroud.

### CODE REVIEW

**Comment by stephanmeesters** [comment]
Did a little pre- post comparison, the results are interesting, this is using the map Winding River:

https://github.com/user-attachments/assets/ff6f582c-1755-4ef7-9bab-3b328409897b

You can try by adding this commit:
https://github.com/stephanmeesters/GeneralsGameCode/commit/c63851dc687ea41c4f14c1c53022a01e69b8c000

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 1]
```diff
@@ -2834,7 +2839,16 @@ void WaterRenderObjClass::drawRiverWater(PolygonTrigger *pTrig)
 			vb->y=y;
 
 			vb->z=innerPt.z;
-			vb->diffuse= diffuse;
+
+			if (shroud) {
```
Comment (stephanmeesters) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: Consider extracting repeated code

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 2]
```diff
@@ -2834,7 +2839,16 @@ void WaterRenderObjClass::drawRiverWater(PolygonTrigger *pTrig)
...
+				Int cellX = REAL_TO_INT_FLOOR(x / shroud->getCellWidth());
+				Int cellY = REAL_TO_INT_FLOOR(y / shroud->getCellHeight());
+				W3DShroudLevel level = shroud->getShroudLevel(cellX, cellY);
+				Real shroudScale = (Real)level / 255.0f;
+				vb->diffuse = REAL_TO_INT(shadeB * shroudScale) | (REAL_TO_INT(shadeG * shroudScale) << 8) | (REAL_TO_INT(shadeR * shroudScale) << 16) | (diffuse & 0xff000000);
```
Comment (stephanmeesters) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: Perhaps cleaner to use `GameMakeColor` here

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 3]
```diff
@@ -2908,19 +2931,8 @@ void WaterRenderObjClass::drawRiverWater(PolygonTrigger *pTrig)
...
-		W3DShaderManager::setShader(W3DShaderManager::ST_SHROUD_TEXTURE, 0);
-		DX8Wrapper::_Get_D3D_Device8()->SetRenderState(D3DRS_CULLMODE, D3DCULL_NONE);
-		//Shroud shader uses z-compare of EQUAL which wouldn't work on water because it doesn't
-		//write to the zbuffer.  Change to LESSEQUAL.
-		DX8Wrapper::_Get_D3D_Device8()->SetRenderState(D3DRS_ZFUNC, D3DCMP_LESSEQUAL);
-		DX8Wrapper::Draw_Triangles(	0,rectangleCount*2, 0,	(rectangleCount+1)*2);
-		DX8Wrapper::_Get_D3D_Device8()->SetRenderState(D3DRS_ZFUNC, D3DCMP_EQUAL);
-		W3DShaderManager::resetShader(W3DShaderManager::ST_SHROUD_TEXTURE);
-	}
+	// TheSuperHackers @bugfix Shroud is now applied per-vertex above, removing the old
```
Comment (stephanmeesters) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: Bit weird to add this comment referring to deleted code. Can we left out since you already explained it around line 2820

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 4]
```diff
@@ -2814,6 +2814,11 @@ void WaterRenderObjClass::drawRiverWater(PolygonTrigger *pTrig)
 
 		Real constA=3*m_riverVOrigin;
 
+		// TheSuperHackers @bugfix Apply shroud per-vertex to avoid double-darkening at river borders.
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: `TheSuperHackers @bugfix username date`

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 5]
```diff
@@ -2856,7 +2870,16 @@ void WaterRenderObjClass::drawRiverWater(PolygonTrigger *pTrig)
 			vb->x=x;
 			vb->y=y;
 			vb->z=outerPt.z;
-			vb->diffuse= diffuse;
+
+			if (shroud) {
+				Int cellX = REAL_TO_INT_FLOOR(x / shroud->getCellWidth());
+				Int cellY = REAL_TO_INT_FLOOR(y / shroud->getCellHeight());
```
Comment (Mauller) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: No need to use the `REAL_TO_INT_FLOOR` macro, the conversion to int will truncate the float which is the same as flooring it.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 6]
```diff
@@ -165,6 +166,19 @@ static ShaderClass blendStagesShader(SC_DETAIL_BLEND);
...
+static Int getRiverVertexDiffuseWithShroud(W3DShroud *shroud, Real x, Real y, Real shadeR, Real shadeG, Real shadeB, Int diffuse)
+{
+	Int cellX = (Int)(x / shroud->getCellWidth());
+	Int cellY = (Int)(y / shroud->getCellHeight());
+	W3DShroudLevel level = shroud->getShroudLevel(cellX, cellY);
+	Real shroudScale = (Real)level / 255.0f;
+	return GameMakeColor(
+		REAL_TO_INT(shadeR * shroudScale),
+		REAL_TO_INT(shadeG * shroudScale),
+		REAL_TO_INT(shadeB * shroudScale),
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: Just use integer cast.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp [hunk 7]
```diff
@@ -2856,7 +2879,12 @@ void WaterRenderObjClass::drawRiverWater(PolygonTrigger *pTrig)
 			vb->x=x;
 			vb->y=y;
 			vb->z=outerPt.z;
-			vb->diffuse= diffuse;
+
+			if (shroud) {
+				vb->diffuse = getRiverVertexDiffuseWithShroud(shroud, x, y, shadeR, shadeG, shadeB, diffuse);
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: Call sites can be simplified by doing

```cpp
static Int getRiverVertexDiffuse(shroud, x, y, shadeR, shadeG, shadeB, diffuse)
{
	if (shroud)
		return getRiverVertexDiffuseWithShroud(shroud, x, y, shadeR, shadeG, shadeB, diffuse);
	return diffuse;
}

**Review by xezon — APPROVED** [review]

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp (hunk 6 above)
Comment (stephanmeesters) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: Implicit cast here appears to be fine

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp (hunk 7 above)
Comment (stephanmeesters) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Water/W3DWater.cpp]: I'd inline getRiverVertexDiffuseWithShroud here then

**Review by xezon — APPROVED** [review]

**Review by Mauller — APPROVED** [review]
Good to me too
