### PR TITLE
unify(object): Merge the unit veterancy effect changes including the veterancy effect fix for detected stealth units from Zero Hour

### LINKED ISSUE #51: Veterancy animation spawns at 0 0 while unit spawns in building
Veterancy animation spawns at 0 0 while unit spawns in building. Can anything be done about that? Or is this a pure code issue?

### PR DESCRIPTION
**Pull request by Stubbjax**
This change ports the `provideFeedback` parameter and respective logic regarding the veterancy effect from Zero Hour to Generals. It also fixes a bug in Generals where detected stealth units would not play the veterancy effect.

### CODE REVIEW

**Comment by xezon** [comment]
Is this meant to be merged with Rebase?

Edit:

1. Most of commits 2 & 3 look to be a unify change.

2. Then the remainder of 1 & 2 are the bugfix.

3. And then 4 & 5 are the optimization/refactor.

I suggest create 3 Pull for these that build on top of each other, in that order.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp [hunk 1]
```diff
@@ -3091,17 +3091,22 @@ void Object::onVeterancyLevelChanged( VeterancyLevel oldLevel, VeterancyLevel ne
 		body->onVeterancyLevelChanged( oldLevel, newLevel, provideFeedback );
 
 	Bool hideAnimationForStealth = FALSE;
-	if( !isLocallyControlled() &&
-			testStatus( OBJECT_STATUS_STEALTHED ) &&
-			!testStatus( OBJECT_STATUS_DETECTED ) &&
-			!testStatus( OBJECT_STATUS_DISGUISED ) )
+	Bool doAnimation = FALSE;
+
+	if (provideFeedback)
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Object.cpp]: This can be simplified more:

Set `provideFeedback = FALSE` in `case LEVEL_REGULAR`

Then move this code up here to down below:

```cpp
if( provideFeedback && TheGameLogic->getDrawIconUI() )
{
  Bool hideAnimationForStealth = !isLocallyControlled() &&
				testStatus( OBJECT_STATUS_STEALTHED ) &&
				!testStatus( OBJECT_STATUS_DETECTED ) &&
				!testStatus( OBJECT_STATUS_DISGUISED );

  Bool doAnimation = ( ! hideAnimationForStealth
									&& (newLevel > oldLevel)
									&& ( ! isKindOf(KINDOF_IGNORED_IN_GUI))); //First, we plan to do the animation if the level went up

  if ( doAnimation )
  {
    ...
  }
}

**Comment by Stubbjax** [comment]
> I suggest create 3 Pull for these that build on top of each other, in that order.

Updated!

**Comment by xezon** [comment]
Title updated.

**Review by xezon — APPROVED** [review]

**Comment by xezon** [comment]
Is this meant to be merged with rebase? If yes then the commit titles need updating.

**Comment by Stubbjax** [comment]
> Is this meant to be merged with rebase? If yes then the commit titles need updating.

I had not intended it to be. If that is preferable, what titles do you suggest?

**Comment by xezon** [comment]
```
unify(object): Merge the condition switch for the unit veterancy effect from Zero Hour (#1455)
unify(object): Merge the missing veterancy effect fix for detected stealth units from Zero Hour (#1455)
```

**Comment by Stubbjax** [comment]
> ```
> unify(object): Merge the condition switch for the unit veterancy effect from Zero Hour (#1455)
> unify(object): Merge the missing veterancy effect fix for detected stealth units from Zero Hour (#1455)
> ```

Done.
