### PR TITLE
fix(shadow): Fix crash by initializing debris shadow name to an empty string

### LINKED ISSUE #2214: ObjectCreationList CreateDebris  object with SHADOW_DECAL Shadow parameter has null texture
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

CreateDebris allows to define a Shadow parameter to apply to the debris model.
In retail version of the game, SHADOW_DECAL is rendered as a blob.
In TSH, built from latest code on January 29, 2026, SHADOW_DECAL is instead rendered as a purple-and-black missing texture.

Call stack points to the m_shadow parameter being a nullptr.

Attaching a custom mission map to recreate issue. Walking over the black square spawns Burtons, which are edited to have the specified CreateDebris death type. The chance to trigger death is not 100%, so walking over the square repeatedly will spawn more Burtons.

[Mission.zip](https://github.com/user-attachments/files/24943308/Mission.zip)

Attached screen recording showing the OCL-triggered death with missing texture:

https://github.com/user-attachments/assets/ec745eb3-60c5-4aea-b7f6-f8c489e604d8

### Reproduction Steps

1. Load the provided Mission map in Skirmish
2. Walk repeatedly over black square to spawn Burtons
3. Allow Patriot and Tunnel Defenders to kill Burtons until the OCL death is triggered.

### Additional Context

Compiled the latest TSH codebase with default settings in Win32 Release mode.

### PR DESCRIPTION
**Pull request by Stubbjax**
* Closes #2214
* Merge after #2225

This change fixes a crash caused by spawning a `CreateDebris` object with an assigned `Shadow` by initializing the shadow name to an empty string.

When the shadow name is uninitialized, checks for `'\0'` and `strlen <= 1` fail and garbage data is instead passed to various locations that do not expect it nor know how to deal with it.

### CODE REVIEW

**Comment by Caball009** [comment]
Perhaps there should be a default constructor for `Shadow::ShadowTypeInfo` where this is handled, instead of relying on each ~call~ construction site to do the right thing.

**Comment by Stubbjax** [comment]
> Perhaps there should be a default constructor for `Shadow::ShadowTypeInfo` where this is handled, instead of relying on each ~call~ construction site to do the right thing.

Good thinking. Updated!

**Comment by Mauller** [comment]
Does this tend to only get hit under mod use?

File: Generals/Code/GameEngine/Source/GameClient/RadiusDecal.cpp [hunk 1]
```diff
@@ -69,7 +69,7 @@ void RadiusDecalTemplate::createRadiusDecal(const Coord3D& pos, Real radius, con
 	if (!m_onlyVisibleToOwningPlayer ||
 			owningPlayer->getPlayerIndex() == ThePlayerList->getLocalPlayer()->getPlayerIndex())
 	{
-		Shadow::ShadowTypeInfo decalInfo;
+		Shadow::ShadowTypeInfo decalInfo = Shadow::ShadowTypeInfo();
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/RadiusDecal.cpp]: Calling the constructor like this is not necessary. It is automatically called on construction.

Several times in this change.

File: Generals/Code/GameEngine/Include/GameClient/Shadow.h [hunk 2]
```diff
@@ -73,6 +73,19 @@ class Shadow
 
 		struct	ShadowTypeInfo
 		{
+				// TheSuperHackers @fix Stubbjax 30/01/2026 Initialize all members in the constructor to avoid garbage data and potential crashes.
```
Comment (xezon) [inline Generals/Code/GameEngine/Include/GameClient/Shadow.h]: You can omit this comment because it does not add any value to the next reader.

**Comment by alanblack166** [comment]
> Does this tend to only get hit under mod use?

Zero Hour does not have `CreateDebris` objects with a defined `Shadow` parameter.

**Comment by xezon** [comment]
This change can now advance.

**Comment by Caball009** [comment]
https://github.com/TheSuperHackers/GeneralsGameCode/blob/d01ec97b9e50513e274445316865d9f96277f47a/Core/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp#L699-L707

Was this one missed or was it planned to be changed after the above merge?

**Comment by xezon** [comment]
It looks like some of the edits were lost on the Rebase?
