### PR TITLE
[GEN][ZH] Fix black terrain in World Builder without RTS_DEBUG

### LINKED ISSUE #1116: [ZH] World Builder behaves differently when built with RTS_BUILD_OPTION_DEBUG enabled
This is what the Zero Hour World Builder looks like for me when built with the default CMake flags:

Image

and this is with default flags + `RTS_BUILD_OPTION_DEBUG` enabled:

Image

Both were in debug mode.

### LINKED ISSUE #1186: Terrain renders black in World Builder
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Terrain renders black in World Builder. Somehow is related to optimization levels or compile options. What are the conditions? Does JMarshalls fork have a fix for it?

### Reproduction Steps

1. Compile World Builder locally
2. Launch it

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1186
* Partially fixes #1116
* Merge after #1036

This change fixes the black terrain in World Builder without `RTS_DEBUG`. This issue happens because all code around `GlobalData::m_shroudOn` is compiled out without `RTS_DEBUG`, which enables shroud and turns the world black.

## TODO

- [x] Rebase after #1036 is merged
- [x] Replicate in Generals

### CODE REVIEW

**Comment by Caball009** [comment]
This fix works as intended for me.

**Comment by xezon** [comment]
Rebased on latest main.

**Comment by ViTeXFTW** [comment]
What are the necessary changes to have WB work in release (without RTS_INTERNAL)? I feel like that should also be a target goal.

**Comment by xezon** [comment]
If you know of more things broken in Release World Builder, please create a report. I only noticed the Terrain and System Maps thing.

**Comment by ViTeXFTW** [comment]
Also tested and works as advertised

**Comment by xezon** [comment]
Rebased.

Replicated in Generals with conflicts.

```
$ git diff 28adea33cec5ca38d28ce276ed668d4e8db9e46a..b0ef819c2278fba9e2adb993de5b0f1480bf07c7 > changes.patch

$ git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch
changes.patch:42: trailing whitespace.

changes.patch:198: space before tab in indent.
        TheDisplay->drawImage( m_overlayImage, ul.x, ul.y, lr.x, lr.y );
Checking patch Generals/GameEngine/Include/Common/GameDefines.h...
error: Generals/GameEngine/Include/Common/GameDefines.h: No such file or directory
Checking patch Generals/Code/GameEngine/Include/Common/GameCommon.h...
Hunk #1 succeeded at 52 (offset -6 lines).
Checking patch Generals/Code/GameEngine/Include/Common/GlobalData.h...
error: while searching for:
#include "Common/SubsystemInterface.h"
#include "GameClient/Color.h"
#include "Common/STLTypedefs.h"
#include "Common/GameCommon.h"
#include "Common/Money.h"

// FORWARD DECLARATIONS ///////////////////////////////////////////////////////////////////////////

error: patch failed: Generals/Code/GameEngine/Include/Common/GlobalData.h:39
error: while searching for:
  Bool m_TiVOFastMode;            ///< When true, the client speeds up the framerate... set by HOTKEY!



#if defined(RTS_DEBUG) || defined(RTS_INTERNAL)
        Bool m_wireframe;
        Bool m_stateMachineDebug;
        Bool m_useCameraConstraints;
        Bool m_shroudOn;
        Bool m_fogOfWarOn;
        Bool m_jabberOn;
        Bool m_munkeeOn;

error: patch failed: Generals/Code/GameEngine/Include/Common/GlobalData.h:482
Checking patch Generals/Code/GameEngine/Include/Precompiled/PreRTS.h...
Checking patch Generals/Code/GameEngine/Source/Common/CommandLine.cpp...
Checking patch Generals/Code/GameEngine/Source/Common/GlobalData.cpp...
error: while searching for:
#endif
  m_TiVOFastMode = FALSE;

#if defined(RTS_DEBUG) || defined(RTS_INTERNAL)
        m_wireframe = 0;
        m_stateMachineDebug = FALSE;
        m_useCameraConstraints = TRUE;
        m_shroudOn = TRUE;
        m_fogOfWarOn = FALSE;
        m_jabberOn = FALSE;
        m_munkeeOn = FALSE;

error: patch failed: Generals/Code/GameEngine/Source/Common/GlobalData.cpp:548
Checking patch Generals/Code/GameEngine/Source/GameClient/GameClient.cpp...
Hunk #1 succeeded at 619 (offset -38 lines).
Hunk #2 succeeded at 650 (offset -38 lines).
Checking patch Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp...
Hunk #1 succeeded at 2488 (offset -60 lines).
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp...
Hunk #1 succeeded at 1267 (offset 12 lines).
Hunk #2 succeeded at 1287 (offset 12 lines).
Hunk #3 succeeded at 1424 (offset 12 lines).
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/BaseHeightMap.cpp...
error: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/BaseHeightMap.cpp: No such file or directory
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp...
Hunk #1 succeeded at 104 (offset -1 lines).
Hunk #2 succeeded at 758 (offset -38 lines).
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp...
Hunk #1 succeeded at 850 (offset -144 lines).
Checking patch Generals/Code/Tools/WorldBuilder/src/WorldBuilder.cpp...
Hunk #1 succeeded at 411 (offset -22 lines).
Applied patch Generals/Code/GameEngine/Include/Common/GameCommon.h cleanly.
Applying patch Generals/Code/GameEngine/Include/Common/GlobalData.h with 2 rejects...
Rejected hunk #1.
Rejected hunk #2.
Applied patch Generals/Code/GameEngine/Include/Precompiled/PreRTS.h cleanly.
Applied patch Generals/Code/GameEngine/Source/Common/CommandLine.cpp cleanly.
Applying patch Generals/Code/GameEngine/Source/Common/GlobalData.cpp with 1 reject...
Hunk #1 applied cleanly.
Hunk #2 applied cleanly.
Rejected hunk #3.
Applied patch Generals/Code/GameEngine/Source/GameClient/GameClient.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DScene.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp cleanly.
Applied patch Generals/Code/Tools/WorldBuilder/src/WorldBuilder.cpp cleanly.
```

**Comment by xezon** [comment]
This needs an approval.

**Comment by ViTeXFTW** [comment]
Wish I could

**Comment by ViTeXFTW** [comment]
By the way, this change also makes the release WorldBuilder work as expected. I think the only issues was no handling of shroud clearing

File: GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp [hunk 1]
```diff
@@ -488,6 +488,10 @@ GlobalData* GlobalData::m_theOriginal = NULL;
 	{ "KeyboardCameraRotateSpeed", INI::parseReal, NULL, offsetof( GlobalData, m_keyboardCameraRotateSpeed ) },
 	{ "PlayStats",									INI::parseInt,				NULL,			offsetof( GlobalData, m_playStats ) },
 
+#if ENABLE_CONFIGURABLE_SHROUD && defined(RTS_DEBUG)
+	{ "ShroudOn",										INI::parseBool,				NULL,			offsetof( GlobalData, m_shroudOn ) },
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp]: This causes error on RTS DEBUG game launch when ENABLE_CONFIGURABLE_SHROUD is 0.

**Comment by xezon** [comment]
Main merged.

File: GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp (hunk 1 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/GlobalData.cpp]: Fixed.
