### PR TITLE
bugfix(buildassistant): Fix Network game mismatch by using the correct player index to check shroud status when placing structures

### LINKED ISSUE #1644: Network match is mismatching when building structures
Network match is mismatching when building structures

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1644

This change fixes an issue introduced by #1543 which used local drawable state that was also used by game logic paths, leading to desynchronised behaviour.

### CODE REVIEW

**Comment by xezon** [comment]
This now fails the Replay Check, so is still not right.

**Comment by Stubbjax** [comment]
> This now fails the Replay Check, so is still not right.

Ah, the player index might need to be the local player as it's from their perspective.

**Comment by Stubbjax** [comment]
~~Multiplayer games seem fine with this change but I'm unsure why the retail replays mismatch. As this is a blocker, I've just CRC checked the fix.~~

I've investigated / tested a bit more and believe I have a solution that resolves desync issues and stuck AI.

File: Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp [hunk 1]
```diff
@@ -686,6 +683,9 @@ Bool BuildAssistant::isLocationClearOfObjects( const Coord3D *worldPos,
 		if (them->isKindOf(KINDOF_INERT))
 			continue;
 
+		if (builderObject && them->getShroudedStatus(builderObject->getControllingPlayer()->getPlayerIndex()) >= OBJECTSHROUD_FOGGED)
+			return LBC_SHROUD;
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp]: `'return' : truncation from 'enum LegalBuildCode' to 'bool'`

File: GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp [hunk 2]
```diff
@@ -718,6 +705,19 @@ LegalBuildCode BuildAssistant::isLocationClearOfObjects( const Coord3D *worldPos
...
+		if (builderObject && them->getShroudedStatus(builderObject->getControllingPlayer()->getPlayerIndex()) >= OBJECTSHROUD_FOGGED)
+			return LBC_SHROUD;
+
+		//Kris: Patch 1.01 - November 5, 2003
+		//Prevent busy units (black lotus hacking from being moved by trying to place a building -- exploit).
+		if (rel == ALLIES)
+		{
+			if (them->testStatus(OBJECT_STATUS_IS_USING_ABILITY) || them->getAI() && them->getAI()->isBusy())
+			{
+				return LBC_OBJECTS_IN_THE_WAY;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:723]: Side note: I wonder if this code path is missing `TheTerrainVisual->addFactionBib( them, TRUE );`...

File: GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp [hunk 3]
```diff
@@ -718,6 +705,19 @@ LegalBuildCode BuildAssistant::isLocationClearOfObjects( const Coord3D *worldPos
 		if (them->isKindOf(KINDOF_INERT))
 			continue;
 
+		if (builderObject && them->getShroudedStatus(builderObject->getControllingPlayer()->getPlayerIndex()) >= OBJECTSHROUD_FOGGED)
+			return LBC_SHROUD;
+
+		//Kris: Patch 1.01 - November 5, 2003
+		//Prevent busy units (black lotus hacking from being moved by trying to place a building -- exploit).
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:718]: Why did this block need moving? If it needs to be here for some reason, can add a comment to help understand.

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:718]: I thought it made more sense for the continues (the ignores) to come before the returns (the fails) - in the odd case something designated removable for construction, inert, a mine, etc. could be busy). And if we were to add a bib to this block as you suggested, it would make sense to process that logic after the shroud check to avoid the same issue the original fix was resolving.

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:718]: If we add the bib without moving the block to after the shroud check:

image

File: GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp (hunk 2 above)
Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:723]: Include that with this change?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:723]: Separate. Was just wondering about it as I looked at this code here.

File: GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp (hunk 3 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:718]: > I thought it made more sense for the continues (the ignores) to come before the returns (the fails)

Oh ok. There is another continue below this return.

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:718]: Do you think it's clean enough to check `KINDOF_IMMOBILE` twice - one with the continue beforehand and the other after?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:718]: yes

File: Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp [hunk 4]
```diff
@@ -686,11 +683,17 @@ Bool BuildAssistant::isLocationClearOfObjects( const Coord3D *worldPos,
 		if (them->isKindOf(KINDOF_INERT))
 			continue;
 
-		// an immobile object may obstruct our building depending on flags.
-		if( them->isKindOf( KINDOF_IMMOBILE ) )	{
-			if (onlyCheckEnemies && builderObject && builderObject->getRelationship( them ) != ENEMIES )	{
+		if (them->isKindOf(KINDOF_IMMOBILE)) {
+			if (onlyCheckEnemies && builderObject && builderObject->getRelationship(them) != ENEMIES) {
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: Can reduce the file diff by not editing the whitespace here. Same in ZH code.

File: Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp [hunk 5]
```diff
@@ -686,11 +683,17 @@ Bool BuildAssistant::isLocationClearOfObjects( const Coord3D *worldPos,
...
 				continue;
 			}
+		}
+
+		if (builderObject && them->getShroudedStatus(builderObject->getControllingPlayer()->getPlayerIndex()) >= OBJECTSHROUD_FOGGED)
+			return false;
+
+		// an immobile object may obstruct our building depending on flags.
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:695]: Is this EA comment still accurate here?

File: Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp (hunk 4 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: For what reason?

File: Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp (hunk 5 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:695]: It is still accurate, but the 'flags' part is just earlier now.

File: Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp (hunk 4 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: It reduces the change complexity.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: Is the respective formatting change too complex?

Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: Not much, but I think if the whitespace edit was removed, then the line would not even show up as changed. This reduces chance of merge conflicts.

In Visual Studio, you can move selected lines with ALT + arrow keys without changing formatting.

You can also disable auto format on Copy Paste.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: I think there is merit to applying formatting incrementally and not globally across the whole project, which is far more conflict-prone. When regarding small changes such as moved lines without any real logic changes, on the unlikely chance there any arising conflicts, they would not be hard to resolve.

Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/System/BuildAssistant.cpp:687]: Okay
