### PR TITLE
bugfix(aiupdate): Invalidate build task of Dozers and Workers if the assigned target scaffold no longer exists

### LINKED ISSUE #1824: Delay in releasing construction ability when cancelling building
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Sometimes when cancelling the construction of a building, there is a delay before the construction options are available again.

### Reproduction Steps

1. Construct a building
2. Cancel construction of the building
3. Observe the controls of the construction unit and see this behavior happen sporadically (attached video for clarity)

### Additional Context

https://github.com/user-attachments/assets/b7b4ef82-c76f-4a13-bb76-01dc36830791

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1824

This change fixes an issue where a builder gets stuck in a busy state if its target scaffold is destroyed just before it reaches its destination.

### CODE REVIEW

**Review by Skyaero42 — APPROVED** [review]
This looks good

File: Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DozerAIUpdate.cpp [hunk 1]
```diff
@@ -1599,6 +1599,10 @@ UpdateSleepTime DozerAIUpdate::update( void )
 		if( currentTask == DOZER_TASK_REPAIR &&
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DozerAIUpdate.cpp:1600]:
```
// validate the task and the target
// TheSuperHackers @bugfix Now also invalidates the task when the build scaffold is destroyed
```

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Update/AIUpdate/DozerAIUpdate.cpp:1600]: Comment can also be replicated in the WorkerAIUpdate.cpp

**Comment by Muntari** [comment]
doesn't this also happen when you cancel a scaffold & the builder gets stuck in greyed out command buttons state
