### PR TITLE
bugfix(worldbuilder): Fix script condition selection when editing newly created condition

### LINKED ISSUE #2066: World Builder: Editing a newly created map script condition changes another condition
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Editing a newly created map script condition changes another condition instead of the condition that shows as selected. Can be worked around by selecting another condition and selecting the latest condition again.

### Reproduction Steps

1. Create a new script with the World Builder.
2. Go to 'Script Conditions' tab.

This should show:
```
*** IF *** 
  True
```

3. Click on 'New', select 'False' and click OK.

This should show:
```
*** IF *** 
  True
  *AND* False
```

4. Click on 'Edit', select 'Timer expired' and click OK.

This should show:
```
*** IF *** 
  *AND* [???]Timer '???' has expired
  *AND* False
```

The above is bugged. Instead of changing the second condition, the first one was changed. There's something wrong with the selection index when creating a new condition.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ViTeXFTW**
* Fixes #2066

**Update**
The only issue was the `m_index` not being updated in the `setSel()` function - the reason for the confusion was improper build directory after the first fix was added. Resolved with deleted build dir and recompilation.

**Description**
This PR fixes an issue in WorldBuilder where the addition of a new condition in the script modal didn't update the `m_index` and left it stale. Which resulted in incorrect update of condition after editing the condition again immidiatly.

**Root Cause**  
1. Missing index update in `setSel()`. When it was called to select a newly created condition, it updated the visual selection and pointer members (`m_orCondition`, `m_condition`) but failed to update `m_index`. This left `m_index` stale.

~~2. Incorrect OrCondition saved in `OnNew()`. When adding a condition with no selection, `OnNew()` saved `m_orCondition` (which was nullptr) instead of the first OrCondition from the script. After `loadList()` triggered `OnSelchangeConditionList()`, `setSel(nullptr, pCond)` failed to find a match and exited without updating any state.~~

Fix in `ScriptConditions.cpp`
1. **setSel():** added `m_index = count;` in https://github.com/TheSuperHackers/GeneralsGameCode/blob/a4f89bc490a5cfb1daebf70a8ec6691b5317a6d7/GeneralsMD/Code/Tools/WorldBuilder/src/ScriptConditions.cpp#L167-L172
https://github.com/TheSuperHackers/GeneralsGameCode/blob/a4f89bc490a5cfb1daebf70a8ec6691b5317a6d7/GeneralsMD/Code/Tools/WorldBuilder/src/ScriptConditions.cpp#L176-L181

~~2. **OnNew():** added `*pSavOr = m_orCondition ? m_orCondition : m_script->getOrCondition();`~~

### CODE REVIEW

File: GeneralsMD/Code/Tools/WorldBuilder/src/ScriptConditions.cpp [hunk 1]
```diff
@@ -166,17 +166,19 @@ void ScriptConditionsDlg::setSel(OrCondition *pOr, Condition *pCond)
...
-					pList->SetCurSel(count);
-					enableUI();
-					return;
-				}
+			if (m_condition == pCond) {
+				pList->SetCurSel(count);
+				m_index = count;
+				enableUI();
+				return;
+			}
```
Comment (xezon) [inline GeneralsMD/Code/Tools/WorldBuilder/src/ScriptConditions.cpp]: Indentation has changed incorrectly.

**Comment by Caball009** [comment]
> It's difficult to understand if this is connect. Can someone else review this?

I can take a look at it later.

**Comment by Caball009** [comment]
First change looks right and directly related to the issue. Not so sure about the second change. Is there a visual cue that there's an issue if the second change isn't implemented?

**Comment by ViTeXFTW** [comment]
> Not so sure about the second change. Is there a visual cue that there's an issue if the second change isn't implemented?

I will do some more testing and provide an update. 

I also initially thought that the first change would fix the behavior however when I recompiled, I still observed the same behavior - however I didn't do a clean rebuild of the codebase at each of the change points, but that shouldn't have an impact right?

**Comment by ViTeXFTW** [comment]
@Caball009 I've updated the PR to only contain the first fix - the issue was with the recompilation as per the updated PR text.

File: GeneralsMD/Code/Tools/WorldBuilder/src/ScriptConditions.cpp (hunk 1 above)
Comment (ViTeXFTW) [reply GeneralsMD/Code/Tools/WorldBuilder/src/ScriptConditions.cpp]: Fixed indentation error in latest push

**Review by Caball009 — APPROVED** [review]
Looks correct. 

Needs to be replicated in Generals.
