### PR TITLE
bugfix(battleplan): Battle plans are now transferred to the new owner on capture

### LINKED ISSUE #2211: USA Strategy Center Battle Plan does not automatically apply its bonus after capturing
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

* Relates to #2209
* Relates to #46

USA Strategy Center Battle Plan does not automatically apply its bonus after capturing.

Dominator
> If you directly capture a strat center with SND, does it automatically apply to your units? currently you have to "reset" it by picking anotehr strategy and then pick SND or whatever again. Is that reset neccessary?

### Reproduction Steps

1. Player 1 build USA Strategy Center
2. Player 1 select Search and Destroy
3. Player 2 capture USA Strategy Center

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Stubbjax**
* Fixes #2211
* Merge after #2335

This change fixes an issue where battle plans are not transferred from the old owner to the new owner when a Strategy Center is captured. In addition, bonuses in effect upon surrender in team games are also now transferred to the new owner, if applicable.

In retail, capturing a Strategy Center leaves any existing bonus intact for the opponent, while giving the capturing player no bonus.

- [x] Run a couple of replays @Skyaero42

### CODE REVIEW

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: `const BattlePlanBonuses *bonus` to ensure bonus is never modified in here.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 1]
```diff
@@ -2971,22 +2971,26 @@ void Player::changeBattlePlan( BattlePlanStatus plan, Int delta, BattlePlanBonus
 	else if( removeBonus )
 	{
 		//First, inverse the bonuses
-		bonus->m_armorScalar				= 1.0f / __max( bonus->m_armorScalar, 0.01f );
-		bonus->m_sightRangeScalar		= 1.0f / __max( bonus->m_sightRangeScalar, 0.01f );
-		if( bonus->m_bombardment > 0 )
+		BattlePlanBonuses* invertedBonus = newInstance(BattlePlanBonuses);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: To avoid this allocation conundrum, I created refactor #2335.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: `const BattlePlanBonusesData *bonus` after #2335

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: #2335 has been merged and this allocation can now be turned into stack variable.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 2]
```diff
@@ -2976,22 +2976,24 @@ void Player::changeBattlePlan( BattlePlanStatus plan, Int delta, BattlePlanBonus
 	else if( removeBonus )
 	{
 		//First, inverse the bonuses
-		bonus->m_armorScalar				= 1.0f / __max( bonus->m_armorScalar, 0.01f );
-		bonus->m_sightRangeScalar		= 1.0f / __max( bonus->m_sightRangeScalar, 0.01f );
-		if( bonus->m_bombardment > 0 )
+		BattlePlanBonusesData invertedBonus = *bonus;
+
+		invertedBonus.m_armorScalar				= 1.0f / __max( bonus->m_armorScalar, 0.01f );
+		invertedBonus.m_sightRangeScalar		= 1.0f / __max( bonus->m_sightRangeScalar, 0.01f );
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: While at it, could remove all the excess tabs here.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 3]
```diff
@@ -2922,7 +2922,7 @@ Bool Player::doesObjectQualifyForBattlePlan( Object *obj ) const
 
 //-------------------------------------------------------------------------------------------------
 // note, bonus is an in-out parm.
```
[the remark this answers is not in the document]
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp]: Comment can be removed entirely, unless this code needs updating...

File: Generals/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp [hunk 4]
```diff
@@ -247,6 +247,16 @@ void BattlePlanUpdate::onObjectCreated()
 	enableTurret( false );
 }
 
+//-------------------------------------------------------------------------------------------------
+void BattlePlanUpdate::onCapture(Player* oldOwner, Player* newOwner)
+{
+#if !RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @bugfix Stubbjax 04/11/2025 Transfer battle plan bonuses on capture.
```
[the remark this answers is not in the document]
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp:254]: This suggestion is good.

File: Generals/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp [hunk 5]
```diff
@@ -247,6 +247,16 @@ void BattlePlanUpdate::onObjectCreated()
...
+	oldOwner->changeBattlePlan(m_planAffectingArmy, -1, m_bonuses);
+	newOwner->changeBattlePlan(m_planAffectingArmy, 1, m_bonuses);
+#endif
```
[the remark this answers is not in the document]
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp:257]: Do we care for this?

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp [hunk 6]
```diff
@@ -2976,22 +2976,24 @@ void Player::changeBattlePlan( BattlePlanStatus plan, Int delta, BattlePlanBonus
 	else if( removeBonus )
 	{
 		//First, inverse the bonuses
-		bonus->m_armorScalar				= 1.0f / __max( bonus->m_armorScalar, 0.01f );
-		bonus->m_sightRangeScalar		= 1.0f / __max( bonus->m_sightRangeScalar, 0.01f );
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/RTS/Player.cpp:2980]: I do wonder, is this CRC safe?

This function is called like so:

```
player->changeBattlePlan( m_planAffectingArmy, -1, m_bonuses );
player->changeBattlePlan( PLANSTATUS_BOMBARDMENT, -1, m_bonuses );
player->changeBattlePlan( PLANSTATUS_HOLDTHELINE, -1, m_bonuses );
player->changeBattlePlan( PLANSTATUS_SEARCHANDDESTROY, -1, m_bonuses );
player->changeBattlePlan( PLANSTATUS_BOMBARDMENT, 1, m_bonuses );
player->changeBattlePlan( PLANSTATUS_HOLDTHELINE, 1, m_bonuses );
player->changeBattlePlan( PLANSTATUS_SEARCHANDDESTROY, 1, m_bonuses );
```

So `m_bonuses` will be written here by the original code.

But now with this change, `m_bonuses` will remain unmodified. Does this not carry the risk of mismatch? If not, why?

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp:2980]: I just tested a multiplayer match between one client @ 7cb5a6275009d506ef967ecd90312fc0bac52f8c and another @ 6e41efa576220843f894e4cffc2410836d81da97 and did not observe any mismatches.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp [hunk 7]
```diff
@@ -253,6 +253,16 @@ void BattlePlanUpdate::onObjectCreated()
...
 }
 
+//-------------------------------------------------------------------------------------------------
+void BattlePlanUpdate::onCapture(Player* oldOwner, Player* newOwner)
+{
+#if !RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @bugfix Stubbjax 04/11/2025 Transfer battle plan bonuses on capture.
+	oldOwner->changeBattlePlan(m_planAffectingArmy, -1, m_bonuses);
+	newOwner->changeBattlePlan(m_planAffectingArmy, 1, m_bonuses);
+#endif
```
[the remark this answers is not in the document]
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp:257]: This looks like a reasonable suggestion by the bot.

File: Generals/Code/GameEngine/Source/Common/RTS/Player.cpp (hunk 6 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/RTS/Player.cpp:2980]: I suspect it does not mismatch because
```
void BattlePlanUpdate::setBattlePlan( BattlePlanStatus plan )
{
...
		m_bonuses->m_armorScalar					= 1.0f;
		m_bonuses->m_sightRangeScalar		= 1.0f;
...
```
This resets the scalars after every removal to restore a clean slate.

It could only mismatch if this reset was not happening after a battle plan removal.

**Review by xezon — APPROVED** [review]
Should be ok. Perhaps @Skyaero42 can run it over a few replays?

Needs rebase

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/BattlePlanUpdate.cpp:257]: We'd be saving one switch and two if statements. Is that worth it?

**Comment by Skyaero42** [comment]
> Should be ok. Perhaps @Skyaero42 can run it over a few replays?
> 
> Needs rebase

Will do, give me a few days.
