### PR TITLE
[GEN][ZH] Fix crash in W3DBufferManager when a shadow buffer limit is exceeded

### LINKED ISSUE #22: The game crashes when a certain 3D Shadow limit is exceeded
The game crashes when a certain 3D Shadow limit (4096) is exceeded.

It is `W3DBufferManager` that has 4096 buffer size.

Thyme has `DX8VertexBufferClass` and `DX8IndexBufferClass` reversed, which use the `W3DBufferManager`.

Can be tested in test map:
[shadow_limit_test_513_scorpions.zip](https://github.com/xezon/GeneralsGamePatch/files/7064456/shadow_limit_test_513_scorpions.zip)

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #22
* Relates to #TheAssemblyArmada/Thyme#1101

This change fixes game crashes from exceeding the limits of `MAX_VB_SIZES`, `MAX_IB_SIZES` and `MAX_NUMBER_SLOTS`.

`MAX_NUMBER_SLOTS` is exceeded in the original game when more than 512 Scorpion tanks are rendered in the scene. This is just a sample test case.

This change also fixes errors in nearby strings and source code comments.

## Callstack for when buffer limit is exceeded

```cpp
> 	generalszh.exe!W3DVolumetricShadow::RenderMeshVolume(int meshIndex, int lightIndex, const Matrix3D * meshXform) Line 1392	C++
 	generalszh.exe!W3DVolumetricShadow::RenderVolume(int meshIndex, int lightIndex) Line 1337	C++
 	generalszh.exe!W3DVolumetricShadowManager::renderShadows(bool forceStencilFill) Line 3563	C++
 	generalszh.exe!DoShadows(RenderInfoClass & rinfo, bool stencilPass) Line 91	C++
 	generalszh.exe!RTS3DScene::Flush(RenderInfoClass & rinfo) Line 857	C++
 	generalszh.exe!RTS3DScene::Render(RenderInfoClass & rinfo) Line 1074	C++
 	generalszh.exe!WW3D::Render(SceneClass * scene, CameraClass * cam, bool clear, bool clearz, const Vector3 & color) Line 979	C++
 	generalszh.exe!RTS3DScene::draw() Line 1724	C++
 	generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
 	generalszh.exe!RTS3DScene::doRender(CameraClass * cam) Line 1708	C++
 	generalszh.exe!W3DView::draw() Line 1565	C++
 	generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
 	generalszh.exe!Display::drawViews() Line 118	C++
 	generalszh.exe!W3DDisplay::draw() Line 1910	C++
 	generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
 	generalszh.exe!GameClient::update() Line 767	C++
 	generalszh.exe!SubsystemInterface::UPDATE() Line 79	C++
 	generalszh.exe!GameEngine::update() Line 741	C++
 	generalszh.exe!Win32GameEngine::update() Line 93	C++
 	generalszh.exe!GameEngine::execute() Line 816	C++
 	generalszh.exe!GameMain(int argc, char * * argv) Line 47	C++
 	generalszh.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 1034	C++
 	[Inline Frame] generalszh.exe!invoke_main() Line 102	C++
 	generalszh.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!75eefcc9()	Unknown
 	ntdll.dll!770e82ae()	Unknown
 	ntdll.dll!770e827e()	Unknown
```

## Callstack for DEBUG_ASSERTCRASH crash

```
>	generalszh.exe!W3DVolumetricShadow::constructVolumeVB(Vector3 * lightPosObject, float shadowExtrudeDistance, int volumeIndex, int meshIndex) Line 2965	C++
 	generalszh.exe!W3DVolumetricShadow::updateMeshVolume(int meshIndex, int lightIndex, const Matrix3D * meshXform, const AABoxClass & meshBox, float floorZ) Line 2190	C++
 	generalszh.exe!W3DVolumetricShadow::updateVolumes(float zoffset) Line 1886	C++
 	generalszh.exe!W3DVolumetricShadow::Update() Line 1843	C++
 	generalszh.exe!W3DVolumetricShadowManager::renderShadows(bool forceStencilFill) Line 3538	C++
 	generalszh.exe!DoShadows(RenderInfoClass & rinfo, bool stencilPass) Line 91	C++
 	generalszh.exe!RTS3DScene::Flush(RenderInfoClass & rinfo) Line 857	C++
 	generalszh.exe!RTS3DScene::Render(RenderInfoClass & rinfo) Line 1074	C++
 	generalszh.exe!WW3D::Render(SceneClass * scene, CameraClass * cam, bool clear, bool clearz, const Vector3 & color) Line 979	C++
 	generalszh.exe!RTS3DScene::draw() Line 1724	C++
 	generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
 	generalszh.exe!RTS3DScene::doRender(CameraClass * cam) Line 1708	C++
 	generalszh.exe!W3DView::draw() Line 1565	C++
 	generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
 	generalszh.exe!Display::drawViews() Line 118	C++
 	generalszh.exe!W3DDisplay::draw() Line 1910	C++
 	generalszh.exe!SubsystemInterface::DRAW() Line 105	C++
 	generalszh.exe!GameClient::update() Line 767	C++
 	generalszh.exe!SubsystemInterface::UPDATE() Line 79	C++
 	generalszh.exe!GameEngine::update() Line 741	C++
 	generalszh.exe!Win32GameEngine::update() Line 93	C++
 	generalszh.exe!GameEngine::execute() Line 816	C++
 	generalszh.exe!GameMain(int argc, char * * argv) Line 47	C++
 	generalszh.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 1034	C++
 	[Inline Frame] generalszh.exe!invoke_main() Line 102	C++
 	generalszh.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!75eefcc9()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!770e82ae()	Unknown
 	ntdll.dll!770e827e()	Unknown
```

### CODE REVIEW

**Comment by Mauller** [comment]
I wonder if we want to consider increasing the limit as well while we are at it? Would also help with the problem alongside the size checks.

I don't think they chose the original limits due to a DX8 limitation, just a choice, likely to help conserve memory.

**Comment by xezon** [comment]
Yes. There is a draft for that at Thyme as well:
https://github.com/TheAssemblyArmada/Thyme/pull/604

But it is not necessary for fixing this crash, so no need for it right now.

**Review by Mauller — APPROVED** [review]
Looks good, is a good thing code beyond this didn't follow the comments lol.

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp [hunk 1]
```diff
@@ -374,31 +385,32 @@ W3DBufferManager::W3DIndexBufferSlot * W3DBufferManager::allocateSlotStorage(Int
 	W3DIndexBufferSlot *ibSlot;
 //	Int sizeIndex = (size >> MIN_SLOT_SIZE_SHIFT)-1;
 
-	DEBUG_ASSERTCRASH(m_numEmptyIndexSlotsAllocated < MAX_NUMBER_SLOTS, ("Nore more IB Slots"));
+	DEBUG_ASSERTCRASH(m_numEmptyIndexSlotsAllocated < MAX_NUMBER_SLOTS, ("No more IB Slots"));
+	// TheSuperHackers @bugfix xezon 18/05/2025 Protect against allocating slot storage beyond the max size.
+	// This will happen when there are too many meshes in the scene to draw shadows with.
+	if (m_numEmptyIndexSlotsAllocated >= MAX_NUMBER_SLOTS) {
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp:391]: Just having a look at it again, we might also want to check ```|| size <= 0``` here like in the get slot functions as an extra sanity check.

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp [hunk 2]
```diff
@@ -260,31 +265,32 @@ W3DBufferManager::W3DVertexBufferSlot * W3DBufferManager::allocateSlotStorage(VB
 	W3DVertexBufferSlot *vbSlot;
 //	Int sizeIndex = (size >> MIN_SLOT_SIZE_SHIFT)-1;
 
-	DEBUG_ASSERTCRASH(m_numEmptySlotsAllocated < MAX_NUMBER_SLOTS, ("Nore more VB Slots"));
+	DEBUG_ASSERTCRASH(m_numEmptySlotsAllocated < MAX_NUMBER_SLOTS, ("No more VB Slots"));
+	// TheSuperHackers @bugfix xezon 18/05/2025 Protect against allocating slot storage beyond the max size.
+	// This will happen when there are too many meshes in the scene to draw shadows with.
+	if (m_numEmptySlotsAllocated >= MAX_NUMBER_SLOTS) {
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp:271]: Like the other comment, might want to ```|| size <= 0``` here too.

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp [hunk 3]
```diff
@@ -260,31 +265,32 @@ W3DBufferManager::W3DVertexBufferSlot * W3DBufferManager::allocateSlotStorage(VB
 	W3DVertexBufferSlot *vbSlot;
 //	Int sizeIndex = (size >> MIN_SLOT_SIZE_SHIFT)-1;
 
-	DEBUG_ASSERTCRASH(m_numEmptySlotsAllocated < MAX_NUMBER_SLOTS, ("Nore more VB Slots"));
+	DEBUG_ASSERTCRASH(m_numEmptySlotsAllocated < MAX_NUMBER_SLOTS, ("No more VB Slots"));
+	// TheSuperHackers @bugfix xezon 18/05/2025 Protect against allocating slot storage beyond the max size.
+	// This will happen when there are too many meshes in the scene to draw shadows with.
+	if (m_numEmptySlotsAllocated >= MAX_NUMBER_SLOTS) {
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp:271]: ditto ```|| size <= 0``` like lower comment

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp [hunk 4]
```diff
@@ -374,31 +385,32 @@ W3DBufferManager::W3DIndexBufferSlot * W3DBufferManager::allocateSlotStorage(Int
 	W3DIndexBufferSlot *ibSlot;
 //	Int sizeIndex = (size >> MIN_SLOT_SIZE_SHIFT)-1;
 
-	DEBUG_ASSERTCRASH(m_numEmptyIndexSlotsAllocated < MAX_NUMBER_SLOTS, ("Nore more IB Slots"));
+	DEBUG_ASSERTCRASH(m_numEmptyIndexSlotsAllocated < MAX_NUMBER_SLOTS, ("No more IB Slots"));
+	// TheSuperHackers @bugfix xezon 18/05/2025 Protect against allocating slot storage beyond the max size.
+	// This will happen when there are too many meshes in the scene to draw shadows with.
+	if (m_numEmptyIndexSlotsAllocated >= MAX_NUMBER_SLOTS) {
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp:391]: ditto ```|| size <= 0```

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp:391]: This is not needed, because `allocateSlotStorage` is protected function and called in `getSlot`, which already asserts and tests exactly that.

Comment (Mauller) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DBufferManager.cpp:391]: Ah yeah i see it now, is all good.
