### PR TITLE
[GEN][ZH] Fix beacon mouse cursor not showing while nothing is selected

### LINKED ISSUE #1174: Beacon mouse cursor is only displayed while an object is selected
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

The mouse cursor does not change to its beacon placement state while nothing is selected. This makes it confusing to the user whether they are in a beacon placement context.

### Reproduction Steps

1. Start a new multiplayer game
2. Click an empty area of the terrain to clear any selection(s)
3. Click the Beacon button in the control bar or press CTRL+B
4. Observe the mouse cursor does not indicate a beacon placement context

### Additional Context

https://github.com/user-attachments/assets/779e3dd2-633d-4a07-8e7e-bdb87cac9ec6

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1174

The mouse cursor now correctly changes to its beacon placement state when the user is in a beacon placement context _without requiring an object to be selected_.

https://github.com/user-attachments/assets/7220b622-1db9-403b-a9d3-9394f5b9d3c0

This is achieved by adding a case to allow a `MSG_VALID_GUICOMMAND_HINT` message to be returned from `CommandXlat` when the user is in a beacon placement context, which is then received by the `HintSpyTranslator` and sent to the `InGameUI` where the cursor is appropriately updated.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp [hunk 1]
```diff
@@ -1393,7 +1393,8 @@ GameMessage::Type CommandTranslator::evaluateContextCommand( Drawable *draw,
 	// Kris: Now that we can select non-controllable units/structures, don't allow any actions to be performed.
 	const CommandButton *command = TheInGameUI->getGUICommand();
 	if( TheInGameUI->areSelectedObjectsControllable()
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp]: This function is an enormous mess. We can simplify the fix by writing it like so:

```cpp
...
	const CommandButton *command = TheInGameUI->getGUICommand();

	if (command && command->getCommandType() == GUICOMMANDMODE_PLACE_BEACON)
	{
		msgType = GameMessage::MSG_VALID_GUICOMMAND_HINT;
		TheMessageStream->appendMessage( msgType );
	}
	else if( TheInGameUI->areSelectedObjectsControllable()
...
```

**Review by xezon — COMMENTED** [review]
Good find.

File: Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp (hunk 1 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp]: That is true; the whole function definitely needs a rewrite. But should it be done in this PR? In this case I intended to follow the existing structure / pattern for consistency and to keep the change as atomic and straightforward as possible.

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp]: No do not refactor this function in this fix. But instead of adding new code in 3 places and making t ever more complicated, add this one new if block and the fix is applied in a much easier to understand way.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp]: Updated.

**Review by xezon — APPROVED** [review]
