### PR TITLE
[GEN][ZH] Implement REPLAY NOT FOUND and MAP NOT FOUND dialogs when attempting to load a Replay that was deleted or whose map is missing

### LINKED ISSUE #126: Replay Menu looks broken when a replay with missing map file is listed
Replay Menu looks broken when a replay with missing map file is listed. Loading such a broken Replay will crash the game.

Image

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Merge after #993
* Fixes #126
* Follow up for #984
* Split off of #398

This change implements a new MAP NOT FOUND dialog when the user attempts to load a Replay whose map is missing in the user data (or game install). Originally the game would crash when trying to start a new game with a missing map.

Additionally it implements a new REPLAY NOT FOUND dialog when the user attempts to load a Replay that was deleted after the Replay Menu was opened.

This change has 2 commits. The first commit is a refactor to help implement the fix efficiently. The second commit contains new code for GameText to allow looking up localization texts with substitute texts when those localizations are not found (which they currently are not because we do not touch game data). The substitution code can be compiled out cleanly when so desired (via GameDefines.h).

## TODO

- [x] Replicate in Generals

## Tip

Ignore whitespace in diff viewer to ease reviewing this change.

## Dialog Image

shot_20250601_164828_1

### CODE REVIEW

File: Core/GameEngine/Include/Common/GameDefines.h [hunk 1]
```diff
@@ -28,3 +28,7 @@
 #ifndef RETAIL_COMPATIBLE_XFER_SAVE
 #define RETAIL_COMPATIBLE_XFER_SAVE (1) // Game is expected to be Xfer Save compatible with retail Generals 1.08, Zero Hour 1.04
 #endif
+
+#ifndef ENABLE_GAMETEXT_SUBSTITUTES
+#define ENABLE_GAMETEXT_SUBSTITUTES (1) // The code can provide substitute texts when labels and strings are missing in the STR or CSF translation file
```
Comment (helmutbuhler) [inline Core/GameEngine/Include/Common/GameDefines.h:33]: Do we really need this? Why would we need the ability to compile out the substitutions?

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 2]
```diff
@@ -102,6 +102,44 @@ UnicodeString GetReplayFilenameFromListbox(GameWindow *listbox, Int index)
...
 }
 
+//-------------------------------------------------------------------------------------------------
+
+struct ReplayMapInfo
+{
+	ReplayMapInfo() : md(NULL) {}
+
+	bool headerAndInfoOk() const { return info.getMapSize() != 0; }
+	bool mdOk() const { return md != NULL; }
```
Comment (helmutbuhler) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: `mapExists` instead of `mdOk`?

**Review by helmutbuhler — APPROVED** [review]
Looks good. I would have preferred out parameters instead of the ReplayMapInfo struct, which is a bit weird because it has methods as a struct, doesn't have m_ prefix for the members and makes callsite code more complicated.

**Comment by helmutbuhler** [comment]
Btw, can you also 'polish' PR #760? It's also split off of #398, and I don't know how to get your approval there.

File: Core/GameEngine/Include/Common/GameDefines.h (hunk 1 above)
Comment (Skyaero42) [reply Core/GameEngine/Include/Common/GameDefines.h:33]: I agree with @helmutbuhler here. I don't think it should be possible to disable the substitution. 
I find using keys (such as `GUI:LabelName`) to be old fashioned. 

In C# for example, the actual English text is used as a key to look up other translations. If the translation is missing, it falls back to the English text. This ensures the user never gets to see a weird key code.

File: GeneralsMD/Code/GameEngine/Include/GameClient/GameText.h [hunk 3]
```diff
@@ -92,5 +94,14 @@ extern GameTextInterface* CreateGameTextInterface( void );
...
 
+// TheSuperHackers @info This is meant to be used like:
+// TheGameText->FETCH_OR_SUBSTITUTE("GUI:LabelName", L"Substitute Fallback Text")
+// The substitute text will be compiled out if ENABLE_GAMETEXT_SUBSTITUTES is not defined.
+#if ENABLE_GAMETEXT_SUBSTITUTES
+#define FETCH_OR_SUBSTITUTE(labelA, substituteTextW) fetchOrSubstitute(labelA, substituteTextW)
+#else
+#define FETCH_OR_SUBSTITUTE(labelA, substituteTextW) fetch(labelA)
+#endif
+
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Include/GameClient/GameText.h:107]: Not needed when substitute cannot be compiled out.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 4]
```diff
@@ -102,6 +102,44 @@ UnicodeString GetReplayFilenameFromListbox(GameWindow *listbox, Int index)
...
+
+	const MapMetaData* md;
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: `md` is quite a cryptic name for a variable. I suggest using `metaData` or `mapMetaData` or maybe even `map`

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 5]
```diff
@@ -102,6 +102,44 @@ UnicodeString GetReplayFilenameFromListbox(GameWindow *listbox, Int index)
...
+	RecorderClass::ReplayHeader header;
+	ReplayGameInfo info;
+};
+
+static ReplayMapInfo readReplayMapInfo(const AsciiString& filename)
+{
+	ReplayMapInfo rmi;
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Cryptic name. I suggest `replayMap`

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp (hunk 2 above)
Comment (Skyaero42) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: See my suggestions on line 114. I would prefer `hasMap` or `hasMetadata` or `isValidMap` rather than `Ok`
Also for the line above: `hasHeader` or `isValidHeader`

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 6]
```diff
@@ -102,6 +102,44 @@ UnicodeString GetReplayFilenameFromListbox(GameWindow *listbox, Int index)
 	return fname;
 }
 
+//-------------------------------------------------------------------------------------------------
+
+struct ReplayMapInfo
+{
+	ReplayMapInfo() : md(NULL) {}
+
+	bool headerAndInfoOk() const { return info.getMapSize() != 0; }
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Is it possible that `info` is NULL? In that case, nullcheck must be performed.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp [hunk 7]
```diff
@@ -1341,6 +1343,19 @@ UnicodeString GameTextManager::fetch( AsciiString label, Bool *exists )
...
+// GameTextManager::fetchOrSubstitute
+//============================================================================
+
+UnicodeString GameTextManager::fetchOrSubstitute( const Char *label, const WideChar *substituteText )
+{
+	Bool exists;
+	UnicodeString str = fetch(label, &exists);
+	if (!exists)
+		str = substituteText;
+	return str;
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GameText.cpp:1356]: Add an empty line after the unbraced if statement.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 8]
```diff
@@ -449,7 +481,18 @@ static void loadReplay(UnicodeString filename)
 	AsciiString asciiFilename;
 	asciiFilename.translate(filename);
 
-	if(!TheRecorder->replayMatchesGameVersion(asciiFilename))
+	ReplayMapInfo rmi = readReplayMapInfo(asciiFilename);
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Variable naming

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 9]
```diff
@@ -145,124 +183,118 @@ void PopulateReplayFileListbox(GameWindow *listbox)
...
-				UnicodeString displayTimeBuffer = getUnicodeTimeBuffer(header.timeVal);
+			//displayTimeBuffer.format( L"%ls", timeBuffer);
 
-				//displayTimeBuffer.format( L"%ls", timeBuffer);
+			// version (no-op)
 
-				// version (no-op)
+			// map
+			UnicodeString mapStr;
+			const MapMetaData *md = TheMapCache->findMap(rmi.info.getMap());
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Variable naming

**Review by roossienb — CHANGES_REQUESTED** [review]
With the subsitute in place, it would be great to have a follow up PR with:
- add text for when the replay is paused/unpaused
- Use substitute for Fast-forward message in Generals

File: Core/GameEngine/Include/Common/GameDefines.h (hunk 1 above)
Comment (xezon) [reply Core/GameEngine/Include/Common/GameDefines.h:33]: > Do we really need this?

Yes. Disabling this gives nice fat MISSING:"GUI:Label" texts in the GUI which is useful when reviewing it.

**Comment by xezon** [comment]
> With the subsitute in place, it would be great to have a follow up PR with:
> * add text for when the replay is paused/unpaused
> * Use substitute for Fast-forward message in Generals

Yes. Good idea.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp (hunk 6 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: No.

File: Core/GameEngine/Include/Common/GameDefines.h (hunk 1 above)
Comment (helmutbuhler) [reply Core/GameEngine/Include/Common/GameDefines.h:33]: Hm, I still don't understand. Why would you want to review it with substitutions disabled? Even if there is a reason, you can just go to `GameTextManager::fetchOrSubstitute` and comment out:
```cpp
	if (!exists)
		str = substituteText;
```

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp (hunk 2 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Function removed.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp (hunk 4 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Fixed.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp (hunk 5 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Fixed.

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp (hunk 9 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp]: Fixed.

**Comment by xezon** [comment]
> I would have preferred out parameters instead of the ReplayMapInfo struct, which is a bit weird because it has methods as a struct, doesn't have m_ prefix for the members and makes callsite code more complicated.

Ok changed to function.

I also moved a bit more of the code into separate functions that could be reused elsewhere.

I also noticed that it is possible to attempt loading a Replay file that was deleted after the Replay Menu was opened. It then triggered the OLDER REPLAY VERSION dialog with the OK button. Pressing OK would get the game stuck loading nothing. So I added another new REPLAY NOT FOUND message to prevent that.

shot_20250602_191632_1

File: Core/GameEngine/Include/Common/GameDefines.h (hunk 1 above)
Comment (xezon) [reply Core/GameEngine/Include/Common/GameDefines.h:33]: Commenting out the code will still compile in the substitution strings in the executable. This means it is not a clean strip out. Also finding the right place to comment out is not very user friendly. Ideally it is a compile option and/or command line argument.

GameDefines.h is perfectly fine for such things.

**Comment by barefootlogician** [comment]
What's with the title! It would better to have the title be something like "Inform when replay can't be loaded"

Also I think instead of waiting for the user to try click it and find out, maybe the titles for such replays should be made strikethrough or grayed out and the dialog information be displayed in a tooltip.

**Comment by xezon** [comment]
> Also I think instead of waiting for the user to try click it and find out, maybe the titles for such replays should be made strikethrough or grayed out and the dialog information be displayed in a tooltip.

There will be a follow up change for making missing map texts dark red, created by helmut.

As for striking through replays, that is not worth it, because
1. There currently is no strikethrough font in the game
2. The Replay Menu list is populated on open. It is not refreshed when the user tinkers with his replay files while the game runs. And the chance that a user deletes his replays from outside the game after opening the Replay Menu are near 0%, because the Replay Menu has a DELETE REPLAY button. One notable feature for the Replay Menu could be a Refresh button. But that is well beyond the scope of this change and beyond what we currently aim to do: Stability fixes.

**Review by roossienb — APPROVED** [review]

File: GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp [hunk 10]
```diff
@@ -102,6 +102,75 @@ UnicodeString GetReplayFilenameFromListbox(GameWindow *listbox, Int index)
...
+//-------------------------------------------------------------------------------------------------
+
+static UnicodeString createMapName(const AsciiString& filename, const ReplayGameInfo& info, const MapMetaData *mapData)
+{
+	UnicodeString mapName;
+	if (!mapData)
+	{
+		// TheSuperHackers @bugfix helmutbuhler 08/03/2025 Just use the filename.
+		// Displaying a long map path string would break the map list gui.
+		const char* filename = info.getMap().reverseFind('\\');
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/ReplayMenu.cpp:165]: Note to myself: I suspect this will still break the Replay list if the file name is very long then. So we perhaps need another change that caps the length of the Replay name here. Unrelated to this Pull Request.

**Comment by xezon** [comment]
Replicated to Generals without conflicts. Commit title improved.
