### PR TITLE
bugfix(controls): Fix and improve next idle worker selection with contained workers

### LINKED ISSUE #1333: Contained idle workers cannot be iterated past with the Select Next Idle Worker button
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When iterating idle workers via the Select Next Idle Worker button, if a container (technically anything that is not an idle worker) is selected, the next selected idle worker will be from the start of the idle list. This is because the logic only checks the _current selection_ against each idle worker when iterating, without considering that the selection may be a container.

In addition, the logic does not factor containers of containers - meaning that e.g. if an idle worker is contained in a Technical that is contained in a Tunnel Network, then the Select Next Idle Worker button will select the Technical instead of the Tunnel Network, resulting in a confusing UI state.

### Reproduction Steps

1. Build a few workers
2. Enter one of the workers into a building, transport or tunnel
3. Move some or all of the remaining workers to push their position in the idle list to after the contained worker
4. Press the Select Next Idle Worker button and observe no idle workers can be selected after the contained worker

### Additional Context

https://github.com/user-attachments/assets/ed4e56c5-a46b-4308-8e60-6d887cd9d174

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1333

Selecting idle workers via the Select Next Idle Worker button now always selects the next unique selectable and correctly selects top-level containers.

https://github.com/user-attachments/assets/183eddde-ef1f-4c45-863a-0f9b7c32d73a

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 1]
```diff
@@ -5600,21 +5600,33 @@ void InGameUI::selectNextIdleWorker( void )
...
+
+		// Find unique selectables to avoid selecting the same or a previous container if multiple idle workers are contained
+		for (ObjectListIt it = m_idleWorkers[index].begin(); it != m_idleWorkers[index].end(); ++it)
+		{
+			Object* itObj = *it;
+			while (itObj->getContainedBy())
+				itObj = itObj->getContainedBy(); // Treat containers as a single idle selectable
+
+			if (std::find(uniqueIdleWorkers.begin(), uniqueIdleWorkers.end(), itObj) == uniqueIdleWorkers.end())
+				uniqueIdleWorkers.push_back(itObj);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Please create and use `stl::push_back_unique` function in StlUtils.h, because this is a common use pattern.

```cpp
// Push back value into vector-like container if it does not yet contain that value.
template <typename Container>
bool push_back_unique(Container& container, const typename Container::value_type& value)
{
	typename Container::iterator it = std::find(container.begin(), container.end(), value);
	if (it == container.end())
	{
		container.push_back(value);
		return true;
	}
	return false;
}
```

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 2]
```diff
@@ -5428,21 +5428,33 @@ void InGameUI::selectNextIdleWorker( void )
 	else
 	{
 		Drawable *selectedDrawable = TheInGameUI->getFirstSelectedDrawable();	
+		ObjectList uniqueIdleWorkers;
+
+		// Find unique selectables to avoid selecting the same or a previous container if multiple idle workers are contained
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: I think this approach is technically correct and the least error prone.

The only upset with this is that it needs to do these allocations, then populate this list, on every idle worker button press. I did have a try at building the idle worker data structures to have container separation already organized on addIdleWorker, but this is very tricky to do because of containers inside containers (Worker inside Humvee inside Chinook) and adds a great level of complexity to this.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 3]
```diff
@@ -5428,21 +5428,33 @@ void InGameUI::selectNextIdleWorker( void )
...
+		for (ObjectListIt it = m_idleWorkers[index].begin(); it != m_idleWorkers[index].end(); ++it)
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: This will be better in a new function with a good name.

`static std::vector<Object*> buildUniqueIdleWorkers(const ObjectList& idleWorkers)`

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 4]
```diff
@@ -5428,21 +5428,33 @@ void InGameUI::selectNextIdleWorker( void )
...
 				else
-					selectThisObject = *m_idleWorkers[index].begin();
+					selectThisObject = *uniqueIdleWorkers.begin();
 				break;
 			}
-			++it;
+			++uit;
 		}
 		// if we had something selected that wasn't a worker, we'll get here
 		if(!selectThisObject)
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: `*m_idleWorkers[index].begin()` here and further up needs looking at. It seems not right.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 5]
```diff
@@ -5454,10 +5466,8 @@ void InGameUI::selectNextIdleWorker( void )
 	{	
 		
 		//If our idle worker is contained by anything, we need to select the container instead.
-		Object *containedBy = selectThisObject->getContainedBy();
-		if( containedBy )
-		{
-			selectThisObject = containedBy;
+		while (selectThisObject->getContainedBy()) {
+			selectThisObject = selectThisObject->getContainedBy();
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: I expect this to be obsoleted and removed if the new logic above works correctly.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 6]
```diff
@@ -5428,21 +5428,33 @@ void InGameUI::selectNextIdleWorker( void )
 	else
 	{
 		Drawable *selectedDrawable = TheInGameUI->getFirstSelectedDrawable();	
+		ObjectList uniqueIdleWorkers;
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: To improve performance a bit, use `std::vector<Object*>` and `reserve(idleWorkers.size())`

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 2 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: I did consider other possible more efficient solutions but as you may have figured, containers can change while the worker remains idle which significantly complicates matters. I don't think efficiency is really much of a concern here seeing as it is a seldom-used action that is not typically spammed nor frame critical. I believe the simplicity of the solution at hand and its isolation to a single block of a dozen or so lines is preferable to adding significant complexity for negligible performance gain.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 3 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Updated.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 4 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: What about it doesn't seem right?

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 5 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: It is required if the first idle worker in the list is selected via the first block if the select count != 1.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 6 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Updated.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 4 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Because it ignores the container bundling. So if the first Worker is in Container, then this behaves incorrectly. Also, code can be simplified to do `*m_idleWorkers[index].begin()` just once, instead of 2 places.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: What about the logic behaves incorrectly? The container bundling occurs further down. If the first worker is contained, subsequent workers are still selected as expected.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 5 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: I am saying this while loop can be removed if the logic above is fixed, because at this point we should expect that we have selected the top most container.

Instead can put an assert for `selectThisObject->getContainedBy() == NULL`

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 4 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: First step:

```
selectThisObject = uniqueIdleWorkers.front();
```

down here.

At the top can do

```cpp
selectThisObject = *m_idleWorkers[index].begin();
while (selectThisObject->getContainedBy()) {
  selectThisObject = selectThisObject->getContainedBy();
```

Then 2x

```
while (itObj->getContainedBy())
  itObj = itObj->getContainedBy();
```

Can be simplified by adding a `getTopContainedBy()` function into Object class.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Yes I agree. The simplicity and correctness of the implementation is way more important here.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 4 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]:
```diff
- while (itObj->getContainedBy())
-   itObj = itObj->getContainedBy();
+ if (itObj->getTopContainedBy())
+   itObj = itObj->getTopContainedBy();
```

Is this really that much of a simplification? Readability-wise, it feels the same. I also generally follow the rule of three when it comes to logic duplication. But I'll do it if you feel strongly about it.

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Ok that does not help readability much. I initially thought we can get that down to one line.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 7]
```diff
@@ -5484,6 +5479,24 @@ void InGameUI::selectNextIdleWorker( void )
 	}
 }
 
+// Finds unique selectables to avoid selecting the same or a previous container if multiple idle workers are contained
+std::vector<Object*> InGameUI::getUniqueIdleWorkers(const ObjectList& idleWorkers)
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: You created a `ObjectPtrVector` but are not using it much.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 8]
```diff
@@ -5424,42 +5424,37 @@ void InGameUI::selectNextIdleWorker( void )
...
-
+		if (!selectThisObject)
+			selectThisObject = uniqueIdleWorkers.front();
 	}
 	DEBUG_ASSERTCRASH(selectThisObject, ("InGameUI::selectNextIdleWorker Could not select the next IDLE worker"));
 	if(selectThisObject)
 	{	
-		
-		//If our idle worker is contained by anything, we need to select the container instead.
-		Object *containedBy = selectThisObject->getContainedBy();
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp:5457]: Can add here `DEBUG_ASSERTCRASH(selectThisObject->getContainedBy() == NULL, ("Selected object is not expected to be contained"));`

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 9]
```diff
@@ -5424,42 +5424,37 @@ void InGameUI::selectNextIdleWorker( void )
...
 	}
 	else
 	{
 		Drawable *selectedDrawable = TheInGameUI->getFirstSelectedDrawable();	
-		
-		ObjectListIt it = m_idleWorkers[index].begin();
-		while(it != m_idleWorkers[index].end())
+		std::vector<Object*> uniqueIdleWorkers = getUniqueIdleWorkers(m_idleWorkers[index]);
+
+		ObjectPtrVector::iterator uit = uniqueIdleWorkers.begin();
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: This is now the only iterator in this scope, so can name it back to `it` as before (makes a smaller diff and is more common name for iterator)

File: GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 10]
```diff
@@ -5596,42 +5596,37 @@ void InGameUI::selectNextIdleWorker( void )
...
+		while (selectThisObject->getContainedBy())
+			selectThisObject = selectThisObject->getContainedBy();
 	}
 	else
 	{
 		Drawable *selectedDrawable = TheInGameUI->getFirstSelectedDrawable();	
-		
-		ObjectListIt it = m_idleWorkers[index].begin();
-		while(it != m_idleWorkers[index].end())
+		std::vector<Object*> uniqueIdleWorkers = getUniqueIdleWorkers(m_idleWorkers[index]);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Better add a `TheSuperHackers @tweak` comment here that explains the change and the user facing benefit it has.

**Review by xezon — COMMENTED** [review]
Looks mostly good.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp (hunk 7 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: Fixed!

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 11]
```diff
@@ -5424,42 +5424,41 @@ void InGameUI::selectNextIdleWorker( void )
...
+			selectThisObject = selectThisObject->getContainedBy();
 	}
 	else
 	{
-		Drawable *selectedDrawable = TheInGameUI->getFirstSelectedDrawable();	
-		
-		ObjectListIt it = m_idleWorkers[index].begin();
-		while(it != m_idleWorkers[index].end())
+		Drawable *selectedDrawable = TheInGameUI->getFirstSelectedDrawable();
+		// The SuperHackers @tweak Stubbjax 22/07/2025 Idle worker iteration now correctly identifies and
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: "TheSuperHackers" in one word

**Review by xezon — APPROVED** [review]
Looks very good overall. Code is a bit simpler too.
