### PR TITLE
[GEN][ZH] Fix untimely Exe CRC generation in GlobalData

### LINKED ISSUE #1083: Fake EXE CRC still does not work with Zero Hour
* Relates to #965
* Relates to #1051

After the fake EXE CRC implementation for VC6 builds, it somehow still does not work, although I have seen it work correctly before. I do not know what is wrong this time.

Image

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #1083
* Follow up for #1068 

#1068 has introduced a bug where `GlobalData::m_exeCRC` remained 0 after `GameEngine::init`. This happened because GlobalData was created before `TheFileSystem` (and `TheVersion`) which were required to access the files for CRC generation.

The EXE CRC generation is now moved to `GlobalData::init`, which is called after `TheFileSystem` (and `TheVersion`) is initialized, and therefore fixes this issue.

`GlobalData::init` is also called by all tools that use `GlobalData`.

There is no user of `GlobalData::m_exeCRC` before `GameEngine::init` is done.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/Common/GlobalData.cpp [hunk 1]
```diff
@@ -1256,3 +1189,76 @@ void GlobalData::parseGameDataDefinition( INI* ini )
 	TheWritableGlobalData->m_yResolution = yres;
 }
 
+
+UnsignedInt GlobalData::generateExeCRC()
+{
+	DEBUG_ASSERTCRASH(TheFileSystem != NULL, ("TheFileSystem is NULL"));
```
Comment (helmutbuhler) [inline Generals/Code/GameEngine/Source/Common/GlobalData.cpp:1195]: Can we also add a check for TheVersion here?

File: Generals/Code/GameEngine/Source/Common/GlobalData.cpp [hunk 2]
```diff
@@ -1256,3 +1189,76 @@ void GlobalData::parseGameDataDefinition( INI* ini )
...
+
+	exeCRC.set(GENERALS_108_CD_EXE_CRC);
+	DEBUG_LOG(("Fake EXE CRC is 0x%8.8X\n", exeCRC.get()));
+
+#else
+	{
+		Char buffer[ _MAX_PATH ];
+		GetModuleFileName( NULL, buffer, sizeof( buffer ) );
+		fp = TheFileSystem->openFile(buffer, File::READ | File::BINARY);
+		if (fp != NULL) {
```
Comment (helmutbuhler) [inline Generals/Code/GameEngine/Source/Common/GlobalData.cpp:1217]: We can keep the runtime check here, but we might also want to assert fp != NULL here.

**Review by helmutbuhler — CHANGES_REQUESTED** [review]

File: Generals/Code/GameEngine/Source/Common/GlobalData.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/GlobalData.cpp:1195]: No, TheVersion is conditional. Because GUIEdit has TheVersion = NULL when it calls init. Other tools maybe too.

File: Generals/Code/GameEngine/Source/Common/GlobalData.cpp (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/GlobalData.cpp:1217]: Done.

File: Generals/Code/GameEngine/Source/Common/GlobalData.cpp (hunk 1 above)
Comment (helmutbuhler) [reply Generals/Code/GameEngine/Source/Common/GlobalData.cpp:1195]: Ok, I didn't know this was also used by the tools.

**Review by helmutbuhler — APPROVED** [review]
Looks good!
