### PR TITLE
bugfix(weapon): Fix unreliability of historic bonus weapons

### LINKED ISSUE #1760: Only 3 Fire Storms can be active at the same time
Only 3 Firestorms can be active at the same time.

hanfield:
> with HistoricBonusCount of 5, only 3 firestorms triggered
with HistoricBonusCount of 1, over 9 infernos triggered firestorms
it is tied to HistoricBonusCount somehow

### PR DESCRIPTION
**Pull request by Stubbjax**
* Fixes #1760

This change fixes historic bonus weapons not triggering reliably. The issue is that whenever a historic bonus weapon is triggered (e.g. a firestorm) it resets the historic bonus count for _all_ weapons using the same template. This means that if a firestorm is triggered while another firestorm is half way to triggering, that other firestorm's progress will be reset.

In addition, historic damage instances now more accurately expire based on the weapon template's `HistoricBonusTime` rather than the global `HistoricDamageLimit`. Historic damage involved in triggering a historic weapon cannot be used in subsequent attempts.

### Example

Four MiGs must strike a target within a certain radius to trigger a firestorm. Each missile contributes +1 to the historic bonus count of `NapalmMissileWeapon`, which must reach 8 to create the firestorm.

Now imagine a scenario where there are two squadrons of four MiGs each, Squad A and Squad B. Both squads strike different targets at the roughly same time.

Squad A MiG 1 increases the historic bonus count to 2.
Squad A MiG 2 increases the historic bonus count to 4.
Squad B MiG 1 increases the historic bonus count to 6.
Squad B MiG 2 increases the historic bonus count to 8.
Squad A MiG 3 increases the historic bonus count to 10.
Squad A MiG 4 increases the historic bonus count to 12.
Of the 12 historic bonus instances, 8 are determined to be in the same location, and thus a firestorm is triggered for Squad A.
The triggering of Squad A's firestorm resets the historic bonus count to 0.
Squad B MiG 3 increases the historic bonus count to 2.
Squad B MiG 4 increases the historic bonus count to 4.
No firestorm is triggered for Squad B.

### Demonstration of the bug

https://github.com/user-attachments/assets/7e3a4c19-8aff-4dba-afdd-3a2ff8daeae5

Note: When testing with Inferno Cannons, it is preferable to test without the `HeightDieUpdate` modules in the `InfernoTankShell` and `InfernoTankShellUpgraded` weapon objects for 100% accuracy. See [#1564](https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1564) from the patch repository for more info.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Include/GameLogic/Weapon.h [hunk 1]
```diff
@@ -331,10 +331,12 @@ struct HistoricWeaponDamageInfo
 	// The time and location this weapon was fired
 	UnsignedInt						frame;
 	Coord3D								location;
+	Bool									triggered;
 
 	HistoricWeaponDamageInfo(UnsignedInt f, const Coord3D& l) :
 		frame(f), location(l)
 	{
+		triggered = false;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Include/GameLogic/Weapon.h]: Or `, triggered(false)` in initializer.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 2]
```diff
@@ -1190,6 +1191,21 @@ void WeaponTemplate::trimOldHistoricDamage() const
...
+{
+	HistoricWeaponDamageList::iterator it = m_historicDamage.begin();
+
+	while (it != m_historicDamage.end())
+	{
+		UnsignedInt expirationDate = it->frame + m_historicBonusTime;
+		if (TheGameLogic->getFrame() > expirationDate || it->triggered)
+			it = m_historicDamage.erase(it);
+		else
+			++it;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Is the chronological order no longer present? If it still is chronological , then aborting on first fail is more efficient.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 3]
```diff
@@ -1254,6 +1263,53 @@ void WeaponTemplate::dealDamageInternal(ObjectID sourceID, ObjectID victimID, co
...
+			if (is2DDistSquaredLessThan(*pos, it->location, radSqr))
+			{
+				// This one is close enough in time and distance, so count it. This is tracked by template since it applies
+				// across units, so don't try to clear historicDamage on success in here.
+				(*it).triggered = true;
+				++count;
+			}
+		}
+
+		if (count >= m_historicBonusCount - 1)	// minus 1 since we include ourselves implicitly
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Style:

if ()
{
}

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 4]
```diff
@@ -1190,6 +1191,21 @@ void WeaponTemplate::trimOldHistoricDamage() const
...
 	}
 }
+#else
+void WeaponTemplate::trimOldHistoricDamage() const
+{
+	HistoricWeaponDamageList::iterator it = m_historicDamage.begin();
+
+	while (it != m_historicDamage.end())
+	{
+		UnsignedInt expirationDate = it->frame + m_historicBonusTime;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: expirationFrame

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 5]
```diff
@@ -1254,6 +1263,53 @@ void WeaponTemplate::dealDamageInternal(ObjectID sourceID, ObjectID victimID, co
...
+				++count;
+			}
+		}
+
+		if (count >= m_historicBonusCount - 1)	// minus 1 since we include ourselves implicitly
+			TheWeaponStore->createAndFireTempWeapon(m_historicBonusWeapon, source, pos);
+		else
+		{
+			for (HistoricWeaponDamageList::iterator it = m_historicDamage.begin(); it != m_historicDamage.end(); ++it)
+				(*it).triggered = false;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: I think we can get rid of this reset loop by having a 

`UnsignedInt HistoricWeaponDamageInfo::triggerFrame`

which is then set to current frame when triggered, and `HistoricWeaponDamageInfo` removed when trigger count is confirmed.

Then have 2 functions:

`trimExpiredHistoricDamage()`

and

`trimTriggeredHistoricDamage(triggerFrame)`

Make `trimExpiredHistoricDamage` efficient by expecting chronological order and call it same place as `trimOldHistoricDamage`.

Call `trimTriggeredHistoricDamage` after the count test, to remove the triggered ones.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 6]
```diff
@@ -1254,6 +1263,53 @@ void WeaponTemplate::dealDamageInternal(ObjectID sourceID, ObjectID victimID, co
...
+		Real radSqr = m_historicBonusRadius * m_historicBonusRadius;
+		Int count = 0;
+		for (HistoricWeaponDamageList::iterator it = m_historicDamage.begin(); it != m_historicDamage.end(); ++it)
+		{
+			if (is2DDistSquaredLessThan(*pos, it->location, radSqr))
+			{
+				// This one is close enough in time and distance, so count it. This is tracked by template since it applies
+				// across units, so don't try to clear historicDamage on success in here.
+				(*it).triggered = true;
+				++count;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Is it correct that is just keeps counting even beyond `m_historicBonusCount`? Perhaps should stop at `m_historicBonusCount - 1`, to just take the required amount, not more?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp (hunk 5 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Thinking about this again, `triggerFrame` would be not quite right if there is another sequence happening elsewhere in the same frame. The Coord3D would be a better identifier for the sequence. But that is a bit big (12 bytes). So instead I suggest creating a `WeaponTemplate` local counter that keeps incrementing on each call of `processHistoricDamage`. That will be unique and safe.

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: I think `trimExpiredHistoricDamage` is already efficient enough when concerning partial clears, as the overwhelming majority of trim calls will either have very few elements to clear, or the entire list will likely be expired.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Yes, but implementation is not so clean this way. I suggest explore what I suggested.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 7]
```diff
@@ -1254,6 +1287,59 @@ void WeaponTemplate::dealDamageInternal(ObjectID sourceID, ObjectID victimID, co
...
+			const Real radSqr = m_historicBonusRadius * m_historicBonusRadius;
+			Int count = 0;
+
+			for (HistoricWeaponDamageList::iterator it = m_historicDamage.begin(); it != m_historicDamage.end(); ++it)
+			{
+				if (is2DDistSquaredLessThan(*pos, it->location, radSqr))
+				{
+					// This one is close enough in time and distance, so count it. This is tracked by template since it applies
+					// across units, so don't try to clear historicDamage on success in here.
+					(*it).triggerIndex = m_historicDamageInstanceCount;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Style: `it->triggerIndex`

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 8]
```diff
@@ -1254,6 +1287,59 @@ void WeaponTemplate::dealDamageInternal(ObjectID sourceID, ObjectID victimID, co
...
+					++count;
+
+					if (count >= requiredCount)
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: `count` cannot become larger than `requiredCount`.

`if (++count == requiredCount)` would be more concise and correct.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 9]
```diff
@@ -1190,6 +1193,43 @@ void WeaponTemplate::trimOldHistoricDamage() const
 		}
 	}
 }
+#else
+void WeaponTemplate::trimOldHistoricDamage() const
+{
+	if (m_historicDamage.empty())
+	{
+		m_historicDamageInstanceCount = 0;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Is this necessary? I think we can just happily have this count to uint max and wrap?

File: Generals/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp [hunk 10]
```diff
@@ -309,6 +309,8 @@ WeaponTemplate::WeaponTemplate() : m_nextTemplate(NULL)
 	m_continueAttackRange						= 0.0f;
 	m_infantryInaccuracyDist				= 0.0f;
 	m_suspendFXDelay								= 0;
+
+	m_historicDamageInstanceCount = 0;
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Weapon.cpp]: Better call this `m_historicDamageTriggerId`

File: Generals/Code/GameEngine/Include/GameLogic/Weapon.h [hunk 11]
```diff
@@ -320,9 +320,10 @@ struct HistoricWeaponDamageInfo
 	// The time and location this weapon was fired
 	UnsignedInt						frame;
 	Coord3D								location;
+	Int										triggerIndex;
```
Comment (xezon) [inline Generals/Code/GameEngine/Include/GameLogic/Weapon.h]: `UnsignedInt triggerId; ///< Unique Id assigned to this and nearby damage infos`

Also should be `UnsignedInt` type.

**Review by xezon — COMMENTED** [review]
New modified implementation looks much better. 👍

**Review by xezon — APPROVED** [review]
Code looks good to me.

If I am not mistaken Historic Weapon is also missing xfer. I have tracked it here: #1754

**Comment by xezon** [comment]
I added the Controversial label. I do think the bug fix itself is perfectly desirable to restore sane behavior, but there may be a desire to still be able to cap the amount of concurrent firestorms per player (or team) if the fire storms are considered too powerful otherwise.
