### PR TITLE
[GEN] Fix wrong water color on radar

### LINKED ISSUE #822: [GEN] Radar does not render water
This bug occurs in `Command and Conquer: Generals` and was possible introduced in the main branch.

## Reproduction steps
 - Use the replay `skirmish 1` from the Wiki
 - Alternatively: play a skirmish game as USA on a water map (e.g. Coral Island)

Image

Image

Triage:
 - Issue is present in commit `e2064f21 [GEN][ZH] Fix dangling pointer at Player::m_defaultTeam when Team is destroyed (#809)`
 - Issue may have been introduced in `44fee199 [GEN] Bring ShaderClass::Apply more in line with Zero Hour (#776)`

### PR DESCRIPTION
**Pull request by roossienb**
* Follow up for #777
* Fixes #822

### CODE REVIEW

**Comment by Mauller** [comment]
Did you see how this is handled in zero hour?

It's likely that zero hour implicitly sets these between 0 and 1 in config somewhere else.

**Comment by roossienb** [comment]
The radar water color has a default value defined in water.h in integer-notation (0-255)
When the application starts, it first assigns this default value.
Then it tries to load any overrides from ini's. However in the INI parser  the integers (0-255) is parsed into a float value (0-1)

RadarWaterColor is defined in ZH's ini file, but not in Generals. So Generals returns to the default integer notation, while ZH returns the float-notation. RadarWaterColor is a value that can be overridden by maps as well. So not all maps in GEN may bug out - which may explain why we didn't pick up on it initially.

The fix should be to convert the default value from integer to float notation for both games, although ZH uses the INI. Will adjust accordingly

**Comment by roossienb** [comment]
> > The radar water color has a default value defined in water.h in integer-notation (0-255) When the application starts, it first assigns this default value. Then it tries to load any overrides from ini's. However in the INI parser the integers (0-255) is parsed into a float value (0-1)
> > RadarWaterColor is defined in ZH's ini file, but not in Generals. So Generals returns to the default value (in integer notation), while ZH returns the INI value that is converted to float-notation by the INI parser.
> > RadarWaterColor is a value that can be overridden by maps as well. So not all maps in GEN may bug out - which may explain why we didn't pick up on it initially.
> > The fix should be to convert the default value from integer to float notation for both games, although ZH uses the INI. Will adjust accordingly
> 
> Does Generals have a parser for the ini and just not have it defined? Might want to also back port the parser if not to align things more with the ZH code?

RGB parser is present, its just the INI that is the issue

File: GeneralsMD/Code/GameEngine/Include/GameClient/Water.h [hunk 1]
```diff
@@ -100,9 +100,9 @@ class WaterTransparencySetting : public Overridable
 			m_standingWaterColor.red = 1.0f;
 			m_standingWaterColor.green = 1.0f;
 			m_standingWaterColor.blue = 1.0f;
-			m_radarColor.red = 140;
-			m_radarColor.green = 140;
-			m_radarColor.blue = 255;
+			m_radarColor.red = 140 / 255.0f;
+			m_radarColor.green = 140 / 255.0f;
+			m_radarColor.blue = 255 / 255.0f;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Include/GameClient/Water.h]: Nice find. Perhaps we just put 0.55f, 0.55f, 1.0f like in the INI file?

**Review by xezon — APPROVED** [review]

**Review by OmniBlade — APPROVED** [review]
