### PR TITLE
bugfix(shadow): Fix missing tree shadow decals when no object shadow decals exist

### LINKED ISSUE #261: Blob shadows pop in
#### Original game source: [e.g. Origin, TFD or game disc]

- Reproducible in the original Generals Zero Hour? yes
- Multiplayer affected? yes
- Are you using any mods? (like Gentool, Rise of the Reds or Contra) no

### Issue explanation

Not sure what the cause is but for some systems this occurs, i observed this in a AGX750 video and recorded that.
I confirmed with ZH community that its a retail issue.

### Steps to reproduce the problem
1. Start a game.
2. Wait a few seconds while observing trees.

### Screenshot(s) or video

https://user-images.githubusercontent.com/1433426/140068064-29711ae4-07ca-4c06-bd1a-a84a52b1c5ed.mp4

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #261

This change fixes the missing tree shadow decals while no object shadow decals exist.

The issue happens because the decal draw bounds are only updated when there are object decal shadows (for example under infantry units).

## Original

Map: North America

shot_20250917_143040_1

## This change

shot_20250917_142959_1

## TODO

- [x] Replicated in Generals

### CODE REVIEW

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp [hunk 1]
```diff
@@ -88,12 +88,6 @@ extern int nShadowStartBatchIndex;
 extern int SHADOW_VERTEX_SIZE;
 extern int SHADOW_INDEX_SIZE;
 
-//Bounding rectangle around rendered portion of terrain.
-static Int drawEdgeX=0;
-static Int drawEdgeY=0;
-static Int drawStartX=0;
-static Int drawStartY=0;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/Shadow/W3DProjectedShadow.cpp:95]: I moved these into the class.

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp [hunk 2]
```diff
@@ -1604,12 +1604,12 @@ void W3DTreeBuffer::drawTrees(CameraClass * camera, RefRenderObjListIterator *pD
...
 				continue;
 			}
-			Real factor = 1.0f;
+
 			if (m_trees[curTree].m_toppleState == TOPPLE_FALLING ||
 					m_trees[curTree].m_toppleState == TOPPLE_DOWN) {
 				continue;
 			}
-			m_shadow->setSize(m_treeTypes[type].m_shadowSize, -m_treeTypes[type].m_shadowSize*factor);
+			m_shadow->setSize(m_treeTypes[type].m_shadowSize, m_treeTypes[type].m_shadowSize);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DTreeBuffer.cpp:1612]: This change does not exactly relate to the fix, but is related to tree shadows. Essentially Y was flipped which should flip the texture, but that does not make a difference because the decal shadow is a dark circle and inconsequential to flipping.

**Comment by xezon** [comment]
While replicating to Generals, I noticed that this issue does not happen in Generals, because Trees are not rendered through the W3DTreeBuffer. Looks like it was WIP from Generals to Zero Hour development and did not make the cut.

```cpp
W3DTreeBuffer::W3DTreeBuffer(void)
{
	m_initialized = false;
	///@toto - reactivate this optimization if useful.  jba.
	return;
...
```

I replicated what can be replicated anyway and user facing it will change nothing in Generals.

**Comment by Mauller** [comment]
> While replicating to Generals, I noticed that this issue does not happen in Generals, because Trees are not rendered through the W3DTreeBuffer. Looks like it was WIP from Generals to Zero Hour development and did not make the cut.
> 
> ```c++
> W3DTreeBuffer::W3DTreeBuffer(void)
> {
> 	m_initialized = false;
> 	///@toto - reactivate this optimization if useful.  jba.
> 	return;
> ...
> ```
> 
> I replicated what can be replicated anyway and user facing it will change nothing in Generals.

When decoupling the tree sway from the render FPS i also noticed something similar. 
The sway is implemented and handled in the tree buffer in zero hour.
