### PR TITLE
[GEN][ZH] Fix crash when launching the game with an unsupported Display Resolution or when the graphics adapter does not support 800 x 600

### LINKED ISSUE #98: Game crashes on full screen launch if game creation resolution is not supported by the graphics adapter
Game crashes on full screen launch if game creation resolution is not supported by the graphics adapter.

There are 2 ways this crash can happen:
* user sets an unsupported resolution in the Options.ini himself
* user hardware does not support the minimum default resolution the game sets (800 x 600) on first launch

Steps to Reproduce:
* open **%USERPROFILE%\Documents\Command and Conquer Generals Zero Hour Data\Options.ini**
* set `Resolution = 3840 2160` or higher, depending on monitor capabilities

Game will crash.

To fix, game should detect whether or not resolution is too low or too high and adjust Resolution accordingly. Applicable in full screen mode only. Windowed mode is not affected.

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #98

This change prevents the game from crashing when launching with an unsupported Display Resolution or when the graphics adapter does not support 800 x 600, because that is the default game creation resolution.

### CODE REVIEW

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp [hunk 1]
```diff
@@ -668,38 +667,74 @@ void W3DDisplay::init( void )
...
+			case 1:
+				// Getting the device at the default bit depth (32) didn't work, so try
+				// getting a 16 bit display.  (Voodoo 1-3 only supported 16 bit.) jba.
+				setBitDepth( 16 );
+				break;
+			case 2:
+			{
+				// TheSuperHackers @bugfix xezon 11/06/2025 Now tries a safe default resolution
+				// if the custom resolution did not succeed. This is unlikely to happen but is possible
+				// if the user writes an unsupported resolution into to the Option Preferences or if the
```
Comment (xezon) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: into to

**Review by sorcerer86pt — APPROVED** [review]

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp [hunk 2]
```diff
@@ -668,38 +667,74 @@ void W3DDisplay::init( void )
...
+				const Int minW = 800;
+				const Int minH = 600;
+				Int xres = minW;
+				Int yres = minH;
+				Int bitDepth = 32;
+				Int displayModeCount = getDisplayModeCount();
+				Int displayModeIndex = 0;
+				for (; displayModeIndex < displayModeCount; ++displayModeIndex)
+				{
+					getDisplayModeDescription(0, &xres, &yres, &bitDepth);
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: getDisplayModeDescription(displayModeIndex, &xres, &yres, &bitDepth);

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp [hunk 3]
```diff
@@ -668,38 +667,74 @@ void W3DDisplay::init( void )
...
-				WW3D::Shutdown();
-				WWMath::Shutdown();
-				throw ERROR_INVALID_D3D;	//failed to initialize.  User probably doesn't have DX 8.1
-				DEBUG_ASSERTCRASH( 0, ("Unable to set render device\n") );
-				return;
+			case 0:
+				// set our default width and height and bit depth
+				setWidth( TheGlobalData->m_xResolution );
+				setHeight( TheGlobalData->m_yResolution );
+				setBitDepth( 32 );
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: setBitDepth(W3D_DISPLAY_DEFAULT_BIT_DEPTH);

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp [hunk 4]
```diff
@@ -668,38 +667,74 @@ void W3DDisplay::init( void )
...
+			{
+				// TheSuperHackers @bugfix xezon 11/06/2025 Now tries a safe default resolution
+				// if the custom resolution did not succeed. This is unlikely to happen but is possible
+				// if the user writes an unsupported resolution into to the Option Preferences or if the
+				// graphics adapter does not support 800 x 600 to begin with.
+				const Int minW = 800;
+				const Int minH = 600;
+				Int xres = minW;
+				Int yres = minH;
+				Int bitDepth = 32;
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Int bitDepth = W3D_DISPLAY_DEFAULT_BIT_DEPTH;

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp [hunk 5]
```diff
@@ -668,38 +667,74 @@ void W3DDisplay::init( void )
...
+				setBitDepth( 16 );
+				break;
+			case 2:
+			{
+				// TheSuperHackers @bugfix xezon 11/06/2025 Now tries a safe default resolution
+				// if the custom resolution did not succeed. This is unlikely to happen but is possible
+				// if the user writes an unsupported resolution into to the Option Preferences or if the
+				// graphics adapter does not support 800 x 600 to begin with.
+				const Int minW = 800;
+				const Int minH = 600;
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: minW = MIN_DISPLAY_RESOLUTION_X;
minH = MIN_DISPLAY_RESOLUTOIN_Y;

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp [hunk 6]
```diff
@@ -668,38 +667,74 @@ void W3DDisplay::init( void )
...
+				{
+					getDisplayModeDescription(0, &xres, &yres, &bitDepth);
+					if (xres * yres >= minW * minH)
+						break; // Is good enough. Use it.
+				}
+				TheWritableGlobalData->m_xResolution = xres;
+				TheWritableGlobalData->m_yResolution = yres;
+				setWidth( xres );
+				setHeight( yres );
+				setBitDepth( 32 );
```
Comment (Mauller) [inline Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: setBitDepth(bitDepth);

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Fixed

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 5 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Fixed. Also fixed the typing error in RESOLUTOIN

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Fixed

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 3 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Fixed

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 4 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Fixed

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 6 above)
Comment (xezon) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: Fixed

File: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp (hunk 5 above)
Comment (Mauller) [reply Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp]: i did not notice that at first, i was just copying the defines

**Review by Mauller — APPROVED** [review]
Looks good.
