### PR TITLE
bugfix(module): A projectile can no longer be jammed multiple times

### LINKED ISSUE #1793: The ECM Tank Missile Deflection Behavior is Bugged
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When one or multiple ECM tanks are in place, missile deflection behavior becomes very erratic. 
Instead of cleanly deflecting incoming missiles, the missiles dance around unpredictably and sometimes disappear without hitting anything.

### Reproduction Steps

1. Build ECM tanks
2. Get opponent to build missile based units
3. Order enemy missile units to fire at your ECM tanks.
4. Missiles jitter, loop erratically, “dance” in midair, or disappear entirely without hitting anything.

### Additional Context

Comparison:
retail
https://github.com/user-attachments/assets/36a9dbf5-1a93-48d6-ac37-febfefa44bd8

No retail (Bugged)
https://github.com/user-attachments/assets/1307f845-82a3-44ea-b6a4-d59f6cefa85b

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1793

This change fixes a bug introduced by 5ba1741dd3335b085e8a36507ab3398687165fe8, which caused `isSubdued` to never return true for projectiles, resulting in continuous and repeated jamming by the ECM Tank's missile jammer.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/ActiveBody.cpp [hunk 1]
```diff
@@ -1323,6 +1323,9 @@ Bool ActiveBody::isSubdued() const
 #if RETAIL_COMPATIBLE_CRC
 	return m_maxHealth <= m_currentSubdualDamage;
 #else
+	if (getObject()->isKindOf(KINDOF_PROJECTILE))
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/ActiveBody.cpp:1328]: Better add a `@info` comment here that generously explains why projectiles are conditioned differently.
