### PR TITLE
bugfix(supply): Implement proportional supply bonus scaling to fix too generous money deposits for partial supply drops

### LINKED ISSUE #132: USA Chinook extra money drop is always 60$ no matter how big the base money load is
USA Chinook extra money drop is always 60 no matter how big the base money load is.

Meaning if it collects 600, then 660 are dropped.
And if it collects 300, then 360 are dropped.

The money upgrade from the strategy is required.

Ideally Chinook would always drop 10% of the collected cash.

### PR DESCRIPTION
**Pull request by tintinhamans**
* Resolves #132 

* Added a new `getMaxBoxes()` method to `SupplyTruckAIInterface` and implemented it in both `SupplyTruckAIUpdate` and `WorkerAIUpdate` to expose the configured maximum box capacity. 

* Updated `SupplyCenterDockUpdate::action` to snapshot the box count before unloading and scale the upgrade bonus proportionally to the delivered cargo.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp [hunk 1]
```diff
@@ -95,12 +95,33 @@ Bool SupplyCenterDockUpdate::action( Object* docker, Object *drone )
...
+			value += upgradedSupplyBoost * deliveredBoxes / maxBoxes; // Intentional integer truncation.
+		}
+		else
+		{
+			value += upgradedSupplyBoost; // Fallback when maxBoxes is not configured.
+		}
+	}
+#else
 	value += supplyTruckAI->getUpgradedSupplyBoost();
+#endif
```
[the remark this answers is not in the document]
Comment (tintinhamans) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: This is intentional and convention in this repo makes me lean towards not adding a comment - the guard is self-explanatory.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp [hunk 2]
```diff
@@ -95,12 +95,33 @@ Bool SupplyCenterDockUpdate::action( Object* docker, Object *drone )
...
 	// Add money boost from upgrades that give extra money
+#if !RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @bugfix arcticdolphin 09/03/2026 Scale supply bonus proportionally to delivered boxes.
+	Int upgradedSupplyBoost = supplyTruckAI->getUpgradedSupplyBoost();
+	if( upgradedSupplyBoost > 0 && deliveredBoxes > 0 )
+	{
+		Int maxBoxes = supplyTruckAI->getMaxBoxes();
+		if( maxBoxes > 0 )
+		{
+			value += upgradedSupplyBoost * deliveredBoxes / maxBoxes; // Intentional integer truncation.
```
Comment (Mauller) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: Is the idea that the supply boost is only applied up to maxBoxes?

So if we have a limit of 5 boxes but we deliver 7? we should only be applying the boost to 5 boxes?

Since the above will be under valuing the bonus if so.

Comment (Mauller) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: Nvm i misunderstood what it was doing.

But if max boxes is zero then should we be giving any kind of bonus since shouldn't it technically not be able to carry anything?

Comment (tintinhamans) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: Good point - units with maxBoxes 0 have no business docking supplies anyways.

File: GeneralsMD/Code/GameEngine/Include/GameLogic/Module/SupplyTruckAIUpdate.h [hunk 3]
```diff
@@ -161,6 +161,8 @@ class SupplyTruckAIInterface
 	// who look this up by name.
 public:
 	virtual Int getNumberBoxes() const = 0;
+	// TheSuperHackers @refactor arcticdolphin 09/03/2026 Expose MaxBoxes for proportional supply bonus.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Include/GameLogic/Module/SupplyTruckAIUpdate.h]: There are too many TheSuperHackers comments added

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp [hunk 4]
```diff
@@ -95,12 +95,26 @@ Bool SupplyCenterDockUpdate::action( Object* docker, Object *drone )
 		return FALSE;
 
 	UnsignedInt value = 0;
+#if !RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @refactor arcticdolphin 09/03/2026 Snapshot box count before unload loop.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: Superfluous comment

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp [hunk 5]
```diff
@@ -95,12 +95,26 @@ Bool SupplyCenterDockUpdate::action( Object* docker, Object *drone )
...
 		value += ownerPlayer->getSupplyBoxValue();
 
 	// Add money boost from upgrades that give extra money
+#if !RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @bugfix arcticdolphin 09/03/2026 Scale supply bonus proportionally to delivered boxes.
+	Int upgradedSupplyBoost = supplyTruckAI->getUpgradedSupplyBoost();
+	Int maxBoxes = supplyTruckAI->getMaxBoxes();
+	if( upgradedSupplyBoost > 0 && deliveredBoxes > 0 && maxBoxes > 0 )
+	{
+		value += upgradedSupplyBoost * deliveredBoxes / maxBoxes; // Intentional integer truncation.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: Maybe make order explicit with `(upgradedSupplyBoost * deliveredBoxes) / maxBoxes`

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp [hunk 6]
```diff
@@ -95,12 +95,26 @@ Bool SupplyCenterDockUpdate::action( Object* docker, Object *drone )
 		return FALSE;
 
 	UnsignedInt value = 0;
+#if !RETAIL_COMPATIBLE_CRC
+	// TheSuperHackers @refactor arcticdolphin 09/03/2026 Snapshot box count before unload loop.
+	Int deliveredBoxes = supplyTruckAI->getNumberBoxes();
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: I suggest implement a new function that returns the boosted cash value, and then get that here and add it to value below. Only requires one `RETAIL_COMPATIBLE_CRC` then.

```cpp
UnsignedInt getBoostedValue(supplyTruckAI)
{
#if RETAIL_COMPATIBLE_CRC
  return supplyTruckAI->getUpgradedSupplyBoost();
#else
  const Int maxBoxes = supplyTruckAI->getMaxBoxes();
  if (maxBoxes > 0)
  {
    const Int deliveredBoxes = supplyTruckAI->getNumberBoxes();
    const Int upgradedSupplyBoost = supplyTruckAI->getUpgradedSupplyBoost();
	return (upgradedSupplyBoost * deliveredBoxes) / maxBoxes; // Intentional integer truncation.
  }
  return 0;
#endif
}
```

**Comment by xezon** [comment]
Is this Zero Hour only?

**Comment by tintinhamans** [comment]
> Is this Zero Hour only?

No Supply Lines upgrade in Generals, only in ZH.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp [hunk 7]
```diff
@@ -95,13 +112,14 @@ Bool SupplyCenterDockUpdate::action( Object* docker, Object *drone )
 		return FALSE;
 
 	UnsignedInt value = 0;
+
+	// TheSuperHackers @refactor arcticdolphin 12/03/2026 Add money boost before unload consumes boxes.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Update/DockUpdate/SupplyCenterDockUpdate.cpp]: Superfluous comment. It simply is necessary to move it for the fix. No need to describe as refactor.

**Review by xezon — APPROVED** [review]

**Comment by xezon** [comment]
This needs rebase.
