### PR TITLE
bugfix(logic): Fix broken camera edge scroll after loading a savegame from the ingame menu

### LINKED ISSUE #1922: Can't move camera after reloading from replay while in-game
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Camera scrolling using mouse stops working. Bug does not appear to happen in retail version

### Reproduction Steps

Start skirmish, save a game, immediately load that save.
Does not happen when going back to the main menu and then loading the save.

### Additional Context

https://github.com/user-attachments/assets/dbe709e2-b60c-46ce-a1f9-9d0225188d90

### PR DESCRIPTION
**Pull request by stephanmeesters**
Closes #1922

The capture state of `TheMouse` includes a paused state, however this paused state is not currently reset when a new game is started. This PR addresses this by resetting the paused state in `GameLogic:reset()`.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 1]
```diff
@@ -512,6 +512,8 @@ void GameLogic::reset( void )
 	TheWeatherSetting = (WeatherSetting*) ws->deleteOverrides();
 
 	m_rankPointsToAddAtGameStart = 0;
+
+	TheMouse->onGamePaused(FALSE);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: The observation makes sense.

The implementation is not optimal. It will be better to replace

```cpp
	m_pauseFrame = 0;
	m_gamePaused = FALSE;
	m_pauseSound = FALSE;
	m_pauseMusic = FALSE;
	m_pauseInput = FALSE;
	m_inputEnabledMemory = TRUE;
	m_mouseVisibleMemory = TRUE;
	m_logicTimeScaleEnabledMemory = FALSE;
```
with
```cpp
	setGamePaused(FALSE);
	m_pauseFrame = 0;
	m_inputEnabledMemory = TRUE;
	m_mouseVisibleMemory = TRUE;
	m_logicTimeScaleEnabledMemory = FALSE;
```
higher up in this function and probably also in the `init` function.

This way other events can also properly update on pause state change.

Not sure if
```
	m_inputEnabledMemory = TRUE;
	m_mouseVisibleMemory = TRUE;
	m_logicTimeScaleEnabledMemory = FALSE;
```
still need to be reset then. I suspect it does not matter, but not sure.

Comment (stephanmeesters) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: I've made the requested changes and moved the memory resets above the `setGamePaused(FALSE)` so that things like `TheMouse->setVisibility` are updated as expected

Mouse edge scroll behavior, music and sound effects and mouse appear fine after the change. I do now notice a very short audio music glitch when loading the savegame ~probably~ (confirmed) because we're now calling `TheAudio->resumeAudio(AudioAffect_Music)` in reset()

**Comment by L3-M** [comment]
What is the current status of this change?
Successfully merging this pull request will not close the linked issues ( #1922 and #1999 ) with this current description. Please check GitHub Docs:

https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by stephanmeesters** [comment]
The description has been updated to link the issues.

I've been looking for a clean solution, the problem right now is that setGamePaused does not only affect state but also performs actions like resuming sounds and music, which now leads to an audio glitch when you do that in reset() or init(), which ideally is a function  only concerned about state.

Also setGamePaused deals with memory variables for restoring variables which does not apply for init() and reset().

So I think either we add some parameter to setGamePaused to indicate we only want state changes and no side effects, or we keep reset() much like it was before and i will do another pass to see that we properly reset everything. 

It was possible to clean up init() a bit by using reset() there see refactor commit.

**Comment by xezon** [comment]
Better make the deduplication a separate refactor change to reduce the complexity of this bug fix.

As for music bug, check why it happens and try to figure out an elegant way to avoid this.

**Comment by stephanmeesters** [comment]
Alright the deduplication commit is gone from this and I've added a parameter to `setGamePaused` to prevent resuming audio in `init()` and `reset()`.

The audio mishap was because reset would resume the music, and then milliseconds later the audiomanager subsystem would also reset which does a hard stop on all sounds

**Comment by xezon** [comment]
I am confused by this change. The title says that this concerns camera edge scrolling, but the code touches resume audio code. How does this relate?

**Comment by stephanmeesters** [comment]
In your first review you suggested using `setGamePaused` to reset the mouse, but this had the side-effect of resuming audio at a point of time you don't want it, so the extra code was added to avoid creating an audio bug.

In hindsight calling `setGamePaused` in `reset()` may not be so elegant so let me know if you want a simpler solution that doesn't touch audio

**Comment by xezon** [comment]
If we can not need `Bool allowResumeAudio` then that would be great. I would try to understand why this audio bug happens and then try to make it robust so that pausing or unpausing would not interfere with the audio muting in undesired ways. If we need multiple reasons for muting audio, then consider introducing mute flags that are reserved for different users.

For example `MuteAudio(MuteAudioReason_GamePaused)`, `MuteAudio(MuteAudioReason_GameLoading)`. Something like that.

Note I did not debug this issue so I cannot accurately say what the right course of action now is, but seeing the observations in this pull and the attempted workarounds make it look brittle.

**Comment by xezon** [comment]
What is the status of this change?

**Comment by stephanmeesters** [comment]
I will be focusing on this again. Probably will need a separate refactor PR for the audio

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 2]
```diff
@@ -387,14 +387,12 @@ void GameLogic::reset( void )
...
-	m_pauseFrame = 0;
-	m_gamePaused = FALSE;
-	m_pauseSound = FALSE;
-	m_pauseMusic = FALSE;
-	m_pauseInput = FALSE;
+	m_logicTimeScaleEnabledMemory = FALSE;
 	m_inputEnabledMemory = TRUE;
 	m_mouseVisibleMemory = TRUE;
-	m_logicTimeScaleEnabledMemory = FALSE;
+	setGamePaused(FALSE);
```
[the remark this answers is not in the document]
Comment (stephanmeesters) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: Wrong

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 3]
```diff
@@ -399,14 +399,12 @@ void GameLogic::reset( void )
...
-	m_pauseFrame = 0;
-	m_gamePaused = FALSE;
-	m_pauseSound = FALSE;
-	m_pauseMusic = FALSE;
-	m_pauseInput = FALSE;
+	m_logicTimeScaleEnabledMemory = FALSE;
 	m_inputEnabledMemory = TRUE;
 	m_mouseVisibleMemory = TRUE;
-	m_logicTimeScaleEnabledMemory = FALSE;
+	setGamePaused(FALSE);
```
[the remark this answers is not in the document]
Comment (stephanmeesters) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: wrong

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 4]
```diff
@@ -387,14 +387,11 @@ void GameLogic::reset( void )
...
+	m_pauseFrame = 0;
```
[the remark this answers is not in the document]
Comment (stephanmeesters) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: wrong

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 5]
```diff
@@ -399,14 +399,12 @@ void GameLogic::reset( void )
...
+	m_pauseFrame = 0;
+	TheAudio->stopAudio(AudioAffect_All);
```
[the remark this answers is not in the document]
Comment (stephanmeesters) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: The order of operations is always:

`TheGameLogic->reset()`

followed by

`TheSubsystemList->resetAll()` which includes a reset of the audio subsystem (hard killing all sounds).

No audio should continue playing during `TheGameLogic->reset()` but still the paused flags should be reset

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 6]
```diff
@@ -399,14 +399,12 @@ void GameLogic::reset( void )
...
```
[the remark this answers is not in the document]
Comment (stephanmeesters) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: See other comment

**Comment by stephanmeesters** [comment]
I think this should be good to go. The edge scrolling after loading is fixed, and I noticed no audio glitches anymore. Played through some skirmish/campaign/loads and sounds are normal

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 7]
```diff
@@ -397,16 +397,14 @@ void GameLogic::reset( void )
...
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: It is still not great.

It will now call

`TheAudio->resumeAudio((AudioAffect)(AudioAffect_All & ~AudioAffect_Music));`
`TheAudio->resumeAudio(AudioAffect_Music);`

and then

`TheAudio->stopAudio(AudioAffect_All);`

---

In your first commit you simply put:

`TheMouse->onGamePaused(FALSE);`

How about we just replace

`m_gamePaused = FALSE` with `pauseGameLogic(FALSE)` and
`m_pauseInput = FALSE` with `pauseGameInput(FALSE)`

Will that fix the problems without new bugs?

Comment (stephanmeesters) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp]: Can confirm this works well

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 8]
```diff
@@ -388,13 +388,13 @@ void GameLogic::reset( void )
...
 	m_pauseFrame = 0;
-	m_gamePaused = FALSE;
 	m_pauseSound = FALSE;
 	m_pauseMusic = FALSE;
-	m_pauseInput = FALSE;
 	m_inputEnabledMemory = TRUE;
 	m_mouseVisibleMemory = TRUE;
 	m_logicTimeScaleEnabledMemory = FALSE;
+	pauseGameLogic(FALSE);
+	pauseGameInput(FALSE);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:397]: This means

```
	m_inputEnabledMemory = TRUE;
	m_mouseVisibleMemory = TRUE;
```

is set before `pauseGameInput` is called. Is this correct? Should not be called before?

Comment (stephanmeesters) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:397]: I think it's alright, with `paused` set to false and `m_inputEnabledMemory` set to true it will trigger an additional call to `TheInGameUI->SetInputEnabled(TRUE)` however very shortly after it will call the reset function of `TheInGameUI` and reset any changes anyway

So it should be fine regardless of order but I’ll check if swapping is more efficient here in case `m_inputEnabledMemory` is often false

Comment (stephanmeesters) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:397]: I had another look still think it's OK: input=enabled and mouse=visible are the right default values to enforce, plus I was only ever able to see both `m_inputEnabledMemory = TRUE` and `m_mouseVisibleMemory = TRUE` in the debugger when entering reset.

**Review by xezon — APPROVED** [review]
