### PR TITLE
bugfix(fps): Fix and improve logic time step and render update decoupling

### LINKED ISSUE #1493: Buildings appear for a single frame when entering construction
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When a builder goes to construct a scaffold and the building's draw module becomes enabled, the building is visible in its completed state for a single frame. This does not occur in the retail build.

### Reproduction Steps

1. Start a new game or replay
2. Witness a builder go to construct a scaffold
3. Observe the building briefly appear for a single frame

### Additional Context

https://github.com/user-attachments/assets/5d13ddba-05d2-456a-9ada-41fe516a0051

### LINKED ISSUE #1505: Locomotor Physics Not Working & Other Visual Bugs
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Since updating to a commit date around 12/8, ground & air vehicles don't show dip/lift physics and structure barrels on the Firebase for instance flicker pivot & muzzle-flash.
Before the 12/8 date this happens mid-game, conspicuously when a jet is built but this is on a modded build whereas the former is on unmodded clean build.

Tested on normal & Steam versions.

### Reproduction Steps

1. Start new project in VS22
2. clone https://github.com/TheSuperHackers/GeneralsGameCode.git
3. build then Start

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
* Follow up for #1451
* Fixes #1493
* Fixes #1505

This change is a follow up for #1451 and the next iteration to decouple logic time step and render update.

The WW3D::Sync and Drawable update are now back in the render update. But timing wise both will be in sync with the logic step, not the render update, to ensure that their visuals represent the gameplay speed.

It is difficult to correctly adapt the locomotor physics to the render update, and that is why I have preserved the legacy behavior for now.

All calls to `TheMessageStream->appendMessage(GameMessage::MSG_CLEAR_GAME_DATA);` have been wrapped into a new function to unpause and unfreeze the game so that the message can be processed in the logic update. Originally the code did that with a hack, peeking into all messages to find the `GameMessage::MSG_CLEAR_GAME_DATA` and then unfreeze the time, but it was incomplete.

Originally, it was possible to freeze time in Network games (tested with CTRL+F10 in Debug), which stops logic updates and will trigger the Network disconnect (the local user cannot see it because the view looks frozen). Therefore I dedided to disable time freeze in Network games.

## TODO

- [x] Replicate in Generals

### CODE REVIEW

**Comment by Muntari** [comment]
is there a way to set these settings other than manually using shift+ctrl+numPLUS etc?

**Comment by xezon** [comment]
Not yet. It is still WIP feature due its complexity.

**Review by Mauller — APPROVED** [review]
Looks reasonably good overall, adds a lot of extra complexity but you can't easily get by some of it.

**Comment by xezon** [comment]
Replicated in Generals with some conflicts

```
D:\Projects\TheSuperHackers\GeneralsGameCode>FOR /F "delims=" %b IN ('git merge-base --fork-point main') DO git diff %b  1>changes.patch

D:\Projects\TheSuperHackers\GeneralsGameCode>git diff 5eaa6aa39609fa0f9f0c761e5e230b85dc6058e7  1>changes.patch

D:\Projects\TheSuperHackers\GeneralsGameCode>git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch
changes.patch:1150: space before tab in indent.
        //
changes.patch:1287: trailing whitespace.

Checking patch Generals/GameEngine/Include/Common/GameDefines.h...
error: Generals/GameEngine/Include/Common/GameDefines.h: No such file or directory
Checking patch Generals/Libraries/Source/WWVegas/WWLib/CMakeLists.txt...
error: Generals/Libraries/Source/WWVegas/WWLib/CMakeLists.txt: No such file or directory
Checking patch Generals/Libraries/Source/WWVegas/WWLib/WWCommon.h...
error: Generals/Libraries/Source/WWVegas/WWLib/WWCommon.h: No such file or directory
Checking patch Generals/Libraries/Source/WWVegas/WWLib/WWDefines.h...
Checking patch Generals/Libraries/Source/WWVegas/WWLib/always.h...
error: Generals/Libraries/Source/WWVegas/WWLib/always.h: No such file or directory
Checking patch Generals/Code/GameEngine/Include/Common/GameEngine.h...
Hunk #3 succeeded at 107 (offset 1 line).
Hunk #4 succeeded at 131 (offset 1 line).
Checking patch Generals/Code/GameEngine/Include/GameClient/Drawable.h...
Hunk #1 succeeded at 390 (offset -16 lines).
Hunk #2 succeeded at 600 (offset -40 lines).
error: while searching for:

        DrawableLocoInfo*       m_locoInfo;     // lazily allocated

        DynamicAudioEventRTS*   m_ambientSound;         ///< sound module for ambient sound (lazily allocated)

        Module** m_modules[NUM_DRAWABLE_MODULE_TYPES];

error: patch failed: Generals/Code/GameEngine/Include/GameClient/Drawable.h:685
Checking patch Generals/Code/GameEngine/Include/GameLogic/GameLogic.h...
Hunk #1 succeeded at 197 (offset -15 lines).
Hunk #2 succeeded at 206 (offset -15 lines).
Hunk #3 succeeded at 353 (offset -23 lines).
Checking patch Generals/Code/GameEngine/Include/GameNetwork/NetworkInterface.h...
Checking patch Generals/Code/GameEngine/Source/Common/GameEngine.cpp...
Hunk #1 succeeded at 260 (offset 2 lines).
Hunk #2 succeeded at 337 (offset -1 lines).
Hunk #3 succeeded at 401 (offset -1 lines).
Hunk #4 succeeded at 749 (offset -175 lines).
Hunk #5 succeeded at 847 (offset -175 lines).
Checking patch Generals/Code/GameEngine/Source/Common/Recorder.cpp...
Checking patch Generals/Code/GameEngine/Source/GameClient/Drawable.cpp...
error: while searching for:
#include "GameClient/Shadow.h"
#include "GameClient/GameText.h"

//#define KRIS_BRUTAL_HACK_FOR_AIRCRAFT_CARRIER_DEBUGGING
#ifdef KRIS_BRUTAL_HACK_FOR_AIRCRAFT_CARRIER_DEBUGGING
        #include "GameLogic/Module/ParkingPlaceBehavior.h"

error: patch failed: Generals/Code/GameEngine/Source/GameClient/Drawable.cpp:78
Hunk #2 succeeded at 372 (offset -38 lines).
Hunk #3 succeeded at 528 (offset -52 lines).
error: while searching for:
}

//-------------------------------------------------------------------------------------------------
void Drawable::applyPhysicsXform(Matrix3D* mtx)
{
        const Object *obj = getObject();

        if( !obj ||     obj->isDisabledByType( DISABLED_HELD ) || !TheGlobalData->m_showClientPhysics )
        {
                return;
        }

        Bool frozen = TheTacticalView->isTimeFrozen() && !TheTacticalView->isCameraMovementFinished();
        frozen = frozen || TheScriptEngine->isTimeFrozenDebug() || TheScriptEngine->isTimeFrozenScript();
        if (frozen)
                return;
        PhysicsXformInfo info;
        if (calcPhysicsXform(info))
        {
                mtx->Translate(0.0f, 0.0f, info.m_totalZ);
                mtx->Rotate_Y( info.m_totalPitch );
                mtx->Rotate_X( -info.m_totalRoll );
                mtx->Rotate_Z( info.m_totalYaw );

        }
}


error: patch failed: Generals/Code/GameEngine/Source/GameClient/Drawable.cpp:1375
error: while searching for:
//-------------------------------------------------------------------------------------------------
Bool Drawable::calcPhysicsXform(PhysicsXformInfo& info)
{
        const Object* obj = getObject();
        const AIUpdateInterface *ai = obj ? obj->getAIUpdateInterface() : NULL;
        Bool hasPhysicsXform = false;
        if (ai)
        {
                const Locomotor *locomotor = ai->getCurLocomotor();
                if (locomotor)
                {
                        switch (locomotor->getAppearance())
                        {
                                case LOCO_WHEELS_FOUR:
                                        calcPhysicsXformWheels(locomotor, info);
                                        hasPhysicsXform = true;
                                        break;
                                case LOCO_MOTORCYCLE:
                                        calcPhysicsXformMotorcycle( locomotor, info );
                                        hasPhysicsXform = TRUE;
                                        break;
                                case LOCO_TREADS:
                                        calcPhysicsXformTreads(locomotor, info);
                                        hasPhysicsXform = true;
                                        break;
                                case LOCO_HOVER:
                                case LOCO_WINGS:
                                        calcPhysicsXformHoverOrWings(locomotor, info);
                                        hasPhysicsXform = true;
                                        break;
                                case LOCO_THRUST:
                                        calcPhysicsXformThrust(locomotor, info);
                                        hasPhysicsXform = true;
                                        break;
                        }
                }
        }


error: patch failed: Generals/Code/GameEngine/Source/GameClient/Drawable.cpp:1403
error: while searching for:
//-------------------------------------------------------------------------------------------------
/** default draw is to just call the database defined draw */
//-------------------------------------------------------------------------------------------------
void Drawable::draw( View *view )
{

  if ( testTintStatus( TINT_STATUS_FRENZY ) == FALSE )
  {
    if ( getObject() && getObject()->isEffectivelyDead() )

error: patch failed: Generals/Code/GameEngine/Source/GameClient/Drawable.cpp:2623
Hunk #7 succeeded at 2217 (offset -449 lines).
Hunk #8 succeeded at 3664 (offset -518 lines).
Checking patch Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DownloadMenu.cpp...
Checking patch Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp...
error: while searching for:

        }
        if (TheGameLogic->isInGame())
                TheMessageStream->appendMessage( GameMessage::MSG_CLEAR_GAME_DATA );
}



error: patch failed: Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp:265
Checking patch Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp...
Checking patch Generals/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp...
Hunk #1 succeeded at 535 (offset -7 lines).
Hunk #2 succeeded at 547 (offset -7 lines).
Checking patch Generals/Code/GameEngine/Source/GameClient/GameClient.cpp...
Hunk #1 succeeded at 602 (offset -38 lines).
Checking patch Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp...
Hunk #1 succeeded at 3328 (offset -150 lines).
Checking patch Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp...
Hunk #1 succeeded at 4807 (offset -735 lines).
Checking patch Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp...
Hunk #1 succeeded at 241 (offset -11 lines).
Hunk #2 succeeded at 407 (offset -15 lines).
Hunk #3 succeeded at 450 (offset -13 lines).
Hunk #4 succeeded at 3158 (offset -531 lines).
Hunk #5 succeeded at 3166 (offset -531 lines).
Hunk #6 succeeded at 3645 (offset -552 lines).
Hunk #7 succeeded at 3711 (offset -552 lines).
Hunk #8 succeeded at 3753 (offset -552 lines).
Checking patch Generals/Code/GameEngine/Source/GameNetwork/Network.cpp...
error: while searching for:
        GameMessage *msg = TheMessageStream->appendMessage(GameMessage::MSG_SELF_DESTRUCT);
        msg->appendBooleanArgument(TRUE);

        TheMessageStream->appendMessage(GameMessage::MSG_CLEAR_GAME_DATA);
        m_localStatus = NETLOCALSTATUS_POSTGAME;
        DEBUG_LOG(("Network::quitGame - quitting game..."));
}

error: patch failed: Generals/Code/GameEngine/Source/GameNetwork/Network.cpp:930
Checking patch Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DDisplay.h...
Hunk #1 succeeded at 162 (offset -1 lines).
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordAircraftDraw.cpp...
error: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordAircraftDraw.cpp: No such file or directory
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordTankDraw.cpp...
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordTruckDraw.cpp...
error: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordTruckDraw.cpp: No such file or directory
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp...
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp...
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTruckDraw.cpp...
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp...
Hunk #1 succeeded at 1606 (offset -71 lines).
Hunk #2 succeeded at 1695 (offset -81 lines).
Hunk #3 succeeded at 1731 (offset -81 lines).
Checking patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp...
error: while searching for:

        //WST 11/12/2002 New camera shaker system
        // TheSuperHackers @tweak The camera shaker is now decoupled from the render update.
        const Real logicTimeScaleOverFpsRatio = TheGameEngine->getActualLogicTimeScaleOverFpsRatio();
        CameraShakerSystem.Timestep(TheW3DFrameLengthInMsec * logicTimeScaleOverFpsRatio);
        CameraShakerSystem.Update_Camera_Shaker(sourcePos, &m_shakerAngles);
        transform->Rotate_X(m_shakerAngles.X);
        transform->Rotate_Y(m_shakerAngles.Y);

error: patch failed: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:410
Hunk #2 succeeded at 555 (offset -145 lines).
Hunk #3 succeeded at 911 (offset -145 lines).
Hunk #4 succeeded at 936 (offset -145 lines).
Hunk #5 succeeded at 963 (offset -145 lines).
error: while searching for:


#ifdef DO_SEISMIC_SIMULATIONS
  // Give the terrain a chance to refresh animaing (Seismic) regions, if any.
  TheTerrainVisual->updateSeismicSimulations();
#endif
}

//-------------------------------------------------------------------------------------------------

error: patch failed: Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp:1408
Checking patch Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp...
Hunk #1 succeeded at 165 (offset -1 lines).
Hunk #2 succeeded at 1168 (offset 5 lines).
Checking patch Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h...
Applied patch Generals/Libraries/Source/WWVegas/WWLib/WWDefines.h cleanly.
Applied patch Generals/Code/GameEngine/Include/Common/GameEngine.h cleanly.
Applying patch Generals/Code/GameEngine/Include/GameClient/Drawable.h with 1 reject...
Hunk #1 applied cleanly.
Hunk #2 applied cleanly.
Rejected hunk #3.
Applied patch Generals/Code/GameEngine/Include/GameLogic/GameLogic.h cleanly.
Applied patch Generals/Code/GameEngine/Include/GameNetwork/NetworkInterface.h cleanly.
Applied patch Generals/Code/GameEngine/Source/Common/GameEngine.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/Common/Recorder.cpp cleanly.
Applying patch Generals/Code/GameEngine/Source/GameClient/Drawable.cpp with 4 rejects...
Rejected hunk #1.
Hunk #2 applied cleanly.
Hunk #3 applied cleanly.
Rejected hunk #4.
Rejected hunk #5.
Rejected hunk #6.
Hunk #7 applied cleanly.
Hunk #8 applied cleanly.
Applied patch Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/DownloadMenu.cpp cleanly.
Applying patch Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/MainMenu.cpp with 1 reject...
Rejected hunk #1.
Applied patch Generals/Code/GameEngine/Source/GameClient/GUI/GUICallbacks/Menus/QuitMenu.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/GameClient/GUI/Shell/Shell.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/GameClient/GameClient.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/GameClient/MessageStream/CommandXlat.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/GameLogic/ScriptEngine/ScriptEngine.cpp cleanly.
Applied patch Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp cleanly.
Applying patch Generals/Code/GameEngine/Source/GameNetwork/Network.cpp with 1 reject...
Hunk #1 applied cleanly.
Hunk #2 applied cleanly.
Hunk #3 applied cleanly.
Rejected hunk #4.
Applied patch Generals/Code/GameEngineDevice/Include/W3DDevice/GameClient/W3DDisplay.h cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DOverlordTankDraw.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTruckDraw.cpp cleanly.
Applied patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DDisplay.cpp cleanly.
Applying patch Generals/Code/GameEngineDevice/Source/W3DDevice/GameClient/W3DView.cpp with 2 rejects...
Rejected hunk #1.
Hunk #2 applied cleanly.
Hunk #3 applied cleanly.
Hunk #4 applied cleanly.
Hunk #5 applied cleanly.
Rejected hunk #6.
Applied patch Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.cpp cleanly.
Applied patch Generals/Code/Libraries/Source/WWVegas/WW3D2/ww3d.h cleanly.
```

**Comment by xezon** [comment]
Briefly tested in Generals and looked ok.

**Comment by MrS-ibra** [comment]
https://github.com/user-attachments/assets/2173404a-31c9-4aa5-8d58-ae9b6cdbb6f3

This PR appears to be causing flickering/visual bugs with buildings and some units, especially on uneven terrain as the video shows.

**Comment by xezon** [comment]
Dang. I explicitly addressed this exact same thing in this change but looks like I missed something. Checking.

**Comment by xezon** [comment]
I have addressed the above issues plus a bunch more things in new change #1579

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 1]
```diff
@@ -3693,22 +3697,6 @@ void GameLogic::update( void )
...
-		{
-			TheScriptEngine->forceUnfreezeTime();
-		}
-		else
-		{
-			/// @todo - make sure this never happens during a network game.  jba.
-			return;
-		}
-	}
-
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:3711]: Why was this removed?

File: GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp [hunk 2]
```diff
@@ -905,55 +1022,22 @@ void GameEngine::update( void )
 			TheCDManager->UPDATE();
 		}
 
-		TheGameLogic->preUpdate();
+		const Bool canUpdate = canUpdateGameLogic();
+		const Bool canUpdateLogic = canUpdate && !m_isGameHalted && !m_isTimeFrozen;
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp:1026]: Why does the game logic update depend on `m_isTimeFrozen` here instead of the removed bloc in the other comment?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp:1026]: Because the game is not supposed to advance when the time is frozen. Only the scripted camera can move around.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp (hunk 1 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:3711]: I think I deemed this no longer necessary with the new code. The new code is meant to make all the frozen time handlers at various places obsolete - to simplify it.

File: GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp (hunk 2 above)
Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp:1026]: The original implementation would update the the script engine and then check if the time is frozen before executing the remainder of the game logic update.

 The new implementation checks if the time is frozen before updating the script engine, and so it's delayed by a single frame AFAICT.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp:1026]: If you are looking for the scripted camera bug in network match, I already saw the issue in W3DDisplay but was not able to continue improvements because I got distracted by other things.

Comment (Caball009) [reply GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp:1026]: I'm looking at a mismatch that was introduced by this change, but it's probably easiest to continue the conversation in the PR that I intend to create for that.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/GameEngine.cpp:1026]: Oh okay. I do not know about the mismatch.
