### PR TITLE
bugfix(radar): Add hero radar objects into its own list to get rid of hero cache updates and its related issues

### LINKED ISSUE #1266: Hero Radar icon disappears for max 6 frames when leaving empty building
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Hero Radar icon disappears for max 6 frames when leaving empty building.

### Reproduction Steps

1. Get Hero
2. Garrison empty building
3. Evacuate
4. Look Radar

Hero Icon disappears briefly.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Merge after #1894
* Fixes #1266
* Closes #1823
* Follow up for #1035

This change adds hero radar objects into its own list to get rid of hero cache updates and its related issues. As a side benefit the local radar object list render update is now also marginally cheaper because it no longer needs to update the hero objects cache.

This change contains 4 commits, of which 3 are refactors to simplify some Radar functions to make them reusable in other call sites.

## TODO

- [x] Replicate in Generals

### CODE REVIEW

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp [hunk 1]
```diff
@@ -1018,6 +1018,8 @@ RadarObjectType W3DRadar::addObject( Object* obj )
 }
 
 //-------------------------------------------------------------------------------------------------
+// TheSuperHackers @bugfix xezon 05/07/2025 Now removes the cached hero immediately because
+// otherwise the object pointer could be dangling and used for a bit too long.
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp]: Should this be here?

File: Core/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp [hunk 2]
```diff
@@ -625,6 +625,52 @@ void W3DRadar::updateObjectTexture(TextureClass *texture)
 	renderObjectList( getLocalObjectList(), texture, TRUE );
 }
 
+//-------------------------------------------------------------------------------------------------
+//-------------------------------------------------------------------------------------------------
+Bool W3DRadar::canRenderObject( const RadarObject *rObj, const Player *localPlayer )
+{
+	if (rObj->isTemporarilyHidden())
+		return false;
```
Comment (Skyaero42) [inline Core/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp:636]: You are using if-brackets for every other if statement in this function, while the original code did not. For consistency, I would also use brackets here.

File: GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp [hunk 3]
```diff
@@ -62,56 +62,39 @@ Radar *TheRadar = NULL;  ///< the radar global singleton
...
+void Radar::deleteList( RadarObject **list )
 {
-	RadarObject *nextObject;
-
-	// delete entries from the local object list
-	while( m_localObjectList )
+	while( *list )
 	{
-
 		// get next object
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp]: Can remove comment as well. code is self-explanatory

File: GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp [hunk 4]
```diff
@@ -62,56 +62,39 @@ Radar *TheRadar = NULL;  ///< the radar global singleton
...
-		nextObject = m_localObjectList->friend_getNext();
+		RadarObject *nextObject = (*list)->friend_getNext();
 
 		// remove radar data from object
-		m_localObjectList->friend_getObject()->friend_setRadarData( NULL );
+		(*list)->friend_getObject()->friend_setRadarData( NULL );
 
 		// delete the head of the list
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp]: remove comment for self-explanatory code

File: GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp [hunk 5]
```diff
@@ -62,56 +62,39 @@ Radar *TheRadar = NULL;  ///< the radar global singleton
...
+	deleteList(&m_objectList);
+	deleteList(&m_localObjectList);
 
-	Object *obj;
-	for( obj = TheGameLogic->getFirstObject(); obj; obj = obj->getNextObject() )
+#ifdef DEBUG_CRASHING
+	for( Object *obj = TheGameLogic->getFirstObject(); obj; obj = obj->getNextObject() )
 	{
-
 		DEBUG_ASSERTCRASH( obj->friend_getRadarData() == NULL, ("oops") );
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp]: Maybe take the opportunity for a more descriptive assert message.

File: Core/GameEngine/Source/Common/System/Radar.cpp [hunk 6]
```diff
@@ -1375,13 +1382,13 @@ void Radar::xfer( Xfer *xfer )
...
 #else
-	XferVersion currentVersion = 2;
+	XferVersion currentVersion = 3;
 #endif
 	XferVersion version = currentVersion;
 	xfer->xferVersion( &version, currentVersion );
 
 	
-	if (version <= 1)
+	if (version < 2)
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/Radar.cpp]: Not sure if this is correct. So in newer versions, we don't want m_radarForceOn to be part of xfer?

File: Core/GameEngine/Source/Common/System/Radar.cpp [hunk 7]
```diff
@@ -1405,12 +1412,66 @@ void Radar::xfer( Xfer *xfer )
 		xfer->xferUser(&m_radarForceOn, sizeof(m_radarForceOn));
 	}
 
+	if (version < 3)
```
Comment (Skyaero42) [inline Core/GameEngine/Source/Common/System/Radar.cpp]: I don't think this is correct as this would apply m_localHeroObjectList xfer on the current version and not when we are in version 3.

**Review by Skyaero42 — CHANGES_REQUESTED** [review]

File: GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp (hunk 1 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp]: I temporarily added it because the original change had no comment why it was made.

File: Core/GameEngine/Source/Common/System/Radar.cpp (hunk 6 above)
Comment (xezon) [reply Core/GameEngine/Source/Common/System/Radar.cpp]: `version <= 1` is logically identical to `version < 2`. I will recheck if the rewrite makes sense. It somehow made sense when I looked at the code.

File: Core/GameEngine/Source/Common/System/Radar.cpp (hunk 7 above)
Comment (xezon) [reply Core/GameEngine/Source/Common/System/Radar.cpp]: This is correct.

File: Core/GameEngine/Source/Common/System/Radar.cpp (hunk 6 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/Radar.cpp]: oh wait, I see there was also an else statement. Must have missed that within github's quirks. Yes, this is correct then.

File: Core/GameEngine/Source/Common/System/Radar.cpp (hunk 7 above)
Comment (Skyaero42) [reply Core/GameEngine/Source/Common/System/Radar.cpp]: Ok, I see now what you are doing. Must have been tired last night.

File: GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp (hunk 5 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp]: Fixed

File: GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp (hunk 4 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp]: Comments removed.

File: GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp (hunk 3 above)
Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/Common/System/Radar.cpp]: Comments removed.

File: Core/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp (hunk 2 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/Common/System/W3DRadar.cpp:636]: Fixed

**Comment by xezon** [comment]
Rebased on main.

**Review by Skyaero42 — APPROVED** [review]
Looks good

**Comment by xezon** [comment]
Replicated in Generals without conflicts

File: Core/GameEngine/Source/Common/System/Radar.cpp (hunk 6 above)
Comment (xezon) [reply Core/GameEngine/Source/Common/System/Radar.cpp]: I reverted this edit to what it was before.
