### PR TITLE
[GEN][ZH] Fix character encoding issues in comments and key mappings

### LINKED ISSUE #436: Bad symbols in code
There is this code in a file:

```cpp
void Debug_Date_And_Time_Stamp ( void )
{
	//-------------------------------------------------------------------------
	//	tm_sec	- Seconds after minute (0 � 59)
	//	tm_min	- Minutes after hour (0 � 59)
	//	tm_hour	- Hours after midnight (0 � 23)
	//	tm_mday	- Day of month (1 � 31)
	//	tm_mon	- Month (0 � 11; January = 0)
	//	tm_year	- Year (current year minus 1900)
	//	tm_wday	- Day of week (0 � 6; Sunday = 0)
	//	tm_yday	- Day of year (0 � 365; January 1 = 0)
	//-------------------------------------------------------------------------
```

When I changed and saved this file it messed up the file diff on these lines with the bad characters.

We may want to
* Strip non ascii characters from code
* Add a .gitattributes to force proper text file rules

### PR DESCRIPTION
**Pull request by DevGeniusCode**
- Closes: #436 
Fix character encoding issues in comments and key mappings and enhance key mappings and symbols info

### CODE REVIEW

File: GeneralsMD/Code/Libraries/Source/debug/_pch.h [hunk 1]
```diff
@@ -22,7 +22,7 @@
 // $Revision: #1 $
 // $DateTime: 2003/07/03 11:55:26 $
 //
-// �2003 Electronic Arts
+// ©2003 Electronic Arts
```
Comment (DevGeniusCode) [inline GeneralsMD/Code/Libraries/Source/debug/_pch.h]: I have no idea how the symbols were destroyed in the last commit. and what append here
image

in direct file view is fine

image

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp [hunk 2]
```diff
@@ -700,7 +700,7 @@ void ReleaseCrash(const char *reason)
 
 	if (!GetRegistryLanguage().compareNoCase("german2") || !GetRegistryLanguage().compareNoCase("german") )
 	{
-		::MessageBox(NULL, "Es ist ein gravierender Fehler aufgetreten. Solche Fehler k�nnen durch viele verschiedene Dinge wie Viren, �berhitzte Hardware und Hardware, die den Mindestanforderungen des Spiels nicht entspricht, ausgel�st werden. Tipps zur Vorgehensweise findest du in den Foren unter www.generals.ea.com, Informationen zum Technischen Kundendienst im Handbuch zum Spiel.", "Fehler...", MB_OK|MB_TASKMODAL|MB_ICONERROR);
+		::MessageBox(NULL, "Es ist ein gravierender Fehler aufgetreten. Solche Fehler k\xf6nnen durch viele verschiedene Dinge wie Viren, \xfcberhitzte Hardware und Hardware, die den Mindestanforderungen des Spiels nicht entspricht, ausgel\xf6st werden. Tipps zur Vorgehensweise findest du in den Foren unter www.generals.ea.com, Informationen zum Technischen Kundendienst im Handbuch zum Spiel.", "Fehler...", MB_OK|MB_TASKMODAL|MB_ICONERROR);
```
Comment (DevGeniusCode) [inline Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: GitHub Action vs6 build error: at `\xfcberhitzte` aka `\xfc` aka `ü`
```
Generals/Code/GameEngine/CMakeFiles/g_gameengine.dir/Source/Common/System/Debug.cpp.obj
Debug.cpp
D:\a\GeneralsGameCode\GeneralsGameCode\Generals\Code\GameEngine\Source\Common\System\Debug.cpp(703) : error C2022: '64702' : too big for character

File: Generals/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp [hunk 3]
```diff
@@ -526,16 +526,16 @@ void Keyboard::initKeyNames( void )
...
 			_set_keyname_(L'-',				L'_',				L'\0',	KEY_SLASH  );
 
-			_set_keyname_(0x00FC,			0x00DC,			L'\0',	KEY_LBRACKET  );		//��
+			_set_keyname_(0x00FC,			0x00DC,			L'\0',	KEY_LBRACKET  );		//üÜ (umlaut u)
 			_set_keyname_(L'+',				L'*',				L'~',		KEY_RBRACKET  );
 
-			_set_keyname_(0x00F6,			0x00D6,			L'\0',	KEY_SEMICOLON  );		//��
-			_set_keyname_(0x00E4,			0x00C4,			L'\0',	KEY_APOSTROPHE  );	//��
-			_set_keyname_(L'^',				0x00B0,			L'\0',	KEY_TICK  );				//�
+			_set_keyname_(0x00F6,			0x00D6,			L'\0',	KEY_SEMICOLON  );		//öÖ (umlaut o)
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp:532]: The characters look strange. It looked different before.

File: Generals/Code/Tools/Autorun/TTFont.cpp [hunk 4]
```diff
@@ -514,7 +514,7 @@ UINT TTFontClass::Get_Double_Byte_Char	( const char *string, int *num_bytes ) co
 
 	//--------------------------------------------------------------------------
 	// The IsDBCSLeadByte function determines whether a character is a 
-	// lead byte � that is, the first byte of a character in a double-byte 
+	// lead byte — that is, the first byte of a character in a double-byte
```
Comment (xezon) [inline Generals/Code/Tools/Autorun/TTFont.cpp]: minus -

File: Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp [hunk 5]
```diff
@@ -1068,7 +1068,7 @@ void CPUDetectClass::Init_Processor_Log()
 	}
 
 	if (CPUDetectClass::Get_L1_Instruction_Trace_Cache_Size()) {
-		SYSLOG(("L1 Instruction Trace Cache: %d way set associative, %dk �OPs\r\n",
+		SYSLOG(("L1 Instruction Trace Cache: %d way set associative, %dk \xb5OPs\r\n",
```
Comment (xezon) [inline Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp]: micro-OPs

File: Generals/Code/Tools/Autorun/autorun.cpp [hunk 6]
```diff
@@ -5253,14 +5253,14 @@ unsigned int LaunchObjectClass::Launch ( void )
...
+	//	tm_sec	- Seconds after minute (0 – 59)
+	//	tm_min	- Minutes after hour (0 – 59)
+	//	tm_hour	- Hours after midnight (0 – 23)
+	//	tm_mday	- Day of month (1 – 31)
+	//	tm_mon	- Month (0 – 11; January = 0)
 	//	tm_year	- Year (current year minus 1900)
-	//	tm_wday	- Day of week (0 � 6; Sunday = 0)
-	//	tm_yday	- Day of year (0 � 365; January 1 = 0)
+	//	tm_wday	- Day of week (0 – 6; Sunday = 0)
+	//	tm_yday	- Day of year (0 – 365; January 1 = 0)
```
Comment (xezon) [inline Generals/Code/Tools/Autorun/autorun.cpp]: minus -

File: GeneralsMD/Code/Libraries/Include/rts/debug.h [hunk 7]
```diff
@@ -22,7 +22,7 @@
 // $Revision: #1 $
 // $DateTime: 2003/07/03 11:55:26 $
 //
-// �2003 Electronic Arts
+// ©2003 Electronic Arts
```
Comment (xezon) [inline GeneralsMD/Code/Libraries/Include/rts/debug.h]: (c)

File: Generals/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp (hunk 3 above)
Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp:532]: What do u mean?
https://www.compart.com/en/unicode/U+00D6
(It's a lowercase letter and an uppercase letter.)

File: Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp (hunk 5 above)
Comment (zzambers) [reply Generals/Code/Libraries/Source/WWVegas/WWLib/cpudetect.cpp]: or maybe uOPs?

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp (hunk 2 above)
Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: 64702 (10) is FCBE (16). Seems like compiler interprets additional 2 letters as hex digits (as they happen to be valid hex). Maybe octal escape sequence could be used here instead.

Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Thanks, it's compiling now, although I don't know what the rendering will be.

**Comment by DevGeniusCode** [comment]
Updated

File: Generals/Code/Tools/Autorun/TTFont.cpp (hunk 4 above)
Comment (DevGeniusCode) [reply Generals/Code/Tools/Autorun/TTFont.cpp]: Now I saw your YouTube video, I thought you meant to add the word `minus` but I now understand that you only meant a minus sign, due to the display being corrupted for some unknown reason, (here it is not corrupted)

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp (hunk 2 above)
Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: I see you have changed it to `\u00FCrhitzte`, but you have removed "be" letters, which were part of the word (they were just interpreted as hex). I am afraid It will render as `ürhitzte` instead of `überhitzte`. (Alternatively you could use `\374berhitzte`)

Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Yes, you are right, I missed that. Thanks!

Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Also `\uxxxx` probably should not be used here, as it produces `UTF-8` char sequence AFAIK. I think we want resulting char sequences to be in `WINDOWS-1252` encoding here, so hex or octal sequences should be used here to produce "RAW" bytes.

File: Generals/Code/Tools/Autorun/TTFont.cpp (hunk 4 above)
Comment (xezon) [reply Generals/Code/Tools/Autorun/TTFont.cpp]: Yes basically use ascii minus sign instead of fancy long dash.

File: GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp [hunk 8]
```diff
@@ -447,8 +447,8 @@ void Keyboard::initKeyNames( void )
 
 			_set_keyname_(L'1',				L'!',				L'\0',	KEY_1  );
 			_set_keyname_(L'2',				L'\"',			L'\0',	KEY_2  );
-			_set_keyname_(L'3',				0x00A3,			L'\0',	KEY_3  );	//�
-			_set_keyname_(L'4',				L'$',				L'�',		KEY_4  );
+			_set_keyname_(L'3',				0x00A3,			L'\0',	KEY_3  );	//£ GBP SIGN
+			_set_keyname_(L'4',				L'$',				L'\x20ac',		KEY_4  ); // € EUR SIGN
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp:451]: Are these comments now utf-8?

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp [hunk 9]
```diff
@@ -700,7 +700,7 @@ void ReleaseCrash(const char *reason)
 
 	if (!GetRegistryLanguage().compareNoCase("german2") || !GetRegistryLanguage().compareNoCase("german") )
 	{
-		::MessageBox(NULL, "Es ist ein gravierender Fehler aufgetreten. Solche Fehler k�nnen durch viele verschiedene Dinge wie Viren, �berhitzte Hardware und Hardware, die den Mindestanforderungen des Spiels nicht entspricht, ausgel�st werden. Tipps zur Vorgehensweise findest du in den Foren unter www.generals.ea.com, Informationen zum Technischen Kundendienst im Handbuch zum Spiel.", "Fehler...", MB_OK|MB_TASKMODAL|MB_ICONERROR);
+		::MessageBox(NULL, "Es ist ein gravierender Fehler aufgetreten. Solche Fehler k\xf6nnen durch viele verschiedene Dinge wie Viren, \u00FCrhitzte Hardware und Hardware, die den Mindestanforderungen des Spiels nicht entspricht, ausgel\xf6st werden. Tipps zur Vorgehensweise findest du in den Foren unter www.generals.ea.com, Informationen zum Technischen Kundendienst im Handbuch zum Spiel.", "Fehler...", MB_OK|MB_TASKMODAL|MB_ICONERROR);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Is there a reason why one is `\x` and the other `\u`?

File: GeneralsMD/Code/Tools/Autorun/autorun.cpp [hunk 10]
```diff
@@ -5290,14 +5290,14 @@ unsigned int LaunchObjectClass::Launch ( void )
...
+	//	tm_sec	- Seconds after minute (0 – 59)
+	//	tm_min	- Minutes after hour (0 – 59)
+	//	tm_hour	- Hours after midnight (0 – 23)
+	//	tm_mday	- Day of month (1 – 31)
+	//	tm_mon	- Month (0 – 11; January = 0)
 	//	tm_year	- Year (current year minus 1900)
-	//	tm_wday	- Day of week (0 � 6; Sunday = 0)
-	//	tm_yday	- Day of year (0 � 365; January 1 = 0)
+	//	tm_wday	- Day of week (0 – 6; Sunday = 0)
+	//	tm_yday	- Day of year (0 – 365; January 1 = 0)
```
Comment (xezon) [inline GeneralsMD/Code/Tools/Autorun/autorun.cpp]: This still look like a non-ascii character.

File: GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp (hunk 8 above)
Comment (DevGeniusCode) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp:451]: Yes

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp (hunk 2 above)
Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: So `\374berhitzte` is better? is this resulting the char to be in WIN-1252 as `ü`?

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp (hunk 9 above)
Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: See the discussion above with zzambers

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Yes please test this dialog text to make sure it does draw correctly.

Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: I can confirm that it displays correctly in English and German, but in non-standard Unicode environments it will display incorrectly, in my opinion this is negligible and can be ignored.

Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: > So `\374berhitzte` is better? is this resulting the char to be in WIN-1252 as `ü`?

AFAIK normal string in quotes  c/c++ without prefix, behaves following way:
- it only really supports printable ascii as literal characters (everything other is implementation defined)
- escape sequences `\ooo` and `\xn...` just add single char (in c/c++ sense; aka byte) with corresponding numerical value (written as base 8 or base 16) to char sequence without further processing
- escape sequence `\unnnn` is later addition, where you request unicode code point from compiler, which may result in one or more chars (chars in c/c++ sense, aka bytes; e.g. unicode code point can have 1-4 chars (bytes) in utf-8), I am not sure if spec specifies encoding, which should be used by compiler, on my system it is utf-8

Note that c and c++ predate unicode.

Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: So to make code portable (i.e. not dependent on system encoding of build machine), we just want make use of raw chars (bytes) which result in correct string with `windows-1252` encoding.

I think there are 2 options how to deal with that problematic `ü` in `überhitzte`:
- use octal escape sequence `"\374berhitzte"`
- use hex sequence but split to multiple quoted parts i.e. `"\xfc""berhitzte"` (so that compiler stops interpreting hex digits after fc)

Comment (DevGeniusCode) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: I did use the first octal option, although in Unicode environments like Arabic an incorrect character will be displayed, but in my opinion this is negligible because the message should only be displayed if the user is German.

Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Actually you can find problem, you are facing [here on cppreference](https://en.cppreference.com/w/cpp/language/string_literal#Notes) in Notes section. they used latter option as workaround:
```
//const char* p = "\xfff"; // error: hexadecimal escape sequence out of range
const char* p = "\xff""f"; // OK: the literal is const char[3] holding {'\xff','f','\0'}
```

File: GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp (hunk 8 above)
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp:451]: So before it was a Windows Codepage symbol and now it is a Unicode symbol? Does this work correctly?

Comment (DevGeniusCode) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Input/Keyboard.cpp:451]: yes, @tomsons26 confirmed it.

**Comment by xezon** [comment]
This change needs to be rebased.

**Review by xezon — APPROVED** [review]

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp (hunk 2 above)
Comment (zzambers) [reply Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: > I can confirm that it displays correctly in English and German, but in non-standard Unicode environments it will display incorrectly, in my opinion this is negligible and can be ignored.

> I did use the first octal option, although in Unicode environments like Arabic an incorrect character will be displayed, but in my opinion this is negligible because the message should only be displayed if the user is German.

Yes, that is inherent limitation of using win32 functions with "narrow" strings, which make use of so called "ANSI" code pages by default. Game would need to use win32 functions with "wide" strings to display same non-ASCII string consistently through different locales. However, I think, this particular message should only ever display with german locale set (so appropriate code page should be in place)
