### PR TITLE
fix(targa): Fix TGA2 footer signature truncation by using strncpy

### LINKED ISSUE #1828: Refactor strlcpy for strcpy with a static_assert were possible in WWVegas
Something is wrong with the following line. Perhaps this was meant to be strcpy. Buffer has same length as TGA2_SIGNATURE.
```cpp
strlcpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature));
```

There are more copies that can use static_assert's instead.
```cpp
strlcpy(Name,w3d_data.Name,sizeof(Name));
```
```cpp
strlcpy(header.Name,AnimName,sizeof(header.Name));
strlcpy(header.HierarchyName,HierarchyName,sizeof(header.HierarchyName));
```
```cpp
strlcpy(Name, aheader.HierarchyName, ARRAY_SIZE(Name));
strlcat(Name, ".", ARRAY_SIZE(Name));
strlcat(Name, aheader.Name, ARRAY_SIZE(Name));
```
```cpp
strlcpy(HierarchyName,aheader.HierarchyName,W3D_NAME_LEN);
```

WWVegas code needs another review pass to use static_assert + strcpy instead of strlcpy where so possible.

### PR DESCRIPTION
**Pull request by bobtista**
* Follow up for #1808
* Fixes #1828

PR 1808 fixed most of this issue, but this PR addresses a remaining item

`strlcpy` was used to write the 16-byte TGA 2.0 footer signature `"TRUEVISION-XFILE"` into `footer.Signature[16]`. Because `strlcpy` always null-terminates, it could only copy 15 characters before writing `\0`, silently truncating the last character of the signature field.

The `Signature` field is a fixed-size binary field per the TGA 2.0 spec — it is not null-terminated (reads confirm this by using `strncmp(..., 16)`). `strncpy` with `n` equal to the field size copies all 16 bytes without writing a null terminator, which is the correct behavior here. A `static_assert` is added to guarantee at compile time that the signature constant and the field are the same size.

This matches the behavior already in `Core/Tools/WW3D/max2w3d/TARGA.cpp` which uses `strncpy(..., 16)` for the same purpose.

### CODE REVIEW

File: Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp [hunk 1]
```diff
@@ -735,7 +735,7 @@ long Targa::Save(const char* name, long flags, bool addextension)
 		if (!error)
 			{
 			footer.Developer = 0;
-			strlcpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature));
+			memcpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature)); // TheSuperHackers @bugfix bobtista 02/04/2026 Use memcpy to copy all 16 bytes of the TGA2 signature without null termination, as the field is a fixed-size binary field per the TGA 2.0 spec
```
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: Comment is superfluous.

Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: Static assert that length of `TGA2_SIGNATURE` matches length of `footer.Signature`.

Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: This originally was

`strncpy(footer.Signature, TGA2_SIGNATURE, 16);`

It probably should be

`strncpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature));`

File: Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: Check why this is still using `strcpy`. It was supposed to be changed with #1533

Comment (bobtista) [reply Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: strlcpy_t looks good here, vs hard coding the size

File: Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp [hunk 2]
```diff
@@ -713,7 +713,7 @@ long Targa::Save(const char* name, long flags, bool addextension)
 			if (!error) {
 
 				mExtension.ExtSize = 495;
-				strcpy(mExtension.SoftID, "Denzil's Targa Code");
+				strlcpy_t(mExtension.SoftID, "Denzil's Targa Code"); // TheSuperHackers @fix bobtista 03/04/2026 Replace strcpy with strlcpy_t
```
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: Remove comments. It is too verbose.

File: Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp [hunk 3]
```diff
@@ -735,7 +735,8 @@ long Targa::Save(const char* name, long flags, bool addextension)
 		if (!error)
 			{
 			footer.Developer = 0;
-			memcpy(footer.Signature, TGA2_SIGNATURE, sizeof(footer.Signature)); // TheSuperHackers @bugfix bobtista 02/04/2026 Use memcpy to copy all 16 bytes of the TGA2 signature without null termination, as the field is a fixed-size binary field per the TGA 2.0 spec
+			static_assert(sizeof(TGA2_SIGNATURE) - 1 == sizeof(footer.Signature), "TGA2 signature length mismatch"); // TheSuperHackers @bugfix bobtista 02/04/2026 Verify TGA2 signature sizes match
```
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: Remove comments. It is too verbose.

File: Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp (hunk 2 above)
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: Compile error.

File: Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp
Comment (xezon) [reply Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: strlcpy was used here before, but then somehow was reverted to strcpy again.

Comment (bobtista) [reply Core/Libraries/Source/WWVegas/WWLib/TARGA.cpp]: It was changed in #1887, but lacked the assert. strlcopy with the sizeof should be good right?

**Review by xezon — APPROVED** [review]
The title and description need updating.

**Comment by bobtista** [comment]
> The title and description need updating.

done
