### PR TITLE
bugfix(upgrade): Fix fake GLA structures losing their selection and grouping when upgraded to real structures

### LINKED ISSUE #36: GLA Fake Building loses group key assignment after upgrading to real building
GLA Fake Building loses group key assignment after upgrading to real building. Likely code issue.

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #36

This change preserves selection and grouping for upgraded fake buildings. In the retail game, players have to reselect and regroup a building that has upgraded from a fake one, which is frustrating and requires meaningless micromanagement.

This change is fully retail compatible as it sends the same commands to the message stream as if the player had executed them manually.

### Before
The building is deselected and the group is lost

https://github.com/user-attachments/assets/9520ba4f-5e7b-4565-add2-5d32f5b87197

### After
The building stays selected and the group is preserved

https://github.com/user-attachments/assets/c2de5adc-11b6-46f4-ac86-4f05c341378b

Note: If a player has an opponent's fake building selected at the time it upgrades, they can see the building flash as it is reselected; though this is still preferable and less conspicuous than losing the selection as previously. It might be worth investigating a NO_FEEDBACK variant of `MSG_CREATE_SELECTED_GROUP` at some point in the future if this is a concern.

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 1]
```diff
@@ -105,6 +110,23 @@ void ReplaceObjectUpgrade::upgradeImplementation( )
 	if( replacementObject->getControllingPlayer() )
 	{
 		replacementObject->getControllingPlayer()->onStructureConstructionComplete(me, replacementObject, FALSE);
+
+		if (oldObjectSelected)
+		{
+			GameMessage* msg = TheMessageStream->appendMessage(GameMessage::MSG_CREATE_SELECTED_GROUP_NO_SOUND);
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:124]: There is a lot of logic in the handling of MSG_CREATE_SLECTED_GROUP_NO_SOUND that is not applicable when selecting a building. I think something like this should work:

```cpp
TheGameLogic->selectObject(obj, true, player->getPlayerMask();
```

instead of sending a message.
which would prevent the selection delay.

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:124]: If you check the previous commits I did have that logic at one point, but it breaks retail compatibility and I decided against having two implementations due to the complexity. What selection delay have you observed?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 2]
```diff
@@ -83,6 +84,10 @@ void ReplaceObjectUpgrade::upgradeImplementation( )
 		return;
 	}
 
+	Drawable* selectedDrawable = TheInGameUI->getFirstSelectedDrawable();
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp]: Shouldn't it be replicated in Generals?

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp (hunk 1 above)
Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:124]: Another problem with the `TheGameLogic->selectObject` logic is that if the identical selection is not processed for all players, it mismatches. And as the selection is dependent on the _local_ player having the fake structure selected, there's no way for the same call to be processed for all players.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp (hunk 2 above)
Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp]: Fake structures do not exist there.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp (hunk 1 above)
Comment (Skyaero42) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:124]: Makes sense.

**Review by roossienb — APPROVED** [review]

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 3]
```diff
@@ -105,6 +110,23 @@ void ReplaceObjectUpgrade::upgradeImplementation( )
 	if( replacementObject->getControllingPlayer() )
 	{
 		replacementObject->getControllingPlayer()->onStructureConstructionComplete(me, replacementObject, FALSE);
+
+		if (oldObjectSelected)
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:122]: These 2 fixes can be commented.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 4]
```diff
@@ -83,6 +84,10 @@ void ReplaceObjectUpgrade::upgradeImplementation( )
 		return;
 	}
 
+	Drawable* selectedDrawable = TheInGameUI->getFirstSelectedDrawable();
+	Bool oldObjectSelected = selectedDrawable && selectedDrawable->getID() == me->getDrawable()->getID();
+	Int oldObjectSquadNumber = me->getControllingPlayer()->getSquadNumberForObject(me);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp]: I suggest put the code starting from `Object *me = getObject();` to ending with `TheGameLogic->destroyObject(me);` into a scope, because the destroyed pointers will be dangling after this.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 5]
```diff
@@ -70,23 +71,34 @@ ReplaceObjectUpgrade::~ReplaceObjectUpgrade( void )
 void ReplaceObjectUpgrade::upgradeImplementation( )
 {
 	const ReplaceObjectUpgradeModuleData *data = getReplaceObjectUpgradeModuleData();
+	const ThingTemplate* replacementTemplate = TheThingFactory->findTemplate(data->m_replaceObjectName);
 
-	Object *me = getObject();
+	Bool oldObjectSelected;
+	Int oldObjectSquadNumber;
+	Matrix3D myMatrix;
+	Team* myTeam = NULL;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp]: Can be left uninitialized like the others.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 6]
```diff
@@ -104,7 +116,26 @@ void ReplaceObjectUpgrade::upgradeImplementation( )
 
 	if( replacementObject->getControllingPlayer() )
 	{
-		replacementObject->getControllingPlayer()->onStructureConstructionComplete(me, replacementObject, FALSE);
+		replacementObject->getControllingPlayer()->onStructureConstructionComplete(NULL, replacementObject, FALSE);
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:119]: Oh wow so it passed the dangling pointer here before... but it was never dereferenced, so no bug.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp [hunk 7]
```diff
@@ -104,7 +116,26 @@ void ReplaceObjectUpgrade::upgradeImplementation( )
...
+			GameMessage* msg = TheMessageStream->appendMessage(GameMessage::MSG_CREATE_SELECTED_GROUP_NO_SOUND);
+			msg->appendBooleanArgument(TRUE);
+			msg->appendObjectIDArgument(replacementObject->getID());
+			TheInGameUI->selectDrawable(replacementObject->getDrawable());
+		}
+
+		// TheSuperHackers @bugfix Stubbjax 26/05/2025 If the old object was grouped, group the new one.
+		if (oldObjectSquadNumber != NO_HOTKEY_SQUAD)
+		{
+			if (replacementObject->isLocallyControlled())
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: What does this test help with?

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: The `isLocallyControlled` check? It stops the object being grouped for other players.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: In what situation would that happen?

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: Player A owns a fake Barracks and it is assigned to group 1. When the fake Barracks is upgraded, Player A determines that the old object is in group 1, and so assigns group 1 to the new Barracks. However, Player B also determines that the old object is in group 1 - but we don't want Player B to assign group 1 to Player A's real Barracks, so we check for local.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: Ok makes sense. How about make the building reselection also dependent on `isLocallyControlled`?

```cpp
if (isLocallyControlled())
{
  select();
  createTeam();
}
```

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: If the opponent has the fake structure selected when it upgrades, don't we want them to maintain their selection too?

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Upgrade/ReplaceObjectUpgrade.cpp:133]: Oh ok.

**Review by xezon — APPROVED** [review]
