### PR TITLE
bugfix(registry): Prioritize HKEY_CURRENT_USER registry reads and writes over HKEY_LOCAL_MACHINE to prevent inaccessible data

### LINKED ISSUE #1059: GetStringFromRegistry can fail to read from the correct registry location depending on process admin privileges
GetStringFromRegistry can fail to read from the correct location depending on process admin privileges. This is reproducible with the HTTP Proxy setting in the Options Menu. When using the game once as Admin, then the game will write a Proxy key into HKEY_LOCAL_MACHINE. Then when using the game without Admin privileges, the game will write a Proxy key into HKEY_CURRENT_USER. But when reading, it will be able to read from HKEY_LOCAL_MACHINE first. This is a bug.

```cpp
bool GetStringFromRegistry(std::string path, std::string key, std::string& val)
{
#if RTS_GENERALS
	std::string fullPath = "SOFTWARE\\Electronic Arts\\EA Games\\Generals";
#elif RTS_ZEROHOUR
	std::string fullPath = "SOFTWARE\\Electronic Arts\\EA Games\\Command and Conquer Generals Zero Hour";
#endif

	fullPath.append(path);

// PROBLEMATICO

	if (getStringFromRegistry(HKEY_LOCAL_MACHINE, fullPath.c_str(), key.c_str(), val))
	{
		return true;
	}

	return getStringFromRegistry(HKEY_CURRENT_USER, fullPath.c_str(), key.c_str(), val);
}
```

```cpp
bool SetStringInRegistry( std::string path, std::string key, std::string val)
{
#if RTS_GENERALS
	std::string fullPath = "SOFTWARE\\Electronic Arts\\EA Games\\Generals";
#elif RTS_ZEROHOUR
	std::string fullPath = "SOFTWARE\\Electronic Arts\\EA Games\\Command and Conquer Generals Zero Hour";
#endif
	fullPath.append(path);

	if (setStringInRegistry( HKEY_LOCAL_MACHINE, fullPath, key, val))
		return true;

	return setStringInRegistry( HKEY_CURRENT_USER, fullPath, key, val );
}
```

### PR DESCRIPTION
**Pull request by bobtista**
- Closes #1059

Per-user settings (e.g. HTTP Proxy) should always go in HKEY_CURRENT_USER.

Flips both read and write priority to prefer HKCU over HKLM across all registry helpers, with HKLM as fallback. This prevents stale HKCU values when the game is run with admin privileges.

### CODE REVIEW

**Comment by Skyaero42** [comment]
Imagine the following:
- I install the game (e.g. through Steam) for windows user1
- I play the game (key is in CURRENT_USER)
- I login as user2 in windows
- I start the game.

could this be an issue, or is there a key generated for user2 as well?

**Comment by bobtista** [comment]
> Imagine the following:
> 
> * I install the game (e.g. through Steam) for windows user1
> * I play the game (key is in CURRENT_USER)
> * I login as user2 in windows
> * I start the game.
> 
> could this be an issue, or is there a key generated for user2 as well?

Ok changed it so:
Reads (HKCU → HKLM): Users can override machine-wide defaults; if no user override exists, fall back to the shared value.
Writes (HKLM → HKCU): Preserves the original behavior—try global first, then per-user if needed.

This is good enough for this issue/change IMHO - Eventually, we should probably have intentional “is this setting global or per-user?” code in the game logic rather than relying on whether the user ran the game as admin or not.

File: Core/Libraries/Source/WWVegas/WWDownload/registry.cpp [hunk 1]
```diff
@@ -137,12 +137,12 @@ bool GetUnsignedIntFromRegistry(std::string path, std::string key, unsigned int&
 #endif
 
 	fullPath.append(path);
-	if (getUnsignedIntFromRegistry(HKEY_LOCAL_MACHINE, fullPath.c_str(), key.c_str(), val))
+	if (getUnsignedIntFromRegistry(HKEY_CURRENT_USER, fullPath.c_str(), key.c_str(), val))
```
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWDownload/registry.cpp:140]: If I am not mistaken this will be wrong when HKEY_CURRENT_USER var is set to something and game is run with Admin privileges and writing to HKEY_LOCAL_MACHINE. Then it will not update HKEY_CURRENT_USER and its value never changes.

Comment (bobtista) [reply Core/Libraries/Source/WWVegas/WWDownload/registry.cpp:140]: Yeah, the write functions (SetStringInRegistry, SetUnsignedIntInRegistry) were still preferring HKLM, so running as admin would write to HKLM while reads would return the stale HKCU value. Fixed by flipping the write priority to also prefer HKCU, matching the read side. So now both SetStringInRegistry and SetUnsignedIntInRegistry to try HKCU first

File: Core/Libraries/Source/WWVegas/WWDownload/registry.cpp [hunk 2]
```diff
@@ -169,9 +170,10 @@ bool SetUnsignedIntInRegistry( std::string path, std::string key, unsigned int v
 #endif
 	fullPath.append(path);
 
-	if (setUnsignedIntInRegistry( HKEY_LOCAL_MACHINE, fullPath, key, val))
+	// TheSuperHackers @fix bobtista 12/02/2026 Prefer HKCU for writes to match read priority
+	if (setUnsignedIntInRegistry( HKEY_CURRENT_USER, fullPath, key, val))
 		return true;
 
-	return setUnsignedIntInRegistry( HKEY_CURRENT_USER, fullPath, key, val );
+	return setUnsignedIntInRegistry( HKEY_LOCAL_MACHINE, fullPath, key, val );
```
Comment (xezon) [inline Core/Libraries/Source/WWVegas/WWDownload/registry.cpp]: In what scenario is this code possible to hit?

If this now always writes to `HKEY_CURRENT_USER`, then `HKEY_LOCAL_MACHINE` fallback can be removed from writes.

Comment (bobtista) [reply Core/Libraries/Source/WWVegas/WWDownload/registry.cpp]: You're right - cleaned this up

File: Core/Libraries/Source/WWVegas/WWDownload/registry.cpp [hunk 3]
```diff
@@ -154,9 +154,8 @@ bool SetStringInRegistry( std::string path, std::string key, std::string val)
 #endif
 	fullPath.append(path);
 
-	if (setStringInRegistry( HKEY_LOCAL_MACHINE, fullPath, key, val))
-		return true;
-
+	// TheSuperHackers @fix bobtista 12/02/2026 Always write to HKCU. Per-user settings belong
+	// in HKEY_CURRENT_USER and writes there should always succeed without admin privileges.
```
[the remark this answers is not in the document]
Comment (bobtista) [reply Core/Libraries/Source/WWVegas/WWDownload/registry.cpp:158]: I don't think this is right. github mentions don't happen in code comments, they happen here in the PR comments.

**Review by xezon — APPROVED** [review]
