### PR TITLE
bugfix: Delay creation of object bound particle emitters until ParticleSystemManager is xfer-loaded

### LINKED ISSUE #754: W3DTankDraw::createEmitters create new particle system before before XFER_LOAD of TheParticleSystemManager cause save crash..
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

W3DTankDraw::createEmitters create new particle system TrackDebrisDirtLeft and TrackDebrisDirtRight before TheParticleSystemManager load xfer, might cause different items in TheParticleSystemManager has same ID, and wrong items are at the front.
Therefore, when a particle system with slave or master system, they will find a wrong particle system in method loadPostProcess which might already be destroyed and cause save crash.

### Reproduction Steps

I reproduced it on a specific map of a specific mod, but it's not the only case, modder fixed it by removing slave system from particle system.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stephanmeesters**
- Closes #754
 - Relates to #2316

During loading a savegame, some particle systems were created before `ParticleSystemManager` had the opportunity to xfer-load the saved particle systems, which led to the possibility that some of these early created  particle systems could be overwritten in `m_systemMap` of `ParticleSystemManager`. When that happens they would no longer reliably be able to use master/slave systems. The retail game does not use master/slave on the involved effects but it could appear as an issue with some mods (as the bug report describes too).

## Todo
 - [x] Replicate in Generals

### CODE REVIEW

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp [hunk 1]
```diff
@@ -106,7 +107,12 @@ W3DTankDraw::W3DTankDraw( Thing *thing, const ModuleData* moduleData )
 	m_lastDirection.y=0.0f;
 	m_lastDirection.z=0.0f;
 
-	createTreadEmitters();
+	// TheSuperHackers @bugfix stephanmeesters 20/02/2026
+	// If loading from savegame, delay non-saveable emitter creation until postProcess.
+	if (TheGameState == nullptr || TheGameState->isInLoadGame() == FALSE)
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: This is calling a function that is commented with "brutal hack", indicating that using this function is undesired. Can we solve this another way perhaps? Perhaps create particle effects later?

**Comment by stephanmeesters** [comment]
@greptileai

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp (hunk 1 above)
Comment (stephanmeesters) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: Particle effects are now created later, in `update` or `doDrawModule`. When loading from savegame these happen after `loadPostProcess`.

I've reworked the create emitters functions a bit to be more performant and readable

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp [hunk 2]
```diff
@@ -504,6 +506,9 @@ void W3DTankTruckDraw::doDrawModule(const Matrix3D* transformMtx)
 	if (obj == nullptr)
 		return;
 
+	// TheSuperHackers @bugfix stephanmeesters 14/03/2026 Delay emitter creation until draw
+	createTreadEmitters();
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp]: So my first thought here is that this is a workaround for a limitation of the particle system manager; changing the particle creation on object creation to a lazy update creation. This is similar to what the wheel emitters do. However, it does not fix the root issue with the particle system manager. So if someone created particles on object creation in the future again, then the issue returns. Is there a way to make the particle system manager robust against this? Or at least add an assert that signals that it is invalid?

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp (hunk 1 above)
Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: So my first thought here is that this is a workaround for a limitation of the particle system manager; changing the particle creation on object creation to a lazy update creation. This is similar to what the wheel emitters do. However, it does not fix the root issue with the particle system manager. So if someone created particles on object creation in the future again, then the issue returns. Is there a way to make the particle system manager robust against this? Or at least add an assert that signals that it is invalid?

Comment (stephanmeesters) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: I've added an assert in `ParticleSystemManager::xfer` that tests that the list is empty on load, this seems like a good thing to have.

One thing we can do is move `CHUNK_ParticleSystem` before `CHUNK_GameLogic`, which means the particle system manager is xfer-loaded early. I verified that this will fix the order of adding particle systems. This only applies to new saves as old saves load the chunks in the order it was saved.

However adding particle systems in the constructor will be problematic regardless of chunk order in the case of a savegame: in the old code there was `tossTreadEmitters()` in `postProcess()`, which appears to be needed because otherwise these early created particles are no longer visible for some reason.

So doing the lazy initalization seems like a good thing. Moving the chunks around would hide this particular problem (and may cause other issues idk).

File: Core/GameEngine/Source/GameClient/System/ParticleSys.cpp [hunk 3]
```diff
@@ -3346,6 +3346,8 @@ void ParticleSystemManager::xfer( Xfer *xfer )
 	}
 	else
 	{
+		DEBUG_ASSERTCRASH(m_allParticleSystemList.size()==0, ("ParticleSystemManager: particle systems list must be empty at start of xfer-load."));
```
Comment (xezon) [inline Core/GameEngine/Source/GameClient/System/ParticleSys.cpp]: .empty()

Comment (xezon) [inline Core/GameEngine/Source/GameClient/System/ParticleSys.cpp]: "is expected empty"

Because technically it still moves on if not empty.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp [hunk 4]
```diff
@@ -435,8 +443,6 @@ void W3DTankDraw::loadPostProcess()
 	// extend base class
 	W3DModelDraw::loadPostProcess();
 
-	// toss any existing tread emitters and re-create 'em (since this module expects 'em to always be around)
-	tossTreadEmitters();
 	createTreadEmitters();
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: Is this call still necessary then?

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp (hunk 2 above)
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp]: Any particular reason this is placed at this spot, before another early return?

File: GeneralsMD/Code/GameEngine/Include/GameLogic/Module/AutoHealBehavior.h [hunk 5]
```diff
@@ -108,9 +108,7 @@ class AutoHealBehaviorModuleData : public UpdateModuleData
 //-------------------------------------------------------------------------------------------------
 class AutoHealBehavior : public UpdateModule,
 												 public UpgradeMux,
-												 public DamageModuleInterface
-{
-
+												 public DamageModuleInterface {
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Include/GameLogic/Module/AutoHealBehavior.h]: Unexpected edit.

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp [hunk 6]
```diff
@@ -126,27 +125,33 @@ void W3DTankDraw::tossTreadEmitters()
...
-				// they come into being stopped.
-				particleSys->stop();
-				m_treadDebrisIDs[i] = particleSys->getSystemID();
-			}
+			m_treadDebrisIDs[0] = createParticleSystem(getW3DTankDrawModuleData()->m_treadDebrisNameLeft, getDrawable());
+		}
+		if (m_treadDebrisIDs[1] == INVALID_PARTICLE_SYSTEM_ID)
+		{
+			m_treadDebrisIDs[1] = createParticleSystem(getW3DTankDrawModuleData()->m_treadDebrisNameRight, getDrawable());
 		}
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp:157]: I suggest put a static assert nearby that the array size is expected 2.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GrantStealthBehavior.cpp [hunk 7]
```diff
@@ -246,5 +232,21 @@ void GrantStealthBehavior::loadPostProcess()
 	// extend base class
 	UpdateModule::loadPostProcess();
 
+	createEmitters();
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GrantStealthBehavior.cpp]: What happens if this was omitted?

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp (hunk 4 above)
Comment (stephanmeesters) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: No, emitter creating in postProcess is not necessary anymore

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp (hunk 2 above)
Comment (stephanmeesters) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp]: Moved them to a more logical place, right before they would be used in the draw function.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GrantStealthBehavior.cpp (hunk 7 above)
Comment (stephanmeesters) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/GrantStealthBehavior.cpp]: Would be created on possibly the next frame, but more likely already exists in the save anyway, so effectively can be removed

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp [hunk 8]
```diff
@@ -668,6 +673,9 @@ void W3DTankTruckDraw::doDrawModule(const Matrix3D* transformMtx)
 	if (velMult.z > 1.0f)
 		velMult.z = 1.0f;
 
+	// TheSuperHackers @bugfix 14/03/2026 Delay emitter creation until draw
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankTruckDraw.cpp]: author missing twice

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp [hunk 9]
```diff
@@ -336,6 +343,9 @@ void W3DTankDraw::doDrawModule(const Matrix3D* transformMtx)
 	if (velMult.z > 1.0f)
 		velMult.z = 1.0f;
 
+	// TheSuperHackers @bugfix 14/03/2026 Delay emitter creation until draw
```
Comment (xezon) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/Drawable/Draw/W3DTankDraw.cpp]: Perhaps also clarify why this needs to be done

Several times.

**Review by xezon — APPROVED** [review]

**Comment by stephanmeesters** [comment]
Replicated in Generals, only `AutoHealBehavior` needed the update.

**Review by xezon — APPROVED** [review]
Tested and worked.
