### PR TITLE
bugfix(contain): Fix unit attachments being visible in fog after exiting a GLA Tunnel Network

### LINKED ISSUE #29: China Overlord and USA Avenger model parts can be seen under fog after exiting GLA Tunnel
Overlord upgrades (bunker?) can be seen under fog under certain condition. Requires Repro for further investigation.

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #29

This change prevents unit attachments from being visible through fog after exiting a Tunnel Network. The tunnel garrison logic goes through a different pathway and does not add the occupants of open containers (e.g. Avenger turrets) to the partition manager on exit. Unfortunately, this change is not retail compatible (though maybe for the best as it would introduce a disadvantage over retail).

See the comparison below:

https://github.com/user-attachments/assets/dbd376eb-7b99-4634-a709-8a00814e6b86

**Left client:** This change - the blue player cannot see the turret attachment of the green Avenger through the fog ✔️
**Right client:** Retail build - the green player can see the turret attachment of the blue Avenger through the fog ❌

### CODE REVIEW

**Comment by Mauller** [comment]
I would check if this happens for contained objects being removed from a container in general.

Such as garrisoned structures, vehicles exiting helicopters etc.

Then this likely wants to go into the base remove from contained function call.

**Comment by Stubbjax** [comment]
> I would check if this happens for contained objects being removed from a container in general.

It does indeed via `addOrRemoveObjFromWorld`.

**Comment by Mauller** [comment]
> > I would check if this happens for contained objects being removed from a container in general.
> 
> It does indeed via `addOrRemoveObjFromWorld`.

So does this not happen for affected units with attachments exiting a helicopter in the fog?

**Comment by Stubbjax** [comment]
> > > I would check if this happens for contained objects being removed from a container in general.
> > 
> > 
> > It does indeed via `addOrRemoveObjFromWorld`.
> 
> So does this not happen for affected units with attachments exiting a helicopter in the fog?

Correct, see https://github.com/TheSuperHackers/GeneralsGameCode/issues/29#issuecomment-2691348929.

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp [hunk 1]
```diff
@@ -106,6 +106,20 @@ void TunnelContain::removeFromContain( Object *obj, Bool exposeStealthUnits )
 
 	owningPlayer->getTunnelSystem()->removeFromContain( obj, exposeStealthUnits );
 
+#if !RETAIL_COMPATIBLE_CRC
+	if (obj->getContain())
```
Comment (Mauller) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: I wonder if this can be cleaned up just by calling `addOrRemoveObjFromWorld(obj, TRUE);` ?

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: That was the way I had originally fixed it before making it more explicit. 😅 I went with this approach because `addOrRemoveObjFromWorld(obj, TRUE);` calls some of the same logic again, and I thought it might be better if the attachment wasn't added to the pathfinding grid (even though this admittedly adds an inconsistency).

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp [hunk 2]
```diff
@@ -106,6 +106,9 @@ void TunnelContain::removeFromContain( Object *obj, Bool exposeStealthUnits )
 
 	owningPlayer->getTunnelSystem()->removeFromContain( obj, exposeStealthUnits );
 
+#if !RETAIL_COMPATIBLE_CRC
+	addOrRemoveObjFromWorld(obj, TRUE);
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: This placement looks suspicious, because there is no counterpart in the `TunnelContain::addToContainList` function.

The counter part appears to be at

https://github.com/TheSuperHackers/GeneralsGameCode/blob/87de0a0d41e793ebd7acdded5fc371582d36c8f4/GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Contain/OpenContain.cpp#L334-L342

I suggest to revisit.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: I have revisited this and I am satisfied with the placement. The logical equivalent to `TunnelContain::removeFromContain` is `OpenContain::removeFromContainViaIterator`.

`TunnelContain` does not implement its own `addToContain`, so `OpenContain::addToContain` is called when a unit enters a tunnel. However, `TunnelContain` **does** provide its own implementation of `removeFromContain`, and so we need to explicitly call some of the equivalent logic from `OpenContain::removeFromContainViaIterator`.

`OpenContain::removeFromContainViaIterator` does the following:
```diff
Updates the contain list
Adds the object to the world
Triggers onRemove callbacks
```

`TunnelContain::removeFromContain` (now) does the following:
```diff
Triggers onRemove callbacks
Updates the contain list (via tunnel system)
+ Adds the object to the world
```

Some of the other logic from `OpenContain::removeFromContainViaIterator` (e.g. setting object position) is handled by `TunnelContain::onRemoving`. It's an inconsistent mess with different logic handled by different methods and events across the contain variants, but this seems to be the optimal placement without requiring significant rewrites.

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp [hunk 3]
```diff
@@ -106,6 +106,9 @@ void TunnelContain::removeFromContain( Object *obj, Bool exposeStealthUnits )
 
 	owningPlayer->getTunnelSystem()->removeFromContain( obj, exposeStealthUnits );
 
+#if !RETAIL_COMPATIBLE_CRC
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: Is this indeed CRC relevant, or just RETAIL_COMPATIBLE_BUG ?

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp (hunk 2 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: Ok `TunnelContain::onRemoving` was responsible for re-adding the object. We ideally have one place that does it. Now we have 2.

I think `TunnelContain::onRemoving` is the right place, because the Tunnel will evacuate dead units when a Neutron Shell kills its contents, unlike other containers.

See `OpenContain::killAllContained`.

Try move `addOrRemoveObjFromWorld` to `TunnelContain::onRemoving`.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: There are at least four methods that are responsible for re-adding the object but I see what you mean, even though the logic is not needed for when units are killed. I will move it.

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp (hunk 3 above)
Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp]: Any applicable attachment objects are added to the partition manager. Though this does not cause any issues regarding the attachment visibility fix itself, I believe it allows the attachment objects to receive collisions and affect pathfinding which can cause a mismatch. I believe the golden replay mismatches at around the 1h12m mark if I recall correctly.

File: Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp [hunk 4]
```diff
@@ -173,6 +172,10 @@ void TunnelContain::onRemoving( Object *obj )
 	}
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp:173]: Do we still need all this mumbo jumbo above here?

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp:173]: I'll add `RETAIL_COMPATIBLE_CRC` checks around the duplicate parts, despite the unsightly appearance.

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/Object/Contain/TunnelContain.cpp:173]: Can write it like so:

```cpp
	/// place the object in the world at position of the container m_object
#if RETAIL_COMPATIBLE_CRC
	ThePartitionManager->registerObject( obj );
	obj->setPosition( getObject()->getPosition() );
	if( obj->getDrawable() )
	{
		obj->setSafeOcclusionFrame(TheGameLogic->getFrame()+obj->getTemplate()->getOcclusionDelay());
		obj->getDrawable()->setDrawableHidden( false );
	}
#else
	// TheSuperHackers @bugfix Now correctly adds the objects to the world without issues with shrouded portable structures.
	obj->setPosition(getObject()->getPosition());
	obj->setSafeOcclusionFrame(TheGameLogic->getFrame() + obj->getTemplate()->getOcclusionDelay());
	addOrRemoveObjFromWorld(obj, TRUE);
#endif
```

**Review by xezon — APPROVED** [review]
