### PR TITLE
bugfix(module): Fix damage calculation for determining the initial death of GLA Battle Bus

### LINKED ISSUE #135: GLA Battle Bus will enter bunkered mode at 50% health left when shot with Toxin and Radiation weapons
GLA Battle Bus will enter bunkered mode at 50% health left when shot with Toxin and Radiation weapons.

https://user-images.githubusercontent.com/4720891/181082349-94efc7d9-2476-4a30-8f09-97cd5da44cdd.mp4

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #135

This change fixes the damage calculation for determining the Battle Bus's initial death, meaning it no longer prematurely dies when receiving damage via radiation or poison fields.

The issue is most notable when receiving damage via radiation or poison fields due to `HazardFieldCoreWeapon` - an invisible 200-damage hazard cleanup weapon that typically accompanies poison and radiation fields to stop them from stacking. As no armour damage modifiers are applied to ignore the hazard cleanup damage, the Battle Bus dies when receiving damage from this source if health is <= 200. Even [an Ambulance can kill a Battle Bus](https://github.com/user-attachments/assets/964a7854-4bbe-414b-ac9b-0b32fe8c6efe) by exploiting this logic.

https://github.com/user-attachments/assets/f5923571-ca3c-45c4-805e-31093d3af092

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp [hunk 1]
```diff
@@ -81,7 +81,11 @@ void UndeadBody::attemptDamage( DamageInfo *damageInfo )
 
 	if( damageInfo->in.m_damageType != DAMAGE_UNRESISTABLE
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp:82]: Please add a comment above that the damage check is now corrected and the user facing bug is fixed.

**Review by xezon — COMMENTED** [review]
Nice.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp [hunk 2]
```diff
@@ -81,7 +81,11 @@ void UndeadBody::attemptDamage( DamageInfo *damageInfo )
...
 			&& !m_isSecondLife
+#if RETAIL_COMPATIBLE_CRC
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp:84]: I think better use RETAIL_COMPATIBLE_BUG here

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp:84]: As in this is a desirable bug to be kept? If some players strangely desire this behaviour, they can surely just tweak the Battle Bus's `HAZARD_CLEANUP` damage modifier to deal damage.
```diff
Armor BattleBusTruckArmor
+  Armor = HAZARD_CLEANUP      50%    ;Now consistently harmed by cleaning weapons
-  Armor = HAZARD_CLEANUP       0%    ;Not harmed by cleaning weapons
End
```

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Body/UndeadBody.cpp:84]: Ok

**Review by xezon — APPROVED** [review]
