### PR TITLE
bugfix(heightmap): Fix dynamic lights on terrain

### LINKED ISSUE #182: Terrain lights from gun fire can get stuck near roads
Terrain lights from gun fire can get stuck near roads.

Tested on Wasted Warlords (2).

https://user-images.githubusercontent.com/4720891/219974044-bf4f96eb-d240-4597-bf89-4067df998a4a.mp4

### PR DESCRIPTION
**Pull request by xezon**
* Fixes #182

This changes fixes the dynamic lights on terrain. The coordinate bounds were incorrectly calculated, which caused dynamic lights to not draw at all within a viewed area or become stuck under some conditions.

Some vehicle types do not emit dynamic lights.

## Fixed Dynamic Lights on Terrain

shot_20251215_201428_1

shot_20251215_202305_4

### CODE REVIEW

File: Core/GameEngineDevice/Source/W3DDevice/GameClient/HeightMap.cpp [hunk 1]
```diff
@@ -1387,7 +1387,10 @@ Int HeightMapRenderObjClass::initHeightData(Int x, Int y, WorldHeightMap *pMap,
 //=============================================================================
 // HeightMapRenderObjClass::On_Frame_Update
 //=============================================================================
-/** Updates the diffuse color values in the vertices as affected by the dynamic lights.*/
+// Updates the diffuse color values in the vertices as affected by the dynamic
+// lights.
+// TheSuperHackers @bugfix xezon 15/12/2025 The dynamic lights are now properly
+// drawn on the entirety of the drawable map region.
```
Comment (Skyaero42) [inline Core/GameEngineDevice/Source/W3DDevice/GameClient/HeightMap.cpp]: I would suggest changing this to:
```
// TheSuperHackers @bugfix xezon 15/12/2025
// Fixed terrain dynamic lighting issues caused by incorrect coordinate bounds.
```

Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/HeightMap.cpp]: I don't see one better than the other. Historically we did not use past tense in comments.

Comment (Skyaero42) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/HeightMap.cpp]: "Draw the dynamic lights properly on the entirety of the drawable map region." perhaps?

Comment (xezon) [reply Core/GameEngineDevice/Source/W3DDevice/GameClient/HeightMap.cpp]: Reworded the comment
