### PR TITLE
[GEN][ZH] Fix crash when exiting Replay playback while a player places a beacon (2)

### LINKED ISSUE #76: Game crashes when exiting Replay Mode while player places beacon
Game crashes when exiting Replay Mode while player places beacon. Maybe also happens in regular match. However, this crash is easy to reproduce in Replay Mode when using Frame Step functionality from GenTool to reach specific frame in Replay.

GenTool fixes this crash by injecting naked function at address `0x4544C1` taking 6 bytes.

```
//////////////////////////////////////////////////////////////////////////////////////

// CPU Disasm (Zero Hour 1.04)
// Address   Hex dump          Command                                  Comments
// 004544C0  /$  51            PUSH ECX                                 ; game.004544C0(guessed Arg1)
// 004544C1  |.  8B81 DC000000 MOV EAX,DWORD PTR DS:[ECX+0DC]
// 004544C7  |.  85C0          TEST EAX,EAX
// 004544C9  |.  56            PUSH ESI
// 004544CA  |.  8B7424 0C     MOV ESI,DWORD PTR SS:[ARG.1]
// 004544CE  |.  C74424 04 000 MOV DWORD PTR SS:[LOCAL.0],0
// 004544D6  |.  8906          MOV DWORD PTR DS:[ESI],EAX
// 004544D8  |.  74 07         JZ SHORT 004544E1
// 004544DA  |.  50            PUSH EAX                                 ; /pTarget => [ARG.ECX+0DC]
// 004544DB  |.  FF15 2C929300 CALL DWORD PTR DS:[<&KERNEL32.Interlocke ; \KERNEL32.InterlockedIncrement
// 004544E1  |>  8BC6          MOV EAX,ESI
// 004544E3  |.  5E            POP ESI
// 004544E4  |.  59            POP ECX
// 004544E5  \.  C2 0400       RETN 4

//////////////////////////////////////////////////////////////////////////////////////

DWORD ccFixBeaconCrashRet;
__declspec(naked) void CC_FixBeaconCrash_ZH()
{
	__asm
	{
		pop [ccFixBeaconCrashRet]
		test ecx, ecx
		je Fix
		MOV EAX, DWORD PTR DS:[ECX+0xDC]
		jmp End
	Fix:
		mov eax, 0
	End:
		push [ccFixBeaconCrashRet]
		ret
	}
}
```

### PR DESCRIPTION
**Pull request by xezon**
* Merge after #969
* Fixes #76
* Relates to #850
* Relates to #971

This change fixes a game crash when exiting a Replay playback while a player places a beacon.

This change is not strictly necessary with #971, but it looks reasonable here to always test NULL, for robustness. Other code places also test `getPlayerTemplate()`.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp [hunk 1]
```diff
@@ -1577,7 +1577,8 @@ void GameLogic::logicMessageDispatcher( GameMessage *msg, void *userData )
 		// --------------------------------------------------------------------------------------------
 		case GameMessage::MSG_PLACE_BEACON:
 		{
-			// how many does this player have active?
+			if (thisPlayer->getPlayerTemplate() == NULL)
+				break;
 			Coord3D pos = msg->getArgument( 0 )->location;
```
Comment (Skyaero42) [inline Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp:1582]: I would add an empty line in between `break` and `Coord3D pos = msg->getArgument( 0 )->location;` for readability.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp [hunk 2]
```diff
@@ -1605,7 +1605,8 @@ void GameLogic::logicMessageDispatcher( GameMessage *msg, void *userData )
 		// --------------------------------------------------------------------------------------------
 		case GameMessage::MSG_PLACE_BEACON:
 		{
-			// how many does this player have active?
+			if (thisPlayer->getPlayerTemplate() == NULL)
+				break;
 			Coord3D pos = msg->getArgument( 0 )->location;
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp:1610]: Add an empty line

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp (hunk 1 above)
Comment (xezon) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogicDispatch.cpp:1582]: Yes I thought about that too but all this code in this file is already super dense, so I did not intent to break the density. I think this function needs to be refactor by moving the code in the switch case labels to their own functions. It is a mess. But we should not do that yet.

**Review by roossienb — APPROVED** [review]
