### PR TITLE
bugfix(audio): UI audio no longer plays at maximum volume for a single frame when navigating between shell map menus

### LINKED ISSUE #1941: Setting Sound FX volume to 0 does not mute all sounds
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Some sound effects are still played despite the volume being at 0. The sounds that play are cut off, randomly

### Reproduction Steps

Set Music Volume and Sound FX Volume both to zero

Confirmed in Options.ini
`MusicVolume = 0
SFX3DVolume = 0
SFXVolume = 0`

Some main menu buttons still trigger a partial sound see video

Bug appears in retail version, ZH on Steam

### Additional Context

https://github.com/user-attachments/assets/780ccd72-417c-4257-8bc4-020d47a3b269

### PR DESCRIPTION
**Pull request by Stubbjax**
Fixes #1941

This change fixes an issue where currently playing UI audio can be heard at maximum volume for a single frame when navigating between the shell map and other menus.

The issue is caused by a script being run via the shell map. The script reduces the sound volume to 5% when opening the options or entering other menu screens in order to silence the explosions and other noise coming from the shell map. As this also reduces the UI sound effect volume, another script is run to offset the reduced volume by adjusting a manually defined list of UI sound effect volumes to 600%. See the script reference images further below.

When the game processes a volume override command for a particular sound, the override is also immediately applied to any currently playing instances of that sound. However, when the game processes a global volume command, that volume adjustment is not applied until the next frame.

The issue is that `adjustVolumeOfPlayingAudio` applies the override without multiplying the global volume (`m_soundVolume`), so the sound immediately plays at 600% volume instead of 30% (6 × 0.05). Then, on the next frame, `processPlayingList()` sees `m_volumeHasChanged = TRUE` and calls `adjustPlayingVolume()`, which correctly applies the global volume. So for one frame, the sound plays at 600% volume before being corrected to 30%.

The solution is to make `adjustVolumeOfPlayingAudio` apply the same global volume modifiers as `adjustPlayingVolume`.

### Script Reference

Image

Image

### CODE REVIEW

File: Core/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp [hunk 1]
```diff
@@ -2109,7 +2109,7 @@ void MilesAudioManager::adjustVolumeOfPlayingAudio(AsciiString eventName, Real n
 			playing->m_audioEventRTS->setVolume(newVolume);
 			Real desiredVolume = playing->m_audioEventRTS->getVolume() * playing->m_audioEventRTS->getVolumeShift();
 			AIL_sample_volume_pan(playing->m_sample, NULL, &pan);
-			AIL_set_sample_volume_pan(playing->m_sample, desiredVolume, pan);
+			AIL_set_sample_volume_pan(playing->m_sample, m_soundVolume * desiredVolume, pan);
```
Comment (xezon) [inline Core/GameEngineDevice/Source/MilesAudioDevice/MilesAudioManager.cpp]: Can we do a follow up refactor and simplify all these volumes by using `MilesAudioManager::getEffectiveVolume`?

Then

```cpp
Real desiredVolume = playing->m_audioEventRTS->getVolume() * playing->m_audioEventRTS->getVolumeShift();
AIL_set_sample_volume_pan(playing->m_sample, m_soundVolume * desiredVolume, pan);
```
becomes
```cpp
AIL_set_sample_volume_pan(playing->m_sample, getEffectiveVolume(playing->m_audioEventRTS), pan);
```

This would streamline and simplify all this volume code.
