### PR TITLE
tweak(drawable): Decouple tint update step from render update

### LINKED ISSUE #1642: Selection flash is improperly scaled by frame rate
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When selecting units or buildings, the selection flash is improperly scaled by the frame rate in network games. The selection flash will not update at all when the frame rate is set to 30.

### Reproduction Steps

1. Start a new game via Multiplayer → Network
2. Use CTRL + NUMPAD PLUS or CTRL + NUMPAD MINUS to change the target frame rate
3. Select buildings / units

### Additional Context

https://github.com/user-attachments/assets/ef9ed24b-24df-4bbb-b8dd-90f148a40ef1

### PR DESCRIPTION
**Pull request by xezon**
* Resolves #1642

This change decouples the tint update step from the render update.

## TODO

- [x] Replicate in Generals

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp [hunk 1]
```diff
@@ -5641,7 +5654,16 @@ void TintEnvelope::xfer( Xfer *xfer )
 	xfer->xferUser( &m_currentColor, sizeof( Vector3 ) );
 
 	// sustain counter
-	xfer->xferUnsignedInt( &m_sustainCounter );
+	if (version <= 1)
+	{
+		UnsignedInt sustainCounter = (UnsignedInt)m_sustainCounter;
```
Comment (Skyaero42) [inline GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp:5659]: Any chance that due to the imprecision of the `Real` value of `m_sustainCounter` that it is truncated incorrectly? E.g., what if `m_sustainCounter = 158.9999999` instead of `159`? The cast would yield `158` and a mismatch occurs.

Comment (xezon) [reply GeneralsMD/Code/GameEngine/Source/GameClient/Drawable.cpp:5659]: The xfer is for Singleplayer save & load. It is not used in Network. Small inaccuracies are negligible.

**Comment by xezon** [comment]
Replicated in Generals without conflicts

```
D:\Projects\TheSuperHackers\GeneralsGameCode>FOR /F "delims=" %b IN ('git merge-base --fork-point main') DO git diff %b  1>changes.patch

D:\Projects\TheSuperHackers\GeneralsGameCode>git diff 16ff7e43b950fc27fb9b37ad3d7b96a54a7eb98b  1>changes.patch

D:\Projects\TheSuperHackers\GeneralsGameCode>git apply -p2 --directory=Generals --reject --whitespace=fix changes.patch
changes.patch:35: trailing whitespace.
                        if (decayRate.Length() > m_currentColor.Length() || m_currentColor.Length() <= FADE_RATE_EPSILON)
Checking patch Generals/Code/GameEngine/Include/GameClient/Drawable.h...
Hunk #1 succeeded at 203 (offset -3 lines).
Checking patch Generals/Code/GameEngine/Source/GameClient/Drawable.cpp...
Hunk #1 succeeded at 4784 (offset -757 lines).
Hunk #2 succeeded at 4797 (offset -757 lines).
Hunk #3 succeeded at 4830 (offset -757 lines).
Hunk #4 succeeded at 4842 (offset -757 lines).
Hunk #5 succeeded at 4876 (offset -757 lines).
Hunk #6 succeeded at 4897 (offset -757 lines).
Applied patch Generals/Code/GameEngine/Include/GameClient/Drawable.h cleanly.
Applied patch Generals/Code/GameEngine/Source/GameClient/Drawable.cpp cleanly.
warning: 1 line applied after fixing whitespace errors.
```
