### PR TITLE
fix: Fix incorrect argument used for isInSaveDirectory()

### LINKED ISSUE #1847: Assertion failure when loading a saved game
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [ ] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When loading a saved game, the following assertion failure occurs:

Image

Looks to be introduced by 038f51f1b7ef9a92b70ea506a265bfd47969e42e.

### Reproduction Steps

1. Load a saved game
2. Observe assertion failure

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Skyaero42**
- Introduced by: #1808
- Resolves #1847

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp [hunk 1]
```diff
@@ -2155,7 +2155,7 @@ void GameLogic::loadMapINI( AsciiString mapName )
 	// the pristine map name string in order to manipulate and load the right map.ini
 	// for that map from it's original location
 	//
-	const char* pristineMapName = TheGameState->isInSaveDirectory(filename)
+	const char* pristineMapName = TheGameState->isInSaveDirectory(mapName.str())
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:2155]: Nice. While at it, move the string buffers above to where they are first used to prevent using them before hand.

Comment (Skyaero42) [reply Generals/Code/GameEngine/Source/GameLogic/System/GameLogic.cpp:2155]: done

**Review by xezon — APPROVED** [review]
