### PR TITLE
  bugfix(dumbprojectile): Fix in-flight DumbProjectile detonating instantly on save load

### LINKED ISSUE #2346: Tank/Artillery Shells instantly Detonates Mid-Air after Loading
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

Saving a game while a Tank/Artillery Shell is in Mid-Flight will cause it to instantly detonate on Loading the Game. The issue is more obvious on Artilleries.

### Reproduction Steps

1. Build artilleries (Inferno Cannons/ Nuke Cannons.)
2. Command them to fire their weapon.
3. Immediately Save after they have fired.
4. Load the game.

### Additional Context

Image

### PR DESCRIPTION
**Pull request by afc-afc0**
* Fixes TheSuperHackers/GeneralsGameCode#2346

  DumbProjectileBehavior does not serialize `m_flightPath` (the Bezier curve points) or `m_currentFlightPathStep` (the current      
  position along the path). On load, `m_flightPath` is empty and `m_currentFlightPathStep` is 0, so the first `update()` call       
  evaluates `0 >= 0` as true and immediately calls `detonate()`. This is most visible with slow artillery like Inferno Cannons and  
  Nuke Cannons.

  The fix adds two things:

  1. Serializes `m_currentFlightPathStep` in `xfer()` (version bumped from 1 to 2) so the projectile knows where it was along its   
  flight path.
  2. Rebuilds the flight path Bezier curve in `loadPostProcess()` using the already-saved start, end, segments and speed parameters.

  Old saves (version 1) remain compatible — the step defaults to 0 and the path is rebuilt, so projectiles restart from the
  beginning of their arc rather than detonating instantly.

  ## Test
  - Built and launched Zero Hour
  - Started a skirmish and built artillery units
  - Fired artillery and immediately saved the game while shells were mid-flight
  - Loaded the save — projectiles continued their flight path and landed at their target without instant detonation
  - Verified loading old saves works correctly — projectiles restart from the beginning of their arc instead of detonating

### CODE REVIEW

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 1]
```diff
@@ -747,13 +747,14 @@ void DumbProjectileBehavior::crc( Xfer *xfer )
 // ------------------------------------------------------------------------------------------------
 /** Xfer method
 	* Version Info:
-	* 1: Initial version */
+	* 1: Initial version
+	* 2: Added m_currentFlightPathStep for mid-flight save/load */
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]:
```
* 2: TheSuperHackers @bugfix Added m_currentFlightPathStep for mid-flight save/load.
*/
```

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 2]
```diff
@@ -747,13 +747,14 @@ void DumbProjectileBehavior::crc( Xfer *xfer )
...
 // ------------------------------------------------------------------------------------------------
 void DumbProjectileBehavior::xfer( Xfer *xfer )
 {
 
 	// version
-	XferVersion currentVersion = 1;
+	XferVersion currentVersion = 2;
```
Comment (Caball009) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp:761]:
```cpp
if RETAIL_COMPATIBLE_XFER_SAVE
	XferVersion currentVersion = 1;
#else
	XferVersion currentVersion = 2;
#endif
```

Save games will become incompatible if this isn't behind the macro.

**Review by Caball009 — COMMENTED** [review]
FWIW it's best to do the Generals changes last (after all feedback), unless there are meaningful changes in the Generals code. That's easier for the PR author and reviewers. This PR is small enough that it doesn't really matter, though.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 3]
```diff
@@ -747,13 +747,18 @@ void DumbProjectileBehavior::crc( Xfer *xfer )
 // ------------------------------------------------------------------------------------------------
 /** Xfer method
 	* Version Info:
-	* 1: Initial version */
+	* 1: Initial version
+	* 2: TheSuperHackers @bugfix Added m_currentFlightPathStep for mid-flight save/load. */
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Can put */ on next line

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 4]
```diff
@@ -804,6 +809,12 @@ void DumbProjectileBehavior::xfer( Xfer *xfer )
 	// lifespan frame
 	xfer->xferUnsignedInt( &m_lifespanFrame );
 
+	// TheSuperHackers @bugfix Serialize current flight path step so projectiles can resume mid-flight on load.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Redundant comment, because above the xfer function already is another comment added.

File: GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp [hunk 5]
```diff
@@ -815,4 +826,10 @@ void DumbProjectileBehavior::loadPostProcess()
 	// extend base class
 	UpdateModule::loadPostProcess();
 
+	// TheSuperHackers @bugfix Rebuild flight path on load to prevent immediate detonation of in-flight projectiles.
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameLogic/Object/Behavior/DumbProjectileBehavior.cpp]: Redundant comment. xfer function already documents it.

**Review by xezon — APPROVED** [review]
Fix makes sense. Comments are too verbose.

**Review by xezon — APPROVED** [review]
