### PR TITLE
bugfix(controls): Fix double-press group selection logic not reselecting deselected groups

### LINKED ISSUE #1332: Centering the camera on a group does not (re)select the group
### Prerequisites

- [x] I have searched for similar issues and confirmed this is not a duplicate

### Game Version

- [x] Command & Conquer Generals
- [x] Command & Conquer Generals: Zero Hour
- [ ] Other (please specify below)

### Bug Description

When selecting a group via the 0 - 9 group hotkeys, the initial press selects the group. Double-pressing the respective group hotkey centers the camera on the group. However, the single-press vs double-press logic are two separate blocks, and the double-press logic does not (re)select the group.

This is an issue if the selection happens to be lost within the 20-frame double-press window, which will cause the group to be unselectable by pressing the hotkey until at least 20 frames pass. This is confusing for the user as attempting to reselect the group via the hotkey does not yield the expected result, and can be catastrophic in intensive micro situations.

Expectation: Double-pressing the group hotkey also selects the group if it is not currently selected.

### Reproduction Steps

1. Start a new game
2. Select any unit
3. Put the unit in a group by pressing CTRL+1
4. Move the unit somewhere
5. Rapidly press 1 to observe the camera repeatedly centering on the unit as it moves
6. While still rapidly pressing 1, click an empty area of the screen to deselect the unit
7. While still rapidly pressing 1, observe the unit is still repeatedly centered, _but not reselected_

### Additional Context

https://github.com/user-attachments/assets/9e8f8a80-cadd-42fd-a200-174daa46f163

### PR DESCRIPTION
**Pull request by Stubbjax**
* Fixes #1332

* Alternative solution to #1334

Centering the camera on a group by double-pressing a group selection hotkey (0 - 9) will now reselect the group if it was deselected.

Technically either one of the two commits fixes the issue. Setting `m_lastGroupSelGroup = -1;` on global deselect is essentially replicating the existing behaviour of selecting something else (where the last group is also set to -1) - which also allows the group to be selected again - whereas the `performSelection` logic adjustment acts as more of a safer catch-all in case the selection can be lost by other means.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp [hunk 1]
```diff
@@ -1039,12 +1043,15 @@ GameMessageDisposition SelectionTranslator::translateGameMessage(const GameMessa
 							if (numObjs > 0)
 							{
 								// if theres someone in the group, center the camera on them.
-								TheTacticalView->lookAt( objlist[numObjs-1]->getDrawable()->getPosition() );
+								Drawable* drawable = objlist[numObjs - 1]->getDrawable();
+								TheTacticalView->lookAt( drawable->getPosition() );
+								performSelection = !TheInGameUI->isDrawableSelected( drawable->getID() );
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp]: This is technically incorrect because if every other thing in the squad is not selected but this one is, then performSelection will be false.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp]: Isn't that situation impossible? If the selection is changed, `m_lastGroupSelGroup` would be reset to -1 and so the entire group would be reselected on the next press.

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp]: Yes it may be practically impossible depending on what the other code does.

What could be good here is a `selectedSquad->isSelected()` function that returns true if all members are selected. Then this logic cannot fail.

Comment (Stubbjax) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp]: Giving Squads awareness of their selection status feels wrong from a SoC perspective. I've instead added a function to the `InGameUI` to check whether all passed objects are selected, and then simply passed in the squad's object list. Is this preferable? I'm not sure whether I like the performance cost.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 2]
```diff
@@ -3335,6 +3335,21 @@ Bool InGameUI::isDrawableSelected( DrawableID idToCheck ) const
 
 }  // end isDrawableSelected
 
+//-------------------------------------------------------------------------------------------------
+/** Return true if all of the selected objects are in the drawable list */
+//-------------------------------------------------------------------------------------------------
+Bool InGameUI::areAllObjectsSelected(std::vector<Object*> objectsToCheck) const
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: `const std::vector<Object*>&`, otherwise this is a copy

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 3]
```diff
@@ -3335,6 +3335,21 @@ Bool InGameUI::isDrawableSelected( DrawableID idToCheck ) const
...
+{
+	for (DrawableListCIt it = m_selectedDrawables.begin(); it != m_selectedDrawables.end(); ++it)
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: This can be optimized by using `object->getDrawable()->isSelected()`

File: Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp [hunk 4]
```diff
@@ -1039,12 +1043,15 @@ GameMessageDisposition SelectionTranslator::translateGameMessage(const GameMessa
 							if (numObjs > 0)
 							{
 								// if theres someone in the group, center the camera on them.
-								TheTacticalView->lookAt( objlist[numObjs-1]->getDrawable()->getPosition() );
+								Drawable* drawable = objlist[numObjs - 1]->getDrawable();
```
Comment (Caball009) [inline Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp:1048]: FWIW, this code base consistently uses `Drawable *drawable` instead of `Drawable* drawable`.

Comment (xezon) [reply Generals/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp:1048]: I think `Drawable* drawable` is perfectly fine style.

File: Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp [hunk 5]
```diff
@@ -3335,6 +3335,21 @@ Bool InGameUI::isDrawableSelected( DrawableID idToCheck ) const
 
 }  // end isDrawableSelected
 
+//-------------------------------------------------------------------------------------------------
+/** Return true if all of the selected objects are in the drawable list */
```
Comment (xezon) [inline Generals/Code/GameEngine/Source/GameClient/InGameUI.cpp]: This comment can be updated to "Return true if all given objects are selected"

File: GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp [hunk 6]
```diff
@@ -1099,10 +1100,13 @@ GameMessageDisposition SelectionTranslator::translateGameMessage(const GameMessa
 					m_lastGroupSelTime = now;
 				}
 
+				Bool performSelection = TRUE;
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp:1103]: I suggest add a "TheSuperHackers" comment somewhere here explaining what was changed and why.

File: GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp [hunk 7]
```diff
@@ -1099,10 +1100,15 @@ GameMessageDisposition SelectionTranslator::translateGameMessage(const GameMessa
...
+
 				// check for double-press to jump view
 				if ( now - m_lastGroupSelTime < 20 && group == m_lastGroupSelGroup )
 				{
 					DEBUG_LOG(("META: DOUBLETAP select team %d",group));
+					// TheSuperHackers @tweak Stubbjax 26/05/2025 Perform selection on double-press
```
Comment (xezon) [inline GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp]: Is this a tweak or a fix or a bugfix? I was under the impression this was fixing a user facing bug.

Comment (Stubbjax) [reply GeneralsMD/Code/GameEngine/Source/GameClient/MessageStream/SelectionXlat.cpp]: Updated to bugfix.

**Review by xezon — APPROVED** [review]
Looks good.
